### ISSUE TITLE
Abstract Monomorphic Refinements don't seem to work

### ISSUE THREAD

**Issue by ethanfrey** [ucsd-progsys/liquidhaskell#1000]
I tried following along this [blog post on abstract refinements](https://ucsd-progsys.github.io/liquidhaskell-blog/2013/07/29/putting-things-in-order.lhs/) and it is an amazing power to have.  However, I couldn't get all the code from the example to work:

```Haskell
module ArtError () where

import Prelude hiding (break)

{-@ predicate Btwn Lo V Hi = (Lo <= V && V <= Hi) @-}

{-@ data Assoc v <p :: Int -> Bool> = KV (z :: [(Int<p>, v)]) @-}
data Assoc v = KV [(Int, v)]

{-@ digits :: Assoc (String) <{\v -> (Btwn 0 v 9)}> @-}
digits    :: Assoc String
digits    = KV [ (1, "one")
               , (21, "two")
               , (3, "three") ]

data AssocP k v = KVP [(k, v)]

{-@ digitsP :: AssocP {v:Int | (Btwn 0 v 9)} String @-}
digitsP :: AssocP Int String
digitsP = KVP [ (1, "one")
              , (21, "two")
              , (3, "three") ]
```

In this case, digitsP correctly complains, but digits does not. This code is straight from the blog post, the only change is that I changed the type from <p :: Int -> Prop> to <p :: Int -> Bool> as the former seems deprecated and didn't even parse properly.

Did the syntax change? Or is the functionality not supported now? It would be great if you could update the syntax in the blog post (or link to an update). I keep finding more amazing info from a few years ago on this project, but often have to play around a bit with syntax to get everything to check out.

**Comment by nikivazou** [comment]
But with your edit `Bool -> Prop` everything works, right?
`digitsP` is supposed to fail.

**Comment by ethanfrey** [comment]
Yes, the only change I made was Prop to Bool and the code runs fine. 

If I understand correctly, they are both supposed to fail. Digits and digitsP. But only digitsP fails. If seems the refinement of the integer keys on digits is ignored. 

Did I type this code wrong? Or understand it wrong? Or is it not enforcing the constraint? 

And thank you for this tool. I've been going through the blog posts and tutorial and some papers and it's really amazing how much you can prove with this system, while retaining the power of Haskell.

**Comment by ethanfrey** [comment]
Hmmm... it seems some of these <p> fields aren't even being parsed fully. I changed the LH signature in the above method to this, and it produces the same results. It seems to be ignored by the parser unless it matches a predicate. And then returns an error when it matches. Odd...

No parse errors, tests on digits pass:
```
{-@ digits :: Assoc (String) <whattodo> @-}
```

Parse error: 
```
{-@ digits :: Assoc (String) <Btwn> @-}
...
 Error: Cannot parse specification:

 17 | {-@ digits :: Assoc (String) <Btwn> @-}
                                    ^
     unexpected "B"
     expecting mmonoPredicateP
```

**Comment by nikivazou** [comment]
Sorry, yes, your syntax was wrong. Type application goes after the abstract refinement, as

```
{-@ digits :: Assoc  <{\v -> (Btwn 0 v 9)}> String @-}
```

**Comment by ethanfrey** [comment]
Thanks for the help.  It totally works properly this way.  This turns out just to be a bug in the blog ;)

Maybe someone can update this? https://ucsd-progsys.github.io/liquidhaskell-blog/2013/07/29/putting-things-in-order.lhs/#abstractly-refined-data

It seems that the best documentation on liquid haskell is from 2013-2015, but the syntax has changed slightly since then.

**Comment by nikivazou** [comment]
Could you send a pull request here???

https://github.com/ucsd-progsys/liquidhaskell-blog/tree/master/docs

Thanks :)

**Comment by ethanfrey** [comment]
I caught that one, the trickier typo (and one with no LH warnings) was:

```
{-@ digits :: Assoc (String) <{\v -> (Btwn 0 v 9)}> @-}
```

rather than 

```
{-@ digits :: Assoc  <{\v -> (Btwn 0 v 9)}> String @-}
```

as Niki corrected me. I'm preparing a PR for this blog post.

**Comment by ethanfrey** [comment]
Okay, PR here: https://github.com/ucsd-progsys/liquidhaskell-blog/pull/3

Thank you both for the feedback.
