### ISSUE TITLE
Support hexadecimal constants in specifications

### ISSUE THREAD

**Issue by sdleffler** [ucsd-progsys/liquidhaskell#1061]
It would be nice to be able to use hex constants in specifications, e.g.

```
{-@ assume chr# :: {n:Int# | 0 <= n && n <= 0x10FFFF} -> Char# @-}
```

instead of

```
{-@ assume chr# :: {n:Int# | 0 <= n && n <= 1114111} -> Char# @-}
```

**Comment by ranjitjhala** [comment]
Good point! Should be quite easy to do IMO [should just have to tweak the parser a touch.]

**Comment by ranjitjhala** [comment]
should be fixed by above unless i've messed up the submodules 😟
