### ISSUE TITLE
Hackage package contains 100mb .stack-work

### ISSUE THREAD

**Issue by mpickering** [ucsd-progsys/liquidhaskell#1063]
Running `cabal get liquidhaskell-0.8.0.0` and inspecting the `liquid-fixpoint` directory there is a hidden directory `.stack-work` which greatly inflates the size of the package. Should this be included?

**Comment by gridaphobe** [comment]
No! Even the `liquid-fixpoint` directory should not be included since it's also on hackage..

Thanks for pointing this out!

**Comment by gridaphobe** [comment]
I've uploaded `liquidhaskell-0.8.0.1` to hackage without the `liquid-fixpoint` and `.stack-work` directories. It looks like somebody made a tarball manually rather than with `cabal sdist`.

Thanks!

**Comment by ranjitjhala** [comment]
Thanks @gridaphobe and @mpickering !
