### ISSUE TITLE
TransformRec makes it impossible to prove termination!

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquidhaskell#1065]
Here's a function @sdleffler is working on in GHC.Exts. A combination of the transform-rec pass and some ugly bugs in LH make it apparently impossible to prove this thing terminating...

```
{-# LANGUAGE TypeFamilies #-}
module GroupBy where

groupByFB :: ([a] -> lst -> lst) -> lst -> (a -> a -> Bool) -> [a] -> lst
groupByFB c n eq xs0 = groupByFBCore xs0
        {- groupByFBCore :: zoo:_ -> _ / [len zoo] @-}
        {- groupByFBCore :: c:_ -> n:_ -> eq:_ -> xs0:_ -> zoo:_ -> _ / [len zoo] @-}
        {- Decrease groupByFBCore 5 @-}
  where groupByFBCore [] = n
        groupByFBCore (x:xs) = c (x:ys) (groupByFBCore zs)
            where (ys, zs) = span (eq x) xs
```

With no annotations, we get a surprising type error.

```
 /Users/gridaphobe/Source/liquid/haskell/GroupBy.hs:10:42-54: Error: Liquid Type Mismatch

 10 |         groupByFBCore (x:xs) = c (x:ys) (groupByFBCore zs)
                                               ^^^^^^^^^^^^^
   Inferred type
     VV : {v : [a] | v == xs0}

   not a subtype of Required type
     VV : {VV : [a] | VV == xs0 && len VV < len xs0}
```

This is no good, the required type is obviously impossible. Furthermore, what a reference to `xs0` doing inside `groupByFBCore`? It's a binder from the outer `groupByFB`! 

Looking at the core, we see that transform-rec has copied all of the parameters from the outer `groupByFB` to `groupByFBCore`

BEFORE
```
       groupByFBCore =
         \ (ds_dAy :: [a]) ->
```
AFTER
```
       groupByFBCore [Occ=LoopBreaker]
         :: forall a lst ->
            ([a] -> lst -> lst)
            -> lst -> (a -> a -> GHC.Types.Bool) -> [a] -> [a] -> lst
       [LclId, Str=DmdType]
       groupByFBCore =
         \ (@ a)
           (@ lst)
           (c :: [a] -> lst -> lst)
           (n :: lst)
           (eq :: a -> a -> GHC.Types.Bool)
           (xs0 :: [a])
           (ds_dAy :: [a]) ->
...
                 ((groupByFBCore @ a @ lst c n eq xs0) zs)
```

So transform-rec is passing these extra parameters through each recursive call unchanged. I forget what the purpose of this pass is, but fine. 

Now `xs0` is the first parameter with a termination metric, so we try and fail to prove it decreases. Mystery solved! Let's just write an explicit metric

```
        {-@ groupByFBCore :: c:_ -> n:_ -> eq:_ -> xs0:_ -> zoo:_ -> _ / [len zoo] @-}
```

```
 6 |         {-@ groupByFBCore :: c:_ -> n:_ -> eq:_ -> xs0:_ -> zoo:_ -> _ / [len zoo] @-}
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 The Liquid type

     _ -> _ -> _ -> _ -> _ -> _

 is inconsistent with the Haskell type

     [a] -> lst
```

Hmm, it appears LH is doing the consistency check before the transform-rec pass. Fine, we'll change the signature to

```
        {-@ groupByFBCore :: zoo:_ -> _ / [len zoo] @-}
```

```
 /Users/gridaphobe/Source/liquid/haskell/GroupBy.hs:7:30: Error: Illegal termination specification for `groupByFBCore`

 7 |         {-@ groupByFBCore :: zoo:_ -> _ / [len zoo] @-}
                                  ^
     Termination metric len zoo is ill-sorted
     Cannot unify (@(43)  @(42)) with func(0, [[a_azU]; lst_azV; lst_azV]) in expression: len zoo
```

But now when we try to generate constraints for the termination check, we're suddenly using the post-transform-rec type! Yikes!

My last thought was to try the old `Decrease` annotation.

```
        {-@ Decrease groupByFBCore 5 @-}
```

```
 /Users/gridaphobe/Source/liquid/haskell/GroupBy.hs:8:22: Error: Cannot parse specification:

 8 |         {-@ Decrease groupByFBCore 5 @-}
                          ^
     unexpected "g"
     expecting space or "::"
```

But perhaps this annotation isn't even supported anymore?

**Comment by gridaphobe** [comment]
I think the obvious solution is to update all signatures that have been transform-rec'd to add the additional parameters.

Though I'm also wondering if transform-rec is still necessary? I forget why we do it, but my hunch is that it's there so inner loops can refer to parameters of the outer loop, in which case it should no longer be needed at all since we can do that natively.

**Comment by ranjitjhala** [comment]
Hmm IIRC transformRec had to do with enabling "polymorphic recursion" for
things like insertion-sort.

But honestly

1. I don't recall
2. Surely there is a way to do it without the overhead of transformRec

**Comment by gridaphobe** [comment]
Hmm, if it's mainly about polymorphic recursion, then presumably we could just pass the type variables rather than everything..

Also, the entire issue goes away in this example if we disable `TypeFamilies`, which seems to suggest that the transform-rec pass is subtly broken anyway as it's relying on an internal detail of how GHC desugars functions (using a single `letrec` vs the weird `let foo = letrec foo = ...  in foo` thing).

**Comment by ranjitjhala** [comment]
Is it feasible to disable `TF` -- or is this still a blocking issue?

**Comment by ranjitjhala** [comment]
Is another possibility to optionally _disable_ `transformRec`?

**Comment by gridaphobe** [comment]
Good question, I just pushed https://github.com/ucsd-progsys/liquidhaskell/tree/no-transform-rec to see what breaks if we disable it

**Comment by ranjitjhala** [comment]
Oh lots of stuff will break (e.g. the stuff that uses AbsRef in recursive
data-types, Map, Sort...)

I was proposing to start with a flag e.g. `--no-transform-rec` ...

**Comment by gridaphobe** [comment]
It looks like there are around 15 failures so far in the regrtests, not including the benchmarks.

https://circleci.com/gh/ucsd-progsys/liquidhaskell/1621

The only problem with a `--no-transform-rec` flag, is that I can't think of a way to indicate to users that they might need to enable the flag. So it could help with the current issue, but it doesn't seem like a long-term fix.

**Comment by ranjitjhala** [comment]
Oh its _definitely_ not a long term fix!
