### ISSUE TITLE
Confusing conflicting definitions error message

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1072]
The following check creates a confusing error message 

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Bare.hs#L268

In the following file 
```
{-# LANGUAGE NoImplicitPrelude #-}

{-@ measure head :: [a] -> a
    head (x:_) = x
    @-}

head                    :: [a] -> a
head (x:_)              =  x
```

The error is created because the measures are not allow to have the same names as the Haskell functions, but this is not clear from the error message.

**Comment by gridaphobe** [comment]
Is this restriction necessary? Why?

We used to be able to do this.

**Comment by ranjitjhala** [comment]
1. `"head"` is special (i.e. see `WiredIn` - which is why the error-location is weird).

2. In general, I'd like things like measures etc. to correspond to GHC visible entities, and to generally disable stuff defined just inside `{-@ ... @-}` 

Hence, not clear what the issue is here?
