### ISSUE TITLE
Support GADTs

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1089]
Can we get this working?

https://github.com/jbrown215/binah/blob/master/db/EvalQuery.hs

via @jbrown215

**Comment by ranjitjhala** [comment]
Associated notes from GHC

[GHC/DataCon/Wrapper etc](https://github.com/ghc/ghc/blob/master/compiler/basicTypes/DataCon.hs#L124)

See also:

- tests/pos/ExactGADT.hs 
- tests/pos/ExactGADT1.hs 
- tests/pos/ExactGADT2.hs 
- tests/pos/ExactGADT3.hs 
- tests/pos/ExactGADT4.hs 

Each of which give a different error...

**Comment by ranjitjhala** [comment]
Turns out the code:

```haskell

{-# LANGUAGE  GADTs #-}

module Query where

{-@ data Field typ where
        FldX :: Field Int
      | FldY :: Field Int
  @-}

data Field typ where
  FldX :: Int -> Field Int
  FldY :: Int -> Field Int

moogle = FldX 122
```

is compiled thus:

```
rjhala@borscht ~/r/s/liquidhaskell (T1089)> ghc tests/pos/ExactGADT.hs -ddump-simpl
[1 of 1] Compiling Query            ( tests/pos/ExactGADT.hs, tests/pos/ExactGADT.o )

==================== Tidy Core ====================
Result size of Tidy Core = {terms: 14, types: 14, coercions: 3}

Query.$WFldX [InlPrag=INLINE] :: Int -> Field Int
[GblId[DataConWrapper],
 Arity=1,
 Caf=NoCafRefs,
 Str=DmdType <L,U>,
 Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
         WorkFree=True, Expandable=True,
         Guidance=ALWAYS_IF(arity=1,unsat_ok=False,boring_ok=False)
         Tmpl= \ (dt_alV [Occ=Once] :: Int) ->
                 Query.FldX @ Int @~ <Int>_N dt_alV}]
Query.$WFldX =
  \ (dt_alV [Occ=Once] :: Int) -> Query.FldX @ Int @~ <Int>_N dt_alV

Query.$WFldY [InlPrag=INLINE] :: Int -> Field Int
[GblId[DataConWrapper],
 Arity=1,
 Caf=NoCafRefs,
 Str=DmdType <L,U>,
 Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
         WorkFree=True, Expandable=True,
         Guidance=ALWAYS_IF(arity=1,unsat_ok=False,boring_ok=False)
         Tmpl= \ (dt_alW [Occ=Once] :: Int) ->
                 Query.FldY @ Int @~ <Int>_N dt_alW}]
Query.$WFldY =
  \ (dt_alW [Occ=Once] :: Int) -> Query.FldY @ Int @~ <Int>_N dt_alW

a_rlT :: Int
[GblId, Caf=NoCafRefs, Str=DmdType]
a_rlT = GHC.Types.I# 122

moogle :: Field Int
[GblId, Caf=NoCafRefs, Str=DmdType]
moogle = Query.FldX @ Int @~ <Int>_N a_rlT
```

So there's this `FldX` stuff which is the worker (?) 
and then we have the wrapper which is `$WFldY`.

Horrors.

@nikivazou have you ever dealt with this stuff before?

**Comment by ranjitjhala** [comment]
See also: `Liquid.Measure.makeDataConType`

**Comment by jbrown215** [comment]
https://github.com/jbrown215/binah/blob/master/db/UpdateQuery.hs#L40

Definitely related, but just want to make sure both use cases are hit in this fix :)

I expect that liquid should point out an error on line 40, since BlobXVal has the property that the value must be non-negative. 

It's also possible that I am messing this up in other ways, though

**Comment by ranjitjhala** [comment]
The relevant action is in `Bare.DataType.ofBDataCtor`.

Important functions:

```
dataConDecl :: DataCon -> DataCtor
```

Rather than changing `DataConP`, may be better to hack

`meetDataConSpec` 

to return two sigs, one for the 

- `dataConWorkId` -- the tricky GADT signature with the coercions, and 
- `dataConWrapId` -- the simple user-level signature.

https://downloads.haskell.org/~ghc/8.0.1/docs/html/libraries/ghc-8.0.1/DataCon.html

**Comment by ranjitjhala** [comment]
Now we get sort errors like so:

```
 /Users/rjhala/research/stack/liquidhaskell/tests/todo/ExactGADT1.hs:9:3-19: Error: Illegal type specification for `constructor Query.FldY`

 9 |   FldY :: Field Int
       ^^^^^^^^^^^^^^^^^

     constructor Query.FldY :: (~# (TYPE PtrRepLifted) (TYPE PtrRepLifted) a Int) =>
                               (Field a)
     Sort Error in Refinement: {VV : (Query.Field typ_ap0) | ((is$Query.FldY VV <=> true)
                                                              && (is$Query.FldX VV <=> false))}
     Unbound Symbol typ_ap0
     Cannot unify int with typ_ap0 in expression: is$Query.FldY VV
```

Next:

1. Tweak `checkRType` in `Bare.Check` to extend the `cb` function so that when we see "the constraint"  `(a ~ TYPE)` we add a binder `a : TYPE` to the fixpoint env -- to do so, we need only extend `RefType.classBinds` appropriately.

2. Extend `liquid-fixpoint` so that we can account for equality constraints; so we should type, e.g.

```
  bind 0 a : {v: Thing | true } 
  bind 1 x : {v: Thing | true } 
  bind 2 y : {v: a       | true } 
  
  constraint:  
     env : [0; 1; 2]
     lhs : {v:Int | x = y }
     rhs : {v: Int | y = x }
```

**Comment by ranjitjhala** [comment]
Next: see tests/todo/ExactGADT3.hs, tests/todo/ExactGADT4.hs in branch T1089.

**Comment by ranjitjhala** [comment]
hmm the files 

* https://github.com/jbrown215/binah/blob/master/db/EvalQuery.hs
* https://github.com/jbrown215/binah/blob/master/db/UpdateQuery.hs#L41

use fancier GHC features than I know, need to first figure out what's going on...

Some notes.

```haskell
λ> :i EntityField
class PersistEntity record where
  type role EntityField nominal nominal
  data family EntityField record a
  	-- Defined at ExactGADT3.hs:15:3
data instance EntityField Blob dog where
  BlobXVal :: EntityField Blob Int
  BlobYVal :: EntityField Blob Int
  	-- Defined at ExactGADT3.hs:35:8
```

So `EntityField Blob` is not a plain `TyCon` but a `data instance`  (type-family instance?)
of type `FamInst` (see `mgi_fam_inst`).

1. Nevertheless, `BlobXVal` and `BlobYVal` are `DataCon`s,
2. The family instance _does_ have a `TyCon` called `Query.R:EntityFieldBlobdog` 
3. But, but we cannot use the `TyCon` name directly as it kills the `lookupGhcTyCon` 
    (with a parse error) I guess its not supposed to be visible to the user.

**Solution (?)** extend `makeHaskellDataDecls` to also handle `FamInst` ?

**Comment by ranjitjhala** [comment]
Should be fixed by https://github.com/ucsd-progsys/liquidhaskell/pull/1171

Specifically, the following -- post-merge -- should now work:

- [ExactGADT.hs](/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/ExactGADT.hs)
- [ExactGADT1.hs](/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/ExactGADT1.hs)
- [ExactGADT2.hs](/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/ExactGADT2.hs)
- [ExactGADT4.hs](/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/ExactGADT4.hs)
