### ISSUE TITLE
LH runs forever (>5min) on complicated patterns

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1095]
The following program takes too long to verify (>6 min)

```
{-@ LIQUID "--exactdc"     @-}
{-@ LIQUID "--higherorder" @-}

module Foo where

data Foo 
  = A Foo Foo Foo 
  | B Foo Foo
  | C Foo
  | D Foo
  | E Foo Int 
  | F Int
  | G Int
  | H 
  | I
  | J  
  | K
  | L
  | M
  | N 
  | X

{-@ 
data Foo [size]
  = A {a1 :: Foo, a2 :: Foo, a3 ::  Foo} 
  | B {b1 :: Foo, b2 :: Foo}
  | C {c  :: Foo}
  | D {d  :: Foo}
  | E {e1 :: Foo, e2 :: Int} 
  | F {f  :: Int}
  | G {g  :: Int}
  | H 
  | I
  | J  
  | K
  | L
  | M
  | N 
  | X
  @-}

size :: Foo -> Integer 
{-@ measure size @-}
{-@ invariant {t:Foo | 0 <= size t} @-}
{-@ size :: Foo -> {v:Integer |  0 <= v }  @-}
size (A x y z) = 1 + size x + size y + size z 
size (B x y)   = 1 + size x + size y 
size (C x)     = 1 + size x 
size (D x)     = 1 + size x 
size (E x _)   = 1 + size x 
size (F _)     = 1 
size (G _)     = 1 
size _         = 0 


foo  :: Foo -> Foo
foo (A X _ _) = X 
foo (A _ X _) = X 
foo (A _ _ X) = X 
foo (B X _)   = X 
foo (B _ X)   = X 
foo (C X)     = X 
foo (D X)     = X 
foo (E X _)   = X 
foo X         = X 
foo (A x y z) = A (foo x) (foo y) (foo z)
foo (B x y)   = B (foo x) (foo y)
foo (C x)     = C (foo x)
foo (D x)     = D (foo x)
foo (E x i)   = E (foo x) i 
foo x         = x 
```

The problem is that `foo` has very complicated case analysis. 
In such cases, my hack was to use ` --no-case-expand` to simplify the ghc internal cases analysis, but this would break reflection of `foo`. 

Note that writing `foo` as follows runs in <2 min

```
{-@ reflect hasX @-}
hasX :: Foo -> Bool 
hasX (A X _ _) = True 
hasX (A _ X _) = True 
hasX (A _ _ X) = True 
hasX (B X _)   = True 
hasX (B _ X)   = True 
hasX (C X)     = True 
hasX (D X)     = True 
hasX (E X _)   = True 
hasX X         = True 
hasX _         = False 

{-@ reflect foo @-}
foo  :: Foo -> Foo
foo x | hasX x = X 
foo (A x y z) = A (foo x) (foo y) (foo z)
foo (B x y)   = B (foo x) (foo y)
foo (C x)     = C (foo x)
foo (D x)     = D (foo x)
foo (E x i)   = E (foo x) i 
foo x         = x 
```

( @ranjitjhala since you asked for programs that take too long to verify...:) 
This is not made up, rather it is a simplification of a real code.

**Comment by ranjitjhala** [comment]
This is a great example thanks. It's shocking that it takes >5 mins...

**Comment by ranjitjhala** [comment]
Wait, the above takes  > 5mins even _without_ PLE?!!!

**Comment by ranjitjhala** [comment]
Looks like the problem is that the "case expand" 
thing blows everything up then, right? 

(i.e. it has nothing to do with PLE).

Also it would be worth looking at just what the raw "core" is...

**Comment by nikivazou** [comment]
Case expand would fix the time. But in my case I cannot use it because I want to reflect `foo` and reflection into logic does not deal breaks with the `Default` case.

BTW, I *believe* this would be fine in the 7 version of ghc and liquid, but from 7 to 8 in ghc they changed things on case patterns and some of our "optimizations" were not ported.

**Comment by ranjitjhala** [comment]
@nikivazou two questions:

1. Does this ALSO take 2 mins with GHC 7? (2mins is absurd...)
2. Why exactly does `--no-case-expand` "break reflection of `foo`" ? Is it something fundamental? Or just something where the `CoreToLogic` has to be extended a bit?

**Comment by ranjitjhala** [comment]
@nikivazou -- at [some point](https://github.com/ucsd-progsys/liquidhaskell/commit/ec7f030e74cd352e9944ff83d8202028fd4db905) I extended the `caseToLg` to handle 
`DEFAULT`, so we can reflect functions with it. See:

https://github.com/ucsd-progsys/liquidhaskell/pull/1274/files#diff-161a5b61bb0e96d3ee5aa0ee9bf0412f

**Comment by ranjitjhala** [comment]
However, looks like `measure` still fails with a `DEFAULT`.

**Comment by nikivazou** [comment]
Yes, I noticed it too. measure fails with DEFAULT when the no-case-expand is on...

**Comment by ranjitjhala** [comment]
Wow, this is what case-expand does, just to @nikivazou 's  `hasX` function:

  https://gist.github.com/ranjitjhala/936252b2a12bbb7666849167d12780b9

it takes GHC core from about 48 lines to about ... 4800 lines.

[The one thing this persuades me is that *by default* we should have `--no-case-expand`.]
