### ISSUE TITLE
Supporting Nix

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#1099]
One neat feature of Nix is that it lets you create transient GHC environments with a corresponding package database.  For example, if I do:

```shell
$ nix-shell --packages 'haskellPackages.ghcWithPackages (pkgs : [ pkgs.vector ])'
```

... then that opens up a shell that has `ghc` set up with a package database that has `vector` installed:

```shell
$ which ghc
/nix/store/977v65a30a1n69hqqadaiaqb1vyrbwj0-ghc-8.0.1-with-packages/bin/ghc
$ which ghc-pkg
/nix/store/977v65a30a1n69hqqadaiaqb1vyrbwj0-ghc-8.0.1-with-packages/bin/ghc-pkg
$ ghc-pkg list
/nix/store/977v65a30a1n69hqqadaiaqb1vyrbwj0-ghc-8.0.1-with-packages/lib/ghc-8.0.1/package.conf.d
    Cabal-1.24.0.0
    array-0.5.1.1
    base-4.9.0.0
    binary-0.8.3.0
    bytestring-0.10.8.1
    containers-0.5.7.1
    deepseq-1.4.2.0
    directory-1.2.6.2
    filepath-1.4.1.0
    ghc-8.0.1
    ghc-boot-8.0.1
    ghc-boot-th-8.0.1
    ghc-prim-0.5.0.0
    ghci-8.0.1
    haskeline-0.7.2.3
    hoopl-3.10.2.1
    hpc-0.6.0.3
    integer-gmp-1.0.0.1
    pretty-1.1.3.3
    primitive-0.6.1.0
    process-1.4.2.0
    rts-1.0
    template-haskell-2.11.0.0
    terminfo-0.4.0.2
    time-1.6.0.1
    transformers-0.5.2.0
    unix-2.7.2.0
    vector-0.11.0.0
    xhtml-3000.2.1
$ ghci
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Prelude> :type Data.Vector.length
Data.Vector.length :: Data.Vector.Vector a -> Int
```

However, for some reason, the `liquid` executable does not appear to use the `ghc` provided by `nix-shell` nor does it use the matching package database

My main questions are:

* How does `liquid` determine which GHC package database to use?
* How can I configure `liquid` to use the GHC executable or package database supplied by Nix?

**Comment by ranjitjhala** [comment]
Hi @Gabriel439, sorry for the delay! There was a point when we had a bunch of code to configure the databases, but with `stack` all that become redundant. Still let me dig around a bit this evening to see how this works...

**Comment by ranjitjhala** [comment]
IIRC `liquid` uses the GHC API (not the binary), so it uses whatever GHC it was built with.

I wonder if there is a way to pass in the package database 
path by using the `--ghc-option` flag, which passes its 
arguments in to GHC?

```
 --ghc-option=OPTION --ghcoptions
```

**Comment by Gabriel439** [comment]
That worked for me!  The only thing I had to be careful with was ensuring that my `nix-shell` loaded the same version of GHC that was used by the `liquid` executable.  In my case my `liquid` executable was built using `ghc-8.0.2`, so I did:

```shell
$ nix-shell -I nixpkgs=/Users/gabriel/proj/nixpkgs --packages 'haskell.packages.ghc802.ghcWithPackages (pkgs: [ pkgs.vector ])'

[nix-shell]$ ghc-pkg list
/nix/store/hy1ihz6ngllvfzyif6b5gf2qgcx54ygz-ghc-8.0.2-with-packages/lib/ghc-8.0.2/package.conf.d
    ...

[nix-shell]$ liquid examples/search.hs --ghc-option='-package-db=/nix/store/hy1ihz6ngllvfzyif6b5gf2qgcx54ygz-ghc-8.0.2-with-packages/lib/ghc-8.0.2/package.conf.d'
...

**** RESULT: SAFE **************************************************************
```

The only remaining thing is figuring out what `stack exec` did so that its package database was automatically picked up by the GHC API

**Comment by gridaphobe** [comment]
Yes, `liquid` is built against the GHC API. IIRC we use the `ghc-paths` package to figure out where the packages are, which means it's linked into the binary. It looks like the nix folks have patched `ghc-paths` to use an environment variable rather than hardcoded paths to get around this issue (long discussion at [nixpkgs](https://github.com/NixOS/nixpkgs/blob/7cd5ff6376fde10e89ad70122d4841dc712884e5/doc/languages-frameworks/haskell.md#how-to-install-a-compiler-with-libraries)).

So perhaps the issue is that those environment variables aren't being set properly? (I'm assuming you also built liquid via nix?) Can you check whether other tools that use the GHC API, like ghc-mod, hdevtools, etc, can see vector? If they can, maybe there's something in their nix expressions that can help us?

**Comment by ranjitjhala** [comment]
Aha, `ghc-paths`! The relevant stuff appears to be here:

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/GHC/Interface.hs#L128


Looks like `libdir` is described here:

```
https://hackage.haskell.org/package/ghc-paths-0.1.0.9/docs/src/GHC-Paths.html#libdir
```

When I did

```
rjhala@borscht ~/r/s/liquidhaskell (T1089)> stack ghci
```

I get:

```
λ> :m +GHC.Paths 
λ> libdir 
"/Users/rjhala/.stack/programs/x86_64-osx/ghc-8.0.2/lib/ghc-8.0.2"
λ> ghc_pkg 
"/Users/rjhala/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg-8.0.2"
```

Also, when run from the command line, I see:

```
rjhala@borscht ~/r/s/liquidhaskell (T1089)> ghc --print-libdir
/Applications/ghc-7.10.2.app/Contents/lib/ghc-7.10.2
rjhala@borscht ~/r/s/liquidhaskell (T1089)> stack exec -- ghc --print-libdir
/Users/rjhala/.stack/programs/x86_64-osx/ghc-8.0.2/lib/ghc-8.0.2
```

**Q:** Is the `libdir` stuff the same as the package database path? Or maybe its enough for GHC to reconstruct the correct package database path?

**Comment by gridaphobe** [comment]
I think this is the relevant environment variable for `stack exec`, but now I'm wondering where `ghc-paths` fits in...

```
> stack exec env | grep GHC
GHC_PACKAGE_PATH=/Users/eseidel13/.stack/global-project/.stack-work/install/x86_64-osx/lts-9.4/8.0.2/pkgdb:/Users/eseidel13/.stack/snapshots/x86_64-osx/lts-9.4/8.0.2/pkgdb:/Users/eseidel13/.stack/programs/x86_64-osx/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d
```

**Comment by ranjitjhala** [comment]
I have the sense that GHC is hardwired to use the $GHC_PACKAGE_PATH
environment variable...?

**Comment by Gabriel439** [comment]
Okay, now I understand what is going on

So, `liquid` built using Nix will respect both the `NIX_GHC_LIBDIR` and `GHC_PATHS_LIBDIR` environment variables:

`stack exec` transiently sets `GHC_PATHS_LIBDIR` which is why `stack exec liquid` works and picks up the GHC package database created by `stack`

`nix-shell` does not set either environment variable, which is why `liquid` did not pick up the package database created by Nix.  I'm not sure if this is intentional or not, but I will open up an issue on `nixpkgs` to see if these environment variables should be set by the `shellHook` for `ghcWithPackages`

However, when I set those environment variables then everything works perfectly.  All you have to do in order to set the correct environment variables inside of a `nix-shell` is to run:

```shell
$ eval "$(egrep ^export "$(type -p ghc)")"
```

... and then everything works correctly

Either way, I think this issue is fixed from my point of view because it's clearly not an issue with Liquid Haskell

**Comment by ranjitjhala** [comment]
Great, thanks a bunch @Gabriel439 ! So, to consolidate, is the following the recipe for now? (May as well add to the README?)

## Usage with nix-shell

1. Create shell, e.g.

```
$ nix-shell -I nixpkgs=/Users/gabriel/proj/nixpkgs --packages 'haskell.packages.ghc802.ghcWithPackages (pkgs: [ pkgs.vector ])'
```

2. Set environment variables

```
[nix-shell]$ eval "$(egrep ^export "$(type -p ghc)")"
```

3. Run LH

```
[nix-shell]$ liquid examples/search.hs
```

**Comment by Gabriel439** [comment]
Yes, that's correct, except you don't need the `-I nixpkgs=/Users/gabriel/proj/nixpkgs`.  That's just an unnecessary flag I left behind from me debugging this

Also, add a note explaining that the `nix-shell` needs to use the same GHC version that the `liquid` executable was built with

**Comment by gridaphobe** [comment]
Thanks for helping debug this @Gabriel439! Can you also ping us the nixpkgs issue number so we can link to it in the README?

**Comment by Gabriel439** [comment]
So after studying this more closely it seems like this is actually a hard limitation of the `--packages` flag to `nix-shell`.  There's no way to set environment variables using `--packages`

Also, the Haskell section of the `nixpkgs` manual did in fact already anticipate this issue and recommends the following approach:

https://nixos.org/nixpkgs/manual/#how-to-create-ad-hoc-environments-for-nix-shell

Specifically:
> For more sophisticated use-cases, however, it’s more convenient to save the desired configuration in a file called shell.nix that looks like this: 
>
> ```nix
> { nixpkgs ? import <nixpkgs> {}, compiler ? "ghc7102" }:
> let
>   inherit (nixpkgs) pkgs;
>   ghc = pkgs.haskell.packages.${compiler}.ghcWithPackages (ps: with ps; [
>           monad-par mtl
>         ]);
> in
> pkgs.stdenv.mkDerivation {
>   name = "my-haskell-env-0";
>   buildInputs = [ ghc ];
>   shellHook = "eval $(egrep ^export ${ghc}/bin/ghc)";
> }
> ```

... and indeed that worked perfectly for my use case.  For my use case (where I needed GHC 8.0.2 and `vector`), I just modified it to:

```nix
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc802" }:
let
  inherit (nixpkgs) pkgs;
  ghc = pkgs.haskell.packages.${compiler}.ghcWithPackages (ps: with ps; [
          vector
        ]);
in
pkgs.stdenv.mkDerivation {
  name = "my-haskell-env-0";
  buildInputs = [ ghc ];
  shellHook = "eval $(egrep ^export ${ghc}/bin/ghc)";
}
```

Another thing worth mentioning is that `liquid` **does** work if you use `nix-shell` without the `--packages` flag (which is the more common use case for project-based development), because that can (and does) set the correct environment variables for the project

So I think there's actually nothing to do on the Nix side either, other than to perhaps document the above trick if people want to use `liquid` outside of a Haskell cabal project.  For example, my use case was using `liquid` to type-check some isolated Haskell source code outside of a project, which is why I was using `--packages` in the first place

**Comment by Gabriel439** [comment]
Also, here is the final `shell.nix` that I came up with (which I'm using for my Liquid Haskell talk):

```nix
let
  inherit (import <nixpkgs> { }) fetchFromGitHub;

  nixpkgs = fetchFromGitHub {
    owner = "NixOS";

    repo = "nixpkgs";

    rev = "1715436b75696d9885b345dd8159e12244d0f7f5";
    sha256 = "18qp76cppm1yxmzdaak9kcllbypvv22c9g7iaycq2wz0qkka6rx5";
  };

  pkgs = import nixpkgs { };

  liquid =
    pkgs.runCommand "liquidhaskell" { buildInputs = [ pkgs.makeWrapper ]; } ''
      mkdir -p $out/bin
      ln -s ${pkgs.haskellPackages.liquidhaskell}/bin/liquid $out/bin
      wrapProgram $out/bin/liquid --prefix PATH : ${pkgs.z3}/bin
    '';

  ghc = pkgs.haskellPackages.ghcWithPackages (ps: with ps; [
          vector
        ]);
in
  pkgs.stdenv.mkDerivation {
    name = "my-haskell-env-0";
    buildInputs = [ ghc liquid ];
    shellHook = "eval $(egrep ^export ${ghc}/bin/ghc)";
  }
```

**Comment by ranjitjhala** [comment]
@Gabriel439 and @gridaphobe -- I added a [NIX.md](/NIX.md) -- with the above instructions. 

When you get a moment can you check if I haven't made any glitches? Thanks!

**Comment by Gabriel439** [comment]
@ranjitjhala: I think one thing that the `NIX.md` needs to stress is that there are two ways to use `liquid` with Nix:

## For a `cabal` project

If you use a `nix-shell` within the context of a Nix-enabled Cabal project then you don't need to take any special precautions to use `liquid` correctly as the right environment variables will already be set

For example, if you do:

```shell
$ cd path/to/cabal/project
$ cabal2nix --shell . >shell.nix
$ nix-shell
[nix-shell]$ cd path/to/src/  # So that `liquid` can resolve relative internal imports
```

... then `liquid` invocations will work without any special considerations

## Outside of a `cabal` project

This section is basically the instructions you already have in `NIX.md`.  This is primarily for ad-hoc tests on isolated Haskell source code that hasn't been converted into a Cabal project yet

**Comment by Gabriel439** [comment]
The other thing to point out is that my example only pins `nixpkgs` for extra reproducibility.  Most users won't need to do that and can get away with just:

```nix
let
  pkgs = import <nixpkgs> { };

  liquid =
    pkgs.runCommand "liquidhaskell" { buildInputs = [ pkgs.makeWrapper ]; } ''
      mkdir -p $out/bin
      ln -s ${pkgs.haskellPackages.liquidhaskell}/bin/liquid $out/bin
      wrapProgram $out/bin/liquid --prefix PATH : ${pkgs.z3}/bin
    '';

  ghc = pkgs.haskellPackages.ghcWithPackages (ps: with ps; [
          vector
        ]);
in
  pkgs.stdenv.mkDerivation {
    name = "my-haskell-env-0";
    buildInputs = [ ghc liquid ];
    shellHook = "eval $(egrep ^export ${ghc}/bin/ghc)";
  }
```

That will let them easily upgrade to newer versions of `liquidhaskell` by upgrading their `nixpkgs` channel
