### ISSUE TITLE
liquid crashing with SMTLIB2 error

### ISSUE THREAD

**Issue by jbrown215** [ucsd-progsys/liquidhaskell#1100]
https://github.com/jbrown215/binah/blob/master/db/UpdateQuery.hs

Running `liquid UpdateQuery.hs` gives the following error message:

:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 141 column 56: invalid declaration, function 'Main.Update' (with the given signature) already declared"

Changing Update to UpdateASDF (to try to get rid of the already declared error?) but that did nothing.

**Comment by jbrown215** [comment]
@ranjitjhala (I can't assign)

**Comment by atondwal** [comment]
`--exact-data-con` creates the liquidhaskell declaration for the datatype, so
`{-@ data Update record typ = Update { updateField :: EntityField record typ, updateValue :: typ } @-}`
is redundant

**Comment by jbrown215** [comment]
Thanks-- removing that got rid of the error

**Comment by ranjitjhala** [comment]
Can you keep it open though; we should fix this so that either it doesn't
crash OR it gives a message saying you don't need the fields...

​

**Comment by ranjitjhala** [comment]
Related to #1085 (removing the refined data definition fixes the problem.)

**Comment by ranjitjhala** [comment]
should be fixed by upcoming T1089 fix
