### ISSUE TITLE
Minor issue with reflected imports

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1102]
I have three modules A, B, and ImportedReflect, as pushed [here](https://github.com/ucsd-progsys/liquidhaskell/commit/1b3f221a86921768f5cfbd45836e4ce9d82adbb7).

Module `ImportedReflect` uses the function `B.bar` and the data type `B.Bar` and the haskell code is using nothing from `A`.
```
module ImportedReflect where

import B 

{-@ theorem :: x:Bar -> {bar x = bar x} @-}
theorem :: Bar -> ()
theorem _ = ()
```

But, both `B.bar` and `B.Bar` use the data `A.Foo`

```
module B where 

import A 

data Bar = Bar {barFoo :: Foo Int Int} 
{-@ data Bar = Bar {barFoo :: Foo} @-}

{-@ reflect bar @-}
bar :: Bar -> Int 
bar (Bar (Foo x _)) = x 
```

with `A` just defining `Foo`

```
module A where 

data Foo a b= Foo {fooA :: a, fooB :: b} 
{-@ data Foo a b = Foo {fooA :: a, fooB :: b} @-} 
```

When I run `liquid  ImportReflected.hs` I get the error `Unbound Symbol A.fooA`. 
This goes away if I import `A` in `ImportedReflect`, but then ghc complains that I import and do not use the module `A` (which is very annoying esp when you turn warnings into errors).

**Comment by ranjitjhala** [comment]
Wonder if this is related to https://github.com/ucsd-progsys/liquidhaskell/issues/1094

[has to do with "transitive imports"]

**Comment by ranjitjhala** [comment]
Hmm, this works fine if you:

1. Use `exact-data-con` and 
2. Drop the `{-@ data ... @-}` lines.

I think the problem may be because when 
explicit field names are provided, 
the serialized names are not qualified?

**Comment by nikivazou** [comment]
Oh, I don't need the `{-@data ...@-}` lines anymore to reflect data constructors?

**Comment by ranjitjhala** [comment]
Nope. But you need the `--exact-data-con`. 

We still need `{-@ data ... @-}` if there are refinements on fields though...

**Comment by ranjitjhala** [comment]
And if you have an associated size then you just need to write:

```
{-@ data Thing [sizeFun] @-}
```

(as before)

**Comment by nikivazou** [comment]
Oh, great. 

Is it the case that 

- If I have only the Haskell definition `data Foo` the you generate some "default" selectors and checkers to reflect `Foo`, 
- If I also have the refined definition `{-@ data Foo @-}` then you use the refinement fields for the selectors?

If you always use the "default" ones (ignore the `{-@ data Foo @-}`) for the reflection, then this issue would be solved.

**Comment by ranjitjhala** [comment]
If you have just `{-@ data Foo @-}` then there are no refinement fields? 

Did you mean `{-@ data Foo =  ... @-}` ? 

What did you mean by "ignore the `{-@ data Foo @-}`" ? 

Did you mean ignore the *field names* inside the data definition?

**Comment by nikivazou** [comment]
Yes! You do not need the field names inside the data definition to reflect the data.

**Comment by ranjitjhala** [comment]
Well now there is no need to write `{-@ data Foo @-}`; if you write `--exact-data-con` then all data descriptions get lifted. IIRC.

**Comment by ranjitjhala** [comment]
So the below works:

```haskell
-- ImpA.hs

{-@ LIQUID "--exact-data-con" @-}
module ImpA where 

data Foo a b = Foo {fooA :: a, fooB :: b} 
```

```haskell
-- ImpB.hs
{-@ LIQUID "--exact-data-con" @-}

module ImpB where 

import ImpA 

data Bar = Bar {barFoo :: Foo Int Int} 

{-@ reflect bar @-}
bar :: Bar -> Int 
bar (Bar (Foo x _)) = x 
```

```haskell
-- ImpC.hs

module ImpC where

import ImpB 

{-@ theorem :: x:Bar -> {bar x = bar x} @-}
theorem :: Bar -> ()
theorem _ = ()
```

**Comment by nikivazou** [comment]
Great! By my point is that adding 

```
{-@ data Foo a b = Foo {fooA :: a, fooB :: b} @-}
```
to A.hs should not break things, which seems feasible.

**Comment by ranjitjhala** [comment]
Yes, I agree, it should not break things,
so keep this issue open and I'll take a
look!

**Comment by nikivazou** [comment]
As another alternative @jprider63 just suggested something like ` {-@ import A @-}` that will make ghc not complain.

**Comment by nikivazou** [comment]
Also, I suggest that the error `Unbound Symbol A.fooA` comes with a 
"you might need to run liquid on module A" suggestion.

**Comment by ranjitjhala** [comment]
Really there should be no error here...

**Comment by ranjitjhala** [comment]
When we use the `{-@ data  ... @-}` the field-name-measures being used/saved *are not* qualified, but exactly as in the definition. However, it seems that names in the reflected signatures *are* qualified. This is why when we later (in module C) try to look up the (qualified) name `A.fooA` it says ... maybe you meant `fooA`.

*Solution:* Qualify the user-defined field-name-measures.

**Comment by ranjitjhala** [comment]
should be fixed by upcoming T1089 PR
