### ISSUE TITLE
LH gets stuck while checking Fibonacci with PLE when run as root

### ISSUE THREAD

**Issue by vikraman** [ucsd-progsys/liquidhaskell#1111]
We noticed this when building the Dockerfile. It goes into a data race with the z3 process. It works fine when run as a non-root user.

**Comment by ranjitjhala** [comment]
!!!!!!!

**Comment by ranjitjhala** [comment]
> It goes into a data race with the z3 process.

How do you know this? Just wondering where to even _begin_ to debug this...!

**Comment by ranjitjhala** [comment]
Do you or @atondwal recall the strace incantation used to determine this?

**Comment by ranjitjhala** [comment]
Is this still an issue? Btw, I've found that often the z3 hanging is actually a "sort"-error (for some reason it sometimes hangs instead...)

So if this is still a thing you can post the `.smt2` file?
