### ISSUE TITLE
invalid number of parameters to sort constructor

### ISSUE THREAD

**Issue by RyanGlScott** [ucsd-progsys/liquidhaskell#1118]
A slight variation on #1117 gives a different error. This time, three files are required:

```haskell
module AuxDef where

data U1 p = U1
data Product f g p = Product (f p) (g p)
```
```haskell
{-@ LIQUID "--higherorder"        @-}
{-@ LIQUID "--exactdc"            @-}
module Aux where

import AuxDef

{-@ data Product @-}
```
```haskell
{-@ LIQUID "--higherorder"        @-}
{-@ LIQUID "--exactdc"            @-}
module Bug where

import Aux
import AuxDef
import Language.Haskell.Liquid.ProofCombinators

{-@ axiomatize leqU1 @-}
leqU1 :: U1 p -> U1 p -> Bool
leqU1 _ _ = True

{-@ leqU1Refl :: x:U1 p -> { leqU1 x x } @-}
leqU1Refl :: U1 p -> Proof
leqU1Refl U1 = leqU1 U1 U1 ==. True *** QED

{-@ axiomatize leqProd @-}
leqProd :: Eq (f p)
        => (f p -> f p -> Bool) -> (g p -> g p -> Bool)
        -> Product f g p -> Product f g p -> Bool
leqProd leqFP leqGP (Product x1 y1) (Product x2 y2) =
  if x1 == x2
    then leqGP y1 y2
    else leqFP x1 x2
{-# INLINE leqProd #-}
```

```
$ /opt/cabal/head/bin/cabal new-run liquid -- Aux.hs
Up to date
LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************
 

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  Transformed Core ***************************************************
 

**** DONE:  Uniqify & Rename ***************************************************
 

**** DONE:  Defunctionalize ****************************************************
 

**** DONE:  Elaborate **********************************************************
 

**** DONE:  Instantiate ********************************************************
 

**** DONE:  Worklist Initialize ************************************************
 
Working -9223372036854775808% []

**** DONE:  annotate ***********************************************************
 

**** RESULT: SAFE **************************************************************
$ /opt/cabal/head/bin/cabal new-run liquid -- Bug.hs 
Up to date
LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************
 

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  Transformed Core ***************************************************
 

**** DONE:  Uniqify & Rename ***************************************************
 

**** DONE:  Defunctionalize ****************************************************
 

**** DONE:  Elaborate **********************************************************
 

**** DONE:  Instantiate ********************************************************
 

**** DONE:  Worklist Initialize ************************************************
 
Working 100% [=================================================================]

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 45 column 66: invalid number of parameters to sort constructor"
```

I'm using `liquidhaskell` commit a5545e942fca3b106407ec5b2b72c4596ee838ff and `liquid-fixpoint` commit https://github.com/ucsd-progsys/liquid-fixpoint/commit/1148baa43b3869bf44518879687a956490544162.

**Comment by ranjitjhala** [comment]
Does this crash if you remove the `{-@ data Product @-}` (it should not be required.)

**Comment by RyanGlScott** [comment]
You're right, it doesn't crash if I remove `{-@ data Product @-}`.

I have to admit that I find this somewhat confusing—I was under the impression that `leqProd` would fail to axiomatize if the `Product` constructor wasn't reflected.

**Comment by ranjitjhala** [comment]
haha. this AGAIN causes my machine (mac) to hang, just like #1113.
 
Looks like when this error gets tickled on z3, older versions hang on the mac? god knows...

At any rate, lets see if this properly reproduces the error on Linux!

**Comment by ranjitjhala** [comment]
When you write `--exact-data-con` you don't have to write `{-@ data Product @-}` any more; it will do the lifting automatically (if needed.) I had asked if you were ok with having to write it because it would make my life easier, but it turns out it was easy enough just to do without the extra annotation...

**Comment by ranjitjhala** [comment]
c.f. https://github.com/ucsd-progsys/liquidhaskell/issues/1112#issuecomment-334916226

**Comment by RyanGlScott** [comment]
Huh, interesting. So the lifting happens even for datatypes on which I don't run `liquid`? That is, despite the fact that I don't run `liquid` on `AuxDef`, the lifting occurs when I run `liquid` on files that _import_ `AuxDef`?

A related question is: under what scenarios am I _required_ to write `{-@ data Product @-}`?

**Comment by ranjitjhala** [comment]
1. Correct, lifting occurs when you run liquid on files that import `AuxDef`.
2. You should _never_ have to write `{-@ data Product @-}`. 

At best, if you want to specify some default measure you can say: 

`{-@ data Product [measureName] @-}`

or of course if you have refined data constructors... 

But in both those cases, you really should add the refined definition in 
the "home" module (where `Product` was defined.)
