### ISSUE TITLE
Implicit measure invariants are not imported

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1125]
When a measure is defined, its post conditions are turned into `invariant`s

```
{-@ measure length @-}
{-@ length :: L a -> Nat @-}
length N        = 0 
length (C _ xs) = 1 + length xs
```

Now when `length` is imported, the implicit invariants are not imported. 

For example, for the [`Theorems.hs`](https://github.com/nikivazou/theorem-proving-template/blob/master/safe-lists/src/Theorems/List.hs) to be SAFE, I need to explicitly define the following invariant [here](https://github.com/nikivazou/theorem-proving-template/blob/master/safe-lists/src/Data/List.hs#L15): 

```
{-@ invariant {v:L a| 0 <= length v } @-}
```

**Comment by ranjitjhala** [comment]
duplicate with #1180
