### ISSUE TITLE
Type aliases are not hygienic

### ISSUE THREAD

**Issue by y-taka-23** [ucsd-progsys/liquidhaskell#1146]
Hi, I tried the current HEAD (16307c7403ba1aeeef9205b414785d36e93a402b) and bumped an anomaly. The following is the minimal snippet to reproduce the trouble:

Input:
```haskell
module Main where

{-@ type Exactly N = { n:Int | n == N } @-}

{-@ incr :: n:Int -> Exactly { n + 1 } @-}
incr :: Int -> Int
incr n = n + 1
```

Output:
```console
/home/ytaka23/test-lh/Main.hs:7:10-14: Error: Liquid Type Mismatch
  
 7 | incr n = n + 1
              ^^^^^
  
   Inferred type
     VV : {v : Int | v == n + ?a}
  
   not a subtype of Required type
     VV : {VV : Int | VV == VV + 1}
  
   In Context
     n : Int
      
     ?a : {?a : Int | ?a == (1 : int)}
```

In fact, it goes well after I changed the `type` alias to:

```haskell
{-@ type Exactly N = { m:Int | m == N } @-}
```

So I guess, the `n` in the `type` and the function argument seem to conflict each other.

IMHO, such variable names are better to be scoped just in the `type` annotation. Speaking of a version in the past (61929e06503a41376d3b1af014bbc876b5da13ae), I know the "troubled" snippet actually worked. Is this the intended design?

**Comment by ranjitjhala** [comment]
Oops this is terrible, many thanks for pointing it out!

**Comment by ranjitjhala** [comment]
Hi @y-taka-23, 

many thanks again for pointing this out! It should be fixed now in `develop`.
 
   https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/T1146.hs

If you get a chance, can you confirm that it works for you?

**Comment by y-taka-23** [comment]
@ranjitjhala Year it works. Thanks!
