### ISSUE TITLE
Support Unconstrained Values in Reflected Terms

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1148]
(Posted on behalf of @jbrown215)

I was working on modelling the world and ran into what may be a bug in liquid haskell:

https://github.com/jbrown215/binah/blob/master/db/world/World.hs

I expect this to pass, but it gives two errors: one for makeBlob and one for makeRange
(Error message here: https://gist.github.com/jbrown215/2bd60740f7681c1b6f35ab9faa23c070)

I assumed that since I put a refinement on the blob record type that liquid haskell would know that
"xVal canonicalBlob" must always be 3, but it seems to not be able to show that. Is this intended?

For more context, I want to do this to have some canonical reference to the record representing a table so that I can access the refinements on its fields. It's not quite clear to me how to encode the world, so I may be approaching this in a bad way. The goal is for me to be able to refer to the refinements from other records while defining a record. Is there an obvious cleaner solution that comes to mind?

**Comment by ranjitjhala** [comment]
Hi @jbrown215 I made this an issue as its a tricky question that may show up elsewhere. Ok so here's the deal:

> I assumed that since I put a refinement on the blob record type that
> liquid haskell would know that
> `xVal canonicalBlob` must always be `3`, 
> but it seems to not be able to show that. Is this intended?

You are correct, that is indeed the goal of the data-constructor refinements. 

The reason its *not* happening here is because the `canonicalBlob` 
is defined as a `measure` and hence is not visible _during_ constraint
generation. If you instead make it a Haskell binder then the code is checked, 
so the following is marked SAFE by LH:

```
{- measure canonicalBlob :: Blob @-}

{-@ reflect canonicalBlob @-}
canonicalBlob = Blob 3 10
```

It would be nice to NOT have to hardwire the `Blob 3 10` 
i.e. to have globally visible "ghost constants" like `canonicalBlob`
but maybe the above works for now?

**Comment by jbrown215** [comment]
Hey Ranjit,

This is _mostly_ good, and definitely good enough to unblock me. My only concern is that this canonical representation leaks more specific refinements that may not be true of all blobs. Take the following example:

```haskell
{-@ LIQUID "--higherorder"                         @-}
{-@ LIQUID "--no-termination"                      @-}
{-@ LIQUID "--automatic-instances=liquidinstances" @-}

{-# LANGUAGE ExistentialQuantification, KindSignatures, TypeFamilies, GADTs #-}

module World where

{-@ data Blob = Blob {xVal :: {v:Int | v = 3}, yVal :: Int} @-}
data Blob = Blob {xVal :: Int, yVal :: Int}

{-@ reflect canonicalBlob @-}
canonicalBlob = Blob 3 10

{-@ data Range = Range {lower :: {v:Int | v = (xVal canonicalBlob)}, upper :: {v:Int | v == yVal canonicalBlob}} @-}
data Range = Range {lower :: Int, upper :: Int}

makeRange :: () -> Range
makeRange () = Range {lower = 3, upper = 10}
```

This passes, since upper is set to 10 in `makeRange`. However, if set to any other value it should fail. I think that it should always fail, since nothing is known of a canonical blob's yValue just from its refinements.

I guess what I'm really searching for is just a way to access the refinements from the data definition instead of a specific value of that type. But again, this is not blocking me now so I can make progress as is!

**Comment by ranjitjhala** [comment]
Yup. What we need is a way to allow `undefined` inside `reflected` functions...

**Comment by atondwal** [comment]
Until then, here's a workaround:

```
{-@ reflect canonicalBlob @-}
canonicalBlob = Blob 3 (undef ())

{-@ reflect undef @-}
undef a = undef a
```

**Comment by ranjitjhala** [comment]
Ah yes, that would work, nice! But assuming we'd have to run with `--no-termination` ?

**Comment by nikivazou** [comment]
Isn't it dangerous to reflect the diverging undefined into the logic?

**Comment by ranjitjhala** [comment]
well, no more than any other uses of "--no-termination" :-)

but anyways, we clearly want a 'safe' way to do something
like the above; should be easy to implement as an extension
in FP.

**Comment by nikivazou** [comment]
I think we figured out a way.... @jbrown215 will explain the details but the idea is simply that

Undefined in the logic is just uninterpreted functions :) 


@ranjitjhala, I kind of disagree:  reflecting undefined is "I intentionally reflect something diverging", while "--no-termination" is trust me I know it is terminating and I will prove it later.

**Comment by ranjitjhala** [comment]
Yup, I was also envisioning using UIFs to encode 'undefined' ...

Whats the difference between "intensionally" and "trust me" :) ?

**Comment by nikivazou** [comment]
It is the same difference as making a Coq proof by 
- using Admitted or 
- abusing a potential Coq bug that I know it exists :)

**Comment by jbrown215** [comment]
Here's the new code sample:

```haskell
{-@ LIQUID "--higherorder"                         @-}
{-@ LIQUID "--no-termination"                      @-}
{-@ LIQUID "--automatic-instances=liquidinstances" @-}

module World where

{-@ data Blob = Blob {xVal :: {v:Int | v = 3}, yVal :: Int} @-}
data Blob = Blob {xVal :: Int, yVal :: Int}


{-@ data Range = Range {lower :: {v:Int | v = (xVal canonicalBlob)}, upper :: Int} @-}
data Range = Range {lower :: Int, upper :: Int}

-- this defines an uninterpreted function, ie not executable and zero information
{-@ measure canonicalBlob :: Blob @-}

-- this defines invariants on the canonicalBlob
{-@ assume blob_invariant :: {v:() | xVal canonicalBlob  == 3} @-}
blob_invariant :: ()
blob_invariant = ()

{-@ measure canonicalRange :: Range @-}
{-@ assume range_invariant :: {v:() | upper canonicalRange == yVal canonicalBlob } @-}
range_invariant :: ()
range_invariant = ()

{-@ assume range_invariant2 :: {v:() | lower canonicalRange == xVal canonicalBlob } @-}
range_invariant2 :: ()
range_invariant2 = ()


{- World is represented as globally accessible, decentralized, canonical version
 - of the data in the database. This allows us to add refinements that reference
 - the refinements on other tables!
 -}

{-@ makeBlob :: () -> {b:Blob | xVal b == (xVal canonicalBlob)} @-}
makeBlob :: () -> Blob
makeBlob () = Blob {xVal = 3, yVal = 4}

{-@ makeRange :: () -> {r:Range | lower r == (xVal canonicalBlob)} @-}
makeRange :: () -> Range
makeRange () = Range {lower = 3, upper = 9}
```

We've added these "range_invariant"s and "blob_invariant"s as a way of encoding assumptions about our `canonicalRange` and `canonicalBlob` into the logic. This gives us access to the refinements in our logic while also not requiring a specific value for the `canonical` representation of a record. The code above is safe as expected, and indeed is what I was going for in my world model.

The code sample that I gave in response to Ranjit's earlier recommendation would now look like this:

```haskell
{-@ LIQUID "--higherorder"                         @-}
{-@ LIQUID "--no-termination"                      @-}
{-@ LIQUID "--automatic-instances=liquidinstances" @-}

module World where

{-@ data Blob = Blob {xVal :: {v:Int | v = 3}, yVal :: Int} @-}
data Blob = Blob {xVal :: Int, yVal :: Int}


{-@ data Range = Range {lower :: {v:Int | v = (xVal canonicalBlob)}, upper :: {v:Int | v == yVal canonicalBlob}} @-}
data Range = Range {lower :: Int, upper :: Int}

-- this defines an uninterpreted function, ie not executable and zero information
{-@ measure canonicalBlob :: Blob @-}

-- this defines invariants on the canonicalBlob
{-@ assume blob_invariant :: {v:() | xVal canonicalBlob  == 3} @-}
blob_invariant :: ()
blob_invariant = ()

{-@ measure canonicalRange :: Range @-}
{-@ assume range_invariant :: {v:() | upper canonicalRange == yVal canonicalBlob } @-}
range_invariant :: ()
range_invariant = ()

{-@ assume range_invariant2 :: {v:() | lower canonicalRange == xVal canonicalBlob } @-}
range_invariant2 :: ()
range_invariant2 = ()


{- World is represented as globally accessible, decentralized, canonical version
 - of the data in the database. This allows us to add refinements that reference
 - the refinements on other tables!
 -}

{-@ makeBlob :: () -> {b:Blob | xVal b == (xVal canonicalBlob)} @-}
makeBlob :: () -> Blob
makeBlob () = Blob {xVal = 3, yVal = 4}

{-@ makeRange :: () -> {r:Range | lower r == (xVal canonicalBlob)} @-}
makeRange :: () -> Range
makeRange () = Range {lower = 3, upper = 9}
```

As expected, this fails verification, since nothing is known about the Blob's yValue, so makeRange cannot be verified!

**Comment by ranjitjhala** [comment]
hi @jbrown215 -- to clarify: are you still stuck on this or is the above a suitable workaround? Thanks!

**Comment by jbrown215** [comment]
No longer blocked-- niki's workaround works!

**Comment by ranjitjhala** [comment]
Changing the title as what we ought to do is to add a thing like the below into ProofCombinators or the LH prelude:

```haskell
{-@ measure nonDetValue :: () -> a @-}
{-@ assume nonDetValue :: () -> {v:a | v = nonDetValue ()} @-}
nonDetValue :: () -> a 
```

and then allow the user to *reflect* functions that have 
calls to `nonDetValue` inside their bodies.

It may be better to think of a

**Comment by ranjitjhala** [comment]
Or maybe we should just let things be. 

May I close this issue then @jbrown215 ?

**Comment by jbrown215** [comment]
You may, @ranjitjhala . Thank you!
