### ISSUE TITLE
Use of reflect causes "Bad Data Specification"

### ISSUE THREAD

**Issue by edsko** [ucsd-progsys/liquidhaskell#1153]
This

``` haskell
{-@ LIQUID "--exact-data-cons" @-}
{-@ LIQUID "--no-adt" @-}

module Step2 where

{-@ reflect sumListWith @-}
sumListWith :: [Int] -> Int -> Int
sumListWith []       c = c
sumListWith (c : cs) _ = sumListWith cs c

{-@ reflect sumList @-}
sumList :: [Int] -> Int
sumList cs = sumListWith cs 0
```

yields

``` 
 <no source information>:0:0: Error: Bad Data Specification
 GHC.Types.[] :: Mismatch in number of type variables
```

Browsing through the existing issues, maybe this is related to, or even the same issue as, https://github.com/ucsd-progsys/liquidhaskell/issues/885, especially given @nikivazou 's comment https://github.com/ucsd-progsys/liquidhaskell/issues/885#issuecomment-265826595 that we cannot reflect functions on imported datatypes. I don't know if that is still the case or not; however, what is confusing is that when I comment out `sumList` and just leave `sumListWith` the program does get accepted. Having said that, replacing `[]` with a custom type it does go through

``` haskell
{-@ LIQUID "--exact-data-cons" @-}
{-@ LIQUID "--no-adt" @-}

module Step2 where

{-@ data List [listLen] a = Nil | Cons { hd :: a , tl :: List a } @-}
data List a = Nil | Cons a (List a)

{-@ measure listLen @-}
{-@ listLen :: List a -> Nat @-}
listLen :: List a -> Int
listLen Nil        = 0
listLen (Cons _ cs) = 1 + listLen cs

{-@ reflect sumListWith @-}
sumListWith :: List Int -> Int -> Int
sumListWith Nil        c = c
sumListWith (Cons c cs) _ = sumListWith cs c

{-@ reflect sumList @-}
sumList :: List Int -> Int
sumList cs = sumListWith cs 0
```

**Comment by edsko** [comment]
The name of the function does not reflect what it does.. ignore that please :flushed: :)

**Comment by nikivazou** [comment]
Hey @edsko, you can use imported data types in your reflected functions, but only when Liquid Haskell can "see" the source that your data types are defined. See this for a template setup 

https://github.com/nikivazou/theorem-proving-template

It is important that you first run `liquid` on the files that define your lists and then run `liquid` on the files that use/reflect lists.

I was actually surprised from your previous issue that reflection of build-in lists went though and hoped that Ranjit fixed it, but it seems that we still do not support build-in Haskell lists.

**Comment by ranjitjhala** [comment]
Hi @edsko,

This was some recent oddity (perhaps a change in the GHC 8.2 API, you might know)
but at any rate, is fixed in the recent `develop` (just a couple of days ago :) )

[For some reason, querying GHC for `tyConTyVars listTyCon` was returning the empty list?]

- Ranjit.

**Comment by ranjitjhala** [comment]
(Just double checked that the above works in b95e481fe5a0eda7d59d6e333662bc8d310e7ad0)

**Comment by edsko** [comment]
Ah, I should have checked whether this was resolved by a more recent commit; I was only a few commits behind though :) 

When using the built-in lists, how does one refer to nil and cons? Saying `[]` yields a syntax error.

**Comment by edsko** [comment]
I'm not aware of any GHC API changes but I'm not actively involved with ghc dev at the moment; I'll ask my colleague Ben.

**Comment by edsko** [comment]
I asked Ben and he wasn't aware of any recent changes in this domain; if you feel that this is a ghc bug, could you file an issue at https://ghc.haskell.org/trac/ghc ? It would be good to know this upstream.

**Comment by ranjitjhala** [comment]
Hmm did you mean in the refinements themselves i.e. "1:2:3:[]" throws a
parse error right now?

Good point: We need to extend the parser!

**Comment by ranjitjhala** [comment]
Btw there's a workaround at the moment: you can use Haskell functions as
predicates in the refinement.

If you show me an example of what you're trying to do I can modify it
suitably...

**Comment by ranjitjhala** [comment]
For example, the following, instead of writing:

```
{-@ listLitPf :: x:Int -> y:Int -> {addList [x, y] == x + y} @-}
```

or 

``` 
{-@ listLitPf :: x:Int -> y:Int -> {addList (x : y : []) == x + y} @-}
```

which would require parsing list literals, you can define a Haskell function for that expression

```haskell
{-@ inline twoList @-}  -- or you can use `reflect` here too, it has the same effect.
twoList :: a -> a -> [a]
twoList x y = [x, y]
```

and then write:

```haskell
{-@ LIQUID "--exact-data-cons" @-}
{-@ LIQUID "--no-adt" @-}
{-@ LIQUID "--automatic-instances=liquidinstances" @-}

module Step2 where

{-@ reflect sumListWith @-}
sumListWith :: [Int] -> Int -> Int
sumListWith []       c = c
sumListWith (c : cs) _ = sumListWith cs c

{-@ reflect sumList @-}
sumList :: [Int] -> Int
sumList cs = sumListWith cs 0


{-@ listLitPf :: x:Int -> y:Int -> {addList (twoList x y) == x + y} @-}
listLitPf :: Int -> Int -> ()
listLitPf x y = ()

{-@ reflect twoList @-}
twoList :: a -> a -> [a]
twoList x y = x:y:[]

{-@ reflect addList @-}
addList :: [Int] -> Int
addList [] = 0
addList (x:xs) = x + addList xs
```

**Comment by edsko** [comment]
Ok, perfect, that will do just fine :) Thanks so much!
