### ISSUE TITLE
liquid --version doesn't show any version information

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquidhaskell#1154]
These results from `liquidhaskell-0.8.2.0` don't look right:

~~~
$ liquid --numeric-version
2013-17
$ liquid --version
LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.
~~~

**Comment by ranjitjhala** [comment]
Now we have:

```
rjhala@borscht ~/r/s/liquidhaskell (develop)> stack exec -- liquid --version
LiquidHaskell v.0.8.2.0 Copyright 2013-17 Regents of the University of California. All Rights Reserved.
```

Wonder if there's some way to generate this automatically from cabal?

**Comment by peti** [comment]
> Wonder if there's some way to generate this automatically from cabal?

The auto-generated `Paths_liquidhaskell` module exports `version`, which is taken from the Cabal file.

**Comment by ranjitjhala** [comment]
Awesome, thanks! Have updated it accordingingly!
