### ISSUE TITLE
Proof combinators allow invalid equations

### ISSUE THREAD

**Issue by edsko** [ucsd-progsys/liquidhaskell#1155]
(This isn't a bug really as such, but more of an unfortunate consequence of how the proof combinators are defined. Not sure it's solvable. Perhaps just consider this wishful musing of a new Liquid Haskell practitioner :slightly_smiling_face:)

@nikivazou 's [blog post about proof combinators](https://ucsd-progsys.github.io/liquidhaskell-blog/2016/09/18/refinement-reflection.lhs/) gives the following example:

``` haskell
import Language.Haskell.Liquid.ProofCombinators

{-@ reflect fib @-}
{-@ fib :: i:Nat -> Nat / [i] @-}
fib :: Int -> Int
fib i | i == 0    = 0
      | i == 1    = 1
      | otherwise = fib (i-1) + fib (i-2)

{-@ fibTwoPretty :: { fib 2 == 1 } @-}
fibTwoPretty
  =   fib 2
  ==. fib 1 + fib 0
  *** QED

{-@ fibThree :: _ -> { fib 3 == 2 } @-}
fibThree _
  =   fib 3
  ==. fib 2 + fib 1
  ==. 1     + 1      ∵ fibTwoPretty
  ==. 2
  *** QED
```

This is indeed very pretty, but consider this variation on `fibThree`:

``` haskell
{-@ fibThree :: _ -> { fib 3 == 2 } @-}
fibThree _
  =   fib 3
  ==. fib 2 + fib 1
  ==. 1     + 1      ∵ fibTwoPretty
  ==. 1234 -- or any other nonsense value
  *** QED
```

Running `liquid` on this modified "proof" still yields "SAFE". Of course, in one sense it _is_ safe; having invalid equations like this will not allow us to deduce invalid conclusions. Nonetheless it is unfortunate.

Coming from a Coq background, the one thing I miss most when working with Liquid Haskell is some notion of proof context where I can see what the current state of my goal is and what I have left to prove. Writing out equations like the above helps a little bit with this: in a way, I can spell out the proof context explicitly. If I get stuck in my proof, perhaps it's because I haven't applied some of the "rewrite rules" correctly in my head. The problem described above makes this rather less useful though: when I get some of the equations wrong, Liquid Haskell won't point me to the problem..

**Comment by nikivazou** [comment]
Yes, I know, this is confusing...
It is very high in my TODO list to fix that.... 

This happens because I have implemented `(==.)` to take an optional proof argument using type classes and LH just skips the checks for some reason... 
If you use the operator `(==:)` from the same library [include/Language/Haskell/Liquid/ProofCombinators.hs#L122](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/include/Language/Haskell/Liquid/ProofCombinators.hs#L122) the intermediate steps will be checked (but then you need to always provide proof arguments, or use another operator when you do not provide proof arguments).

**Comment by edsko** [comment]
Ah! Perfect. I didn't realize this was due to some subtle interaction with the type class. I will use `==:` so :)

**Comment by edsko** [comment]
Thanks so much once again for pointing this out. I can now build up proofs gradually and catch errors. Soooo much better :)

**Comment by ranjitjhala** [comment]
@nikivazou we should find some prominent way to link to the examples file you just added?

- https://github.com/ucsd-progsys/liquidhaskell/blob/develop/include/Language/Haskell/Liquid/Example.hs
