### ISSUE TITLE
Ambiguous names cause errors even when unused

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1158]
Importing a module that defines a measure or reflected function with a name that would be ambiguous if used causes an error even if that function is not used. For example, given:

#### Main.hs
```haskell
module Main where

import Foo

main :: IO ()
main = return ()
```

#### Foo.hs
```haskell
module Foo(Foo(..), length) where

import Prelude hiding (length)

{-@ data Foo [length] @-}
data Foo = Bar

{-@ measure length @-}
{-@ length :: Foo -> Nat @-}
length :: Foo -> Int
length Bar = 0
```

Running `liquid Foo.hs` passes, but running `liquid Main.hs` gives
```
Foo.hs:8:13: Error: Ambiguous specification symbol `length`
  
 8 | {-@ measure length @-}
                 ^
  
     Could refer to any of the names
      
     * - Foo.length
      
     * - Data.Foldable.length
```

To fix this, we have to change Main.hs to
```haskell
module Main where

import Prelude hiding (length)
import Foo

main :: IO ()
main = return ()
```
even though we never use `length` (or `Foo`, for that matter) in Main.hs. At the very least the error message should indicate that the error is in Main.hs, not in Foo.hs, but ideally this would not cause an error at all; GHC is happy to ignore conflicting names if they're never used.

**Comment by ranjitjhala** [comment]
Thanks for pointing this out, will get to it ASAP!

**Comment by ranjitjhala** [comment]
On further thought, this is very tricky to fix.

Even though `length` is not _explicitly_ used, `measure`s are effectively **global** names that are associated with the given datatype (here, `[]`) and its constructors and hence, appear _implicitly_ at all sorts of places (e.g. pattern match, and constructor sites). 

Tracking those down will be rather tricky. 

:( 

Hence, closing for now...
