### ISSUE TITLE
Mention #liquidhaskell irc channel in docs

### ISSUE THREAD

**Issue by edsko** [ucsd-progsys/liquidhaskell#1159]
There is a `#liquidhaskell` IRC channel on `freenode`; admittedly it's very very quiet but might be worthwhile mentioning it in the docs.

**Comment by nikivazou** [comment]
I personally do not use irc. 

I generated a slack channel some time ago, quiet too, but will add this in the readme now: 

https://join.slack.com/t/liquidhaskell/shared_invite/enQtMjY4MTk3NDkwODE3LTY1YzBiY2JlZjBjMTM5M2ZkMjNmZDk5ZjA2MGQyZjQ5ZjBmYjZjNGMzOTUyMTU2MDlmM2YzZDM2YjhiMWFjM2I

**Comment by edsko** [comment]
Ok, perfect :) Joined.
