### ISSUE TITLE
Parser for predicates does not support tuples

### ISSUE THREAD

**Issue by edsko** [ucsd-progsys/liquidhaskell#1162]
This

``` haskell
{-@ LIQUID "--exact-data-cons" @-}

module Tuples where

{-@ reflect f @-}
f :: Int -> Int
f x = x

{-@ reflect g @-}
g :: Int -> (Int, Int) -> (Int, Int)
g z (x, y) = (x, y)

{-@ reflect p @-}
p :: (Int, Int) -> Bool
p (x, y) = x == y

{-@ foo :: x:Int -> y:Int -> {z:Int | p (g z (f x, f y))} @-}
foo :: Int -> Int -> Int
foo x y = undefined
```

yields

```
 /home/edsko/wt/clients/iohk/ouroboros-spec/praos/lh/Tuples.hs:17:41: Error: Cannot parse specification:
  
 17 | {-@ foo :: x:Int -> y:Int -> {n:Int | p (g z (f x, f y))} @-}
                                              ^
  
     unexpected "("
     expecting operator, white space or "}"
```

After browsing through issues I found #819 and realize that tuples are not actually supported, but different examples with tuples parse (or rather, fail to parse) in different ways and moreover there does not seem to be an explicit ticket open about tuples so I figured I'd record this one explicitly. Also, for others stumbling across this: can work around this in the manner described in https://github.com/ucsd-progsys/liquidhaskell/issues/1153#issuecomment-341553327 :

``` haskell
{-@ reflect pair @-}
pair :: a -> b -> (a, b)
pair x y = (x, y)

{-@ foo :: x:Int -> y:Int -> {z:Int | p (g z (pair (f x) (f y)))} @-}
foo :: Int -> Int -> Int
foo x y = undefined
```

**Comment by ranjitjhala** [comment]
Thanks for filing this @edsko !

**Comment by ranjitjhala** [comment]
High time we fixed this. @rosekunkel you want to take a crack at it :)

**Comment by ranjitjhala** [comment]
@zgrannan and @nikivazou we should close this then right?  thanks!!

**Comment by zgrannan** [comment]
@ranjitjhala Updated to use the most recent `liquid-fixpoint` and add parser tests in https://github.com/ucsd-progsys/liquidhaskell/pull/1518.
