### ISSUE TITLE
SMTLIB2 crash with z3 4.4.1

### ISSUE THREAD

**Issue by vikraman** [ucsd-progsys/liquidhaskell#1164]
```hs
{-@ LIQUID "--higherorder" @-}

module Boolean where

{-@ dne :: p:(a -> Bool) -> (((x:a -> {p x}) -> {False}) -> {False}) -> x:a -> {p x} @-}
dne :: (a -> Bool) -> (((a -> ()) -> ()) -> ()) -> a -> ()
dne p f x =
  case p x of
    True  -> ()
    False -> f (\g -> g x)
```
```
$ liquid Boolean.hs
LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************


**** DONE:  Extracted Core using GHC *******************************************


**** DONE:  Transformed Core ***************************************************


**** DONE:  Uniqify & Rename ***************************************************

Working 100% [=================================================================]

**** DONE:  annotate ***********************************************************


**** RESULT: ERROR *************************************************************


:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 197 column 1175: Wrong number of arguments (1) passed to function (declare-fun lam_int_arg$35$$35$1 () Int)"
```
The generated `.liquid/Boolean.hs.smt2` and `.liquid/Boolean.hs.evals.smt2` files are here: https://gist.github.com/vikraman/bee891aa8f14d1a121cbe69e3444e753

It works fine on goto, which might be using an older version of z3.

**Comment by nikivazou** [comment]
This seems like a z3 issue. 

Can you simpify the .smt2 files and if this turns out to be a z3 bug, then you should create an issue on z3.

**Comment by ranjitjhala** [comment]
I'd be shocked if its a z3 issue. 

Can you paste a link to the .smt2 file?

**Comment by vikraman** [comment]
@ranjitjhala the smt2 file link is in my issue: https://gist.github.com/vikraman/bee891aa8f14d1a121cbe69e3444e753

```
$ z3 Boolean.hs.smt2
unsat
(error "line 197 column 1175: Wrong number of arguments (1) passed to function (declare-fun lam_int_arg$35$$35$1 () Int)")
sat
```

It looks like `(declare-fun lam_int_arg$35$$35$1 () Int)` is being declared with no arguments, but gets called on line 197 `(smt_lambda lam_int_arg$35$$35$1 (lam_int_arg$35$$35$1 x$35$$35$aw7))` with one argument, if I'm interpreting the syntax correctly.

**Comment by ranjitjhala** [comment]
Yes, thanks @vikraman -- that is indeed the problem, wonder why z3 was not crashing on earlier versions. But yes, the problem is there appears to be a missing "apply" ...

**Comment by ranjitjhala** [comment]
Yes, thanks @vikraman.

That is indeed the problem, a missing `apply`.

On the bright side, I think you're using an old version of LH? 

I just checked that on `develop` the above doesn't happen 
because it does in fact do the right thing viz `apply` etc.

Can you confirm?

**Comment by vikraman** [comment]
Got it, works fine with the latest develop (f4b3f716dc30), I was on the popl18 branch earlier.
