### ISSUE TITLE
Illegal data refinement for `[]` on a file with no annotations

### ISSUE THREAD

**Issue by kozross** [ucsd-progsys/liquidhaskell#1165]
I used Stack to install Liquid Haskell as per the instructions on Github. I then tried ``stack exec liquid src/Test.hs``, with ``Test.hs`` containing no Liquid Haskell annotations of any kind. I got the following output:

```
LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************
 

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


 LH.Bare.listTyDataCons:0:0: Error: Illegal data refinement for `[]`
     Size function len x should have type int.
     Unbound Symbol len
 Perhaps you meant: head, x
```

I then tried adding the following annotation to ``Test.hs``, following the Liquid Haskell  book examples:

```
{-@ type Zero    = {v:Int | v == 0} @-}
```

When I retried ``stack exec liquid src/Test.hs``, I got the exact same error as before. Is there something major I'm missing here, or is it a bug?

**Comment by ranjitjhala** [comment]
Thats odd. Can you paste the exact source you are running LH on so we can reproduce?

**Comment by ranjitjhala** [comment]
Also: is this on `develop` ?

**Comment by ranjitjhala** [comment]
And do you by chance, do `hiding Prelude` ?

**Comment by kozross** [comment]
I've attached the entire Stack-generated project here: [test.zip](https://github.com/ucsd-progsys/liquidhaskell/files/1473034/test.zip) Notably, I do the following:

- Use a Stack nightly (otherwise, Liquid Haskell doesn't work at all)
- Have Protolude included
- Have the NoImplicitPrelude extension enabled

**Comment by ranjitjhala** [comment]
Unfortunately the prelude is kind of hard wired into the specifications
right now, and LH won't work with NoImplicitPrelude.

Still thanks for filing this, we will keep this issue open so that we can
eventually re-factor the dependency on the prelude (or at the very least
allow opting out...)

**Comment by kozross** [comment]
@ranjitjhala Thank you for the information!

**Comment by timjs** [comment]
Had the same problem today, but reading this issue made me aware it's about `NoImplicitPrelude`. Should this be closed?

**Comment by nikivazou** [comment]
Closing it! Thanks!
