### ISSUE TITLE
Will not work with LTS Stack builds

### ISSUE THREAD

**Issue by kozross** [ucsd-progsys/liquidhaskell#1167]
I have installed Liquid Haskell using Stack as per the Github instructions. If I make a new Stack project using an LTS resolver, ``stack exec liquid`` will not work, giving the following error message:

```
liquid: /home/koz/.stack/programs/x86_64-linux/ghc-nopie-8.0.2/lib/ghc-8.0.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not enough bytes)
```

Is this a bug? This shows up as recently as ``lts-9.13``.

**Comment by ranjitjhala** [comment]
Hmm this is because the stack resolvers in the two projects are different,
and hence use different GHC versions. Can you change the stack resolver in
the new stack project to be the same as LH or at least use the same GHC as
LH? E.g. To

```
resolver: nightly-2017-10-06
```

And let me know if that works?

**Comment by kozross** [comment]
Yes, that works. I was just curious if this was a bug or a feature. Clearly, it's a feature.

**Comment by ranjitjhala** [comment]
Yes, its a consequence of using the GHC API...
