### ISSUE TITLE
SMTLIB2 error related to importing and --exact-data-cons

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1169]
I found a strange combination of features that triggers an SMTLIB2 error. In particular, given these two files:
#### Foo.hs
```haskell
{-@ LIQUID "--exact-data-cons" @-}
module Foo where

import Bar

{-@ measure f @-}
f :: () -> Int
f () = 0

{-@ reflect g @-}
g :: () -> A
g () = B
```
#### Bar.hs
```haskell
module Bar (A(..)) where

{-@ data A @-}
data A = B
```
running `liquid Foo.hs` fails with
```
:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 27 column 30: invalid datatype declaration, datatype does not have any constructors"
```
This is a minimal example that I pared down from some real code that was triggering the same issue; doing any of the following causes the problem to disappear:

- Moving the contents of `Bar.hs` into `Foo.hs`
- Removing `f`.
- Removing `g`.
- Removing `{-@ LIQUID "--exact-data-cons" @-}`.

I'm using Z3 version 4.5.0.

**Comment by ranjitjhala** [comment]
Hi @wkunkel ,

thanks for pointing this out.

It should work if you remove the `{-@ data A @-}`  annotation.

In general that annotation should either 

1. List all the constructors of the given data-type (here `A`), *or*
2. Mention the default size parameter for the datatype e.g. (`{-@ data List [len] @-}`).

Of course, there is no way for a user to know that, and so let's keep 
this open till I have added a proper, actionable error message!

**Comment by ranjitjhala** [comment]
We now give an error message:

```
 /Users/rjhala/research/stack/liquidhaskell/tests/errors/EmptyData.hs:5:10: Error: Bad Data Specification

 5 | {-@ data A @-}
              ^

 You should specify either a default [size] or one or more fields in the data declaration for `A`
```
