### ISSUE TITLE
Reflection fails on GHC.Lists?

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1174]
Why does the below fail? (It works fine with `--ple` but not the regular equational proof...)

```haskell
{- LIQUID "--ple"             @-}
{-@ LIQUID "--exact-data-cons" @-}
{-@ LIQUID "--no-adt"          @-}

module PLE where

import Prelude hiding ((++))
import Language.Haskell.Liquid.ProofCombinators

assocThm :: (Eq a) => [a] -> [a] -> [a] -> Bool
assocProof :: [a] -> [a] -> [a] -> Proof

{-@ infix ++ @-}

{-@ reflect ++ @-}
(++) :: [a] -> [a] -> [a]
[]     ++ ys = ys
(x:xs) ++ ys = x : (xs ++ ys)


{-@ reflect assocThm @-}
assocThm xs ys zs = (xs ++ ys) ++ zs == xs ++ (ys ++ zs)


{-@ assocProof :: xs:[a] -> ys:[a] -> zs:[a] -> { assocThm xs ys zs } @-}
assocProof []     ys zs
  =   ([] ++ ys) ++ zs
  ==. [] ++ (ys ++ zs)
  *** QED


assocProof (x:xs) ys zs
  =   ((x:xs) ++ ys) ++ zs
  ==. (x : (xs ++ ys)) ++ zs
  ==: x : ((xs ++ ys) ++ zs) ? ()
  ==. x : (xs ++ (ys ++ zs)) ? assocProof xs ys zs
  ==. (x:xs) ++ (ys ++ zs)
  ***  QED
```

**Comment by atondwal** [comment]
We don't strengthen by the output refinements of functions that are applied only in the spec, so `assocThm` gets treated as a uninterpreted reflected function instead of being expanded (and PLE fixes this by expanding it out one step to its definition).

**Comment by ranjitjhala** [comment]
Oh silly me I thought I'd fixed that by making assicThm an inline!

**Comment by atondwal** [comment]
I believe the problem is that we don't strengthen by the output refinements of functions that are applied only in the spec, so `assocThm` gets treated as a uninterpreted reflected function instead of being expanded (and PLE fixes this by expanding it out one step to its definition).
