### ISSUE TITLE
Liquid + realgcc = :-(((

### ISSUE THREAD

**Issue by nuwus** [ucsd-progsys/liquidhaskell#1177]
Greetings,
got trouble with realgcc \/ liquid. Just installed Liquid Haskell, tried to check first three exercises from book and here's what I've got:

> D:\Haskell-projects\liquid>liquid homework.hs
LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.
realgcc.exe: fatal error: no input files
compilation terminated.
liquid: `gcc.exe' failed in phase `gcc'. (Exit code: 1)

realgcc\gcc is visible in PATH:

> D:\Haskell-projects\liquid>gcc --help
Usage: realgcc.exe [options] file...
Options: ...

Content of homework.hs, if it matters:

> {-@ LIQUID "--notermination" @-}
{-@ type TRUE = {v:Bool | v} @-}
{-@ type FALSE = {v:Bool | not v} @-}
{-@ ex3' :: Bool -> Bool -> TRUE @-} 
ex3' a b = (a => a) || b 

> {-@ exDeMorgan2 :: Bool -> Bool -> TRUE @-}
exDeMorgan2 a b = not (a && b) <=> (not a || not b)

> {-@ ax6 :: Int -> Int -> TRUE @-}
ax6 x y = (0 <= y) ==> (x <= x + y)

Fastgoogling gave me nothing, suggestions?

**Comment by ranjitjhala** [comment]
Wow I'm afraid I've never seen that before! My suggestions would be:

1. Try to use 'stack' which manages the paths and may solve this problem,
and

2. Alternatively, a Linux vm? Actually maybe we can even provide a docker
image for this purpose. @atondwal can you add a link to the aec image ?

**Comment by nuwus** [comment]
Thank you for your answer.
Here's what I've got. 

> **D:\Haskell-projects\liquid-stack>stack install liquidhaskell --resolver=ghc-8.2.1**
Error: While constructing the build plan, the following exceptions were encountered:
> In the dependencies for deepseq-1.3.0.2:
**base-4.10.0.0 must match >=4.3 && <4.8 (latest applicable is 4.7.0.2)** 
needed since deepseq-1.3.0.2 is a build target.
Plan construction failed.

Then I tried ghc-7.8.4:
> **D:\Haskell-projects\liquid-stack>stack install liquidhaskell --resolver=ghc-7.8.4**
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
Error: While constructing the build plan, the following exceptions were encountered:

> In the dependencies for ghc-boot-8.2.1:
**base-4.7.0.2 must match >=4.8 && <4.11 (latest applicable is 4.10.0.0)**
needed since ghc-boot-8.2.1 is a build target.

> In the dependencies for liquid-fixpoint-0.7.0.5:
base-4.7.0.2 must match >=4.8.1.0 && <5 (latest applicable is 4.10.0.0)
needed since liquid-fixpoint-0.7.0.5 is a build target.

> In the dependencies for liquidhaskell-0.8.2.0:
**base-4.7.0.2 must match >=4.8.1.0 && <5 (latest applicable is 4.10.0.0)
ghc-7.8.4 must match ==8.2.1 (latest applicable is 8.2.1)**
needed for unknown reason - stack invariant violated.

> In the dependencies for located-base-0.1.1.1:
base-4.7.0.2 must match >=4.8.1.0 && <5 (latest applicable is 4.10.0.0)
needed since located-base-0.1.1.1 is a build target.
Plan construction failed.

As I can see ghc-8.2.1 requires base-4.7.0.2 and ghc-7.8.4 requires base-4.10.0.0

**Comment by ranjitjhala** [comment]
Hmm. not sure what's going on above, but can you do this:

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#build-with-stack-recommended

**Comment by nuwus** [comment]
When I tried this:
> git clone --recursive git@github.com:ucsd-progsys/liquidhaskell.git

I got a weird error about RSA. So I changed to 
> git clone --recursive https://github.com/ucsd-progsys/liquidhaskell.git

then everything was downloaded except of fixpoint. I downloaded it manually and tried
> cd liquidhaskell
> stack install

But I had the very same error about gcc!
So I finally decide this:
> stack ghci liquidhaskell

and here's what stack gave me:
> D:\Haskell-projects\liquidhaskell>stack ghci liquidhaskell
> The following GHC options are incompatible with GHCi and have not been passed to it: -Werror -threaded
> Configuring GHCi with the following packages: liquidhaskell
> Using main module: 1. Package `liquidhaskell' component exe:liquid with main-is file: D:\Haskell-projects\liquidhaskell\src\Liquid.hs
> GHCi, version 8.2.1: http://www.haskell.org/ghc/  :? for help
> Loaded GHCi configuration from D:\Haskell-projects\liquidhaskell\.ghci
> 
> <command-line>:0:14: error: lexical error (UTF-8 decoding error)
> Failed, 0 modules loaded.
> 
> <command-line>:0:14: error: lexical error (UTF-8 decoding error)
> Failed, 0 modules loaded.
> 
> <no location info>: error:
>     Could not find module `Gradual.Concretize'
>     It is not a module in the current program, or in any known package.
> Loaded GHCi configuration from \AppData\Local\Temp\ghci6824\ghci-script
> Prelude> :q
> Leaving GHCi.

Although I do have Gradual.Concretize:
> 01.12.2017  14:33    <DIR>          .
> 01.12.2017  14:33    <DIR>          ..
> 01.12.2017  14:33    <DIR>          Gradual
> 01.12.2017  14:33             3 532 Gradual.hs
> 01.12.2017  14:33    <DIR>          Language
> 01.12.2017  14:33             1 278 LHi.hs
> 01.12.2017  14:33               140 Liquid.hs
> 01.12.2017  14:33               144 LiquidHaskell.hs
> 01.12.2017  14:33               995 Target.hs
> 01.12.2017  14:33    <DIR>          Test

The content of ghci-script is:

> :add Gradual.Concretize Gradual.GUI Gradual.GUI.Annotate Gradual.GUI.Misc Gradual.GUI.Types Gradual.Misc Gradual.PrettyPrinting Gradual.Refinements Gradual.Trivial Gradual.Types Gradual.Uniquify Language.Haskell.Liquid.Bare Language.Haskell.Liquid.Bare.Axiom Language.Haskell.Liquid.Bare.Check Language.Haskell.Liquid.Bare.DataType Language.Haskell.Liquid.Bare.Env Language.Haskell.Liquid.Bare.Existential Language.Haskell.Liquid.Bare.Expand Language.Haskell.Liquid.Bare.Lookup Language.Haskell.Liquid.Bare.Measure Language.Haskell.Liquid.Bare.Misc Language.Haskell.Liquid.Bare.OfType Language.Haskell.Liquid.Bare.Plugged Language.Haskell.Liquid.Bare.RTEnv Language.Haskell.Liquid.Bare.Resolve Language.Haskell.Liquid.Bare.Spec Language.Haskell.Liquid.Bare.SymSort Language.Haskell.Liquid.Bare.ToBare Language.Haskell.Liquid.Constraint.Constraint Language.Haskell.Liquid.Constraint.Env Language.Haskell.Liquid.Constraint.Fresh Language.Haskell.Liquid.Constraint.Generate Language.Haskell.Liquid.Constraint.Init Language.Haskell.Liquid.Constraint.Monad Language.Haskell.Liquid.Constraint.Qualifier Language.Haskell.Liquid.Constraint.Split Language.Haskell.Liquid.Constraint.ToFixpoint Language.Haskell.Liquid.Constraint.Types Language.Haskell.Liquid.Desugar.Check Language.Haskell.Liquid.Desugar.Coverage Language.Haskell.Liquid.Desugar.Desugar Language.Haskell.Liquid.Desugar.DsArrows Language.Haskell.Liquid.Desugar.DsBinds Language.Haskell.Liquid.Desugar.DsCCall Language.Haskell.Liquid.Desugar.DsExpr Language.Haskell.Liquid.Desugar.DsForeign Language.Haskell.Liquid.Desugar.DsGRHSs Language.Haskell.Liquid.Desugar.DsListComp Language.Haskell.Liquid.Desugar.DsMeta Language.Haskell.Liquid.Desugar.DsMonad Language.Haskell.Liquid.Desugar.DsUtils Language.Haskell.Liquid.Desugar.HscMain Language.Haskell.Liquid.Desugar.Match Language.Haskell.Liquid.Desugar.MatchCon Language.Haskell.Liquid.Desugar.MatchLit Language.Haskell.Liquid.Desugar.StaticPtrTable Language.Haskell.Liquid.Desugar.TmOracle Language.Haskell.Liquid.Foreign Language.Haskell.Liquid.GHC.Interface Language.Haskell.Liquid.GHC.Misc Language.Haskell.Liquid.GHC.Play Language.Haskell.Liquid.GHC.Resugar Language.Haskell.Liquid.GHC.SpanStack Language.Haskell.Liquid.GHC.TypeRep Language.Haskell.Liquid.Interactive.Handler Language.Haskell.Liquid.Interactive.Types Language.Haskell.Liquid.Liquid Language.Haskell.Liquid.List Language.Haskell.Liquid.Measure Language.Haskell.Liquid.Misc Language.Haskell.Liquid.Model Language.Haskell.Liquid.Parse Language.Haskell.Liquid.Prelude Language.Haskell.Liquid.ProofCombinators Language.Haskell.Liquid.Transforms.ANF Language.Haskell.Liquid.Transforms.CoreToLogic Language.Haskell.Liquid.Transforms.Rec Language.Haskell.Liquid.Transforms.RefSplit Language.Haskell.Liquid.Transforms.Rewrite Language.Haskell.Liquid.Transforms.Simplify Language.Haskell.Liquid.Types Language.Haskell.Liquid.Types.Bounds Language.Haskell.Liquid.Types.Dictionaries Language.Haskell.Liquid.Types.Errors Language.Haskell.Liquid.Types.Fresh Language.Haskell.Liquid.Types.Literals Language.Haskell.Liquid.Types.Meet Language.Haskell.Liquid.Types.Names Language.Haskell.Liquid.Types.PredType Language.Haskell.Liquid.Types.PrettyPrint Language.Haskell.Liquid.Types.RefType Language.Haskell.Liquid.Types.Specifications Language.Haskell.Liquid.Types.Strata Language.Haskell.Liquid.Types.Variance Language.Haskell.Liquid.Types.Visitors Language.Haskell.Liquid.UX.ACSS Language.Haskell.Liquid.UX.Annotate Language.Haskell.Liquid.UX.CTags Language.Haskell.Liquid.UX.CmdLine Language.Haskell.Liquid.UX.Config Language.Haskell.Liquid.UX.DiffCheck Language.Haskell.Liquid.UX.Errors Language.Haskell.Liquid.UX.QuasiQuoter Language.Haskell.Liquid.UX.Tidy Language.Haskell.Liquid.WiredIn LiquidHaskell Test.Target Test.Target.Eval Test.Target.Expr Test.Target.Monad Test.Target.Targetable Test.Target.Targetable.Function Test.Target.Testable Test.Target.Types Test.Target.Util
> > :add D:\Haskell-projects\liquidhaskell\src\Liquid.hs
> > :module + Gradual.Concretize Gradual.GUI Gradual.GUI.Annotate Gradual.GUI.Misc Gradual.GUI.Types Gradual.Misc Gradual.PrettyPrinting Gradual.Refinements Gradual.Trivial Gradual.Types Gradual.Uniquify Language.Haskell.Liquid.Bare Language.Haskell.Liquid.Bare.Axiom Language.Haskell.Liquid.Bare.Check Language.Haskell.Liquid.Bare.DataType Language.Haskell.Liquid.Bare.Env Language.Haskell.Liquid.Bare.Existential Language.Haskell.Liquid.Bare.Expand Language.Haskell.Liquid.Bare.Lookup Language.Haskell.Liquid.Bare.Measure Language.Haskell.Liquid.Bare.Misc Language.Haskell.Liquid.Bare.OfType Language.Haskell.Liquid.Bare.Plugged Language.Haskell.Liquid.Bare.RTEnv Language.Haskell.Liquid.Bare.Resolve Language.Haskell.Liquid.Bare.Spec Language.Haskell.Liquid.Bare.SymSort Language.Haskell.Liquid.Bare.ToBare Language.Haskell.Liquid.Constraint.Constraint Language.Haskell.Liquid.Constraint.Env Language.Haskell.Liquid.Constraint.Fresh Language.Haskell.Liquid.Constraint.Generate Language.Haskell.Liquid.Constraint.Init Language.Haskell.Liquid.Constraint.Monad Language.Haskell.Liquid.Constraint.Qualifier Language.Haskell.Liquid.Constraint.Split Language.Haskell.Liquid.Constraint.ToFixpoint Language.Haskell.Liquid.Constraint.Types Language.Haskell.Liquid.Desugar.Check Language.Haskell.Liquid.Desugar.Coverage Language.Haskell.Liquid.Desugar.Desugar Language.Haskell.Liquid.Desugar.DsArrows Language.Haskell.Liquid.Desugar.DsBinds Language.Haskell.Liquid.Desugar.DsCCall Language.Haskell.Liquid.Desugar.DsExpr Language.Haskell.Liquid.Desugar.DsForeign Language.Haskell.Liquid.Desugar.DsGRHSs Language.Haskell.Liquid.Desugar.DsListComp Language.Haskell.Liquid.Desugar.DsMeta Language.Haskell.Liquid.Desugar.DsMonad Language.Haskell.Liquid.Desugar.DsUtils Language.Haskell.Liquid.Desugar.HscMain Language.Haskell.Liquid.Desugar.Match Language.Haskell.Liquid.Desugar.MatchCon Language.Haskell.Liquid.Desugar.MatchLit Language.Haskell.Liquid.Desugar.StaticPtrTable Language.Haskell.Liquid.Desugar.TmOracle Language.Haskell.Liquid.Foreign Language.Haskell.Liquid.GHC.Interface Language.Haskell.Liquid.GHC.Misc Language.Haskell.Liquid.GHC.Play Language.Haskell.Liquid.GHC.Resugar Language.Haskell.Liquid.GHC.SpanStack Language.Haskell.Liquid.GHC.TypeRep Language.Haskell.Liquid.Interactive.Handler Language.Haskell.Liquid.Interactive.Types Language.Haskell.Liquid.Liquid Language.Haskell.Liquid.List Language.Haskell.Liquid.Measure Language.Haskell.Liquid.Misc Language.Haskell.Liquid.Model Language.Haskell.Liquid.Parse Language.Haskell.Liquid.Prelude Language.Haskell.Liquid.ProofCombinators Language.Haskell.Liquid.Transforms.ANF Language.Haskell.Liquid.Transforms.CoreToLogic Language.Haskell.Liquid.Transforms.Rec Language.Haskell.Liquid.Transforms.RefSplit Language.Haskell.Liquid.Transforms.Rewrite Language.Haskell.Liquid.Transforms.Simplify Language.Haskell.Liquid.Types Language.Haskell.Liquid.Types.Bounds Language.Haskell.Liquid.Types.Dictionaries Language.Haskell.Liquid.Types.Errors Language.Haskell.Liquid.Types.Fresh Language.Haskell.Liquid.Types.Literals Language.Haskell.Liquid.Types.Meet Language.Haskell.Liquid.Types.Names Language.Haskell.Liquid.Types.PredType Language.Haskell.Liquid.Types.PrettyPrint Language.Haskell.Liquid.Types.RefType Language.Haskell.Liquid.Types.Specifications Language.Haskell.Liquid.Types.Strata Language.Haskell.Liquid.Types.Variance Language.Haskell.Liquid.Types.Visitors Language.Haskell.Liquid.UX.ACSS Language.Haskell.Liquid.UX.Annotate Language.Haskell.Liquid.UX.CTags Language.Haskell.Liquid.UX.CmdLine Language.Haskell.Liquid.UX.Config Language.Haskell.Liquid.UX.DiffCheck Language.Haskell.Liquid.UX.Errors Language.Haskell.Liquid.UX.QuasiQuoter Language.Haskell.Liquid.UX.Tidy Language.Haskell.Liquid.WiredIn LiquidHaskell Test.Target Test.Target.Eval Test.Target.Expr Test.Target.Monad Test.Target.Targetable Test.Target.Targetable.Function Test.Target.Testable Test.Target.Types Test.Target.Util
>

**Comment by atondwal** [comment]
(if you're so inclined you can run LH in docker with `docker run -it parfunc/popl18-lh-prover-artifact bash`)

**Comment by ranjitjhala** [comment]
Yes, sorry @nuwus I don't know what's going on -- I'm guessing if `stack` can't build it, there is something odd with the haskell installation itself? I would suggest using `docker` VM.

**Comment by nuwus** [comment]
Ok, folks. Although _$ liquid some-file.hs_ still doesn't work (I think the problem lies somewhere in visibility of gcc, verbose mode doesn't help). The following work almost perfectly:
I reinstalled Liquid in cabal sandbox and  then

> cabal exec ghci
> :m +Language.Haskell.Liquid.Liquid
> liquid ["some-file.hs"]

But now I have the next thing (hopefully unrelated with general issue):

> **** DONE:  Worklist Initialize ************************************************
> 
> *** Exception:
> **** ERROR *********************************************************************
> **** ERROR *********************************************************************
> **** ERROR *********************************************************************
> SMTREAD:string
> **** ERROR *********************************************************************
> **** ERROR *********************************************************************
> **** ERROR *********************************************************************
> 
> CallStack (from HasCallStack):
>   error, called at src\Language\Fixpoint\Misc.hs:146:14 in liquid-fixpoint-0.7.0.5-3rsoMTDMh8wILBxNUkqRrW:Language.Fixpoint.Misc
>   errorstar, called at src\Language\Fixpoint\Smt\Interface.hs:175:16 in liquid-fixpoint-0.7.0.5-3rsoMTDMh8wILBxNUkqRrW:Language.Fixpoint.Smt.Interface

**Comment by ranjitjhala** [comment]
Ah, I missed this message. 

can you do `cabal exec z3` ? My guess is that the `z3` process is not starting up, perhaps because it is not in your path?

**Comment by nuwus** [comment]
@ranjitjhala, Yes! Thank you, it finally works!!

**Comment by ranjitjhala** [comment]
btw, I wonder if this issue is related to https://github.com/commercialhaskell/stack/issues/2998

**Comment by jneira** [comment]
I am getting the original error (`realgcc.exe: fatal error: no input files`) building the lastest hackage version (http://hackage.haskell.org/package/liquidhaskell-0.8.2.4) built with stack (`stack install --resolver=lts-11.18 liquid-fixpoint-0.7.0.7 dotgen-0.4.2 fgl-visualize-0.1.0.1 located-base-0.1.1.1 liquidhaskell-0.8.2.4`)
I have z3 installed and installing the package from source works (see #1527).

**Comment by jneira** [comment]
It turns out that the file that gcc doent found is `pthread.lib`
```
# liquid -v -ghc-option -v3 Even.hs
...
*** gcc:
"D:\Trabajo\NO-SALVAR\jneira\bin\Programs\stack\x86_64-windows\ghc-8.2.2\lib/../mingw/bin/gcc.exe" "-fno-stack-protector" "-DTABLES_NEXT_TO_CODE" "-BD:\ws\haskell\liquidhaskell-0.8.2.4\.stack-work\install\e3b7bed4\share\x86_64-windows-ghc-8.2.2\liquidhaskell-0.8.2.4\include\802" "-BD:\ws\haskell\liquidhaskell-0.8.2.4\.stack-work\install\e3b7bed4\share\x86_64-windows-ghc-8.2.2\liquidhaskell-0.8.2.4\include\\" "--print-file-name" "pthread.lib"
realgcc.exe: fatal error: no input files
...
```
So i will have to install pthreads...

**Comment by jneira** [comment]
No need to install pthreads, in ghc >= 8.4 the mingw gcc doesnt throw an error when calling with `"-BD:\ws\haskell\liquidhaskell-0.8.2.4\.stack-work\install\e3b7bed4\share\x86_64-windows-ghc-8.2.2\liquidhaskell-0.8.2.4\include\\"`, so i changed in `/path/to/ghc-8.2.2/lib/settings` the path of gcc compiler to ghc-8.4.4 one:
```
("C compiler command", "$topdir/../../ghc-8.4.4/mingw/bin/gcc.exe")
```
Ugly, ugly hack, but `liquid` seems to work now
