### ISSUE TITLE
Reflecting infix functions causes parse error

### ISSUE THREAD

**Issue by jbrown215** [ucsd-progsys/liquidhaskell#1179]
To repro:

```haskell
{-@ LIQUID "--no-adt" 	                           @-}
{-@ LIQUID "--exact-data-con"                      @-}
{-@ LIQUID "--higherorder"                         @-}
{-@ LIQUID "--no-termination"                      @-}
{-@ LIQUID "--ple" @-}

module Repro where

{-@ reflect (==.) @-}
(==.) :: Eq a => a -> a -> Bool
x ==. y = x == y
```

Error message:
```
LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************


**** DONE:  annotate ***********************************************************


**** RESULT: ERROR *************************************************************


 <interactive>:1:1: Error: GHC Error
     GHC error in safeParseIdentifier:
         parse error (possibly incorrect indentation or mismatched brackets)
```

Parses with GHC, parses when not reflecting.

**Comment by ranjitjhala** [comment]
Yes you have to add

{-@ infix ==. @-}

To the top of the file ... IIRC /cc @nikivazou

**Comment by ranjitjhala** [comment]
See this

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/benchmarks/popl18/ple/pos/OverviewListInfix.hs

**Comment by jbrown215** [comment]
Hmm ok, so it seems to only take issue with the fact that the operator ends with a '.'

New error message:
```
 /Users/JordanBrown/research/binah/db/EvalQuery.hs:7:14: Error: Cannot parse specification:

 7 | {-@ infixr ==. @-}
                  ^

     unexpected '.'
     expecting white space or end of input
```

Same happens with `infix` instead of `infixr`

**Comment by ranjitjhala** [comment]
Yes, my bad. The `.` thing is a bit tedious because its 
also used to separate module names etc so I'm not that 
superkeen to tinker with it (but maybe its easy to fix..) 

Is it possible to e.g. use something like this (which works)? 

```
module Repro where

{-@ reflect ==* @-}
(==*) :: Eq a => a -> a -> Bool
x ==* y = x == y
```

**Comment by jbrown215** [comment]
Yep! I can just make wrapper functions around the Yesod functions that don't have '.'

**Comment by ranjitjhala** [comment]
super, but LMK if the wrapper thing doesn't work and I'll tweak LH accordingly...
