### ISSUE TITLE
One of interactive examples lead to crash

### ISSUE THREAD

**Issue by varosi** [ucsd-progsys/liquidhaskell#1208]
http://goto.ucsd.edu:8090/index.html#?demo=lenMapReduce.hs

**Comment by ranjitjhala** [comment]
Hi @varosi -- thanks for pointing this out! Looks like some of the module imports were out of date, I've fixed it. Thanks!

**Comment by varosi** [comment]
There is still a crash with:
```LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.

liquid: ListLengths: Could not find module â€˜Data.HashMap.Strictâ€™
Perhaps you meant
  Data.IntMap.Strict (from containers-0.5.7.1)
  Data.Map.Strict (from containers-0.5.7.1)
Use -v to see a list of the files searched for.```

**Comment by ranjitjhala** [comment]
Is this after you edit the above link?
I just confirmed that the direct link works fine e.g. On my phone.

May be some browser cache issue where it is still loading/showing the old
code for you? (I modified the demo so it uses Data.Map and there is no
mention of HashMap)

**Comment by varosi** [comment]
After hard refresh - it's working now! Sorry and thanks for the fix!

2017-12-25 18:26 GMT+02:00 Ranjit Jhala <notifications@github.com>:

> Is this after you edit the above link?
> I just confirmed that the direct link works fine e.g. On my phone.
>
> May be some browser cache issue where it is still loading/showing the old
> code for you? (I modified the demo so it uses Data.Map and there is no
> mention of HashMap)
>
