### ISSUE TITLE
Build from source code failed: /usr/bin/ld.gold error

### ISSUE THREAD

**Issue by denisshevchenko** [ucsd-progsys/liquidhaskell#1212]
I try to build from source code on Arch Linux:

```
$ git clone --recursive git@github.com:ucsd-progsys/liquidhaskell.git
$ cd liquidhaskell
$ stack setup
```

I've installed additional packages:

```
$ pacaur -S numactl
$ pacaur -S ncurses
$ pacaur -S z3
```

But after:

```
$ stack install
```

I got this error:

```
/usr/bin/ld.gold: error: .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-2.0.0.2/build/System/Console/Terminal/Posix_hsc_make.o: requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
```

**Comment by ranjitjhala** [comment]
Was this on on windows with WSL by any chance?

I hit it too and don’t know why...

**Comment by denisshevchenko** [comment]
No, I have pure Arch Linux.

**Comment by denisshevchenko** [comment]
I found a hack (thanks to StackOverflow), in my case :

1. Open `~/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.2.1/lib/ghc-8.2.1/settings`
2. Change
    ` ("C compiler flags", "-fno-PIE -fno-stack-protector"),` 
    to
    `("C compiler flags", "-fPIC -fno-stack-protector"),`

So now it (at least) compiles.

**Comment by ranjitjhala** [comment]
Excellent, thanks for finding this workaround!
