### ISSUE TITLE
Error message with wrong type information in it

### ISSUE THREAD

**Issue by varosi** [ucsd-progsys/liquidhaskell#1214]
Trying this code at http://goto.ucsd.edu:8090/index.html#?demo=lenMapReduce.hs
```
{-@ test :: Num a => [a] -> a @-}
test [x] = 10
```
give misleading error:
![image](https://user-images.githubusercontent.com/6051718/34410696-b5c14822-ebda-11e7-8625-23c96b382212.png)

Which is some kind of wrong message, because GHCi infer this type:
```
test :: Num p => [a] -> p
```
i.e. there are two types *p* and *a*, not a single one.

**Comment by ranjitjhala** [comment]
Hmm thanks for pointing this out! Looks like the error message pretty
printer is doing something odd...!

**Comment by ranjitjhala** [comment]
Hmm, looks like on `develop` we get a nicer error message:

```
/Users/rjhala/research/stack/liquidhaskell/tests/todo/T1214.hs:17:13: Error: Specified type does not refine Haskell type for `ListLengths.test` (Checked)

 17 | {-@ test :: Num a => [a] -> a @-}
                  ^

 The Liquid type

     forall p a -> GHC.Num.Num p => [a] -> a

 is inconsistent with the Haskell type

     forall p a -> GHC.Num.Num p => [a] -> p

 defined at /Users/rjhala/research/stack/liquidhaskell/tests/todo/T1214.hs:18:1-4
```

will update the web-demo!

**Comment by ranjitjhala** [comment]
Fixed the web-demo too; now it looks like this:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1514487079_19979.hs

<img width="706" alt="screen shot 2017-12-28 at 10 52 26 am" src="https://user-images.githubusercontent.com/1650232/34420226-4c264c36-ebbd-11e7-80aa-c9065a5e27ae.png">

**Comment by varosi** [comment]
Great! Thanks!
