### ISSUE TITLE
Shorter file path for the only file (from user's stand point) in the Web demo

### ISSUE THREAD

**Issue by varosi** [ucsd-progsys/liquidhaskell#1215]
Error messages will be a bit more readable in the Web demo if file paths are replaced with "demo.hs" or something short like this. Even line numbers and positions are not needed in the hint text as they are already selected in the text.

![image](https://user-images.githubusercontent.com/6051718/34420510-a9b781a8-ec12-11e7-89a1-559a418a804d.png)

**Comment by ranjitjhala** [comment]
Thanks for the suggestion! Its implemented on the online demo now:

<img width="331" alt="screen shot 2017-12-28 at 2 15 15 pm" src="https://user-images.githubusercontent.com/1650232/34424590-a29b799e-ebd9-11e7-9892-188e01b69e88.png">

**Comment by varosi** [comment]
Thanks! Looks very nice and clean!
