### ISSUE TITLE
`not (x == y)` does not behave as `x/= y` when x and y are exactDC

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1220]
In the following `unsafe` is unsafe while `safe` is safe. Both are safe without the `exactdc` flag. (bug generated by @jprider63 , thanks :) )

```
{-@ LIQUID "--exactdc" @-}

module AB where

{-@ unsafe :: {t : AB | not (isA t)} -> {t /= A}  @-}
unsafe :: AB -> ()
unsafe t | isA t = ()
unsafe _ = ()

{-@ safe :: {t : AB | not (isA t)} -> {not (t == A)}  @-}
safe :: AB -> ()
safe t | isA t = ()
safe _ = ()

{-@ measure isA @-}
isA :: AB -> Bool 
isA A = True
isA B = False


data AB = A | B 
```

**Comment by ranjitjhala** [comment]
Wow, that's bizarre!

Adding the `--no-adt` also makes them both safe,

even when `--exactdc` is on, so thats a temporary

workaround if you need `--exactdc`.

**Comment by nikivazou** [comment]
How about this: https://github.com/ucsd-progsys/liquid-fixpoint/pull/353

Should I merge, if travis accepts?

**Comment by ranjitjhala** [comment]
Looks great to me! Please merge if Travis is ok! Thanks!!!
