### ISSUE TITLE
liquidhaskell-0.8.2.3 build fails during Haddock stage

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquidhaskell#1238]
I get this issue building with GHC 8.2.2 on Linux:

~~~
src/Language/Haskell/Liquid/Bare/Check.hs:405:48: error:
    parse error on input ‘{- $+$ text "In environment" $+$ nest 4 (pprint env) -}’
    |
405 | checkReft env emb (Just t) _ = (\z -> dr $+$ z {- $+$ text "In environment" $+$ nest 4 (pprint env) -}) <$> checkSortedReftFull env r
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
~~~

**Comment by ranjitjhala** [comment]
My apologies will fix right away!!!

**Comment by ranjitjhala** [comment]
btw, any idea why haddock is complaining about the above?

**Comment by ranjitjhala** [comment]
I just pushed 0.8.2.4 to hackage. Can you let me know if that solves the problem? `haddock` seems to work fine both locally and on CI.

**Comment by peti** [comment]
Maybe passing `--hyperlink-source` to Haddock makes a difference? That's what we use in Nix.

Anyhow, version 0.8.2.4 compiles just fine now. Thank you for the quick fix!

**Comment by ranjitjhala** [comment]
Thanks @peti !!!
