### ISSUE TITLE
Feature request: Autogenerate measures for record selectors

### ISSUE THREAD

**Issue by jprider63** [ucsd-progsys/liquidhaskell#1252]
This is somewhat related to #1251. It'd be nice if liquid autogenerated measures to test which constructor a value is. For example, with the following: 

```
data Foo = FA {fa :: Int} |  FB {fb :: Int }
```

Maybe liquid could autogenerate:

```
{-@ measure isFA @-}
isFA (FA _) = True
isFA _ = False

{-@ measure isFB @-}
isFB (FB _) = True
isFB _ = False
```

I could write template haskell code to generate `isFA` and `isFB`, but I don't know how to make them measures.

**Comment by jprider63** [comment]
Apparently there already is a regular [haskell package](http://hackage.haskell.org/package/derive-2.6.3/docs/Data-Derive-Is.html#v:makeIs) that will generate `isFA` and `isFB` for you.

**Comment by nikivazou** [comment]
Cool! And template Haskell still does not generate comments, correct? 
If it did, we could user LH to generate the measure annotations...

**Comment by jprider63** [comment]
I don't [see](http://hackage.haskell.org/package/template-haskell-2.12.0.0/docs/Language-Haskell-TH-Syntax.html) a way to generate comments.

**Comment by facundominguez** [comment]
Closing since this seems to be addressed by `--exact-data-cons`. Please, reopen if it still doesn't.
