### ISSUE TITLE
Build error in Misc: Can't install liquid haskell via cabal

### ISSUE THREAD

**Issue by farao** [ucsd-progsys/liquidhaskell#1254]
Hi, when trying to install liquidhaskell via cabal, I get:
[  9 of 106] Compiling Language.Haskell.Liquid.Misc ( src/Language/Haskell/Liquid/Misc.hs, dist/build/Language/Haskell/Liquid/Misc.o )

src/Language/Haskell/Liquid/Misc.hs:224:14: error:
    Ambiguous occurrence ‘=>>’
    It could refer to either ‘Language.Fixpoint.Misc.=>>’,
                             imported from ‘Language.Fixpoint.Misc’ at src/Language/Haskell/Liquid/Misc.hs:24:1-39
                          or ‘Language.Haskell.Liquid.Misc.=>>’,
                             defined at src/Language/Haskell/Liquid/Misc.hs:221:1

ghc version: 8.0.2
LH version: 0.8.0.5

**Comment by ranjitjhala** [comment]
Hmm. This looks like something quite stale;

can you move to the latest version `0.8.2.4` ?

Thanks!

**Comment by farao** [comment]
I tried cabal install liquidhaskell-0.8.2.4, but I get a dependency conflict around ghc-boot-8.2.2 (maybe it's because my ghc has version 8.0.2?):

Resolving dependencies...
cabal: Could not resolve dependencies:
trying: liquidhaskell-0.8.2.4 (user goal)
trying: template-haskell-2.11.1.0/installed-2.1... (dependency of
liquidhaskell-0.8.2.4)
next goal: ghc-boot (dependency of liquidhaskell-0.8.2.4)
rejecting: ghc-boot-8.0.2/installed-8.0... (conflict: liquidhaskell =>
ghc-boot==8.2.2)
rejecting: ghc-boot-8.2.2 (conflict: template-haskell =>
ghc-boot-th==8.0.2/installed-8.0..., ghc-boot => ghc-boot-th==8.2.2)
rejecting: ghc-boot-8.2.1, ghc-boot-8.0.2, ghc-boot-8.0.1 (conflict:
liquidhaskell => ghc-boot==8.2.2)
Dependency tree exhaustively searched.

My ghc is the system ghc of Fedora, so not unnecessarily stale I guess. And I can't use stack to install liquid haskell, right?

**Comment by ranjitjhala** [comment]
Hi, on th contrary, stack is the best way to install LH see this for
directions!

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md

**Comment by farao** [comment]
Oh, sorry somehow I didn't see that and that worked for me.
Nevertheless, this does not change that on a current Fedora, one can not use cabal to install liquid haskell with the system ghc - if it's not solvable, I guess it might make sense to add the information to the "install via cabal" section?

**Comment by ranjitjhala** [comment]
Agree, would be great to add to the “install by cabal” section! Will do!

**Comment by facundominguez** [comment]
Closing since there is a section discussing installation in the [website](https://ucsd-progsys.github.io/liquidhaskell/install/).
