### ISSUE TITLE
Feature Request: Substitute equalities in error messages

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1258]
Liquid type error messages (especially those generated by proofs) often have refinement types where the refinement is of the form `{v | v == foo}`. It would be helpful if these equalities were substituted as much as possible. For example, in issue #1257, the error message:
```text
Error: Liquid Type Mismatch
  
 19 |   f B C === F
        ^^^^^^^^^^^
  
   Inferred type
     VV : {v : Baz | v == Example.F}
  
   not a subtype of Required type
     VV : {VV : Baz | VV == ?a}
  
   In Context
     ?a : {?a : Baz | ?a == Example.f Example.B Example.C}
```
would be better reported as
```text
Error: Liquid Type Mismatch
  
 19 |   f B C === F
        ^^^^^^^^^^^
  
   Inferred type
     VV : {v : Baz | v == Example.F}
  
   not a subtype of Required type
     VV : {VV : Baz | VV == Example.f Example.B Example.C}
```

**Comment by ranjitjhala** [comment]
Yes, excellent idea. Thanks for submitting this -- I'd started on this on an old branch, let me try to  return to it next week! (Its really painful to have to piece together the equalities by hand...)
