### ISSUE TITLE
Allow refinements in the output type of measures

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquidhaskell#126]
Only base types are allowed to appear in the type of a measure, but this is less accurate than it could be, e.g. when dealing with measures that denote the size of a value.

``` haskell
measure len :: [a] -> Int
len []     = 0
len (x:xs) = 1 + len xs
```

Since the type only specifies that `len` returns an `Int`, we need to additionally define an invariant on `Int`.

``` haskell
invariant {v:[a] | (len v) >= 0}
```

This is a bit tedious when what we really want to write is just

``` haskell
measure len :: [a] -> Nat
len []     = 0
len (x:xs) = 1 + len xs
```

Perhaps there's a good reason to disallow refinements in the return type of a measure, but it isn't apparent to me.

**Comment by ranjitjhala** [comment]
Hey, is this still open? I thought @nikivazou implemented it?

**Comment by nikivazou** [comment]
It is implemented for Haskell defined measures!

**Comment by gridaphobe** [comment]
@nikivazou what about for old-style measures? Not all measures can be defined in Haskell, e.g. uninterpreted measures.

**Comment by nikivazou** [comment]
Curently, there is no support for invariants over old style measures.

**Comment by ranjitjhala** [comment]
I think that's fine ... we would like to eventually deprecate old style
measures anyway and just use the lifted style.

**Comment by gridaphobe** [comment]
But how would you define an uninterpreted measure in the lifted style? I
suppose we could write a Haskell function that **actually** does the
computation and change the annotation to `{-@ abstract measure @-}` or
some such..

**Comment by nikivazou** [comment]
Agree, but abstract measure is just an uninterpreted function. Would need to clarify all these definitions.
