### ISSUE TITLE
Proof combinators should be available as a separate library

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1261]
Currently if I want to use proof combinators in a project, I need to either include all of Liquid Haskell as a dependency, or I need to just copy the source of the combinators I need into my own code. Since proof combinators have no dependency on the internals of Liquid Haskell, they would ideally exist as their own library on Hackage.

**Comment by nikivazou** [comment]
Totally agree!!!! 

I will do that ASAP.

**Comment by nikivazou** [comment]
I did just upload some very basic lib: https://hackage.haskell.org/package/proof-combinators-0.1.0.0

**Comment by ranjitjhala** [comment]
May I suggest you add "NewProofCombinators" too?

I find it a lot more consistent and simpler to use.
​

**Comment by nikivazou** [comment]
Not sure what you want me to keep from the `NewProofCombinators`.

I do not have the type class mechanism anymore to the "optional" argument. 

I have a different implementation where `?` basically binds the proof to the second argument and passes their combination to the proof combinator: `x ==. (y ? p)`, where `x ? p = x`. 
Much simpler.

**Comment by ranjitjhala** [comment]
Does this also check the equalities by default?

**Comment by nikivazou** [comment]
It depends what is the type of `==.`, i.e., if it has precondition to check the equalities.

**Comment by ranjitjhala** [comment]
@nikivazou it is odd to use 

* `==?` to check the equality precondition, and
* `==.` to _not_ check it,

Given that you are using `?` to give the "reason". 

Maybe just use or export `because` or some such, as an alias for `?`

**Comment by facundominguez** [comment]
Closing since this conversation seems to be about `liquid-prelude` which is released as a separate package. Please, feel free to reopen if it is about something different.
