### ISSUE TITLE
Imprecisions with no-case-expand 

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1267]
The following is UNSAFE. It should get safe even with the `no-case-expand` flag.

```
{-@ LIQUID "--no-case-expand" @-}

module NoCaseExpand where

data ABC = A | B | C 

foo :: Int -> ABC -> ()
foo 0 A  =  ()

foo x A | x /= 0 = ()

foo _ A = error " " 

foo _ t = ()
```

**Comment by ranjitjhala** [comment]
Interesting. Wonder what the ghc-core is for this program...

**Comment by nikivazou** [comment]
Exactly what I was looking into....

The core is this 

```
fooCore x y = 
  let fail _ = case y of 
                 A -> case x /=  0 of 
                       False -> error " " 
                       True  -> () 
                 _ -> () 
  in case x of 
       0 -> case y of 
               A -> () 
               _ -> fail ()
       _ -> fail () 
````

Seems that to avoid the error, we need to inline `fail`...

**Comment by ranjitjhala** [comment]
!!! how does it come up with that bizarre code.

Regardless, @nikivazou I am not wholly persuaded
by your conclusion, because if you type that exact
code in, LH is happy to prove SAFE, even with `"--no-case-expand"`

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1522267761_23890.hs

?

**Comment by nikivazou** [comment]
Apart that `ABC` should have 3 data constructors! Not two as in your example above. 
When the default case expands to exactly one data constructor, LH always expands it.

**Comment by ranjitjhala** [comment]
Good point!
