### ISSUE TITLE
Attempting to reflect a function which contains a non-reflected function gives confusing error

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1275]
This actually appeared in the example code for #1263, I just didn't realize it at the time. The code
```haskell
f :: () -> ()
f _ = ()

{-@ reflect g @-}
g :: ()
g = f ()

{-@ g' :: { False } @-}
g' :: ()
g' = g
```
causes Liquid Haskell to error with this message:
```text
:1:1-1:1: Error
  Constraint with free vars
  2
  [Example.f]
  Try using the --prune-unsorted flag
```
when the actual error it should report is that `g` uses an unreflected function `f` in its definition.

Note that we don't actually need to be trying to prove `False` for this to happen; that's only included because we actually have to use `g`, and trying to prove `False` is a good way to ensure Liquid Haskell inspects `g`.

Interestingly, this error disappears if we run Liquid Haskell with the `--higherorder` flag (which means it also disappears when using the new `--reflection` flag).

**Comment by ranjitjhala** [comment]
Hmm. I *think* this is related to #1265.

**Comment by rosekunkel** [comment]
Ah, I didn't see that issue. This is just a simplification of the second example there.

**Comment by facundominguez** [comment]
Closing because the current LH gives a better error. I think #1892 can offer a better experience than failing, but we can continue the conversation there.
```
Test.hs:7:13: error:
    Illegal type specification for `Main.g`
    Main.g :: {VV : () | VV == Main.g
                         && VV == Main.f GHC.Tuple.Prim.()}
    Sort Error in Refinement: {VV : Tuple | VV == Main.g
                                            && VV == Main.f GHC.Tuple.Prim.()}
    Unbound symbol Main.f --- perhaps you meant: Main.g ?
    Just reflect
  |
7 | {-@ reflect g @-}
  | 
```
