### ISSUE TITLE
How to write a pattern match in a refinement

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1283]
This is either a feature request or a documentation request, I'm not sure which. I have the type
```haskell
data Foo = A | B

data Bar = C Foo Foo

data Baz = D Bar
```
and I'd like to refine the type `Baz` to only allow those `Bar`s whose two `Foo`s are the same. That is, I want the inhabitants of `Baz` to be exactly
```haskell
D (C A A)
D (C B B)
```
This feels like it ought to be possible, but trying to write a refinement on `D` requires a pattern match on its `Bar` parameter, and I can't figure out what the syntax is to express that as a refinement type. Is there a way to write this refinement?

**Comment by ranjitjhala** [comment]
This is possible using data refinements, e.g. see 

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/README.md#modules-with-code-data

```haskell
{-@ LIQUID "--exactdc" @-}

module Blank where

data Foo = A | B

data Bar = C Foo Foo

{-@ data Baz = D { db :: {v:Bar | isEqBar v} } @-}
data Baz = D Bar

{-@ measure isEqBar @-}
isEqBar :: Bar -> Bool 
isEqBar (C A A) = True 
isEqBar (C B B) = True 
isEqBar (C _ _) = False 

test = [ D (C A A)  -- ok
       , D (C B B)  -- ok
       , D (C A B)  -- fails
       , D (C B A)  -- fails
       ]
```

Does that work?

Btw, if instead you _always_ want the two fields of the `Bar` to have the same value regardless of whether they appear in a `D` or not, then you can do:

```haskell
{-@ data Bar = C { barX :: Foo, barY :: {v:Foo | v = barX} }  @-}
```

that is, use a data-refinement that forces the second field to be equal to the first. (This way, you don't need the `isEqBar` refinement on `Baz` because _every_ constructed `Bar` value has the above property.

---
@nikivazou why does this need `--exactdc` ? I get that error about unknown constructor `is$...`? Is this due to your recent fix for the case-expand business?

**Comment by nikivazou** [comment]
@ranjitjhala it should not be due to my recent fix, since I only apply it when the exactdc flag is on: https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Constraint/Generate.hs#L1137

**Comment by rosekunkel** [comment]
@ranjitjhala That works for this instance, but if Foo is a more complex type, it breaks down. For example, this doesn't work, because `isEqBar` is not structurally recursive in the way that measures require:
```haskell
data IntList = Nil | Cons Int IntList

data Bar = C IntList IntList

{-@ data Baz = D { db :: {v:Bar | isEqBar v} } @-}
data Baz = D Bar

{-@ measure isEqBar @-}
isEqBar :: Bar -> Bool 
isEqBar (C Nil Nil) = True 
isEqBar (C (Cons x xs) (Cons y ys)) = x == y && isEqBar (C xs ys) 
isEqBar (C _ _) = False
```
In refinements, `==` is structural equality, but as soon as I drop out of the refinements and into Haskell, there is no way to get back structural equality short of writing it myself, which isn't a measure. So I don't think using measures to do the pattern matching will work in the general case.

**Comment by ranjitjhala** [comment]
Not quite following your exact use case.

Is the above an example of where measures are not enough?

(else can you give an example that's insufficient?)

In general, note that you can use `reflect` instead

of `measure` and get in whatever constraint you like

(that is expressible as a Haskell function?)
​

**Comment by rosekunkel** [comment]
I can't see how to write a measure for the above that would constrain `Baz` to contain only the values
```haskell
D (C Nil Nil)
D (C (Cons 0 Nil) (Cons 0 Nil))
D (C (Cons 1 Nil) (Cons 1 Nil))
D (C (Cons 0 (Cons 0 Nil)) (Cons 0 (Cons 0 Nil)))
-- etc.
```

The actual use case here is that I'm trying to write a sequent-calculus proof-checker in Liquid Haskell. So the actual code looks like
```haskell
data Formula = Var String | Not Formula | Or Formula Formula
data Sequence = Nil | Cons Formula Sequence
data Sequent = Seq Sequence Sequence

data Proof where
  Identity :: Sequent -> Proof

{-@
data Proof where
  Identity :: what goes here?
@-}
```
I want to refine `Identity` to only accept sequents that look like `x |- x`, so all sequents of the form `Seq (Cons x Nil) (Cons x Nil)`. Ideally, I'd like to avoid reflection, because it seems kind of pointless to have a proof checker where you have to write a proof that your proof is valid. It seems like Liquid Haskell should be able to do this, because checking that a sequent calculus proof is valid just requires checking that each step has the right shape, which feels like it should be expressible with (relatively simple) refinement types.

**Comment by ranjitjhala** [comment]
Ah, ok how about using plain equality? (The below works)

```haskell
{-@ LIQUID "--exactdc" @-}

module Blank where

data IntList = Nil | Cons Int IntList

data Bar = C IntList IntList

{-@ data Baz = D { db :: {v:Bar | bar1 v == bar2 v} } @-}
data Baz = D Bar

{-@ measure bar1 @-}
bar1 :: Bar -> IntList
bar1 (C x _) = x

{-@ measure bar2 @-}
bar2 :: Bar -> IntList
bar2 (C _ x ) = x

test =
  [ D (C Nil Nil)                                     -- OK
  , D (C (Cons 0 Nil) (Cons 0 Nil))                   -- OK
  , D (C (Cons 1 Nil) (Cons 1 Nil))                   -- OK
  , D (C (Cons 0 (Cons 0 Nil)) (Cons 0 (Cons 0 Nil))) -- OK
  , D (C Nil (Cons 0 Nil))                            -- BAD
  , D (C (Cons 0 Nil) Nil)                            -- BAD
  ]
```

Also, thanks to `ple`, in this case, you can use `reflection` 
quite automatically (i.e. without having to write proofs, 
which would, indeed be pointless!) So the below works as expected:

```haskell
{-@ LIQUID "--exactdc"        @-}
{-@ LIQUID "--no-termination" @-}
{-@ LIQUID "--ple"            @-}

module Blank where

data IntList = Nil | Cons Int IntList

data Bar = C IntList IntList

{-@ data Baz = D { db :: {v:Bar | isEqBar v} } @-}
data Baz = D Bar

{-@ reflect isEqBar @-}
isEqBar :: Bar -> Bool
isEqBar (C Nil Nil)                 = True
isEqBar (C (Cons x xs) (Cons y ys)) = x == y && isEqBar (C xs ys)
isEqBar (C _ _)                     = False

test =
  [ D (C Nil Nil)                                     -- OK
  , D (C (Cons 0 Nil) (Cons 0 Nil))                   -- OK
  , D (C (Cons 1 Nil) (Cons 1 Nil))                   -- OK
  , D (C (Cons 0 (Cons 0 Nil)) (Cons 0 (Cons 0 Nil))) -- OK
  , D (C Nil (Cons 0 Nil))                            -- BAD
  , D (C (Cons 0 Nil) Nil)                            -- BAD
  ]
```

In general,  PLE will let you "evaluate" functions on "concrete" inputs.

**Comment by rosekunkel** [comment]
Good point about PLE, I was thinking for some reason that I would still be required to write proof terms with PLE, they'd just be trivial. Thanks!
