### ISSUE TITLE
Can't test equality of characters in reflected function

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1286]
The following code
```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--ple" @-}
module Example where

{-@ reflect charEqual @-}
charEqual :: Char -> Char -> Bool
charEqual x y = x == y

{-@ foo :: x:Char -> {y:Char | charEqual x y} -> () @-}
foo :: Char -> Char -> ()
foo x y = ()

bar = foo 'a' 'a'
```
causes an error:
```text
Error: Liquid Type Mismatch
  
 11 | bar = foo 'a' 'a'
            ^^^^^^^^^^^
  
   Inferred type
     VV : {v : Char | v == ?b}
  
   not a subtype of Required type
     VV : {VV : Char | Example.charEqual ?a VV}
  
   In Context
     ?b : Char
      
     ?a : Char
```
but the equivalent code with `Int` in place of `Char` and `0` in place of `'a'` is deemed safe. In particular, this means that there is (as far as I know) no way for reflected code to test string equality.

**Comment by ranjitjhala** [comment]
Hmm interesting! What happens when you use strings eg  “a” ?

There was a pending issue about reflection and strings but regardless this
should be easy to fix...

**Comment by rosekunkel** [comment]
Oh interesting, it works with strings. I pared this down from an example where it was refusing to reflect a function which used `==` on strings, so I wrote my own string-equality tester and ran into this issue. I had just been assuming `==` on strings was unsupported.

I'll see if I can track down the other issue I was having.

**Comment by rosekunkel** [comment]
I can't seem to reproduce the issue I was having with reflecting `==` for strings.

Unfortunately,
```haskell
charEqual x y = [x] == [y]
```
doesn't work, so we can't use equality for strings to get equality for characters

**Comment by ranjitjhala** [comment]
Yes, this doesn't have to do with reflect, but has to do with `Char`. See this e.g.

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1522898575_24111.hs

Probably has to do with how a `Char` literal is encoded in Core. (String literals are actually treated separately IIRC.)

**Comment by ranjitjhala** [comment]
To fix this:

1. Add a sig to `GHC/Prim.spec`

``` 
assume GHC.Types.C# :: x:GHC.Prim.Char# -> {v: GHC.Types.Char | v = (x :: Char) }
```

2. Add a case to `CoreToLogic.mkLit` 

```
mkLit (MachChar c)      = mkC c

mkC c = Just (ECon (L _test char)) 
  where 
    char  = FTC charFTyCon
    _test  = ... convert 'c' into Text 
```
