### ISSUE TITLE
Measures can't have a wildcard as their only pattern

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1288]
The following measure definition is rejected:
```haskell
{-@ measure f @-}
f :: () -> Int
f _ = 0
```
with the error message
```text
Error: Cannot lift Haskell function `f` to logic
  
 3 | {-@ measure f @-}
                 ^
  
     Measure Functions should have a case at top level
```

However, the following equivalent definition is accepted:
```haskell
{-@ measure f @-}
f :: () -> Int
f () = 0
```

Interestingly, this doesn't happen if we have at least one non-wildcard pattern, i.e., this is accepted:
```haskell
data Foo = A | B | C

{-@ measure f @-}
f :: Foo -> Int
f A = 0
f _ = 0
```

**Comment by ranjitjhala** [comment]
Hmm. Looks like this is because the core doesn't contain a `case-of`. 

Now that we support `DEFAULT` (or did we always?) we can probably 
treat core that looks like

```
\x -> e
```

simply as: 

```
\x -> case x of DEFAULT -> e 
```

**Comment by ranjitjhala** [comment]
While technically its easy to support the above, it muddies the waters re: the definition of `measure` cf #1285, e.g. things like 

```
{-@ reflect id @-}
id x = x 
```

can also pass the *syntactic* requirements for `measure` but they don't really make sense as measures. So best to not allow this, just to keep the "measures-are-one-equation-per-data-constructor" rule.

**Comment by rosekunkel** [comment]
Why exactly _are_ measures limited to one equation per data constructor? Why can't any structurally-recursive function be a measure?

**Comment by atondwal** [comment]
Under the hood, "measures" are just the conjuncts of the output refinement of data constructors. Concretely, consider:
```haskell
measure len :: [a] -> Int
len []     = 0
len (x:xs) = 1 + (len xs)
```
this just means that
```haskell
 [] ::             {v | len v = 0}
(:) :: _ -> xs:_-> {v | len v = len xs + 1 }
```

**Comment by ranjitjhala** [comment]
@wkunkel as @atondwal says above, measures are really a way to "strengthen" the data constructors' types, and so they really only make sense when there is one equation per 
constructor. See Sec 2.6 of the [ICFP 2014 paper](http://goto.ucsd.edu/~nvazou/refinement_types_for_haskell.pdf) for more details.

That said, the PR above allows for 

```haskell
{-@ measure f @-}
f :: () -> Int
f _ = 0
```

because its basically the same as `f () = 0` ... (see tests/pos/T1288.hs)
