### ISSUE TITLE
Can't specify null as a measure

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1290]
The following module:
```haskell
module Example where

import Prelude hiding (null)

{-@ measure null @-}
null :: [a] -> Bool
null [] = True
null _ = False
```
fails with the error:
```text
Error: Cannot lift Haskell function `null` to logic
  
 9 | null         :: xs:[a] -> {v: Bool | ((v) <=> len(xs) = 0) }
                     ^
  
     Specification of boolean measures is not allowed
```
This error goes away if I rename `null` to e.g. `isEmpty`, so I'm assuming `null` has been special-cased somewhere? In any case, this error message is very confusing and makes it seem as though boolean-valued measures are not allowed.

**Comment by facundominguez** [comment]
Closing since the given example passes verification in the latest LH.
