### ISSUE TITLE
Documentation request: How to run liquid on multiple files

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1304]
Currently, for [this project](https://github.com/wkunkel/lh-sequent-calc), I'm using a test framework (Tasty) to run liquid on each of my source files. Tests run in the root of the project by default, so I'm executing a command that looks like
```sh
liquid --idirs=src src/Example.hs
```
for each file in my source directory. However, this doesn't work very well; I find that when I make changes I often need to run the tests multiple times, because the first few runs will report strange errors. I think what's happening is this:

1. Module Foo depends on module Bar.
2. I make changes to Foo and Bar.
3. I run my tests, which runs liquid on Foo and then liquid on Bar.
4. Because Foo is checked before Bar, it uses stale information about the types in Bar.

The solution seems to be running liquid on modules in topologically-sorted order, but there's no obvious way to do that automatically. I'd like to get documentation on the correct way to run liquid on multiple files.

**Comment by atondwal** [comment]
I'm not sure if we've thought out a "correct way", but the workaround is that if you nuke `src/.liquid` that should fix the problem with having to run the tests multiple times.

**Comment by ranjitjhala** [comment]
Hi @wkunkel  -- yes, this is definitely a pain point. Have you tried this:

https://hackage.haskell.org/package/liquidhaskell-cabal 

and there is a demo on how to use it

https://github.com/spinda/liquidhaskell-cabal-demo

**Comment by ranjitjhala** [comment]
@wkunkel can you let us know if the cabal thing works for you?

**Comment by rosekunkel** [comment]
I'll take a look at it.

**Comment by rosekunkel** [comment]
@atondwal nuking src/.liquid unfortunately doesn't always fix the problem. In this project doing so will cause the first run of the tests to fail (probably) with lots of "Unbound Symbol" errors.

**Comment by facundominguez** [comment]
Closing this since the `liquid` executable has been replaced by the LH plugin. I think changing the specification does not always cause GHC to recompile dependent modules, but I don't have an example handy and I think we can make a separate issue for that.
