### ISSUE TITLE
Same function definition in different way, causes an error

### ISSUE THREAD

**Issue by CodePeters** [ucsd-progsys/liquidhaskell#1313]
Defining the function below:

{-@ reflect pred @-}
pred :: Int -> Int
pred n 
  | n == 0 = 0
  | otherwise = n-1

Works fine, but if we write the same function in a different way causes an error:

{-@ reflect pred @-}
pred :: Int -> Int
pred  0 = 0
pred  n = n-1 

The above definition leads to the error:

 <no location info>: Error: Uh oh.
     /Users/Desktop/List.hs:38:13: Error: Cannot lift Haskell function `pred` to logic
    Oops, not yet handled: checkDataAlt on Lit

**Comment by ranjitjhala** [comment]
Hi @CodePeters -- Can you tell us what version of LH you're using? 
I recently fixed this issue in `develop`, e.g.

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1525190202_25091.hs

Thanks!

**Comment by CodePeters** [comment]
LiquidHaskell Version 0.8.2.4, Git revision cd75b3041db4ed15973547c044904c193ee562a2
Copyright 2013-18 Regents of the University of California. All Rights Reserved.

**Comment by ranjitjhala** [comment]
Ah yes, that about a month old; if you [rebuild from `develop`](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#build-with-stack-recommended) this is fixed. thanks!

**Comment by CodePeters** [comment]
thanks for the replies !!!
