### ISSUE TITLE
cannot run LiquidHaskell Version 0.8.2.4 (installed with cabal)

### ISSUE THREAD

**Issue by astefano** [ucsd-progsys/liquidhaskell#1314]
C02SY2VXH03Q:haskell_tests $ liquid filter.hs
LiquidHaskell Version 0.8.2.4
Copyright 2013-18 Regents of the University of California. All Rights Reserved.

**** DONE:  A-Normalization ****************************************************

**** DONE:  Extracted Core using GHC *******************************************

**** DONE:  Transformed Core ***************************************************

Working   0% [=................................................................]
liquid:
**** ERROR *********************************************************************
**** ERROR *********************************************************************
**** ERROR *********************************************************************
SMTREAD:string
**** ERROR *********************************************************************
**** ERROR *********************************************************************
**** ERROR *********************************************************************

CallStack (from HasCallStack):
  error, called at src/Language/Fixpoint/Misc.hs:146:14 in liquid-fixpoint-0.7.0.7-3WDAzayqLs2DrFctcioEP3:Language.Fixpoint.Misc
  errorstar, called at src/Language/Fixpoint/Smt/Interface.hs:176:16 in liquid-fixpoint-0.7.0.7-3WDAzayqLs2DrFctcioEP3:Language.Fixpoint.Smt.Interface

**Comment by ranjitjhala** [comment]
Hi, can you check if `z3` is in your path? I suspect it is missing? 

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#step-1-install-smt-solver

**Comment by astefano** [comment]
Hi, thanks, yes, this did the trick. (I had only cvc4 installed as my reading was that one solver is enough. If Z3 is a requirement, maybe the documentation can be updated? I also tried liquid x --smtsolver=cvc4 and had the same error.)
