### ISSUE TITLE
[LiquidHaskell v0.8.2.4 or v0.8.2.2] compile error of example from blog

### ISSUE THREAD

**Issue by astefano** [ucsd-progsys/liquidhaskell#1316]
The example of fMono from https://ucsd-progsys.github.io/liquidhaskell-blog/2016/09/18/refinement-reflection.lhs/ does not compile:

The Liquid type

     (Int -> Int) -> (Int -> _) -> Int -> Int -> _

 is inconsistent with the Haskell type

     forall a1 a2 ->
(GHC.Num.Num a1, GHC.Classes.Ord a1) =>
(a1 -> a2) -> (a1 -> ()) -> a1 -> a1 -> () 

After explicitly writing the Haskell type of fMono

`fMono :: (Int -> Int) -> (Int -> Proof) -> Int -> Int -> Proof`

the error is:

/Users/lara.astefanoaei/haskell_tests/ref_reflect_p0.hs:70:14: Error: Illegal type specification for `Main.fMono`

 70 | {-@ fMono :: f:(Nat -> Int)
                   ^

     Main.fMono :: f:({v : Int | v >= 0} -> Int) -> (z:{v : Int | v >= 0} -> {VV : () | f z <= f (z + 1)}) -> x:{v : Int | v >= 0} -> y:{v : Int | v >= 0
                                                                                                                                                   && x < v} -> {VV : () | f x <= f y}
     Sort Error in Refinement: {VV : Tuple | f z <= f (z + 1)}
     Unbound Symbol f
 Perhaps you meant: z

**Comment by nikivazou** [comment]
To run this example you also need to give the Haskell type signature for `fMono`, as you figured out. 
Then, to put `f` in scope you need to enable the higher order flag by writing: 

```
{-@ LIQUID "--higherorder" @-}
```

Here is a demo with everything in : http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1525968879_25504.hs

I liked to hide all these details from the blog, but indeed it is confusing...

**Comment by astefano** [comment]
Thanks Niki, i've just seen that this was already addressed in a comment on the blog, i overlooked this...
