### ISSUE TITLE
Termination is not checked on reflected functions without decreasing arguments

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1321]
E.g. the [following](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1527627433_26017.hs) is SAFE

```
{-@ LIQUID "--reflection" @-}

data Map a b = Map [(a,b)]

{-@ reflect foo @-}
foo :: Eq k => k -> Map k v -> Maybe v
foo x (Map []) = Nothing
foo x (Map ((k, v):kvs))
  | x == k       = Just v
  | True         = foo x (Map ((k, v):kvs))
```

but gives termination error once the reflect annotation is removed.

**Comment by ranjitjhala** [comment]
! I hope you are going to fix it? :)

**Comment by facundominguez** [comment]
Closing this because the latest LH gives a termination error with or without the reflection annotation.
