### ISSUE TITLE
Diverging program proclaimed safe

### ISSUE THREAD

**Issue by formrre** [ucsd-progsys/liquidhaskell#1332]
Playing around with examples from:
https://mail.haskell.org/pipermail/haskell-cafe/2010-January/072600.html

I came up with this minimal modification of the example, which Liquid Haskell proclaims safe, yet it doesn't terminate.

```
data Fix a = Fix {unFix :: Fix a -> a}

absurd :: (Show a) => a -> a
absurd _ = unFix (Fix (\x -> unFix x x)) (Fix (\x -> unFix x x))

main = putStrLn $ show (absurd "a")
```

**Comment by ranjitjhala** [comment]
Yes, this is a _longstanding_ issue, c.f. https://github.com/ucsd-progsys/liquidhaskell/issues/159

@nikivazou perhaps we should button down and fix it :)

**Comment by ranjitjhala** [comment]
PS: thanks @formrre for bumping it up!
