### ISSUE TITLE
Termination - unsafe?

### ISSUE THREAD

**Issue by snap9** [ucsd-progsys/liquidhaskell#1333]
Liquid Haskell is marking the following clearly safe code as unsafe:

    foo :: Int -> Int -> Bool
    foo i1 i2
        | i1 < i2 = foo i2 i1
        | otherwise = True

Are there plans to remedy this?

**Comment by nikivazou** [comment]
This is not clearly SAFE, since it might diverge (as you observe). 
You can turn termination checking of using the `--no-termination` flag when you call liquid or add the following pragma in your code `{-@ LIQUID "--no-termination" @-}`

**Comment by ranjitjhala** [comment]
@nikivazou I think @snap9 means this code _cannot_ diverge, 
and is wondering how to get LH to prove this fact.

In fact, you can -- it requires a tricky termination metric, 
essentially the `max (i2 - i1) 0`. So the following works:

```haskell
{-@ foo :: i1:Int -> i2:Int -> Bool /  [( if (i2 - i1) >= 0 then (i2 - i1) else  0) ] @-}
foo :: Int -> Int -> Bool
foo i1 i2
  | i1 < i2   = foo i2 i1
  | otherwise = True
```

You can [play with it here](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1528913759_26542.hs)

**Comment by ranjitjhala** [comment]
PS: @snap9 thanks for the interesting example :)  
Do let us know -- i.e. reopen -- if the above doesn't make sense...

**Comment by snap9** [comment]
@ranjitjhala Thanks for that! Is it possible to prove this for similar examples that are only Ord but not numbers? Example that fails: http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1528921727_26549.hs

**Comment by ranjitjhala** [comment]
Sure, you just modify the `i2 - i1 >= 0` to be `i2 > i1` and use `1` instead of `i2 - i1` so the following works:

```haskell
{-@ foo :: i1:_ -> i2:_ -> _ /  [if i2 > i1 then 1 else  0] @-}
foo :: (Ord a) => a -> a -> Bool 
foo i1 i2
  | i1 < i2   = foo i2 i1
  | otherwise = True
```

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1528926939_26552.hs

**Comment by snap9** [comment]
@ranjitjhala Thank you, this works, but what are 1 and 0 here? Is 1 just a synonym for "it decreases during next recursive call" and 0 for "it terminates right now"? I don't see this termination feature documented anywhere...

**Comment by ranjitjhala** [comment]
@snap9 they are simply the integers (or rather, natural numbers) `0` and `1`. 

The expression in `[...]` is a "termination metric", which is 
some expression mapping the function inputs to an integer 
that is:

1. _Strictly decreasing_ and 
2. _Non-negative_ 

at each recursive call. LH checks the above facts (1, 2) are true,
and if so, verifies that the function is terminating.

Hmm, you are right -- we should have more documentation about this!

In the mean time, you can read more about it on:

- the [blog](https://ucsd-progsys.github.io/liquidhaskell-blog/tags/termination.html) 
- the [README](https://github.com/ucsd-progsys/liquidhaskell#explicit-termination-metrics)
- this [tutorial](https://liquid.kosmikus.org/02-lists.html#/termination) by @kosmikus
