### ISSUE TITLE
FEATURE: Pattern Synonyms

### ISSUE THREAD

**Issue by snap9** [ucsd-progsys/liquidhaskell#1334]
Either a sequence is empty or it isn't. Both cases are covered in

    import Data.Sequence (Seq((:<|), Empty))
    foo :: Seq a -> Bool
    foo Empty = True
    foo (_ :<| _) = True

yet LiquidHaskell doesn't like it.

Demo: http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1529011239_26561.hs

**Comment by buggymcbugfix** [comment]
@snap9 Maybe this is to do with pattern synonyms? (I can't check right now.)

**Comment by ranjitjhala** [comment]
Thanks @vimuel -- yes indeed this _does_ have to do with pattern synonyms. These are not supported right now in LH. It would be interesting to think about how to support them, since 
AFAICT they don't even show up in the GHC "Core" that LH uses...

**Comment by snap9** [comment]
@ranjitjhala @vimuel Here's an idea. For now, just hardcode in the commonly used pattern synonyms. Data.Sequence is one of the common ones, and creating one's own pattern synonyms is AFAIK rare in practice.

When one day LH has general support for pattern synonyms, delete the hardcoded ones.

**Comment by buggymcbugfix** [comment]
Hard-coding patterns seems like a bad idea to me.

There is the `--no-totality` flag for enabling totality checking, although that seems like a bit of a sledgehammer to me. Unfortunately I couldn't find a way of disabling totality on a per-function basis (like `lazy` for termination.). @ranjitjhala ?

**Comment by facundominguez** [comment]
Closing since the given example passes verification in the latest LH.
