### ISSUE TITLE
The sort (GHC.Real.Ratio int) is not numeric

### ISSUE THREAD

**Issue by philderbeast** [ucsd-progsys/liquidhaskell#1336]
Does liquid haskell work with rational numbers? With this single @-marked comment refinement type annotation;

```
newtype NominalLaunch = NominalLaunch Rational deriving (Eq, Ord, Show)

{-@ launchValidity1 :: _ -> _ @-}
launchValidity1 :: NominalLaunch -> Bool
launchValidity1 _ = False
```

I have a small test case in which it works with `RESULT: SAFE` but putting the same refinement type annotation in a larger project fails. These are the reproduction steps for the failure;

```
> git clone https://github.com/BlockScope/flare-timing.git
...
> git checkout fix/liquid-gap-46
...
> stack build
...
> ./stack-shake-build.sh liquid-gap
...
:1:1-1:1: Error
  elaborate solver failed on:
      VV##F##372 /= 0
  with error
      The sort (GHC.Real.Ratio int) is not numeric
  because
Cannot unify (GHC.Real.Ratio int) with int in expression: VV##F##372 /= 0
  because
Elaborate fails on VV##F##372 /= 0
  in environment
      VV##F##372 := (GHC.Real.Ratio int)
```

That shake build rule is equivalent to;

```
> stack exec liquid -- \
--ghc-option=-XPackageImports \
"--ghc-option=-fplugin Data.UnitsOfMeasure.Plugin" \
gap/library/Flight/Gap/Validity.hs \
gap/library/Flight/Gap/Pilots.hs \
gap/library/Flight/Gap/Time/Best.hs \
aeson-via-uom/library/Data/Aeson/Via/UnitsOfMeasure.hs \
units/library/Flight/Units.hs \
units/library/Flight/Units/Angle.hs \
gap/library/Flight/Gap/Time/Nominal.hs \
gap/library/Flight/Gap/Ratio/Goal.hs \
gap/library/Flight/Gap/Ratio/Launch.hs \
gap/library/Flight/Gap/Validity/Task.hs \
gap/library/Flight/Gap/Validity/Time.hs \
gap/library/Flight/Gap/Validity/Distance.hs \
gap/library/Flight/Gap/Validity/Launch.hs \
gap/library/Flight/Gap/Validity/Area.hs \
gap/library/Flight/Gap/Distance/Sum.hs \
gap/library/Flight/Gap/Distance/Max.hs \
gap/library/Flight/Gap/Distance/Min.hs \
gap/library/Flight/Gap/Distance/Best.hs \
gap/library/Flight/Gap/Distance/Nominal.hs \
units/library/Flight/Ratio.hs
```

**Comment by philderbeast** [comment]
Note that I needed to use the `-XPackageImports` to resolve the ambiguity for module `Control.Newtype`. This ambiguity only appears when running `liquid`, not when building with `stack`;

```
liquid: Data.Aeson.Via.UnitsOfMeasure: Ambiguous module name ‘Control.Newtype’:
  it was found in multiple packages:
  newtype-0.2 newtype-generics-0.5.3
```

**Comment by philderbeast** [comment]
I made an attempt to reproduce the error with a [smaller setup](https://github.com/BlockScope/liquid-sort-ratio-not-numeric) but this passes with `RESULT: SAFE`.

**Comment by ranjitjhala** [comment]
Hi sorry for the delay — am traveling.

Does this happen if you use “data” inst as of “new type”?

**Comment by philderbeast** [comment]
Safe travels.

I made the switch from `newtype` to `data` but this made no change with the smaller setup still passing and the larger setup failing with the same error.

**Comment by ranjitjhala** [comment]
Hmm. Can you point me to where `GHC.Real.Ratio` is being defined? 

Aha -- its from here: http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Ratio.html

**Comment by ranjitjhala** [comment]
Also, are you writing a refinement containing `/= 0` somewhere? If so, can you show me where?

(Am trying to first make a tiny program that replicates the issue...)

**Comment by ranjitjhala** [comment]
@philderbeast -- I think I have a minimal version of your problem; namely:

```haskell
import Data.Ratio

foo :: Ratio Int -> Bool
foo x = y == y
  where
    y = 10 / x
```

**Comment by ranjitjhala** [comment]
Hi @philderbeast -- there is a fix in the works for this -- will merge into `develop` if/when tests pass. The fix is to tell LH to treat `Ratio` values as numeric (in the refinements) so they can be compared against 0 etc., by writing:

`{-@ embed Ratio * as int @-}`

**Comment by ranjitjhala** [comment]
Hi @philderbeast this is fixed in develop by PR #1341 -- you should be able to write

```haskell
{-@ embed Ratio * as int @-}
```

in the relevant file [you should _also_ get a proper line number reporting where the elaborate fails; put the above line in that file]. 

Let me know if it doesn't work. Thanks!

**Comment by philderbeast** [comment]
Thanks @ranjitjhala. I will give it a go to see if this fix works in place.

The module I chose to add the one liquid haskell refinement comment to imports a lot of other modules and a GHC plugin that itself pulls in some GHC types.

Each time I got an error like the following, I've known how to find the module `liquid` is missing and so have kept adding files for `liquid` to check.

```
liquid: Flight.Units.Angle: Could not find module ‘Data.UnitsOfMeasure’
```

This is where I'm at. I've unpacked the source code for `uom-plugin-0.3.0.0` and `ghc-8.2.2` to be able to have the source for modules that `liquid` has been wanting to find. This feels wrong. How do I stop `liquid` asking for modules?

```
'stack exec liquid --
"--ghc-option=-XPackageImports"
"--ghc-option=-fplugin Data.UnitsOfMeasure.Plugin"
gap/library/Flight/Gap/Validity.hs
gap/library/Flight/Gap/Pilots.hs
gap/library/Flight/Gap/Time/Best.hs
aeson-via-uom/library/Data/Aeson/Via/UnitsOfMeasure.hs
units/library/Flight/Units.hs
units/library/Flight/Units/Angle.hs
gap/library/Flight/Gap/Time/Nominal.hs
gap/library/Flight/Gap/Ratio/Goal.hs
gap/library/Flight/Gap/Ratio/Launch.hs
gap/library/Flight/Gap/Validity/Task.hs
gap/library/Flight/Gap/Validity/Time.hs
gap/library/Flight/Gap/Validity/Distance.hs
gap/library/Flight/Gap/Validity/Launch.hs
gap/library/Flight/Gap/Validity/Area.hs
gap/library/Flight/Gap/Distance/Sum.hs
gap/library/Flight/Gap/Distance/Max.hs
gap/library/Flight/Gap/Distance/Min.hs
gap/library/Flight/Gap/Distance/Best.hs
gap/library/Flight/Gap/Distance/Nominal.hs
units/library/Flight/Ratio.hs
aeson-via-sci/library/Data/Aeson/Via/Scientific.hs
uom-plugin-0.3.0.0/src/Data/UnitsOfMeasure/Convert.hs
uom-plugin-0.3.0.0/src/Data/UnitsOfMeasure/Singleton.hs
uom-plugin-0.3.0.0/src/Data/UnitsOfMeasure/Internal.hs
uom-plugin-0.3.0.0/src/Data/UnitsOfMeasure.hs
uom-plugin-0.3.0.0/src/Data/UnitsOfMeasure/TH.hs
uom-plugin-0.3.0.0/src/Data/UnitsOfMeasure/Show.hs
uom-plugin-0.3.0.0/src/Data/UnitsOfMeasure/Read.hs
siggy-chardust/library/Data/Number/RoundingFunctions.hs
uom-plugin-0.3.0.0/src/Data/UnitsOfMeasure/Plugin.hs
ghc-8.2.2/types/TyCoRep.hs'
Exit code: 1
Stderr:
liquid: `gcc' failed in phase `C pre-processor'. (Exit code: 1)
)
```

I have come up against an error with `CPP`. Would defining `*.spec` files for some modules prevent a search for those modules by `liquid`?

**Comment by ranjitjhala** [comment]
That's odd, you shouldn't have to do that as it should just use the same
modules that GHC is using, though I guess we've never really tried this
with plugins like "UnitsOfMeasure" so I'm not sure how those modules get
pulled into the compilation process...

**Comment by philderbeast** [comment]
I also got the error with the minimal reproduction test case and have added that to [liquid-sort-ratio-not-numeric](https://github.com/BlockScope/liquid-sort-ratio-not-numeric).

I applied the `{-@ embed Ratio * as int @-}` fix and tested with `liquid` by referencing the latest commits to the `develop` branches of `liquidhaskell` and `liquid-fixpoint`.

```
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: 9d2694ac82262d135dd7ca0f3b9034b7c556cd48
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: ec88f568d101bfd35b6254aa7db034164d9c89dd
  extra-dep: true
```

I can confirm the fix works for the minimal reproduction test case.

```
./repro.sh
LiquidHaskell Version 0.8.2.4, Git revision ec88f568d101bfd35b6254aa7db034164d9c89dd
Copyright 2013-18 Regents of the University of California. All Rights Reserved.
...
RESULT: SAFE
```

**Comment by philderbeast** [comment]
Using the `develop` branch of `liquidhaskell` and `liquid-fixpoint` I no longer need to pull in `ghc` sources separately.
