### ISSUE TITLE
Record names conflicting when they shouldn't

### ISSUE THREAD

**Issue by snap9** [ucsd-progsys/liquidhaskell#1342]
Create these two files:

A1.hs

    module A1(Asdf1()) where
    
    {-@ data Asdf1 = Asdf1 { foo :: Int } @-}
    data Asdf1 = Asdf1 { foo :: Int }

A2.hs

    module A2 where
    
    import A1
    
    {-@ data Asdf2 = Asdf2 { foo :: Int, asdf :: Asdf1 } @-}
    data Asdf2 = Asdf2 { foo :: Int, asdf :: Asdf1 }

Running "liquid A2.hs" fails:

     5 | {-@ data Asdf2 = Asdf2 { foo :: Int, asdf :: Asdf1 } @-}
                  ^^^^^^
      
         assumed type A2.foo :: lq$recSel:Asdf2 -> {VV : Int | VV == foo lq$recSel}
         Sort Error in Refinement: {VV : int | VV == A2.foo lq$recSel}
         Cannot unify A1.Asdf1 with A2.Asdf2 in expression: A2.foo lq$recSel 
         
     6 | data Asdf2 = Asdf2 { foo :: Int, asdf :: Asdf1 }
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
         constructor A2.Asdf2 :: foo:Int -> asdf:Asdf1 -> {VV : Asdf2 | asdf VV == asdf
                                                                        && foo VV == foo}
         Sort Error in Refinement: {VV : A2.Asdf2 | (A2.asdf VV == asdf##A2.Asdf2
                                                     && A2.foo VV == foo##A2.Asdf2)}
         Cannot unify A1.Asdf1 with A2.Asdf2 in expression: A2.foo VV

Just changing `foo` to `bar` in A2.hs "fixes" the "problem", but this should not be a problem because `foo` isn't even exported from A1.hs.

How do you solve this?

**Comment by ranjitjhala** [comment]
In the short term, I suggest just using different field names -- this is 
quite non-trivial to fix otherwise, as it requires a significant re-jiggering 
of how modules are handled... :(

**Comment by snap9** [comment]
@ranjitjhala This is a common use case. The example I showed was silly but imagine "foo" being called "length", "count", "context", etc. Now I'd have to call one of them "context2", "contextSomeDescription", etc. to make LiquidHaskell happy?

Is there some way to change a record name in only LiquidHaskell and leave the rest of my Haskell code clean? Thanks.

**Comment by ranjitjhala** [comment]
Hmm, good point. Let me think about it!

**Comment by facundominguez** [comment]
I'm closing this one since the example doesn't fail in the latest LH.
