### ISSUE TITLE
alpha-equivalent terms not subtypeable

### ISSUE THREAD

**Issue by stelleg** [ucsd-progsys/liquidhaskell#1351]
Getting the following error: 

```
   Inferred type
     VV : {v : (Ptr a) | plen v == n
                         && 0 <= pbase v
                         && 0 <= plen v}
  
   not a subtype of Required type
     VV : {VV : (Ptr a) | plen VV == n
                          && 0 <= pbase VV
                          && 0 <= plen VV}
```

Seems like there is an issue with alpha-equivalence checking, or maybe shadowing?

**Comment by ranjitjhala** [comment]
Yikes!

1. Can you share the code that triggers this?

2. Are there any bindings named “v” in scope at the error? (Maybe in the
type spec for the function being checked?)

**Comment by stelleg** [comment]
1. Here's the code: https://gist.github.com/stelleg/241f0671a1d7cb413c07f0d9ec9a32bb

Run with `liquid --alphaequivalence --prune-unsorted`

2. Doesn't look like there should be any other variables named `v` in scope, though maybe the way I'm using the type alias is problematic?

**Comment by stelleg** [comment]
Whoops! My alias had single `=` when it should have had `==`. Replacing `PtrLen` with the bundled `PtrN` fixes the issue. 

Edit: Upon closer inspection the single `=` doesn't seem to be the issue, but using `PtrN` does fix the issue, though I'm not sure why.

**Comment by stelleg** [comment]
So I noticed that changing type variable from `n` to `N` (as defined in Ptr.spec) fixes the issue. Is there some kind of case sensitivity for type alias arguments?

**Comment by ranjitjhala** [comment]
Ah yes! We use lower case for “type” variables and upper case for “values”
(the latter of which can appear in refinements)
