### ISSUE TITLE
No decreasing parameter for length :: List a -> Int

### ISSUE THREAD

**Issue by bno1** [ucsd-progsys/liquidhaskell#1355]
I'm following the tutorial pages (more specifically: http://ucsd-progsys.github.io/lh-workshop/03-datatypes.html) and I'm working on the examples in an environment with ghc 8.2.2 and liquidhaskell 0.8.2.4. When verifying the following code I get the error below it.

```haskell
data List a = Emp               -- Nil
            | (:::) a (List a)  -- Cons

{-@ measure lengthx @-}
{-@ lengthx :: List a -> Int @-}
lengthx :: List a -> Int
lengthx Emp        = 0
lengthx (_ ::: xs) = 1 + lengthx xs

{-@
data List a where
    Emp :: {v:List a | lengthx v = 0}
    | (:::) :: x:a -> xs:List a -> {v:List a | lengthx v = 1 + lengthx xs}
@-}
```

```
Main.hs:40:1-7: Error: Termination Error

 40 | lengthx Emp        = 0
      ^^^^^^^

   Main.lengthx
 No decreasing parameter
```

Does it need help figuring out the decreasing parameter?

**Comment by ranjitjhala** [comment]
Apologies, unfortunately we need to update the tutorial to account for the termination checks that have been added after the last version of the tutorial!

You can either:

1. Disable termination checking with `{-@ LIQUID "--no-termination" @-}` 

OR 

2. Tell LH that the  `lengthx` function _is_ the default metric for the `List` type as described 
[here](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/README.md#default-termination-metrics)

```
data List [lengthx] a 
```

3. Use the new "structural" termination check `{-@ LIQUID "--structural" @-}`

Btw, once you define the measure, `lengthx` you don't need to write the refinements 
on the data constructors `Emp` and `:::` -- LH does that for you automatically.

Let me know if that helps!

**Comment by bno1** [comment]
@ranjitjhala I've noticed that and I started following the tutorial from the book. I tried the second option and I get the following.
```haskell
{-@ data List [lengthx] a = Emp | (:::) a (List a) @-}
data List a = Emp               -- Nil
            | (:::) a (List a)  -- Cons

{-@ measure lengthx @-}
lengthx :: List a -> Int
lengthx Emp        = 0
lengthx (_ ::: xs) = 1 + lengthx xs
```
```
Main.hs:38:6-10: Error: Bad Data Specification

 38 | data List [lengthx] a = Emp | (:::) a (List a) @-}
           ^^^^^


 GHC and Liquid specifications have different numbers of fields for `Main.:::`
```

**Comment by ranjitjhala** [comment]
If you use the second option, you can just write:

```haskell
{-@ data List [lengthx] a @-}
```

leave the fields out.

You will later in the tutorial see why you may need fields, but in that case the syntax is different, something like:
```
    {-@ data L [llen] a = Nil | Cons { x::a, xs:: L a} @-}
```

(Basically, you need to name the fields...)

**Comment by bno1** [comment]
@ranjitjhala It seems that it's expecting something after `a`. I also tried downgrading my stack environment to lts-10.10 and compile liquedhaskell from source but it didn't have any effect.

```haskell
{-@ data List [lengthx] a @-}
data List a = Emp               -- Nil
            | (:::) a (List a)  -- Cons


{-@ measure lengthx @-}
lengthx :: List a -> Int
lengthx Emp        = 0
lengthx (_ ::: xs) = 1 + lengthx xs
```
```
Error: Cannot parse specification:

 34 | {-@ data List [lengthx] a @-}
                                ^

     unexpected end of input
     expecting lowercase letter, "_", predVarDefP, "=", "where" or "::"
```

**Comment by ranjitjhala** [comment]
Oops that should be just

   {-@ data List [lengthx] @-}


(No type parameters...) for example see


   http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1534265472_329.hs

**Comment by bno1** [comment]
@ranjitjhala awesome, thanks for all the help!
