### ISSUE TITLE
Pattern match failure at Language/Haskell/Liquid/Constraint/Generate.hs:816:8-23

### ISSUE THREAD

**Issue by mkf** [ucsd-progsys/liquidhaskell#1358]
## Steps to reproduce:

```
git clone https://github.com/ArchieT/ThreeManChess
cd ThreeManChess
git checkout 8f3b4a4eda592ef7eee7889a8a669e71476a53b0
cd src
liquid ThreeManChess/Engine/Possibilities.hs
```

Sorry that you would have to see my eye-hurting code which is in the process of being refactored currently, after I dove into doing some type stuff *really* wrong a few months ago — that is, until I sit down to try to investigate and isolate the issue and manage to do so.

I just hope it's OK that I submit the issue already, as I guess `liquid` crashing with a pattern match failure would always be a bug, no matter what would be in the input.

### Output:
```
LiquidHaskell Version 0.8.2.4
Copyright 2013-18 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************
 

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  Transformed Core ***************************************************
 
liquid: Pattern match failure in do expression at src/Language/Haskell/Liquid/Constraint/Generate.hs:816:8-23
```

**Comment by ranjitjhala** [comment]
Many thanks for submitting it!

Yes pattern match failures are always bugs we need to fix :)

Will get to it as soon as I finish with a current refactoring,

unless @nikivazou can look at it sooner.

At the very least some source-position information so the user

knows what part of their code is tickling the bug!

**Comment by nikivazou** [comment]
Hi @ArchieT, thanks for the report! 

The bug is still there, but with all these extensions in your file it is very difficult for me to understand what exactly is triggering it... 

Is it possible for you to minimize `ThreeManChess/Engine/Possibilities.hs` so that it only contains the source code that triggers the bug in liquid?

**Comment by mkf** [comment]
@nikivazou 
> Is it possible for you to minimize `ThreeManChess/Engine/Possibilities.hs` so that it only contains the source code that triggers the bug in liquid?

I don't really have time to tamper with that project at the moment, I'm rather busy with my studies and exams and one scientific project; I also couldn't find time for that back then — as I said in my first comment, I chose to post it here without isolating the issue as I knew it will be long before I can find time for that. Sorry.

**Comment by facundominguez** [comment]
I'm closing this issue since this was reported on a version of GHC that we no longer support. But please, feel free to reopen if you encounter similar issues with a newer Liquid Haskell.
