### ISSUE TITLE
Cannot define `pos` from reflection paper

### ISSUE THREAD

**Issue by remysucre** [ucsd-progsys/liquidhaskell#1370]
I was trying to run the `pos` example from the POPL 18 paper that differentiates LH from Dafny: 

```
pos :: Int -> Int
pos n | n < 0 = 0
      | otherwise = 1 + pos (n - 1)
```
But I'm getting a type error: 
```
13 |       | otherwise = 1 + pos (n - 1) 
                                   ^^^^^
  
   Inferred type
     VV : {v : GHC.Types.Int | v == n - 1}
  
   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV < n
                                && VV >= 0}
  
   In Context
     n : GHC.Types.Int
```
Why should `n - 1` be required to be non-negative?

**Comment by ranjitjhala** [comment]
This is an error reported by the termination checker.

By default LH checks that `pos` is only invoked on decreasing `Nat` values, i.e. at the recursive call, it checks that the `n-1` parameter is a `VV` that iss

* `0 <= VV` (non-negative i.e. `Nat`)  and 
* `V < n`.

The first condition fails when the `n == 0`.

You can appease the checker either by LH either by adding a case for the `n==0` case,
or by providing an explicit termination metric, here `n+1` -- which is always non-negative and decreasing:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1541095878_1357.hs

```
-- extra equation for n==0 case
pos1 :: Int -> Int 
pos1 n 
  | n <  0    = 0 
  | n == 0    = 1 
  | otherwise = 1 + pos1 (n-1) 
  
-- explicit metric
{-@ pos :: n:_ -> _ / [n+1] @-}
pos :: Int -> Int 
pos n 
  | n <  0    = 0 
  | otherwise = 1 + pos (n-1) 
```
