### ISSUE TITLE
Error with Proof Combinators and Types Refined by Predicates

### ISSUE THREAD

**Issue by asvarga** [ucsd-progsys/liquidhaskell#1378]
As a minimal example of the problem I'm having, here's a definition of natural numbers, a doubling function, and a type refined by an even-ness predicate:

    data Nat' = Z | S Nat' deriving Show

    {-@ reflect double' @-}
    double' :: Nat' -> Nat'
    double' Z = Z
    double' (S x) = (S (S (double' x)))

    {-@ type Even' = {v:Nat' | even' v} @-}

    {-@ reflect even' @-}
    even' :: Nat' -> Bool
    even' Z = True
    even' (S Z) = False
    even' (S (S x)) = even' x

I'd like to first declare `{-@ double' :: Nat' -> Even' @-}` and then prove this to be true, but I'm under the impression that I instead must first write the proof and then use `castWithTheorem` (which itself has worked for me) as such:

    {-@ even_double :: x:Nat' -> {even' (double' x)} @-}
    even_double Z =     even' (double' Z) 
                  ==.   even' Z  
                  ==.   True 
                  ***   QED
    even_double (S x) =     even' (double' (S x))
                      ==.   even' (S (S (double' x)))
                      ==.   even' (double' x)
                      ?     even_double x
                      ==.   True
                      ***   QED

    {-@ double :: Nat' -> Even' @-}
    double x = castWithTheorem (even_double x) (double' x)

However, this gives fairly illegible errors like:

    :1:1-1:1: Error
      elaborate solver elabBE 177 "lq_anf$##7205759403792806976##d3tK" {lq_tmp$x##1556 : (GHC.Types.$126$$126$ (GHC.Prim.TYPE GHC.Types.LiftedRep) (GHC.Prim.TYPE GHC.Types.LiftedRep) bool bool) | [(lq_tmp$x##1556 = GHC.Types.Eq#)]} failed on:
          lq_tmp$x##1556 == GHC.Types.Eq#
      with error
          Cannot unify (GHC.Types.$126$$126$ (GHC.Prim.TYPE GHC.Types.LiftedRep) (GHC.Prim.TYPE GHC.Types.LiftedRep) bool bool) with func(0 , [(GHC.Prim.$126$$35$ @(42) @(43) @(44) @(45));
              (GHC.Types.$126$$126$ @(42) @(43) @(44) @(45))]) in expression: lq_tmp$x##1556 == GHC.Types.Eq# 
      because
    Elaborate fails on lq_tmp$x##1556 == GHC.Types.Eq#
      in environment
          GHC.Types.Eq# := func(4 , [(GHC.Prim.$126$$35$ @(0) @(1) @(2) @(3));
                                     (GHC.Types.$126$$126$ @(0) @(1) @(2) @(3))])

          lq_tmp$x##1556 := (GHC.Types.$126$$126$ (GHC.Prim.TYPE GHC.Types.LiftedRep) (GHC.Prim.TYPE GHC.Types.LiftedRep) bool bool)

Am I doing something wrong? From my experiments, it seems to be caused by trying to prove that some predicate function is true of some argument.

**Comment by ranjitjhala** [comment]
Hi @asvarga -- 

apologies for this; can you post your entire file. 

Are you importing `NewProofCombinators`? 

We should deprecate the `==.` combinator as it tickles some odd new constructs in GHC 8.6 ... 

So you should instead use `===` as shown here:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1543595949_5844.hs

**Comment by asvarga** [comment]
Thank you! That fix works for me. I was using `ProofCombinators` and wasn't aware of `NewProofCombinators`. Are there any examples/documentation of the combinators? I've been referring to 

- https://arxiv.org/pdf/1806.03541.pdf
- http://ucsd-progsys.github.io/liquidhaskell-tutorial/
- https://ucsd-progsys.github.io/liquidhaskell-blog/2016/09/18/refinement-reflection.lhs/. 

Also, is this the correct/simplest way to prove these kinds of properties?

**Comment by ranjitjhala** [comment]
Yes, that's the main documentation ATM (and am currently working on a bunch more.)
(Un)fortunately, we keep simplifying the combinators...

Yes, this is the simplest. Once you get a little more experience, you may want to "skip" 
all the intermediate steps of the proof, by switching on something called "--ple"; when 
you switch it on, your proofs are simplified to:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1543601468_5947.hs

Intuitively, with `ple` you never need to unfold function definitions, you only need the 
"lemmas" or "induction hypothesis", but it can be difficult to understand why a proof fails...

Am working on a large-ish tutorial on this new material since I think its mature enough. 

Stay tuned!

**Comment by ranjitjhala** [comment]
@asvarga I just merged a new `ProofCombinators` module into `develop` -- you should be able to use it on your original file too!
