### ISSUE TITLE
Totality checking of lazy functions depends on argument order

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1396]
Given the following definitions:
```haskell
data Peano = Z | S Peano

{-@ lazy ack @-}
ack :: Peano -> Peano -> Peano
ack Z n = S n
ack (S m) Z = ack m (S Z)
ack (S m) (S n) = ack m (ack (S m) n)

{-@ lazy ackFlipped @-}
ackFlipped :: Peano -> Peano -> Peano
ackFlipped n Z = S n
ackFlipped Z (S m) = ackFlipped (S Z) m
ackFlipped (S n) (S m) = ackFlipped (ackFlipped n (S m)) m
```
Liquid Haskell fails to prove `ackFlipped` is total, but it has no trouble with `ack`:
```text
Error: Liquid Type Mismatch
  
 11 | ackFlipped n Z = S n
      ^^^^^^^^^^
  
   Inferred type
     VV : {v : GHC.Prim.Addr# | v == "/home/rose/research/liquidhaskell/tests/terminate/pos/Ackermann.hs:(11,1)-(13,58)|function ackFlipped"}
  
   not a subtype of Required type
     VV : {VV : GHC.Prim.Addr# | 5 < 4}
```
If you give `ackFlipped` an explicit termination metric, it succeeds:
```haskell
data Peano = Z | S Peano

{-@ measure peanoToNat @-}
{-@ peanoToNat :: Peano -> Nat @-}
peanoToNat :: Peano -> Int
peanoToNat Z = 0
peanoToNat (S n) = 1 + peanoToNat n

{-@ lazy ack @-}
ack :: Peano -> Peano -> Peano
ack Z n = S n
ack (S m) Z = ack m (S Z)
ack (S m) (S n) = ack m (ack (S m) n)

{-@ ackFlipped :: n:_ -> m:_ -> _ / [peanoToNat m, peanoToNat n] @-}
ackFlipped :: Peano -> Peano -> Peano
ackFlipped n Z = S n
ackFlipped Z (S m) = ackFlipped (S Z) m
ackFlipped (S n) (S m) = ackFlipped (ackFlipped n (S m)) m
```
This is also a problem for the new structural termination checker: even if `ackFlipped` passes it, it fails the totality check.

**Comment by ranjitjhala** [comment]
Interesting; I wonder what the core for ackFlipped looks like. In
particular why does GHC not think it total?

**Comment by rosekunkel** [comment]
This is the core:
```haskell
Rec {
-- RHS size: {terms: 38, types: 14, coercions: 0, joins: 1/1}
ackFlipped [Occ=LoopBreaker] :: Peano -> Peano -> Peano
[LclIdX]
ackFlipped
  = \ (n_ask :: Peano) (ds_dXx :: Peano) ->
      join {
        fail_dXF :: GHC.Prim.Void# -> Peano
        [LclId[JoinId(1)]]
        fail_dXF _ [Occ=Dead, OS=OneShot]
          = Control.Exception.Base.patError
              @ 'GHC.Types.LiftedRep
              @ Peano
              "Ackermann.hs:(7,1)-(9,58)|function ackFlipped"# } in
      case ds_dXx of {
        __DEFAULT ->
          case n_ask of {
            Z ->
              case ds_dXx of {
                __DEFAULT -> jump fail_dXF GHC.Prim.void#;
                S m_asl -> ackFlipped (AckFlipped.S AckFlipped.Z) m_asl
              };
            S n_asm ->
              case ds_dXx of {
                __DEFAULT -> jump fail_dXF GHC.Prim.void#;
                S m_asn -> ackFlipped (ackFlipped n_asm (AckFlipped.S m_asn)) m_asn
              }
          };
        Z -> AckFlipped.S n_ask
      }
end Rec }
```

**Comment by rosekunkel** [comment]
For reference this is the core for `ack`:
```haskell
Rec {
-- RHS size: {terms: 21, types: 6, coercions: 0, joins: 0/0}
ack [Occ=LoopBreaker] :: Peano -> Peano -> Peano
[LclIdX]
ack
  = \ (ds_dXr :: Peano) (n_as8 :: Peano) ->
      case ds_dXr of {
        Z -> Ackermann.S n_as8;
        S m_as9 ->
          case n_as8 of {
            Z -> ack m_as9 (Ackermann.S Ackermann.Z);
            S n_asc -> ack m_as9 (ack ds_dXr n_asc)
          }
      }
end Rec }
```

**Comment by ranjitjhala** [comment]
Note no patError in the second one (ack) ie even GHC knows it’s ok, but for
some reason not so in the first one ... bit late in the day to decipher the
JOIN stuff but I wonder why the metrics should make a difference. Any clue
@nikivazou?

**Comment by rosekunkel** [comment]
Interestingly, if I add a case
```haskell
ackFlipped _ _ = error "unreachable"
```
GHC complains about redundant patterns. The core still has failure cases when I do this, but LH can somehow prove it's total with this extra case. This is the new core:
```haskell
Rec {
-- RHS size: {terms: 39, types: 14, coercions: 0, joins: 1/1}
ackFlipped [Occ=LoopBreaker] :: Peano -> Peano -> Peano
[LclIdX]
ackFlipped
  = \ (n_asa :: Peano) (ds_d2b6 :: Peano) ->
      case ds_d2b6 of {
        __DEFAULT ->
          join {
            fail_d2bh :: GHC.Prim.Void# -> Peano
            [LclId[JoinId(1)]]
            fail_d2bh _ [Occ=Dead, OS=OneShot]
              = error
                  @ 'GHC.Types.LiftedRep
                  @ Peano
                  $dIP_a1Zf
                  (GHC.CString.unpackCString# "unreachable"#) } in
          case n_asa of {
            Z ->
              case ds_d2b6 of {
                __DEFAULT -> jump fail_d2bh GHC.Prim.void#;
                S m_asb -> ackFlipped (Ackermann.S Ackermann.Z) m_asb
              };
            S n_asc ->
              case ds_d2b6 of {
                __DEFAULT -> jump fail_d2bh GHC.Prim.void#;
                S m_ase -> ackFlipped (ackFlipped n_asc ds_d2b6) m_ase
              }
          };
        Z -> Ackermann.S n_asa
      }
end Rec }
```
It looks like the main difference is just where the `join` happens.

**Comment by ranjitjhala** [comment]
so to be clear, if you do:

```
foo PAT1 = E1
foo PAT2 = E2
...
foo PATN = EN
```

GHC adds a `patError` BUT if you then add

```
foo PAT1 = E1
foo PAT2 = E2
...
foo PATN = EN
foo _    = error "..."
```

it says "redundant patterns" ?!!



<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.

**Comment by rosekunkel** [comment]
That's correct.

**Comment by ranjitjhala** [comment]
Can you replicate this just by compiling with GHC and using the flag
—ddump-core (I think that’s what it’s called) to make sure it’s not some LH
oddness?

**Comment by rosekunkel** [comment]
That's how I've been getting the core (with `--ddump-ds`). Is there a way to ask LH to dump the core directly?

**Comment by rosekunkel** [comment]
Oh I guess running with `-v` does that.

**Comment by gridaphobe** [comment]
Interesting example! If you write out the cases manually for `ackFlipped` you get

```
ackFlippedCase :: Peano -> Peano -> Peano
ackFlippedCase n m =
  case m of
    Z -> S n
    S m' ->
      case n of
        Z -> ackFlippedCase (S Z) m'
        S n' -> ackFlippedCase (ackFlippedCase n' (S m')) m'
```

which GHC desugars into

```
ackFlippedCase
  = \ (n_aYF :: Peano) (m_aYG :: Peano) ->
      case m_aYG of {
        Z -> Ack.S n_aYF;
        S m'_aYH ->
          case n_aYF of {
            Z -> ackFlippedCase (Ack.S Ack.Z) m'_aYH;
            S n'_aYI ->
              ackFlippedCase (ackFlippedCase n'_aYI (Ack.S m'_aYH)) m'_aYH
          }
      }
```

(If you swap the order of the `Z` and `S` alts, you get something similar, ie still no `patError`.)

Also, notice that the desugared `ackFlipped` does a complete case on `ds_d2b6` twice, which is clearly redundant. And indeed, if you add `-dverbose-core2core` and `-O`, you'll see that the very first simplifier pass cleans up the redundant case, giving

```
ackFlipped
  = \ (n_aYB :: Peano) (ds_d1bB :: Peano) ->
      case ds_d1bB of {
        Z -> Ack.S n_aYB;
        S ipv_s1c5 ->
          case n_aYB of {
            Z -> ackFlipped (Ack.S Ack.Z) ipv_s1c5;
            S n_aYD -> ackFlipped (ackFlipped n_aYD (Ack.S ipv_s1c5)) ipv_s1c5
          }
      }
```

This is probably the case-of-known-constructor optimization at work. Perhaps it would be worth running the simplifier once before we generate constraints to clean up things like this? It's pretty [configurable](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/Core2CorePipeline#Simplifier), so we could run just the bits that we expect to help LH.

**Comment by rosekunkel** [comment]
@nikivazou pointed out that the problem goes away with `--exactdc`. It seems because we don't define a measure, LH doesn't know enough about `Peano`'s constructors to prove `ackFlipped` is total when GHC fails to eliminate the error cases.

Maybe we should be turning `--exactdc` on by default? Structural termination eliminates the need to write a lot of measures, so it seems like we will run into this more and more.

**Comment by nikivazou** [comment]
This flippedAck is creating another problem. 
Structural termination fails when I turned on the `-fdefer-typed-holes` flag (in #1440). 
The only difference that I can see in core is that the `GHC.Stack.Types.HasCallStack` let binding is generated inside the `flippedAck` definition and globally with the `-fdefer-typed-holes` flag. Is that a reason for the structural termination checker to get confused? (@rosekunkel ?)

**Comment by rosekunkel** [comment]
@nikivazou Yes, if the let binding appears above one of the lambdas, it will get confused. I.E., this works fine:
```haskell
foo =
  \x ->
    let bar = 123 in
    case x of
      [] -> bar
      _:xs -> foo xs
```
But this fails:
```haskell
foo =
  let bar = 123 in
  \x ->
    case x of
      [] -> bar
      _:xs -> foo xs
```

**Comment by nikivazou** [comment]
@rosekunkel if there a reason for this restriction? doesn't seem like too difficult to fix it.

**Comment by rosekunkel** [comment]
@nikivazou There isn't a good reason. It was while attempting to fix this that I found all the other soundness bugs in the structural checker, though. I have a patch for it that's 90% complete, I just haven't had a chance to get it to 100%.

**Comment by ranjitjhala** [comment]
Here's another silly example of a "let" appearing above the lambda: the below FAILS the structural termination checker, 

```haskell
data Map k
  = Leaf
  | Node k (Map k)

foo :: (Ord k) => Map k -> k -> ()
foo (Node k l) key
  | key == k  = ()
  | otherwise = foo l key
foo Leaf _ = ()
```

but if I replace `Ord` with `Eq` it passes! 

The reason is that GHC converts the version with `Ord` into something like:

```haskell
foo = 
  let dEq = ...get eq-dict-from-ord-dict... in
  \ (m :: Map k) (key :: k) -> 
     case m of ...
```

in short, would be nice to resolve this :-)

**Comment by ranjitjhala** [comment]
RELATED: https://github.com/ucsd-progsys/liquidhaskell/issues/1403

**Comment by ranjitjhala** [comment]
Argh, and yet another failing case (I guess, really the same as the above...)

```haskell
module Bug where

data AExp
  = N Int
  | V String
  | Plus AExp AExp

subst :: String -> AExp -> AExp -> AExp
subst x e (Plus  a1 a2)  = Plus  (subst x e a1) (subst x e a2)
subst x e (V y) | x == y = e
subst _ _ a              = a
```

**Comment by ranjitjhala** [comment]
@rosekunkel any headway on this? were you stuck on those last three failing regressions or something else?

**Comment by rosekunkel** [comment]
I'm stuck on those 3 regressions, although more accurately I've been stuck
on classwork. I'll try to get those fixed tomorrow.

**Comment by ranjitjhala** [comment]
No worries, can you list those three here -- I can take a look if I get a moment.

**Comment by rosekunkel** [comment]
https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/MutualRec.hs
https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/GhcSort1.hs
https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/malformed0.hs
And possibly this one, although that might be caused by something I changed:
https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/neg/LocalSpec.hs

**Comment by ranjitjhala** [comment]
Of these, I suggest:

1. For `MutualRec`, `GhcSort1` and `malformed0`, just add `{-@ LIQUID "--no-termination" @-}` because it seems like those files were being marked safe because of some bug. (It's possible that the "decrease" annotations were working, but those have long been superseded by the metric stuff, so we should probably just open a *separate issue* on extending the metric stuff to work on mutually-recursive functions with *different* numbers of parameters. (Assuming that doesn't work now, right @nikivazou ?)

2.  For `LocalSpec` yes, make sure that is not a bonafide regression: it has nothing to do with termination AFAICT, and I think was a test added to make sure we resolved local names correctly,
so we definitely don't want to break that test.
