### ISSUE TITLE
Another failure to prove structural termination  

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1405]
The following cannot be proved to terminate structurally: 

```
data Pair a b = Pair a b 
data Q a
  = QEmp
  | QOneZero a   (Q (Pair a a))
  | QOneOne  a   (Q (Pair a a)) a 
  
snoc :: Q a -> a ->  (Q a)
snoc (QOneOne y1 ys y2) x 
  = QOneZero y1 (snoc ys (Pair y2 x))
snoc _ _ = QEmp 
```

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1549275297_15704.hs

**Comment by ranjitjhala** [comment]
Why should the structural checker get this?

**Comment by nikivazou** [comment]
`snoc (QOneOne y1 ys y2) x` calls  `snoc ys (Pair y2 x)`, one element is removed, so I thought it would accept it. No?

**Comment by ranjitjhala** [comment]
There’s some funky polymorphic recursion going on so not clear ... I guess
it should but this is not a plain ADT. Maybe @nomeata or @rosekunkel can
comment?

**Comment by nomeata** [comment]
This is not generally considered structural recursion; it does not follow the *structure* of the ADT. Instead, you are arguing about the size of the expression, but once you talk about size, you need something to solve linear inequalities … like an SMT.

**Comment by rosekunkel** [comment]
Why is this not structural recursion? It looks like ys is a subterm of the
first argument.

**Comment by nomeata** [comment]
So, I misread the code. Ignore what I said. This should be structurally recursive

**Comment by rosekunkel** [comment]
This example works for me (locally and on the demo). What error were you seeing @nikivazou?

**Comment by nikivazou** [comment]
True, I oversimplified... Here is the whole (failing) function: 

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1549469245_15764.hs

**Comment by nomeata** [comment]
Well, this is not structural recursive:
```
snoc (QTwoOne y1 y2 ys y3) x
  = exactBind 2 ys (\ys' -> 
                waitN 2 (QTwoZero y1 y2 (snoc ys' (Pair y3 x))))
```
Note that `ys'` is not a subterm of the argument to `snoc`.

**Comment by nikivazou** [comment]
Correct, I did miss that (and got spoiled with everything getting accepted by structural checker with zero annotations) Thanks!
