### ISSUE TITLE
Value of a tuple not evaluated when the type is Data.Text

### ISSUE THREAD

**Issue by racherb** [ucsd-progsys/liquidhaskell#1406]
The following refinement works well for Int, Char and String data types but not for the Text type.

```
{-@ type NoRouteToHimself = {v:(_, _) | (fst v) /= (snd v)} @-}
{-# LANGUAGE OverloadedStrings #-}
import qualified Data.Text as Tx

{-@ foo :: NoRouteToHimself @-}
foo :: (Tx.Text, Tx.Text)
foo = ("AA", "AB")
```

It is expected that the output of Liquid will be SAFE, however, it seems that it is not enough to evaluate the value of the tuple for the Data.Text type. 

 ```
..Example.hs:102:3-5: Error: Liquid Type Mismatch

 102 |   foo = ("AA", "AB")
         ^^^

   Inferred type
     VV : {v : (Data.Text.Internal.Text, Data.Text.Internal.Text) | x_Tuple22 v == ?a
                                                                    && x_Tuple21 v == ?b
                                                                    && snd v == ?a
                                                                    && fst v == ?b}

   not a subtype of Required type
     VV : {VV : (Data.Text.Internal.Text, Data.Text.Internal.Text) | fst VV /= snd VV}

   In Context
     ?b : Data.Text.Internal.Text

     ?a : Data.Text.Internal.Text
```

**Comment by ranjitjhala** [comment]
Hmm, this _should_ be easy to fix, essentially:

1. Figure out how the literal is represented in the Core,

2. Extend the current handling of string literals as below, to the corresponding functions in the `Text` library.

```haskell
-- include/GHC/CString.spec
GHC.CString.unpackCString :: x:GHC.Prim.Addr# -> {v:[Char] | v ~~ x && len v == strLen x}
```

**Comment by ranjitjhala** [comment]
Thanks for filing this issue @racherb !

**Comment by racherb** [comment]
Hello **@ranjitjhala**, thank you for the contribution of your project to the Haskel community. I've tried to execute the specifications as indicated and my code still doesn't work. 

For example: 

`$ liquid -i include/GHC/CString.spec target.hs -v`

Am I making incorrect use? or do I need to specify something else?

Best regards,

**Comment by ranjitjhala** [comment]
Hi @racherb -- LH already includes those files so that doesn't help. Instead, what is needed is to refine the type of  `Data.String.fromString` to say that the value returned is equal to the input string.
The easiest way for you to make progress is to add that signature as an `assume` to your file, e.g.

```haskell
{-@ assume Data.String.fromString :: x:_ -> {v:_ | v ~~ x} @-}

{-@ type NoRouteToHimself = {v:(_, _) | (fst v) /= (snd v)} @-}
{-# LANGUAGE OverloadedStrings #-}
import qualified Data.Text as Tx

{-@ foo :: NoRouteToHimself @-}
foo :: (Tx.Text, Tx.Text)
foo = ("AA", "AB")
```

LH says "safe" on the above file :-)

The _ideal_ situation is to add that signature to the LH prelude e.g. to modify the line 

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/include/Data/String.spec#L8

to have the additional constraint `i ~~ o` (so it says the same thing as the above `assume`.)

It would be great if you could submit a PR to do that (if not, I can do it later this afternoon too...)

(Hopefully it shouldn't break anything...)

**Comment by racherb** [comment]
Thank you very much, it worked excellently just by adding the **assume** sentence.

I think this kind of specifications should be solved on the LH side, so the programmer focuses only on the specification. We understand that this is only the beginning of LH and that in the future LH will resolve these details internally, at least for Haskell's most popular code libraries.

We are very excited to follow this project. I will include a PR to consider this topic.

(Your help has been very accurate. Thank you ...)

**Comment by racherb** [comment]
Ranjit, the PR has been generated.

**Comment by ranjitjhala** [comment]
Thanks a bunch! merged!
