### ISSUE TITLE
Reflected infix append function causes "Error: Cannot parse specification"

### ISSUE THREAD

**Issue by adrwes** [ucsd-progsys/liquidhaskell#1421]
The code below should be accepted by Liquid Haskell but is not. Removing the function `nilAppendId` or using an prefix append function instead, results in the code being accepted.

``` haskell
module Bug where
{-@ LIQUID "--higherorder"    @-}
{-@ LIQUID "--exact-data-con" @-}

import Language.Haskell.Liquid.ProofCombinators 
import Prelude hiding ((++))

{-@ infix ++ @-}
{-@ reflect ++ @-}
(++) :: [a]-> [a] -> [a] 
[] ++ ys = ys 
(x:xs) ++ ys = x : (xs ++ ys)

{-@ appendNilId :: xs:[a] -> { xs ++ [] = xs } @-}
appendNilId :: [a] -> Proof
appendNilId xs = undefined 

{-@ nilAppendId :: xs:[a] -> { [] ++ xs = xs } @-}
nilAppendId :: [a] -> Proof
nilAppendId xs = undefined 
```

### Error message

```
LiquidHaskell Version 0.8.4.0, Git revision ea8217bcdd78e550ef2b39237dc83fe2f1122b69
Copyright 2013-18 Regents of the University of California. All Rights Reserved.

**** DONE:  annotate ***********************************************************
 
**** RESULT: ERROR *************************************************************

 [PATH TO FILE]/Bug.hs:19:35: Error: Cannot parse specification:
  
 19 | {-@ nilAppendId :: xs:[a] -> { [] ++ xs = xs } @-}
                                        ^
     unexpected "+"
     expecting white space or "}"
```

**Comment by rosekunkel** [comment]
As a workaround, if you change `[]` to `nil` then it parses:
```haskell
module Bug where
{-@ LIQUID "--higherorder"    @-}
{-@ LIQUID "--exact-data-con" @-}

import Language.Haskell.Liquid.ProofCombinators 
import Prelude hiding ((++))

{-@ infix ++ @-}
{-@ reflect ++ @-}
(++) :: [a]-> [a] -> [a] 
[] ++ ys = ys 
(x:xs) ++ ys = x : (xs ++ ys)

{-@ appendNilId :: xs:[a] -> { xs ++ nil = xs } @-}
appendNilId :: [a] -> Proof
appendNilId xs = undefined 

{-@ nilAppendId :: xs:[a] -> { nil ++ xs = xs } @-}
nilAppendId :: [a] -> Proof
nilAppendId xs = undefined 
```

**Comment by adrwes** [comment]
> As a workaround, if you change `[]` to `nil` then it parses:
> 
> ```
> module Bug where
> {-@ LIQUID "--higherorder"    @-}
> {-@ LIQUID "--exact-data-con" @-}
> 
> import Language.Haskell.Liquid.ProofCombinators 
> import Prelude hiding ((++))
> 
> {-@ infix ++ @-}
> {-@ reflect ++ @-}
> (++) :: [a]-> [a] -> [a] 
> [] ++ ys = ys 
> (x:xs) ++ ys = x : (xs ++ ys)
> 
> {-@ appendNilId :: xs:[a] -> { xs ++ nil = xs } @-}
> appendNilId :: [a] -> Proof
> appendNilId xs = undefined 
> 
> {-@ nilAppendId :: xs:[a] -> { nil ++ xs = xs } @-}
> nilAppendId :: [a] -> Proof
> nilAppendId xs = undefined 
> ```

Ok interesting, is nil a synonym for [] in the logic? 
Still strange that the specification for appendNilId is parsed just fine with []!

**Comment by rosekunkel** [comment]
Yes, `nil` is a synonym for `[]`. The parser does not handle list literals well in general, unfortunately.

**Comment by ranjitjhala** [comment]
Thanks @rosekunkel!

This is a recurring issue, I think I'll try to fix the parser to accept `[]` ...

**Comment by adrwes** [comment]
Another workaround seems to be to wrap the [] in parentheses:
``` haskell
module Bug where
{-@ LIQUID "--higherorder"    @-}
{-@ LIQUID "--exact-data-con" @-}

import Language.Haskell.Liquid.ProofCombinators 
import Prelude hiding ((++))

{-@ infix ++ @-}
{-@ reflect ++ @-}
(++) :: [a]-> [a] -> [a] 
[] ++ ys = ys 
(x:xs) ++ ys = x : (xs ++ ys)

{-@ appendNilId :: xs:[a] -> { xs ++ [] = xs } @-} 
appendNilId :: [a] -> Proof
appendNilId xs = undefined 

{-@ nilAppendId :: xs:[a] -> { ([]) ++ xs = xs } @-}
nilAppendId :: [a] -> Proof
nilAppendId xs = undefined 
```

**Comment by ranjitjhala** [comment]
Wow! Thanks Adrian I didn’t know about this workaround!

**Comment by nikivazou** [comment]
It also works if you put the parenthesis around the append ` ([] ++ xs)  == xs`, in case it is a bit less ugly...
