### ISSUE TITLE
Demo does not compile

### ISSUE THREAD

**Issue by ulysses4ever** [ucsd-progsys/liquidhaskell#1430]
Take the simplest example: [Basics/Evens.hs](http://goto.ucsd.edu:8090/index.html#?demo=evens.hs). Clicking on "Check" gives the error, which I can reproduce locally on a fresh `master` checkout.:
```
liq.hs:9:1-7: Error: Liquid Type Mismatch
  
 9 | notEven = 7
     ^^^^^^^
  
   Inferred type
     VV : {v : GHC.Types.Int | v == 7}
  
   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV mod 2 == 0}
```

**Comment by ranjitjhala** [comment]
Oh dear, `master` is _super_ old (thanks for the reminder, will update!)
please use `develop` which is kept upto date. (sorry for the confusion!)

**Comment by ulysses4ever** [comment]
Gotcha, thanks!

**Comment by ulysses4ever** [comment]
Just noting that online availability is an important feature.

**Comment by ranjitjhala** [comment]
Oh sorry, I didn't realize you were referring to the demo! 

Notice that response in the online demo is the *correct* 
and *desired* one: note that `7` is not an even number :-)

**Comment by ulysses4ever** [comment]
Ouch, silly me, thanks!
