### ISSUE TITLE
Parsing include/Data/ByteString/Lazy.spec fails

### ISSUE THREAD

**Issue by lippirk** [ucsd-progsys/liquidhaskell#1445]
I've spent a while trying to get liquidhaskell working with nix, but finally hit this blocker.

I've compiled `liquidhaskell` with v0.8.0.1 of `liquid-fixpoint` and v0.8.4.0 of `liquidhaskell` (I borrowed the exact commits to use from the following overlays https://github.com/mhwombat/dotWombat/tree/master/nix-overlays). I compiled with ghc-8.4.3 (specifically nixos-18.09 ghc843). 

Running `liquid -i src/ Path/To/Module.hs` gives me an error about not being able to parse the lazy bytestring spec file (specifically the error relates to the `tail` function). I removed the `tail` spec to see what happens, and I get the same error, but about the next function in the file, `init`:

```
LiquidHaskell Version 0.8.4.0
Copyright 2013-18 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************
 

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


 /nix/store/wqzlkaqdrrga6viarp5yj4v3p4mrk5lg-liquidhaskell-0.8.4.0-data/share/ghc-8.4.3/x86_64-linux-ghc-8.4.3/liquidhaskell-0.8.4.0/include/Data/ByteString/Lazy.spec:71:1: Error: Cannot parse specification:
  
 71 | init
      ^
  
     unexpected "i"
     expecting space, "->", "~>", "=>" or "/"
     Type signature (bs:{bs : Data.ByteString.Lazy.ByteString | 1 <= bllen bs}
     -> Data.Word.Word8 defined from: "/nix/store/wqzlkaqdrrga6viarp5yj4v3p4mrk5lg-liquidhaskell-0.8.4.0-data/share/ghc-8.4.3/x86_64-linux-ghc-8.4.3/liquidhaskell-0.8.4.0/include/Data/ByteString/Lazy.spec" (line 68, column 8) to: "/nix/store/wqzlkaqdrrga6viarp5yj4v3p4mrk5lg-liquidhaskell-0.8.4.0-data/share/ghc-8.4.3/x86_64-linux-ghc-8.4.3/liquidhaskell-0.8.4.0/include/Data/ByteString/Lazy.spec" (line 71, column 1),Nothing) must have non-empty list of binders!
```

I expect this not to happen. Perhaps this relates to #707 ? Also, perhaps it has been fixed on master (i think the commits i am using are from late 2018).

In addition, ideally I would not have to compile liquidhaskell from source, as it is not obvious which versions of `liquidihaskell`, `liquid-fixpoint` and `ghc` work well together!

**Comment by nikivazou** [comment]
This version of LH is indeed quite old. Can you pull the develop branch? 
We use`stack` to synch `ghc` with the `liquidhaskell` version and `submodules` to synch with `liquid-fixpoint`. So if you follows these steps, it should work https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#step-2-install-liquid-from-source

**Comment by lippirk** [comment]
Yes, compiling LH (in isolation) works :+1: and the spec error has gone!

Unfortunately `stack` refuses to compile LH alongside the other packages in a project where I want to use LH. The next thing to try is to install LH globally. I gave this a go, but then calling `liquid` falls over, presumably because it can't see the local packages I have installed:

```
LiquidHaskell Version 0.8.6.0
Copyright 2013-19 Regents of the University of California. All Rights Reserved.

liquid: Prelude: Could not find module ‘GDP’
Use -v to see a list of the files searched for.
```
^ here GDP is a module from the `gdp` package

Do you know if there is a way of remedying this? Maybe a way to tell `liquid` - 'use this ghc package database please'?

**Comment by lippirk** [comment]
It seems that my question above was answered here:

https://github.com/ucsd-progsys/liquidhaskell/issues/1099

you can do it with: 

`liquid examples/search.hs --ghc-option='-package-db=/nix/store/hy1ihz6ngllvfzyif6b5gf2qgcx54ygz-ghc-8.0.2-with-packages/lib/ghc-8.0.2/package.conf.d'`

Now I have a ghc linker error, but I guess that's my own fault.

Thanks for your help!
