### ISSUE TITLE
Can't reflect functions with recursive helpers.

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1448]
A function with a recursive helper like this:
```haskell
{-@ LIQUID "--reflection" @-}

{-@ reflect foo @-}
foo :: Bool -> ()
foo x = go x
  where
    go False = ()
    go True = go False
```
can't be reflected at all currently. The error message is:
```text
 Error: Cannot lift Haskell function `foo` to logic
    Cannot make Logical Substitution of Recursive Definitions
```
It would be nice if it could be reflected, although it's not clear how we would reference `go` in proofs; maybe we could do something like this:
```haskell
{-@ thm :: { foo True == () } @-}
thm :: ()
thm =
  foo True
  === go True
  === go False
  === ()
  *** QED
  where
    {-@ go :: x:_ -> {v:() | v == foo.go x} @-}
    go False = ()
    go True = go False

**Comment by rosekunkel** [comment]
This should probably still be changed even if we don't come up with a way to reference `go` in proofs, since PLE can remove the need to in a lot of cases.

**Comment by ranjitjhala** [comment]
This is tricky but doable; I guess it’s always been easier to just rewrite
to hoist the inner function out?

**Comment by rosekunkel** [comment]
Yes, the way I encountered it was trying to reflect Prelude's definition of `gcd`: if we're going to make people copy library functions in order to reflect them, it would be nice if they didn't have to rewrite them as well.

**Comment by ranjitjhala** [comment]
True, but PLE won't always work, esp. if the internal functions are recursive, and require some sort of induction. Given that its unclear how to then "call" the internal functions, in a "proof term", I can't think of a reasonable way around this (without rewriting code to expose helpers at the top level...)

**Comment by ranjitjhala** [comment]
Not sure whether to keep closed or open; definitely an interesting problem to think about! /cc @abakst
