### ISSUE TITLE
`is$...` measures not generated for imported types

### ISSUE THREAD

**Issue by abakst** [ucsd-progsys/liquidhaskell#1454]
Error of the sort:

`Unbound symbol is$Foo.Bar.A1 --- perhaps you meant: is$Foo.Bar.D1 ?`

To reproduce: 
  1. clone https://github.com/abakst/scratch
  2. run `make proof`

The `is$...` measures are not available in `Foo.Baz` despite the refined data in `Foo.Bar`.

Possibly related to #1284.

**Comment by ranjitjhala** [comment]
You're missing a `-i lib` to tell LH to use the `lib/` to search for the source files, and generated intermediate stuff.

For example, tweak your Makefile to:

```
LIQUID = stack exec -- liquid -i lib --reflection --no-termination

proof:
        stack build
        $(LIQUID) lib/Foo/Bar.hs
        $(LIQUID) lib/Foo/Baz.hs
```

**Comment by ranjitjhala** [comment]
Of course, please reopen if the above doesn't work :-)

**Comment by abakst** [comment]
Aha, thanks.

Now, if I *remove* the data refinements, then the error reappears (note that `--exact-data-cons` is provided in the Makefile).

**Comment by abakst** [comment]
(I should add that I am not sure if this is expected behavior or not, hence not re-opening)

**Comment by abakst** [comment]
On second second thought, re-opening since the issue title seems relevant still :)

**Comment by ranjitjhala** [comment]
Is your repo upto date? (i.e. can still reproduce with current repo?)

btw,

1. You don't need the `data` refinements unless there are actual
refinements,
2. `exact-data-con` is subsumed by `reflection` and not needed...

**Comment by ranjitjhala** [comment]
Looks like this has to do with the command line params;
putting `{-@ LIQUID "--reflection" @-}` in the files
solves it. Can you confirm?

**Comment by abakst** [comment]
Yep that does it, thanks
