### ISSUE TITLE
`is$...` measures not generated for imported types without data decl

### ISSUE THREAD

**Issue by abakst** [ucsd-progsys/liquidhaskell#1455]
Error of the sort:

`Unbound symbol is$Foo.Bar.A1 --- perhaps you meant: is$Foo.Bar.D1 ?`

To reproduce: 
  1. clone https://github.com/abakst/scratch
  2. run `make proof`

The `is$...` measures are not available in `Foo.Baz` despite running `liquid` with `--exact-data-cons`

Is this expected behavior?

Possibly related to #1284.

**Comment by abakst** [comment]
Note that w.r.t. #1454, in this case the data types are not refined, so it's not clear if `--exact-data-cons` is expected to produce the `is$...` measures.

**Comment by ranjitjhala** [comment]
See note: 

* Don't use `exact-data-con` (should be deprecated...!)
* Do put `--reflection` in the source.

IIRC there was a reason I wanted it to be in the file and not passed in the command line...

**Comment by abakst** [comment]
Adding `--reflection` to the source does solve the issue, thanks.
