### ISSUE TITLE
PBE fails with let-bound function

### ISSUE THREAD

**Issue by abakst** [ucsd-progsys/liquidhaskell#1457]
```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--ple" @-}
module Foo.Qux where

{-@ reflect doFoo @-}
doFoo :: Int -> Int
doFoo n = go n
  where
    go :: Int -> Int
    go 0 = 1
    go n = n

{-@ sillyTheorem :: { doFoo 0 = 1 } @-}
sillyTheorem :: ()
sillyTheorem = ()
```

Running `liquid` on this module results in:

`crash: SMTLIB2 respSat = Error "line 303 column 23: unknown constant ds_d2oN"`

The crash goes away if I pull the definition of `go` out to the top level (and reflect it). Possibly related to #1204, but the failure is different.

**Comment by ranjitjhala** [comment]
Thanks for filing! As a general thing I think the reflect stuff doesn’t
like local functions so hoist to top level; am surprised this doesn’t
complain earlier ...

**Comment by abakst** [comment]
Is there a reason this can’t be mechanized besides a shortage of person-hours?

**Comment by ranjitjhala** [comment]
see https://github.com/ucsd-progsys/liquidhaskell/issues/1448

**Comment by facundominguez** [comment]
Verification passes for this example in the latest LH.
