### ISSUE TITLE
PartialTypeSignatures causes parameter number mismatch

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1458]
The following code has a type mismatch, even though the Haskell and LH signatures are identical:
```
{-# Language PartialTypeSignatures #-}

module ExtraParam where

foo :: (Eq a) => [a] -> [[a]]
foo xs = bar xs 0
  where
    bar (a:as) _ = baz a (a:) as 0

    {-@ baz :: _ -> _ -> _ -> Int -> _ @-}
    baz :: _ -> _ -> _ -> Int -> _
    baz b f bs _
      | b == b = baz b (b:) bs 0
      | otherwise = f [] : bar bs 0
```
The error is:
```
Error: Specified type does not refine Haskell type for `baz` (Plugged Init types old)
  
 10 |     {-@ baz :: _ -> _ -> _ -> Int -> _ @-}
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  
  
 The Liquid type
  
     _
     -> _
        -> _
           -> GHC.Types.Int
              -> _
  
 is inconsistent with the Haskell type
  
     forall a ->
GHC.Classes.Eq a =>
[a] -> a -> ([a] -> [a]) -> [a] -> GHC.Types.Int -> [[a]]
  
 defined at /home/rose/research/scratch/ExtraParam.hs:12:5-7
  
 Specifically, the Liquid component
  
     GHC.Types.Int
  
 is inconsistent with the Haskell component
  
     [a##a1Zg]
  
 
 HINT: Use the hole '_' instead of the mismatched component (in the Liquid specification)
```
The reason for the type mismatch is that the core for `baz` has an additional parameter not appearing in the source, the first parameter of type `[a]`. It seems like `baz` has gained `foo`'s argument for some reason. This is the most minimal example I could produce, changing pretty much anything about it no longer causes the problem. This seems to be some kind of interaction between `PartialTypeSignatures`, class constraints, and local mutual recursion.

**Comment by ranjitjhala** [comment]
Seems like GHC is trolling LH ...

Does deleting the GHC sig for baz help?

**Comment by rosekunkel** [comment]
Yes, if you delete the GHC signature for baz you get
```
The Liquid type
  
     a -> ([a] -> [a]) -> [a] -> GHC.Types.Int -> [[a]]
  
 is inconsistent with the Haskell type
  
     a -> ([a] -> [a]) -> [a] -> GHC.Integer.Type.Integer -> [[a]]
```
which can be fixed by annotating the `0`s as having type `Int`.

**Comment by ranjitjhala** [comment]
Wow. Well, pretty unclear what to do here, if GHC starts fiddling around 
with the binders in this fashion, beyond adding a link to this issue in the 
error message?

**Comment by ranjitjhala** [comment]
Closing since totally unclear what to do! :'(
