### ISSUE TITLE
Parsing include/Data/ByteString/Lazy.spec fails with head

### ISSUE THREAD

**Issue by Shimuuar** [ucsd-progsys/liquidhaskell#1459]
I have exactly same issue as #1445 except I'm building against develop branch (580aef36671058c9f8a28bf5900acf41d70b4f89)

```
LiquidHaskell Version 0.8.6.0, Git revision 580aef36671058c9f8a28bf5900acf41d70b4f89 (dirty)
Copyright 2013-19 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************
 

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


 /home/alexey/program/haskell/liquidhaskell/include/Data/ByteString/Lazy.spec:71:1: Error: Cannot parse specification:
  
 71 | tail
      ^
  
     unexpected "t"
     expecting space, "->", "~>", "=>" or "/"
     Type signature (bs:{bs : Data.ByteString.Lazy.ByteString | 1 <= bllen bs}
     -> Data.Word.Word8 defined from: "/home/alexey/program/haskell/liquidhaskell/./include/Data/ByteString/Lazy.spec" (line 68, column 8) to: "/home/alexey/program/haskell/liquidhaskell/./include/Data/ByteString/Lazy.spec" (line 71, column 1),Nothing) must have non-empty list of binders!
```

Example file triggering problem is:

```haskell
import qualified Data.ByteString.Lazy as BL

bar2 :: BL.ByteString -> Int
bar2 = sum . map fromIntegral . BL.unpack . BL.tail
```

I tried to build current head using nix, cabal and stack with identical results

**Comment by ranjitjhala** [comment]
Hi @Shimuuar, 

Thanks for posting this! I have fixed it in the above branch, which I'll merge in to `develop` soon.

If you are in a hurry, you can copy over the file 

https://github.com/ucsd-progsys/liquidhaskell/blob/f54e903a6e8068dbae103a74136888b8895bfa83/include/Data/ByteString/Lazy.spec

into your `include/Data/ByteString/Lazy.spec` -- or just wait a bit till I finish and merge!

**Comment by Shimuuar** [comment]
Thanks!

I think it would be nice to have tests checking that *.spec files shipped with liquidhaskell could be parsed. It will allow to catch regressions like these immediately. Also who knows how many other spec files bitrotted. I could try to write such test over weekend

**Comment by nikivazou** [comment]
That would be great! Thanks!
