### ISSUE TITLE
Remove `import` directive

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquidhaskell#146]
Since we have both `.spec` and `.hs` files in `include/`, the `import` directive can give the impression that you can import a `.hs` from a `.spec`. This is not the case, `.hs` imports are all handled by GHC in the `depanal` phase. Furthermore, the only reason to put a `.hs` file into the include directory is to add new Haskell functions, which would then have to be imported by the original source file anyway.

I suggest we scrap the `import` directive since it serves no purpose other than to let spec files include other spec files, but the Haskell module system already solves this problem. We should instead grab the _entire_ module graph from GHC (not the local modules that are exposed by `getModuleGraph`) and parse the specs that are part of the graph. It's not immediately clear to me how to get the whole graph, but it _must_ be possible somehow..

As an alternative, I would suggest making it an explicit error to import a `.hs` file from a `.spec` file.

**Comment by spinda** [comment]
I have a solution to this as part of my modular verification work.
