### ISSUE TITLE
LH can't determine that calling a function with an uninhabited type is impossible

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1480]
This file is deemed unsafe:
```haskell
module ErrorVoidType where

data Void

foo :: Void -> a
foo _ = error "impossible"
```
The message is
```
Error: Liquid Type Mismatch
  
 6 | foo _ = error "impossible"
                   ^^^^^^^^^^^^
  
   Inferred type
     VV : {v : [GHC.Types.Char] | v ~~ "impossible"
                                  && len v == strLen "impossible"
                                  && len v >= 0
                                  && v == "impossible"}
  
   not a subtype of Required type
     VV : {VV : [GHC.Types.Char] | false}
```
Since `Void` is uninhabited, this call to `error` should be deemed safe.

**Comment by ranjitjhala** [comment]
You can tell LH  that `Void` is uninhabited via the `using`  (/cc @nikivazou)

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1556217196_20867.hs

```haskell
{-@ using (Void) as {v:Void | False} @-}

data Void

foo :: Void -> a
foo _ = error "impossible"
```

**Comment by rosekunkel** [comment]
Unfortunately this doesn't work for uninhabited data families:
```haskell
{-# LANGUAGE TypeFamilies #-}
module ErrorVoidType where

class HasVoid a where
  data Void a

data MyType = MyType

instance HasVoid MyType where
  data Void MyType

{-@ using (Void MyType) as {v:Void MyType | False} @-}

foo :: Void MyType -> a
foo _ = error "impossible"
```

**Comment by ranjitjhala** [comment]
What possible reason could someone have for writing code like this? :)

**Comment by ranjitjhala** [comment]
The solution is to put a False precondition on foo.

Yes one shouldn’t have to, but really one shouldn’t write code like the
below ;-)

**Comment by rosekunkel** [comment]
Tell that to template Haskell d:

In seriousness the reasoning seems to be to allow a type class to have
optional data/methods attached in a well-typed way. In persistent the type
which is uninhabited represents additional uniqueness constraints on fields
in a table. If there are no additional constraints, the type is
uninhabited, and so the class methods which deal with those constraints
become uncallable.

**Comment by ranjitjhala** [comment]
This seems to work?

I guess the hassle is getting the preconditions in?


```
{-# LANGUAGE TypeFamilies #-}
module Zog where

class HasVoid a where
  data Void a

data MyType = MyType

instance HasVoid MyType where
  data Void MyType

{-@ foo :: {v: _ | false} -> b @-}
foo :: Void MyType -> b
foo _ = error "impossible"
```

<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.
