### ISSUE TITLE
Broken link for StreamInvariants example

### ISSUE THREAD

**Issue by googleson78** [ucsd-progsys/liquidhaskell#1488]
The following links: [pos](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/StreamInvariants.hs) [neg](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/neg/StreamInvariants.hs) are broken.

They are referenced in the readme in the [invariants section](https://github.com/ucsd-progsys/liquidhaskell#invariants)

**Comment by ranjitjhala** [comment]
Thanks for posting! Fixed now, see: `tests/measure/{pos, neg}/Using00.hs`
