### ISSUE TITLE
release on hackage is old

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#1494]
The version on hackage is 8.2.4 from Feb 2018, using GHC 8.2.2

The most recent release tag on github is [v8.4.3-final](https://github.com/ucsd-progsys/liquidhaskell/releases/tag/v8.4.3-final) which is built with GHC 8.4.3.

Current `development` branch tip builds with GHC 8.6.4.

Is there any reason not to update the version on hackage?

See also https://github.com/haskell/haskell-ide-engine/issues/1196

And it seems hie needs some minor tweaks to present the current develop branch properly.

**Comment by ranjitjhala** [comment]
Thanks for the ping @alanz -- Am meeting @nikivazou and we will update ASAP!

**Comment by alanz** [comment]
Thanks. Especially relevant with the co-recursive podcast just out.

**Comment by svmhdvn** [comment]
Would you be able to push a release now? Current version in master is 0.8.10.1 and the version on hackage is at 0.8.6.2. Doing this would help unbreak the build on nixpkgs.

**Comment by ranjitjhala** [comment]
Hi Siva, yes we are gearing up to release 0.8.10.1 very soon (just a last
few wrinkles to be ironed out.) thanks for your patience!

**Comment by facundominguez** [comment]
Closing as several releases on hackage have been done since.
