### ISSUE TITLE
Specs for specialised class functions?

### ISSUE THREAD

**Issue by googleson78** [ucsd-progsys/liquidhaskell#1496]
Is there a way to add a spec for a typeclass function, but specialised to a concrete type?

Example:
I want to add this spec:
```haskell
(<>) :: l : ByteString -> r : ByteString -> {x : ByteString | bslen l + bslen r == bslen x}
```
Currently `liquid` rejects this because it expects
```haskell
(<>) :: forall s. Semigroup s => s -> s -> s
```
and not `ByteString`s.

This really gets in the way of using the standard typeclasses in Haskell (I also encountered something similar when trying to use `any` from `Data.Foldable` on `[a]` and wanting to state that 
`any :: _ -> xs : [a]  -> {b : Bool | len xs == 0 ==> b ~ False }`)

**Comment by ranjitjhala** [comment]
Hmm, great question -- this is somewhat in flux right now. 
@nikivazou and @jprider63 -- how would something like 
this mesh with what you're thinking about for classes? 

Is this (a) already allowed? or (b) Not desirable?

**Comment by nikivazou** [comment]
There is no clear solution right now. 
What I do in these cases is define a new function with the specific type, e.g., 

```
{-@ assume (<>) :: l : ByteString -> r : ByteString -> {x : ByteString | bslen l + bslen r == bslen x} @-}
appendBS :: ByteString -> ByteString -> ByteString
appendBS = (<>)
```

**Comment by ranjitjhala** [comment]
Is the problem that it is somehow _unsound_ to have special instance
signatures?

**Comment by nikivazou** [comment]
No, there is nothing unsound, but you cannot prove this type signature. 
If you want to drop the `assume`, you need to use a run time check, e.g., 


```
{-@ (<>) :: l : ByteString -> r : ByteString -> {x : ByteString | bslen l + bslen r == bslen x} @-}
appendBS :: ByteString -> ByteString -> ByteString
appendBS l r = if BS.len o == BS.len l + BS.len r then o else error "this sound never happen" 
  where o = l <>r
```

**Comment by ranjitjhala** [comment]
You would put that signature on the _actual_ implementation of  `appendBS`, 
and then have it carry over to the `<>` instance. So:

```haskell
{-@ appendBS ::  l : ByteString -> r : ByteString -> {x : ByteString | bslen l + bslen r == bslen x} @-}
appendBS = ... code that is checked ...
```

and then you'd want do:

```haskell
instance Monoid ByteString where 
  {-@ (<>) ::  l : ByteString -> r : ByteString -> {x : ByteString | bslen l + bslen r == bslen x} @-}
  <> = appendBS
```

**Comment by jprider63** [comment]
For supporting this with typeclasses, I think we can add this refinement to the ByteString Monoid dictionary in core. We also discussed something like extending the refinement to `<>` with `&& (Monoid s == dictByteStringMonoid => {x : ByteString | bslen l + bslen r == bslen x})`.

**Comment by googleson78** [comment]
I would be fine with not checking the signature, it's going to be in a `.spec` file anyway (it's for `base`/`some-other-library-whose-source-code-i-dont-have-access-to`, so I can't attach it to the instance definition).

**Comment by facundominguez** [comment]
Closing since this has been implemented as [instance specifications](https://ucsd-progsys.github.io/liquidhaskell/specifications/#modules-with-code-type-classes-legacy).
