### ISSUE TITLE
SMTLIB2 crash with z3 4.8.5, but not with 4.8.4

### ISSUE THREAD

**Issue by googleson78** [ucsd-progsys/liquidhaskell#1503]
The following file:
```
module A where

import Foreign.Storable (poke)
import Foreign.Ptr (nullPtr)

x :: IO ()
x = poke nullPtr ()
```
crashes with the following error:
```
:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 13 column 13: invalid sort definition, sort already declared/defined"
```

with a `z3` built from its `Z3-4.8.5` tag (`e79542c`), but works fine from the `z3-4.8.4` tag (`d6df519`).

Not sure if I should be reporting this here (?)
 
(`--prune-unsorted` doesn't help)

My `liquid` is 
```
LiquidHaskell Version 0.8.6.0, Git revision fd35e1c17500ebe706d99260921a8e833561cdde [develop@fd35e1c17500ebe706d99260921a8e833561cdde (Mon May 20 15:33:05 2019 +0200)]
```

**Comment by nikivazou** [comment]
Thanks!!!

It seems that as of this version Z3 comes with a pre-defined sort for `Set`. 
Liquid Haskell defines it's own `Set` sort here: https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Smt/Theories.hs#L66
Can you edit the above definition to a different name (e.g., `LSet`) and check if this solves the problem? 
If it does a PR would be great!

**Comment by ranjitjhala** [comment]
What? Z3 now has a builtin `Set` -- not sure `LSet` will help then because
the name clash is in the LH prelude?

<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.

**Comment by nikivazou** [comment]
No, the name class comes the the SMT.Theories of fixpoint (LH prelude is qualified so we are good at that).

**Comment by googleson78** [comment]
[#403](https://github.com/ucsd-progsys/liquid-fixpoint/pull/403) fixes this. Feel free to close when the submodule here is updated.
