### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by mmport80** [ucsd-progsys/liquidhaskell#1509]
On Debian + Stack, I cannot build without GHC being installed. Perhaps add to installation instructions.

**Comment by rosekunkel** [comment]
That's interesting - I'm on Arch and I don't need to have GHC installed globally to build; stack installs one locally as needed. What version of stack + liquid haskell + debian are you using?

**Comment by rosekunkel** [comment]
Also - have you run `stack setup`?

**Comment by mmport80** [comment]
Hmm I cannot remember - good point - perhaps I missed that.

The error from stack though, was I was missing 'libtinfo.so'.

Not a big deal, just never saw that stack error message before - perhaps a
Stack useability issue..

**Comment by rosekunkel** [comment]
Oh, I've had that problem before. The issue is that stack depends on
ncurses and it must not have been installed - maybe GHC also depends on
ncurses and that's why installing GHC fixed the problem?

**Comment by mmport80** [comment]
possible - i was using a fresh google cloud Debian vm..

**Comment by facundominguez** [comment]
Closing because the build tooling has evolved since this was reported. But please, feel free to reopen if this is still problematic with a newer setup.
