### ISSUE TITLE
Dependence on GHC with which LH was compiled

### ISSUE THREAD

**Issue by googleson78** [ucsd-progsys/liquidhaskell#1513]
This is my use case:
I'm compiling LH with a "generic" `ghc` (just `git clone` and `stack install` afterwards), however I would like to be able to run it on a machine where I'm using a different `ghc` variant (`integer-simple` instead of `gmp` or `ncurses` instead of `tinfo` for example) to build my project.
Yet LH depends on
`/home/user/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/settings`
which depends on what `ghc` LH was built with.
This might not be the right place to ask but:

0. Does LH really require not only the same `ghc` version, but also the exact same variant?
1. Is there any way to tell it where to find/place this directory (like how you can use `--datadir` to tell `cabal` where to put the `include` stuff), either during build or at runtime?

More generally:
It's a big pain to get some kind of container (`docker` for example) with only `liquid` in it, so you can reuse it to test different projects, which could possibly use different `ghc` versions and variants. Is it possible to make it not depend on specific `ghc` versions/variants?

**Comment by gridaphobe** [comment]
LiquidHaskell heavily depends on the GHC API to parse/typecheck/desugar Haskell programs. So unfortunately, like most other users of the GHC API, it must be built for each variant of GHC that you use.

I think eventually LH should be converted to a GHC plugin rather than a standalone binary, which could avoid this confusion.

**Comment by ranjitjhala** [comment]
Btw in principle the ghc-lib library of Mitchell et al solves this problem
... but it has some restrictions I think eg no template Haskell.

**Comment by gridaphobe** [comment]
IIRC `ghc-lib`s restrictions are much more severe, i.e. you can't interact with any external libraries. The reason for this is very simple, using external libraries requires interacting with the package database, which is tied to the specific version of GHC you built against. (This is precisely the same reason LH is tied to specific GHC versions.)

**Comment by ranjitjhala** [comment]
Interesting! (Also unfortunate!)

Btw why would plug-ins not have the same issue?

**Comment by gridaphobe** [comment]
They would have the same issue, but cabal/stack would transparently handle building the correct version of LH for your GHC. So users shouldn't have to deal with it anymore.

**Comment by googleson78** [comment]
Thanks! Feel free to close if there is nothing left to discuss here.

**Comment by googleson78** [comment]
This should be "fixed" now that LH is a plugin, so I think we can close this.
