### ISSUE TITLE
Adding a data constructor named `Bool` causes name resolution error

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1521]
This file errors with "Error: Unknown type constructor `Bool`":
```haskell
data Foo = Bool

{-@ measure bar :: Int -> Bool @-}
```

This is a bigger problem than it seems because
1. Aeson defines a data constructor named `Bool`
2. Transitively including Aeson (even qualified) also triggers this problem

**Comment by nikivazou** [comment]
I assume somewhere in the LH codebase I have hard coded the name `Bool` (unqualified). 
Can you grep the codebase to find this place?

**Comment by ranjitjhala** [comment]
It could also just be the heuristics for name resolution yielding a crash.
Shouldn’t happen because one is a tycon and the other a datacon...

**Comment by ranjitjhala** [comment]
Rose,

clearly this needs fixing but you can work around this by qualifying
the measure signature, e.g. replacing the line with:

```haskell
{-@ measure bar :: Int -> GHC.Types.Bool @-}
```
and generally, writing `GHC.Types.Bool` whenever you're referring to the
name of the type.

Does that get you unstuck?

**Comment by nikivazou** [comment]
Or, if you give this hard coded ["Bool](https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Types/Names.hs#L565)" a different (fixpoint-specific) name, e.g., `LFBool` I suspect you will solve the problem
