### ISSUE TITLE
Bug in Tutorial Example

### ISSUE THREAD

**Issue by mbrodersen** [ucsd-progsys/liquidhaskell#1528]
The following tutorial example:

```
vectorSum :: Vector Int -> Int
vectorSum vec = go 0 0
  where
    go acc i
      | i < sz    = go (acc + (vec ! i)) (i + 1)
      | otherwise = acc
    sz            = length vec
```
is expected (according to the tutorial) to be verified safe but instead liquidhaskell returns:
```
Error: Liquid Type Mismatch
141 |       | i < sz    = go (acc + (vec ! i)) (i + 1)
                              ^^^^^^^^^^^^^^^^^
  
   Inferred type
     VV : {v : GHC.Types.Int | v == acc + ?b}
  
   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV < acc
                                && VV >= 0}
  
   In Context
     ?b : GHC.Types.Int
      
     acc : GHC.Types.Int
```

**Comment by ranjitjhala** [comment]
Ah right, this is because the termination checker is now “on by default”
and this is a termination error.

The fix here is to run the file with “—no-termination” ; I will update
immediately! Thanks for filing the issue!

**Comment by mbrodersen** [comment]
You are welcome ranjitjhala. And thanks for getting back with an answer so quickly!
