### ISSUE TITLE
LH doesn't pick up enabled language extensions from project.yaml/.cabal files

### ISSUE THREAD

**Issue by spacekitteh** [ucsd-progsys/liquidhaskell#1533]
Also, it took a good fifteen minutes to figure out that was the case (it got tripped up by a bang pattern, and just declared it to be an illegal pattern; it didn't suggest the extension). There should be some error message to inform about this.

**Comment by ranjitjhala** [comment]
Yikes, what was the exact error message you got? (A GHC error?)

**Comment by spacekitteh** [comment]
`vecOf f: invalid pattern`

The actual function definition was `vecOf f !a = ...`

**Comment by facundominguez** [comment]
I don't think this issue still stands after eliminating the standalone LH. But please, feel free to reopen this issue if you can reproduce with the latest LH.
