### ISSUE TITLE
The specifications in the benchmarks for common libraries should be pulled out into the include directory

### ISSUE THREAD

**Issue by spacekitteh** [ucsd-progsys/liquidhaskell#1535]

**Comment by ranjitjhala** [comment]
Did you mean, e.g. the ones for Text and ByteString?

**Comment by spacekitteh** [comment]
And hmatrix etc, yeah.

**Comment by facundominguez** [comment]
The include directory has been removed. The `liquidhaskell` package now includes the specifications of boot libraries. Please, feel free to reopen if this arrangement is not ideal.
