### ISSUE TITLE
crash: SMTLIB2 Error "Wrong number of arguments passed to function"

### ISSUE THREAD

**Issue by dtaskoff** [ucsd-progsys/liquidhaskell#1537]
Hello,

This error occured, after I tried to prove that for the following functions `f` and `g`, `f . g = id`:

```hs
{-@ reflect f @-}
f :: (b -> a, c -> a) -> Either b c -> a
f (l, r) e = 
  case e of
    Left y -> l y 
    Right z -> r z

{-@ reflect dot @-}
dot :: (a -> b) -> (c -> a) -> c -> b
dot f g z = f (g z)

{-@ reflect g @-}
g :: (Either b c -> a) -> (b -> a, c -> a)
g h = (dot h Left, dot h Right)

-- eta-expanding: f . g = id <=> (f . g) h = h <=> (f . g) h e = h e
{-@
f_dot_g_eq_id ::
  h:(Either b c -> a) -> e:(Either b c)
  -> {f (g h) e = h e}
@-}
f_dot_g_eq_id h e = 
  f (g h) e
  ==. h e
  *** QED 
```

Full error message:
```
:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 348 column 1508: Wrong number of arguments (0) passed to function (declare-fun Data.Either.Left (Int) (Data.Either.Either Int Int))"
```

I'm providing the `.liquid` directory produced by liquid: [liquid.tar.gz](https://github.com/ucsd-progsys/liquidhaskell/files/3537946/liquid.tar.gz)

*Note*: might be related to #1164

I'm using `liquid` from branch **develop**.

**Comment by dtaskoff** [comment]
*Update*: I have a "feeling", that this is caused by the expressions `dot h Left` and `dot h Right`.
Is it not possible to use partially applied functions in proofs?

**Comment by ranjitjhala** [comment]
I *think* this is because the SMT solver doesn't like partially applied
constructors (e.g. Left, Right). Does the error remain if you add:

```
{-@ LIQUID "--no-adt" @-}
```

Which disables the native ADT encoding?

**Comment by dtaskoff** [comment]
Thank you very much, it worked!
