### ISSUE TITLE
Equational reasoning and higher-order functions

### ISSUE THREAD

**Issue by dtaskoff** [ucsd-progsys/liquidhaskell#1538]
Hello, I'm struggling with proving some things with equational reasoning, which, I feel, should be done very easily.

For example, see [this gist](https://gist.github.com/dtaskoff/750821199f8720c9118ee0a1b91c5650).
The first proof seems to be accepted by `liquid`, however, the second one, which follows the same pattern, gives a `Liquid Type Mismatch`.

Is there some kind of a trick, that needs to be done to help `liquid`, or am I missing something more general?

(*Note*: while playing around with the options, I found out that adding `{-@ LIQUID "--ple" @-}` produces a quite cryptic error even for the first proof, I am not sure if that's intended behaviour, or not)

**Comment by ranjitjhala** [comment]
Hi Daniel,

Unfortunately am traveling and away from my machine so can't run LH but my
guess is that
the problem here is that the composition operator `.` has not been
"reflected" -- so LH
only knows that `.` has the type (b -> c) -> (a -> b) -> a -> c and in
particular, does not
"know" that the equality

  `(f' . g') h e == f' (g' h) e`

follows from the definition. To fix, add the following to your code:

```
{-@ reflect compose @-}
compose f g x = f (g x)
```

and then replace all occurrences of `x . y` in your code with `compose x
y`...

In theory you could also do:

```
import Prelude hiding ((.))

{-@ infix . @-}
{-@ reflect . @-}

(.) f g x = f (g x)
```

but the parser may not like it as `.` is special...


Can you let me know if that works? (Will be back at a machine soon so can
double check...)





want you can use the `.` operator

**Comment by dtaskoff** [comment]
Hi,
Reflecting a custom `compose` didn't help me prooving the equation (I've updated the gist), although, `{-@ LIQUID "--ple" @-}` now produces the same `Liquid Type Mismatch`, instead of a cryptic error, so, at least, that's not a bug.

This concrete expansion seems to be the thing, which `liquid` doesn't like.
```
(compose (f' (l, r)) Left, compose (f' (l, r)) Right)
  ==. (\y -> f' (l, r) (Left y), \z -> f' (l, r) (Right z))
```

**Comment by ranjitjhala** [comment]
@dtaskoff  -- reposting my reply again so its searchable. 

Ok, so once you use `===` ("checked equality combinator", we have the old one `==.` for historical reasons but should deprecate it...) I found that the issue was with the equalities:

```
      (compose (f' (l, r)) Left, compose (f' (l, r)) Right)
  === (\y -> f' (l, r) (Left y), \z -> f' (l, r) (Right z))
```


which only holds with eta-expansion/function equality which is a bit tedious to spell out to LH (especially proving the equality of two lambda-terms). In general, proving equality of functions 
directly is tedious, because you have to explicitly tell LH about "extensionality" which is not 
impossible but rather a hassle.

Here's a version of your proof that goes through, I'll send a longer explanation later when my 
kids stop howling at me :-) but maybe you can understand it... see the proof of `gfId` which is 
the thing you wanted to prove.
 

```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--no-adt"     @-}
{-@ LIQUID "--ple"        @-}

import Language.Haskell.Liquid.ProofCombinators


-- | Proof that a ^ b * a ^ c = a ^ (b + c)
--
-- a ^ b * a ^ c corresponds to (b -> a, c -> a)
-- a ^ (b + c) corresponds to Either b c -> a


{-@ reflect f' @-}
f' :: (b -> a, c -> a) -> Either b c -> a
f' (l, r) e =
  case e of
    Left y -> l y
    Right z -> r z

{-@ reflect compose @-}
compose :: (a -> b) -> (c -> a) -> c -> b
compose f g z = f (g z)

{-@ reflect g' @-}
g' :: (Either b c -> a) -> (b -> a, c -> a)
g' h = (compose h Left, compose h Right)

-- Note: f' . g' = id is eta-expanded
-- f' . g' = id <=> (f' . g') h = h <=> (f' . g') h e = h e
{-@
f'_dot_g'_eq_id ::
  h:(Either b c -> a) -> e:(Either b c)
  -> {f' (g' h) e = h e}
@-}
f'_dot_g'_eq_id h e =
  f' (g' h) e
  ==. f' (compose h Left, compose h Right) e
  ==. case e of
        Left y ->
          compose h Left y
          ==. h (Left y)
        Right z ->
          compose h Right z
          ==. h (Right z)
  ==. h e
  *** QED

------------------------------------------------------------------------------------------------
-- | Extensionality "Axiom"
------------------------------------------------------------------------------------------------

{-@ assume axiom_ext :: f:_ -> g:_ -> (x:_ -> {f x == g x}) -> {f = g} @-}
axiom_ext :: (a -> b) -> (a -> b) -> (a -> Proof) -> Proof
axiom_ext _ _ _ = () 

-- | The theorem you wanted proved  -----------------------------------------------------------

{-@ gfId :: h:_ -> { (g' (f' h)) = h } @-}
gfId :: (b -> a, c -> a) -> Proof 
gfId h = eqPair (g' (f' h)) h (gfId1 h) (gfId2 h) 

{-@ gfId1 :: h:_ -> {fst (g' (f' h)) = fst h} @-}
gfId1 :: (b -> a, c -> a) -> Proof 
gfId1 h = axiom_ext (fst (g' (f' h))) (fst h) (gfId1' h) 

{-@ gfId1' :: h:_ -> x:_ -> {fst (g' (f' h)) x = fst h x} @-}
gfId1' :: (b -> a, c -> a) -> b -> Proof 
gfId1' (l, r) x = ()      -- << PLE automates this proof   

{-@ gfId2 :: h:_ -> {snd (g' (f' h)) = snd h} @-}
gfId2 :: (b -> a, c -> a) -> Proof 
gfId2 h = axiom_ext (snd (g' (f' h))) (snd h) (gfId2' h) 

{-@ gfId2' :: h:_ -> x:_ -> {snd (g' (f' h)) x = snd h x} @-}
gfId2' :: (b -> a, c -> a) -> c -> Proof 
gfId2' (l, r) x = ()       -- << PLE automates this proof 

-- | "lemma" stating when two pairs are equal --------------------------------------------------

{-@ eqPair :: p1:_ -> p2:_ -> {v:_ | fst p1 == fst p2} -> {v:_ | snd p1 == snd p2 } -> {p1 == p2} @-}
eqPair :: (a, b) -> (a, b) -> Proof -> Proof -> Proof
eqPair (x1, y1) (x2, y2) pf1 pf2 = ()  


------------------------------------------------------------------------------------------------

-- | For some reason Liquid Haskell doesn't accept the following proof

-- RJ: The combinator `==!` means "trust-me-equality" (it is a cheat, but useful to debug proofs...)

-- Note: g' . f' = id is eta-expanded
-- g' . f' = id <=> (g' . f') h = h
{-@
g'_dot_f'_eq_id ::
  l:(b -> a)
  -> r:(c -> a)
  -> {(g' (f' (l, r))) = (l, r)}
@-}
g'_dot_f'_eq_id l r =
  g' (f' (l, r))
  === (compose (f' (l, r)) Left, compose (f' (l, r)) Right)
  ==! (\y -> f' (l, r) (Left y), \z -> f' (l, r) (Right z))
  ==! (\y -> l y, \z -> r z)
  ==! (l,  r)
  *** QED
```

**Comment by dtaskoff** [comment]
Thank you very much for the detailed proof!
I think I understand what is going on.

To generalise, every time I want to prove something with nested functions (in this case, the functions are the first and second part of a tuple: `(b -> a, c -> a)`), I'll have to deconstruct and use the extensionality axiom for the functions inside, am I correct?

*EDIT*: While making sure that I'm understanding the proof, I tried to rewrite it, while keeping the same "typical for equational reasoning" structure, i.e. to make it look more like a proof written on paper, and this is what I came up with (might be useful to someone else, as well):

```hs
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--no-adt"     @-}
{-@ LIQUID "--ple"        @-}

import Language.Haskell.Liquid.ProofCombinators


-- | Proof that a ^ b * a ^ c = a ^ (b + c)
--
-- a ^ b * a ^ c corresponds to (b -> a, c -> a)
-- a ^ (b + c) corresponds to Either b c -> a


{-@ reflect f @-}
f :: (b -> a, c -> a) -> Either b c -> a
f (l, r) e =
  case e of
    Left y -> l y
    Right z -> r z

{-@ reflect compose @-}
compose :: (a -> b) -> (c -> a) -> c -> b
compose f g z = f (g z)

{-@ reflect g @-}
g :: (Either b c -> a) -> (b -> a, c -> a)
g h = (compose h Left, compose h Right)

-- Note: f . g = id is eta-expanded
-- f . g = id <=> (f . g) h = h <=> (f . g) h e = h e
{-@
f_dot_g_eq_id ::
  h:(Either b c -> a) -> e:(Either b c)
  -> {f (g h) e = h e}
@-}
f_dot_g_eq_id h e =
  f (g h) e
  === f (compose h Left, compose h Right) e
  === case e of
        Left y ->
          compose h Left y
          === h (Left y)
        Right z ->
          compose h Right z
          === h (Right z)
  === h e
  *** QED


------------------------------------------
-- | Here is the interesting part:
------------------------------------------

-- | This is the same as RJ's `axiom_ext`, only with types added in the specification
{-@
  assume extensionality ::
    f:(a -> b)
    -> g:(a -> b)
    -> (x:a -> {f x = g x})
    -> {f = g}
@-}
extensionality :: (a -> b) -> (a -> b) -> (a -> Proof) -> Proof
extensionality _ _ _ = ()

{-@
  compose_f_Left_eq_l ::
    l:(b -> a)
    -> r:(c -> a)
    -> y:b
    -> {compose (f (l, r)) Left y = l y}
@-}
compose_f_Left_eq_l :: (b -> a) -> (c -> a) -> b -> Proof
compose_f_Left_eq_l _ _ _ = ()

{-@
  compose_f_Right_eq_r ::
    l:(b -> a)
    -> r:(c -> a)
    -> z:c
    -> {compose (f (l, r)) Right z = r z}
@-}
compose_f_Right_eq_r :: (b -> a) -> (c -> a) -> c -> Proof
compose_f_Right_eq_r _ _ _ = ()

-- Note: g . f = id is eta-expanded
-- g . f = id <=> (g . f) h = h
{-@
g_dot_f_eq_id ::
  l:(b -> a)
  -> r:(c -> a)
  -> {(g (f (l, r))) = (l, r)}
@-}
g_dot_f_eq_id l r =
  g (f (l, r))
  === (compose (f (l, r)) Left, compose (f (l, r)) Right)
        ? extensionality
            (compose (f (l, r)) Left)
            l
            (compose_f_Left_eq_l l r)
  === (l, compose (f (l, r)) Right)
        ? extensionality
            (compose (f (l, r)) Right)
            r
            (compose_f_Right_eq_r l r)
  === (l, r)
  *** QED
```

**Comment by ranjitjhala** [comment]
Yes that is right! Let me know if it it’s too tedious — we haven’t had a
lot of use cases for improving support for function-equality so would be
great to get some!

**Comment by dtaskoff** [comment]
I don't think writing that is too bothersome, especially with the existence of `--ple`.
Of course, in the ideal case, I'd like to write
```hs
compose (f (l, r)) Left
  === l
```
instead of
```hs
compose (f (l, r)) Left
  ? extensionality (compose (f (l, r)) Left) l (compose_f_Left_eq_l l r)
  === l
```
but that doesn't seem to be easy to implement, at all, so maybe it won't be worth it?

**Comment by nikivazou** [comment]
Hi @dtaskoff, 
I added support for the `(.)` haskell function, so on develop you can use `.` on refinements and your proof. But extensionality, yes, is not at all easy to implement or automatically derive. 

Shall we close the issue?

**Comment by dtaskoff** [comment]
Thank you very much, being able to use (.) is very convenient!
