### ISSUE TITLE
What happened to the "reflection" flag?

### ISSUE THREAD

**Issue by mpdairy** [ucsd-progsys/liquidhaskell#1539]
I'm working through the tutorial and can't get `congruence` to work, as described here:
https://www.reddit.com/r/haskell/comments/cpuha0/simple_congruence_proof_error_with_liquid_haskell/

The solution presented there, which points to https://github.com/ucsd-progsys/liquidhaskell#theorem-proving is to use the `--reflection` flag, but my version (0.8.2.4), which is the latest you can get with cabal, doesn't have a `reflection` flag.

**Comment by ranjitjhala** [comment]
Dear Matt,

Unfortunately the version on cabal is SUPER old -- @nikivazou do you have
the cycles to update it sometime soon? --
and it predates `reflection`. You can either:

1. Use `--higher-order` which was the old name for `reflection` (IIRC), or
2. Build from github as described here:

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#build-with-stack-recommended

Do let us know if either works for you!

- Ranjit.

**Comment by mpdairy** [comment]
Ah hah, thanks! I just installed the latest from source and the reflection flag works now.

**Comment by ranjitjhala** [comment]
👍
