### ISSUE TITLE
vectorSum example doesn't work

### ISSUE THREAD

**Issue by mpdairy** [ucsd-progsys/liquidhaskell#1540]
Here's the example:
```
{-@ LIQUID "--reflection" @-}

module Blaze.Liquid.Ex4 where

import Prelude hiding (abs, length)
import Data.Vector (Vector, (!))
import qualified Data.Vector as V

vectorSum         :: Vector Int -> Int
vectorSum vec     = go 0 0
  where
    go acc i
      | i < sz    = go (acc + (vec ! i)) (i + 1)
      | otherwise = acc
    sz            = V.length vec
```
I'm getting these errors:
```
 /home/matt/haskell/blaze/src/Blaze/Liquid/Ex5.hs:18:24-40: Error: Liquid Type Mismatch
  
 18 |       | i < sz    = go (acc + (vec ! i)) (i + 1)
                             ^^^^^^^^^^^^^^^^^
  
   Inferred type
     VV : {v : GHC.Types.Int | v == acc + ?a}
  
   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV < acc
                                && VV >= 0}
  
   In Context
     ?a : GHC.Types.Int
      
     acc : GHC.Types.Int


 /home/matt/haskell/blaze/src/Blaze/Liquid/Ex5.hs:18:38: Error: Liquid Type Mismatch
  
 18 |       | i < sz    = go (acc + (vec ! i)) (i + 1)
                                           ^
  
   Inferred type
     VV : {v : GHC.Types.Int | v == i}
  
   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV >= 0
                                && VV < vlen vec}
  
   In Context
     vec : {vec : (Data.Vector.Vector GHC.Types.Int) | 0 <= vlen vec}
      
     i : GHC.Types.Int
```

I tried changing `length` to `V.length` (https://github.com/ucsd-progsys/liquidhaskell/issues/1170) but it's still the same error. I also tried making my own Vector type (which is just a list-like structure) and I used my own `vlen` measure function, and it still failed in the same way.

I also found an unanswered StackOverflow question about this: 
https://stackoverflow.com/questions/56626772/why-does-liquidhaskell-fail-to-take-guard-into-account

**Comment by ranjitjhala** [comment]
Hi @mpdairy -- these errors are related to "termination" i.e. proving that the recursive `go` function always terminates. Unfortunately, the tutorial _predates_ the point where termination checking was switched on by default -- and I haven't had a chance to update those chapters yet.

There are two solutions:

1. **Simple** -- _disable_ the termination checker by adding the option `{-@ LIQUID "--no-termination" @-}` to the file,

2. **Fun** -- you can read a bit about how the termination checker works in the blog posts https://ucsd-progsys.github.io/liquidhaskell-blog/tags/termination.html

and then see how you can prove that your `go` actually terminates.

I'd suggest (1) in the short term!

**Comment by mpdairy** [comment]
Ok thanks, I used the Simple solution and it works. I'll try the really Fun way when I'm further along in the tutorial.
