### ISSUE TITLE
incompleteness of PLE

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1549]
The following is SAFE: https://github.com/ucsd-progsys/liquidhaskell/blob/fc4c46b02b43a738e47ac1ba135be73c72f6dea0/tests/todo/T1549.hs#L9-L17

By completeness of PLE the following should also be safe: 

```
example g p = hFun g
```

Currently, PLE is just crashing, but even if it did not, it would not be able to prove the theorem, since `.` does not appear fully applied, so it will not unfold.

**Comment by nikivazou** [comment]
^^ @ranjitjhala

**Comment by ranjitjhala** [comment]
Why does it crash? (Ie what is the error?)

**Comment by ranjitjhala** [comment]
My hunch is the crash has to do with the type of “second”, specifically the
quantifier in the output probably messes up the sorts in the refinements.

**Comment by nikivazou** [comment]
My hunch is the same. The crash is the following
```
liquid: Data.Text.Internal.Fusion.Common.head: Empty stream
CallStack (from HasCallStack):
  error, called at libraries/text/Data/Text/Internal/Fusion/Common.hs:943:24 in text-1.2.3.1:Data.Text.Internal.Fusion.Common
```

I am not so concerned about this, we can fix it. 
What is interesting is that ple will not be able to prove the theorem (see the description of the issue) which means that ple is not actually complete.

**Comment by ranjitjhala** [comment]
PLE cant prove everything that’s True N— that’s not what “complete” means
:-)

There’s a very specific notion of proofs it is complete for, and partial
applications, unfortunately, are outside that set.

I think in theory this would not be hard to fix. In practice, however, it
would require dealing with lambdas- in the refinements...

**Comment by ranjitjhala** [comment]
That is to say, I *think* If we managed to get proper support for
beta-reduction in PLE, this would work.

**Comment by nikivazou** [comment]
Makes sense, I did not realize we explicitly had partial applications out of the completeness domain, so I was surprised that such case did not appear in the completeness proof of PLE. 

Still leaving the issue open to fix the crash.

**Comment by facundominguez** [comment]
This test doesn't crash in the latest LH. Moreover it passes verification.
I'm closing the issue as it was the criterion to keep it open.
