### ISSUE TITLE
Installation issue for macOS via cabal

### ISSUE THREAD

**Issue by Luke-Dramko** [ucsd-progsys/liquidhaskell#1552]
I've run into an issue attempting to install liquidhaskell via cabal following the instructions at 
https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md.

I consistently get the following error after about a minute or so of compilation:
```
src/Language/Haskell/Liquid/UX/DiffCheck.hs:388:10: error:
    • The type synonym ‘Diff’ should have 1 argument, but has been given none
    • In the instance declaration for ‘Functor Diff’
    |
388 | instance Functor Diff where
    |          ^^^^^^^^^^^^
cabal: Failed to build liquidhaskell-0.8.6.2 (which is required by exe:liquid
from liquidhaskell-0.8.6.2). See the build log above for details.
```

I'm on macOS Mojave, 10.14.6.

I have ghc installed, version 8.6.5.

The `mathsat` executable (version 5.5.4) is in `/usr/local/bin/`, which is in my PATH. I've confirmed that I can call it from arbitrary folders.

The full output log is here:
[install_output.txt](https://github.com/ucsd-progsys/liquidhaskell/files/3668169/install_output.txt)

I was able to build successfully from source via stack, but figured I should let the liquidhaskell team know about this error.

**Comment by ranjitjhala** [comment]
Very strange, thanks for the heads up, will look into it ASAP!

**Comment by the-dr-lazy** [comment]
Had same problem using Nix on macOS. There was a conflict via `Diff` package (I had `0.4.0` in my nixpkgs).
Tried to jailbreak liquidhaskell! :D

```nix
enableSeparateBinOutput (doJailbreak self.haskell.packages.ghc865.liquidhaskell)
```
Then I encountered same error message:

```bash
[55 of 90] Compiling Language.Haskell.Liquid.UX.DiffCheck ( src/Language/Haskell/Liquid/UX/DiffCheck.hs, dist/build/Language/Haskell/Liquid/UX/DiffCheck.o )

src/Language/Haskell/Liquid/UX/DiffCheck.hs:388:10: error:
    • The type synonym ‘Diff’ should have 1 argument, but has been given none
    • In the instance declaration for ‘Functor Diff’
    |
388 | instance Functor Diff where
```

To fix it I should override `Diff` to `0.3.4` in my nixpkgs and there was no need for jailbreaking.
Also, the `Functor` instance for `Diff` is orphan. Maybe we should wrap it in a newtype.

**Comment by nikivazou** [comment]
Thanks! We will soon release the new version. Till then, can you install it from source? 

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#step-2-install-liquid-from-source

**Comment by facundominguez** [comment]
Closing since this issue is likely to be obsolete for the latest LH. Please, feel free to reopen it if installation still doesn't work for you.
