### ISSUE TITLE
Forall types are unrefined which can get imprecise and unsound

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1555]
Consider

```
type ForAll a  = forall z. a
data Wrapper a = Wrapper (ForAll a)
```

since `ForAll a` does not have a top level refinement it will not propagate information, e.g., the following fails

```
foo :: ForAll a -> ForAll a  -> Proof
{-@ foo :: f:ForAll a -> g:{ForAll a | f == g }  -> { Wrapper f == Wrapper g } @-} 
foo g f = Wrapper g ==. Wrapper f *** QED 
```

WORSE, the top level refinements of `forall` are ignored, leading to **unsoundness**. e.g., the following is SAFE 

```
{-@ unsound :: ForAll a -> {v:ForAll a | false } @-}
unsound :: ForAll a -> ForAll a 
unsound x = x 
```

The solution I see is to add top refinements to forall. @ranjitjhala objections?

**Comment by nikivazou** [comment]
The code is here: https://github.com/ucsd-progsys/liquidhaskell/blob/11ae5342983221a262cc92887e981afe350b87c3/tests/todo/T1555.hs

**Comment by ranjitjhala** [comment]
Go for it!
