### ISSUE TITLE
Diff 0.4 breaks orphan Functor Diff instance

### ISSUE THREAD

**Issue by BillHallahan** [ucsd-progsys/liquidhaskell#1558]
The new version of the Diff package (version 0.4.0) switched Diff from a datatype with a single constructor:
```
data Diff a = First a | Second a | Both a a
```
to a type synonym for a type with two type variables:
```
data PolyDiff a b = First a | Second b | Both a b
type Diff a = PolyDiff a a
```
This causes an error when building [Language.Haskell.Liquid.DiffCheck](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/UX/DiffCheck.hs#L388), which declares a Functor instance for Diff:
```
src/Language/Haskell/Liquid/UX/DiffCheck.hs:386:10: error:
    • The type synonym ‘Diff’ should have 1 argument, but has been given none
    • In the instance declaration for ‘Functor Diff’
    |
386 | instance Functor Diff where
    |          ^^^^^^^^^^^^
```
I think the solution is either to:
* update the cabal file, to restrict the version of Diff used, or
* remove the instance for Functor and write a special mapDiff function

Also, ideally the dependencies on versions on Hackage would be updated, to put an upper bound on the allowable versions of Diff.  Currently there is only a lower bound on the dependency:
[http://hackage.haskell.org/package/liquidhaskell-0.8.6.2](http://hackage.haskell.org/package/liquidhaskell-0.8.6.2)

**Comment by nikivazou** [comment]
Thanks! I added the bounds `Diff >= 0.3 && < 0.4` and revised hackage as you suggested. Is it ok now?

**Comment by BillHallahan** [comment]
Thanks!  Would it be possible to also update the bounds for some of the older versions? In particular, I'm currently using back to 0.8.2.2.

**Comment by ranjitjhala** [comment]
Bill, it may be easier to use stack to build those?

**Comment by BillHallahan** [comment]
Hm, Ok.  I'll look into that.
