### ISSUE TITLE
reflected equations are always saturated

### ISSUE THREAD

**Issue by yiyunliu** [ucsd-progsys/liquidhaskell#1560]
The following code is marked as unsafe:

```haskell
k :: a -> b -> b
k _ b = b

{-@ reflect f @-}
f :: Int -> Int -> Int
f x y = x + y

{-@ reflect g @-}
g :: Int -> Int -> Int
g = f

{-@ fgeqxy :: x:Int -> y:Int -> {f x y = g x y} @-}
fgeqxy :: Int -> Int -> ()
fgeqxy x y = g x y `k` f x y `k` ()

{-@ fgeqx :: x:Int -> {f x = g x} @-}
fgeqx :: Int -> ()
fgeqx x = f x `k` g x `k` ()

{-@ fgeq :: {f = g} @-}
fgeq :: ()
fgeq = f `k` g `k` ()
```

In Haskell, if we write down: `f = g`, it is not always the case that f and g are the same since they may still have different type signatures. However, if they share the same type, then we should be able to conclude that `f = g` rather than the weaker statement that `forall x. f x = g x`.

Currently, the equation is saturated:
```haskell
define Main.g (lq1 : int,  lq2 : int) = ((Main.f lq1 lq2))
```
Is it possible to add a corner case for the synonym definition and generate the following unsaturated equation instead?
```haskell
define Main.g = Main.f
```

Otherwise, we need to use the functional extensionality axiom to have the proof go through, which is unnecessary since we already have the function equality in the first place.

**Comment by yiyunliu** [comment]
Looks like it's not as simple as I imagined. I wrote a function which translates things of the form:
```haskell
define f a... = g a...
```
into 
```haskell
define f = g 
```
so the equation now looks like:
```haskell
define Main.g () = (Main.f)
```
However, the program still won't typecheck.

**Comment by nikivazou** [comment]
Here is a possible solution

```
k :: a -> b -> b
k _ b = b

{-@ reflect f @-}
f :: Int -> Int -> Int
f x y = x + y

{-@ measure g :: Int -> Int -> Int @-}
g :: Int -> Int -> Int
{-@ assume g :: {v2:(x:Int -> {v1:(y:Int 
      -> {v:Int | g x y = f x y && v == g x y}) 
       | v1 == g x}) | v2 == f && v2 == g} @-}
g = f

{-@ fgeqxy :: x:Int -> y:Int -> {f x y = g x y} @-}
fgeqxy :: Int -> Int -> ()
fgeqxy x y = g x y `k` f x y `k` ()

{-@ fgeqx :: x:Int -> {f x = g x} @-}
fgeqx :: Int -> ()
fgeqx x = f x `k` g x `k` ()

{-@ fgeq :: {f = g} @-}
fgeq :: ()
fgeq = f `k` g `k` ()
```

The type of `g` is refined (or manually reflected) so that the equality of its definition is preserved at each argument application.

**Comment by yiyunliu** [comment]
Interesting. This approach doesn't break the invariant that the equations have to be saturated while it still keeps the information that f = g. 
If you are busy I can try fixing this myself.

**Comment by nikivazou** [comment]
Hi @yiyunliu, sorry for the delay but it was not clear how to address this problem. 
There are two solutions: either edit the generation of reflected signatures to be more precise or saturate the refinements before they are send to PLE/SMT. I believe the second is the correct approach and will solve other limitations of reasoning about partially applied functions. 

@conal also had similar concerns and the suggested solution is add a normalization step that "converts refinements to long beta-eta normal form and canonicalizes variable naming". 
This step will get added in the sanitization process (https://github.com/ucsd-progsys/liquid-fixpoint/blob/8d7e6633483f1e47be3384175d7247cfe67d1c16/src/Language/Fixpoint/Solver/Sanitize.hs#L40).  

@yiyunliu do you think you can give it a try?

**Comment by jprider63** [comment]
This is fixed now right? Can we close this?
