### ISSUE TITLE
Make tests not stack-dependent

### ISSUE THREAD

**Issue by adinapoli** [ucsd-progsys/liquidhaskell#1584]
Currently `mkTest` [assumes](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/test.hs#L462) that `liquid` has been installed/provisioned via `stack`, but this might not be true for users using `cabal`.

In particular, it took me a while to realise why on my machine calling `cabal new-test` was hanging indefinitely, and only when I (accidentally) tried to run `stack test` (so that the relevant folders were generated on my machine) that I have realised what was going on 😉 I can see how others might end up into the same pit.

I think it would be nice for users not being tied to a particular program, even though `stack` is the de facto for this project.

@nikivazou , @ranjitjhala Would you accept a pull request in this area or is this something that doesn't warrant the effort? Thanks!

**Comment by adinapoli** [comment]
~~I do wonder if using `binDir` as before (cfr. commented-out code) is indeed the cleanest solution, as the user can always override the choice by doing `export liquidhaskell_bindir=/path/to/custom/liquid`.~~

~~Alternatively, we could pass some optional test option to tweak the behaviour, but that feels slightly overkill.~~

After playing a bit with the tests, perhaps the path of least resistance is a new "--liquid-runner" optional flag to be passed to the testsuite executable; it would default to `stack exec -- liquid` if not set or allow the user to pass something like `cabal new-exec liquid -- ` , which will have basically the same effect of the stack's counterpart. It's not very elegant, but it might get the job done for now.

**Comment by ranjitjhala** [comment]
Hi Alfredo,

this code is certainly a bit old (perhaps predating the recent advances in
cabal).
My sense is that if there is some easy way to generalize then we can do it,
otherwise
maybe it is of lower priority?

Would *certainly* accept a PR if you or someone else knows how to do it!

Thanks!

- Ranjit.
