### ISSUE TITLE
Create CircleCI task to build the project using Cabal

### ISSUE THREAD

**Issue by adinapoli** [ucsd-progsys/liquidhaskell#1589]
After #1584 and #1586 will be closed, we would be in the position to build the project with Cabal and potentially with unreleased GHC versions via something like [head.hackage](https://ghc.gitlab.haskell.org/head.hackage/).

It would be nice to capitalise on this by creating a CircleCI job (to be run alongside the stack one) so that we can at least automatically test as part of CI that we cannot incur into situations like #1584 anymore.

**Comment by kosmikus** [comment]
I'm closing this, as I think we have cabal builds on CI now.
