### ISSUE TITLE
higher-kinded data type definition causes ghc error

### ISSUE THREAD

**Issue by yiyunliu** [ucsd-progsys/liquidhaskell#1593]
It seems to happen when the type parameter m appears within a function type (first two cause the error and the third one is fine):
```haskell
{-@ LIQUID "--reflection"     @-}

-- not ok
data Thing0 m = Thing
  { t0 :: (m Int -> Int) -> Int
  }

-- not ok
data Thing1 m = Thing1
  { t1 :: (Int -> m Int) -> Int
  }

-- ok
data Thing2 m = Thing2
  { t2 :: Int -> m Int -> Int
  }
```

Here's the full error message:
LiquidHaskell Version 0.8.6.0, Git revision f0958eeb3fb35406ad05f2fe25d99f08ac091b14 (dirty) [develop@f0958eeb3fb35406ad05f2fe25d99f08ac091b14 (Tue Jan 21 08:16:34 2020 -0800)] 
Copyright 2013-19 Regents of the University of California. All Rights Reserved.

Targets: failed.hs

**** DONE:  A-Normalization ****************************************************
 
liquid: liquid: panic! (the 'impossible' happened)
  (GHC version 8.6.5 for x86_64-unknown-linux):
	piResultTys1
  *
  [Int]
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/utils/Outputable.hs:1160:37 in ghc:Outputable
        pprPanic, called at compiler/types/Type.hs:1022:5 in ghc:Type

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

**Comment by nikivazou** [comment]
I have to debug the translation of `Things` to STM data declarations. Meanwhile if you run it with the `"--no-adt"` flag the error goes away.

**Comment by yiyunliu** [comment]
> if you run it with the `"--no-adt"` flag the error goes away.

That is indeed the case. However, if the goal is to refine the data types, then the adt will be generated in the refinement logic regardless of "--no-adt", right?

**Comment by yiyunliu** [comment]
For example, if I add the refinement, I will end up getting the same error message even with "--no-adt" on:
```haskell
{-@ LIQUID "--reflection"     @-}
{-@ LIQUID "--no-adt"     @-}

-- not ok
{-@ data Thing0 m = Thing
  { t0 :: (m Int -> Int) -> Int
  }
 @-}
data Thing0 m = Thing
  { t0 :: (m Int -> Int) -> Int
  }

```

**Comment by ranjitjhala** [comment]
Niki I believe no-adt doesn’t fix it did you see above?

**Comment by nikivazou** [comment]
> Niki I believe no-adt doesn’t fix it did you see above?

Yes, I fixed with a PR :)

**Comment by ranjitjhala** [comment]
Super 😊
