### ISSUE TITLE
Reflection fails with negate

### ISSUE THREAD

**Issue by wenkokke** [ucsd-progsys/liquidhaskell#1596]
There's a problem with Haskell's `negate` and unary negation being interpreted by Liquid Haskell as minus, as far as I can tell.

The following piece of code defines two versions of the (real) number `-1.0`:

```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--ple"        @-}

{-@ reflect yay @-}
yay :: Double
yay = 0.0 - 1.0

{-@ reflect boo @-}
boo :: Double
boo = -1.0
```
The first version, `yay`, is fine. However, the second version, `boo`, fails, with the following error:
```
 ~/test.hs:8:13-15: Error: Illegal type specification for `Main.boo`
  
 8 | {-@ reflect boo @-}
                 ^^^
  
     Main.boo :: {VV : GHC.Types.Double | VV == boo
                                          && VV == (-1.0)}
     Sort Error in Refinement: {VV : real | (VV == Main.boo
                                             && VV == (-1.0))}
     The sort real is not numeric
```
In fact, a variant using `negate` also fails, with the same error:
```haskell
{-@ reflect bigBoo @-}
bigBoo :: Double
bigBoo = negate 1.0
```
This leads me to believe it has something to do with the rendition of `negate` in the SMT language. Could it be that the SMT expression simply needs a space between the minus and the number, as was the problem [here](https://stackoverflow.com/questions/56342112/z3-v4-1-does-not-accept-negative-integers-as-input)?

**Comment by ranjitjhala** [comment]
Hmm thanks for pointing this out! Don’t think it’s the space issue because
that would cause some parse error. I have a feeling it’s because we’ve not
tested the reflect code at all with double — let me check! Thanks!

**Comment by ranjitjhala** [comment]
Even more puzzling, the below works fine:

```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--ple"        @-}

{-@ reflect yay @-}
yay :: Double
yay = 0.0 - 1.0

{-@ reflect boo @-}
boo :: Double
boo = negat 1.0

{-@ reflect minus @-}
minus :: Double -> Double -> Double
minus x y = x - y

{-@ reflect negat @-}
negat :: Double -> Double
negat x = 0.0 - x
```

@nikivazou this is because for some reason we had a special case `ENeg` for unary negation 
instead of using the `EBin Minus Zero e` -- and it looks like that doesn't work for the `FReal` sort...

**Comment by nikivazou** [comment]
Thanks @ranjitjhala !!!
