### ISSUE TITLE
Reflection fails with divison

### ISSUE THREAD

**Issue by wenkokke** [ucsd-progsys/liquidhaskell#1597]
I don't think reflection of real number division is supported in Liquid Haskell, even though it is supported in the SMT language, e.g., as used [here](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/include/GHC/Real.spec#L8).

The following piece of code defines two reflected operators, addition and negation, for real numbers:

```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--ple" @-}

{-@ reflect plus @-}
plus :: Double -> Double -> Double
plus x y = x + y

{-@ reflect rdiv @-}
rdiv :: Double -> Double -> Double
rdiv x y = x / y
```
The first version, `plus`, is fine. However, the second, `rdiv`, fails. I think this is probably because reflection for `GHC.Real./` isn't implemented? (Browsing the source, I couldn't find where reflection is implemented, so I haven't verified this.)
```
~/test.hs:8:13-16: Error: Illegal type specification for `Main.rdiv`
  
 8 | {-@ reflect rdiv @-}
                 ^^^^
  
     Main.rdiv :: lq1:GHC.Types.Double -> lq2:GHC.Types.Double -> {VV : GHC.Types.Double | VV == rdiv lq1 lq2
                                                                                           && VV == / lq1 lq2}
     Sort Error in Refinement: {VV : real | (VV == Main.rdiv lq1 lq2
                                             && VV == GHC.Real./ lq1 lq2)}
     Unbound symbol GHC.Real./ --- perhaps you meant: GHC.Real.:% ?
```

**Comment by nikivazou** [comment]
@wenkokke thanks for reporting! Should be fixed now!
