### ISSUE TITLE
Unexpected ":"

### ISSUE THREAD

**Issue by theodoretliu** [ucsd-progsys/liquidhaskell#1609]
Hi, I'm relatively new to Liquid Haskell, but was curious about using the type system for a project of mine. The basics of my code are below:

```
{-@ LIQUID "--exact-data-con" @-}
data Nparray a = Const a | Array [Nparray a]

{-@ measure len @-}
len :: [a] -> Int
len [] = 0
len (hd : tl) = 1 + len tl

{-@ measure shape @-}
shape :: Nparray a -> [Int]
shape (Const a) = []
shape (Array []) = [0]
shape (Array (hd : tl)) = (len (hd : tl)) : (shape hd)

{-@ type NparrayN a S = {v: Nparray a | shape v == S} @-}

{-@ example :: {v : Nparray _ | shape v == [2]} @-}
example = Array [Const 1, Const 2]

{-@ example2 :: {v : Nparray _ | shape v = [2, 2]} @-}
example2 = Array [Array [Const 1, Const 2], Array [Const 3, Const 4]]
```
but when I try to run `liquid` on this file, I get the error
```
unexpected ":"
expecting operator, white space or "}"
```
on the line with 
```
{-@ example2 :: {v : Nparray _ | shape v = [2, 2]} @-}
```
Am I misunderstanding the syntax that would be allowed here? How would I properly express this type?

**Comment by nikivazou** [comment]
What version are you using? It seems you are using an old one (we have not updated hackage in a while...) Can you install from source (https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#step-2-install-liquid-from-source) and try again? 


Edit: Sorry, it is not the version... Our parser does not support lists (I thought it was fixed...). Try the following instead: 

```
{-@ inline list22 @-}
list22 :: [Int]
list22 = [2,2]

{-@ example2 :: {v : Nparray Int | shape v == list22 } @-}
example2 :: Nparray Int
example2 = Array [Array [Const 1, Const 2], Array [Const 3, Const 4]]
```

**Comment by theodoretliu** [comment]
Yeah, that did fix it! Thank you for such an expedient response!
