### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by theodoretliu** [ucsd-progsys/liquidhaskell#1617]
I saw in the readme that there's a Slack channel for questions, but the link appears to be expired. Could a new one be generated? I don't want to flood the Github Issues with one-off questions.

**Comment by nikivazou** [comment]
No, the link does not expire, but I invited you be email.

**Comment by theodoretliu** [comment]
Okay, I got the request, thank you! I saw this when I clicked the Slack link in the README though.
![image](https://user-images.githubusercontent.com/19197539/74636557-3fe0c380-5136-11ea-8614-1a525e6086ed.png)

**Comment by nikivazou** [comment]
The link is the below, correct?

https://join.slack.com/t/liquidhaskell/shared_invite/enQtMjY4MTk3NDkwODE3LTFmZGFkNGEzYWRkNDJmZDQ0ZGU1MzBiZWZiZDhhNmY3YTJiMjUzYTRlNjMyZDk1NDU3ZGIxYzhlOTIzN2UxNWE

**Comment by theodoretliu** [comment]
They're not the same. The one on the `README` differs after a bit

**Comment by nikivazou** [comment]
updated, thanks!
