### ISSUE TITLE
Failed to load dependencies error

### ISSUE THREAD

**Issue by jprider63** [ucsd-progsys/liquidhaskell#1654]
If LH marks a dependency as safe, but GHC fails to compile it, LH reports a `Failed to load dependencies` error. Here's a minimal example: 

```
module A where

foo = "test"

{-# inline (?) #-}
```

```
module B where

import A

bar = foo
```

Running `ghc A.hs` gives the following error:
```
A.hs:5:12: error:
    The INLINE pragma for ‘?’ lacks an accompanying binding
  |
5 | {-# inline (?) #-}
```

Running `liquid B.hs` results in A being marked as safe, and then B errors with `liquid: Failed to load dependencies of module A`.

**Comment by facundominguez** [comment]
The `liquid` executable has been removed. Please, feel free to reopen if it is still a problem with the `liquidhaskell` plugin.
