### ISSUE TITLE
Unsoundness from Refinement Reflection

### ISSUE THREAD

**Issue by nrioux** [ucsd-progsys/liquidhaskell#1656]
The following code is accepted by LH even though it causes a runtime division by zero error.
```
{-@ reflect n @-}
{-@ n :: {n : Integer | n = 3} @-}
n = 0

z = 1 `div` n
```

The issue is that the type of `n` gets reflected to `{n : Integer | n = 3 && n = 0}`, which is a contradiction. This means that the body of `n` and any use of `n` trivially type-check.

**Comment by ranjitjhala** [comment]
Oh no! Wait I could have sworn we saw and fixed this a long time ago (but
maybe I'm wrong!)

Is this a recent LH version?

**Comment by mystaroll** [comment]
Did you install liquidhaskell from source? Your example doesn't type check on the latest version

**Comment by nrioux** [comment]
Ah my apologies, I only tested this in the online demo. Good to hear it has already been fixed!

**Comment by ranjitjhala** [comment]
No matter, I should fix the demo, thanks!
