### ISSUE TITLE
Local inference not working

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1679]
Thanks to  @hafizhmakmur

https://github.com/ucsd-progsys/liquidhaskell-tutorial/issues/94

It's also further puzzling to me that the below is SAFE

(why does the presence of the GHC sig `test :: Int -> Bool` make a difference?)

```haskell
{-@ aaaa :: Int -> Maybe {y:Int | y > 0} @-}
aaaa :: Int -> Maybe Int
aaaa dim  
   | test dim  = Just dim
   | otherwise = Nothing
   where
        test :: Int -> Bool
        test dim = dim > 0
```

but that the following variant is UNSAFE ???

```haskell
{-@ aaaa :: Int -> Maybe {y:Int | y > 0} @-}
aaaa :: Int -> Maybe Int
aaaa dim = if test dim then Just dim else Nothing
   where
        test :: Int -> Bool
        test dim = dim > 0
```

I wonder if it has to do with how GHC core gets generated for the two cases.

**Comment by facundominguez** [comment]
In the latest LH, both snippets above are accepted, and so are the snippets in ucsd-progsys/liquidhaskell-tutorial#94.
