### ISSUE TITLE
installation issue for Arch Linux (tried cabal install and from source)

### ISSUE THREAD

**Issue by linen101** [ucsd-progsys/liquidhaskell#1680]
When I tried to install liquidhaskell using 
`cabal install liquidhaskell` 
I got the following error during the compilation phase

`Configuring library for liquidhaskell-0.8.6.2..
Preprocessing library for liquidhaskell-0.8.6.2..
Building library for liquidhaskell-0.8.6.2..
[ 1 of 90] Compiling Gradual.GUI.Misc ( src/Gradual/GUI/Misc.hs, dist/build/Gradual/GUI/Misc.o )
[ 2 of 90] Compiling Gradual.Misc     ( src/Gradual/Misc.hs, dist/build/Gradual/Misc.o )
[ 3 of 90] Compiling Gradual.Trivial  ( src/Gradual/Trivial.hs, dist/build/Gradual/Trivial.o )
[ 4 of 90] Compiling Language.Haskell.Liquid.Bag ( include/Language/Haskell/Liquid/Bag.hs, dist/build/Language/Hask>
[ 5 of 90] Compiling Language.Haskell.Liquid.Equational ( include/Language/Haskell/Liquid/Equational.hs, dist/build>
[ 6 of 90] Compiling Language.Haskell.Liquid.Foreign ( include/Language/Haskell/Liquid/Foreign.hs, dist/build/Langu>
[ 7 of 90] Compiling Language.Haskell.Liquid.GHC.API ( src/Language/Haskell/Liquid/GHC/API.hs, dist/build/Language/>
[ 8 of 90] Compiling Language.Haskell.Liquid.List ( include/Language/Haskell/Liquid/List.hs, dist/build/Language/Ha>
[ 9 of 90] Compiling Language.Haskell.Liquid.Prelude ( include/Language/Haskell/Liquid/Prelude.hs, dist/build/Langu>
[10 of 90] Compiling Language.Haskell.Liquid.ProofCombinators ( include/Language/Haskell/Liquid/ProofCombinators.hs>
[11 of 90] Compiling Language.Haskell.Liquid.Types.Names ( src/Language/Haskell/Liquid/Types/Names.hs, dist/build/L>
[12 of 90] Compiling Language.Haskell.Liquid.Types.Variance ( src/Language/Haskell/Liquid/Types/Variance.hs, dist/b>
[13 of 90] Compiling Language.Haskell.Liquid.UX.Config ( src/Language/Haskell/Liquid/UX/Config.hs, dist/build/Langu>
[14 of 90] Compiling Gradual.Types    ( src/Gradual/Types.hs, dist/build/Gradual/Types.o )
[15 of 90] Compiling Gradual.Uniquify ( src/Gradual/Uniquify.hs, dist/build/Gradual/Uniquify.o )
[16 of 90] Compiling Gradual.Refinements ( src/Gradual/Refinements.hs, dist/build/Gradual/Refinements.o )
[17 of 90] Compiling Gradual.Concretize ( src/Gradual/Concretize.hs, dist/build/Gradual/Concretize.o )
[18 of 90] Compiling Paths_liquidhaskell ( dist/build/autogen/Paths_liquidhaskell.hs, dist/build/Paths_liquidhaskel>
[19 of 90] Compiling Language.Haskell.Liquid.Misc ( src/Language/Haskell/Liquid/Misc.hs, dist/build/Language/Haskel>
[20 of 90] Compiling Language.Haskell.Liquid.Types.Errors ( src/Language/Haskell/Liquid/Types/Errors.hs, dist/build>
[21 of 90] Compiling Language.Haskell.Liquid.GHC.Misc ( src/Language/Haskell/Liquid/GHC/Misc.hs, dist/build/Languag>

src/Language/Haskell/Liquid/GHC/Misc.hs:90:15: error:
    Not in scope: data constructor ‘TvBndr’
    Perhaps you meant ‘Bndr’ (imported from Var)
   |
90 | isAnonBinder (TvBndr _ TC.AnonTCB) = True
   |               ^^^^^^

src/Language/Haskell/Liquid/GHC/Misc.hs:91:15: error:
    Not in scope: data constructor ‘TvBndr’
    Perhaps you meant ‘Bndr’ (imported from Var)
   |
91 | isAnonBinder (TvBndr _ _)          = False
   |               ^^^^^^`

And then I tried 
`git clone --recursive https://github.com/ucsd-progsys/liquidhaskell.git
cd liquidhaskell
cabal install`

and I got the following error 

`Configuring library for liquid-fixpoint-0.8.0.2..
Preprocessing library for liquid-fixpoint-0.8.0.2..
Building library for liquid-fixpoint-0.8.0.2..
[ 1 of 59] Compiling Language.Fixpoint.Utils.Progress ( unix/Language/Fixpoint/Utils/Progress.hs, dist/build/Langua>
[ 2 of 59] Compiling Paths_liquid_fixpoint ( dist/build/autogen/Paths_liquid_fixpoint.hs, dist/build/Paths_liquid_f>
[ 3 of 59] Compiling Text.PrettyPrint.HughesPJ.Compat ( src/Text/PrettyPrint/HughesPJ/Compat.hs, dist/build/Text/Pr>
[ 4 of 59] Compiling Language.Fixpoint.Misc ( src/Language/Fixpoint/Misc.hs, dist/build/Language/Fixpoint/Misc.o )
[ 5 of 59] Compiling Language.Fixpoint.Utils.Files ( src/Language/Fixpoint/Utils/Files.hs, dist/build/Language/Fixp>
[ 6 of 59] Compiling Language.Fixpoint.Types.Config ( src/Language/Fixpoint/Types/Config.hs, dist/build/Language/Fi>
[ 7 of 59] Compiling Language.Fixpoint.Types.PrettyPrint ( src/Language/Fixpoint/Types/PrettyPrint.hs, dist/build/L>

src/Language/Fixpoint/Types/PrettyPrint.hs:17:1: error: [-Wunused-imports, -Werror=unused-imports]
    The import of ‘Data.Semigroup’ is redundant
      except perhaps to import instances from ‘Data.Semigroup’
    To import instances alone, use: import Data.Semigroup()
   |
17 | import           Data.Semigroup (Semigroup (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by linen101** [comment]
excuse my messy output :)

**Comment by mystaroll** [comment]
What version of GHC? It will work if you use stack (recommended)

**Comment by linen101** [comment]
The Glorious Glasgow Haskell Compilation System, version 8.8.3

Trying with stack I get 
stack: error while loading shared libraries: libHSstack-2.3.1-DERj23NJZlH7HjBTNySw2W-ghc8.10.1.so: cannot open shared object file: No such file or director

but this has to do with my platform installation

**Comment by ranjitjhala** [comment]
I strongly recommend this

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#build-with-stack-recommended

**Comment by linen101** [comment]
stack install from source was successfull but I'm still wondering why cabal didnt work

**Comment by rosekunkel** [comment]
It probably doesn't help that the version of LH on Hackage is from September 2019 :grimacing:

**Comment by ranjitjhala** [comment]
Surprisingly recent :-)

**Comment by rosekunkel** [comment]
The error building from source was because the liquidhaskell repo has a cabal.project file that turns on `-Werror` by default. You can override it with `cabal install --flags="-devel"`.

**Comment by rosekunkel** [comment]
The issue with installing from Hackage seems like a version mismatch between the ghc version you're running and the one the library was built for
Unfortunately it doesn't seem like the Hackage package documents what GHC it was built for anywhere - It would be nice to have that, and also a link to whatever commit is packaged.

**Comment by safinaskar** [comment]
This bug affects me, too. I get similar error when I do "cabal install". So, yes, document dependency on ghc version

**Comment by facundominguez** [comment]
Cabal package constraints now tied liquidhaskell to specific versions of GHC. Please, reopen if installation is still not obvious.
