### ISSUE TITLE
Add metadata to Hackage releases.

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1681]
We should document which GHC version was used to build the current Hackage release and what commit/tag the release is created from, ideally within the release itself. This would help us diagnose GHC version incompatibilities and make the packages easier to use. See #1680.

**Comment by ranjitjhala** [comment]
Yes, this should be available from the stack.yaml of the corresponding git
commit?

**Comment by safinaskar** [comment]
This bug affects me, too. I get similar error when I do "cabal install". So, yes, document dependency on ghc version

**Comment by adinapoli** [comment]
Under the new versioning scheme, we are releasing versions of Liquid Haskell "in lockstep" with the relevant GHC version.

For example, currently we have two versions uploaded following this scheme:

* https://hackage.haskell.org/package/liquidhaskell-0.8.10.1
* https://hackage.haskell.org/package/liquidhaskell-0.8.10.2

Which are bound to `8.10.1` and `8.10.2`, respectively. I do agree that this should be better documented, but hopefully in the future as more releases come, it should become self-documenting.

**Comment by facundominguez** [comment]
I think this issue has been addressed with documentation for installation in the website, and via cabal package constraints. Feel free to reopen if more documentation is needed.
