### ISSUE TITLE
Cannot use "amPred1 a" in function "bar" if I have {-@ assume bar :: {a:String|amPred1 a} -> ... @-}

### ISSUE THREAD

**Issue by safinaskar** [ucsd-progsys/liquidhaskell#1702]
Consider this code. This is full source. It is a bit artificial.
```haskell
{-@ measure amPred1 :: String -> Bool @-} -- amPred1 intentionally not defined, it exists in Liquid Haskell only. "am" stands for "abstract measure". amPred1 is abstract measure dual of pred1
{-@ assume pred1 :: x:String -> {y: Bool | y == amPred1 x} @-}
pred1 :: String -> Bool
pred1 a = True

{-@ foo :: {x: String | amPred1 x} -> String @-}
foo :: String -> String
foo a = a

{-@ assume bar :: {a: String | amPred1 a} -> {y: String | amPred1 y} @-}
bar :: String -> String
bar a = foo a -- I want to use here assumption "amPred1 a", but it is not available

{-@ use :: {x: String | amPred1 x} -> {y: String | amPred1 y} @-}
use :: String -> String
use a = bar a

main = return ()
```
I get the following error:
```text
LiquidHaskell Version 0.8.6.2 no git information
Copyright 2013-19 Regents of the University of California. All Rights Reserved.

Targets: Main1.hs

**** [Checking: Main1.hs] ******************************************************

**** DONE:  A-Normalization ****************************************************
 

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  Transformed Core ***************************************************
 
Working 175% [===============================================================
===================================================]

**** DONE:  annotate ***********************************************************
 

**** RESULT: UNSAFE ************************************************************


 /root/Main1.hs:12:13: Error: Liquid Type Mismatch
  
 12 | bar a = foo a -- I want to use here assumption "amPred1 a"
                  ^
  
   Inferred type
     VV : {v : [GHC.Types.Char] | len v >= 0
                                  && v == a}
  
   not a subtype of Required type
     VV : {VV : [GHC.Types.Char] | amPred1 VV}
  
   In Context
     a : {a : [GHC.Types.Char] | len a >= 0}
```
For unknown reasons I cannot use "amPred1 a" in definition of "bar". I think this is a bug. The error goes away if I add `{-@ bar :: {a: String | amPred1 a} -> String @-}` to this source (without removing `assume bar`!). But this doesn't work across modules. Consider this:
```haskell
module C where

{-@ measure amPred1 :: String -> Bool @-} -- amPred1 intentionally not defined, it exists in Liquid Haskell only. "am" stands for "abstract measure". amPred1 is abstract measure dual of pred1
{-@ assume pred1 :: x:String -> {y: Bool | y == amPred1 x} @-}
pred1 :: String -> Bool
pred1 a = True

{-@ foo :: {x: String | amPred1 x} -> String @-}
foo :: String -> String
foo a = a

{-@ assume bar :: {a: String | amPred1 a} -> {y: String | amPred1 y} @-}
{-@ bar :: {a: String | amPred1 a} -> String @-}
bar :: String -> String
bar a = foo a -- I want to use here assumption "amPred1 a", but it is not available
```
```haskell
import C

{-@ use :: {x: String | amPred1 x} -> {y: String | amPred1 y} @-}
use :: String -> String
use a = bar a

main = return ()
```
I get this:
```text
LiquidHaskell Version 0.8.6.2 no git information
Copyright 2013-19 Regents of the University of California. All Rights Reserved.

Targets: C.hs

**** [Checking: C.hs] **********************************************************

**** DONE:  A-Normalization ****************************************************
 
WARNING: Assume Overwrites Specifications for C.bar : /root/C.hs:12:19

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  Transformed Core ***************************************************
 
Working 150% [===============================================================
===================================]

**** DONE:  annotate ***********************************************************
 

**** RESULT: SAFE **************************************************************
LiquidHaskell Version 0.8.6.2 no git information
Copyright 2013-19 Regents of the University of California. All Rights Reserved.

Targets: D.hs

**** [Checking: D.hs] **********************************************************

**** DONE:  A-Normalization ****************************************************
 

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


 C.hs:15:1-3: Error: Multiple specifications for `C.bar` :
  
 15 | bar a = foo a -- I want to use here assumption "amPred1 a", but it is not available
      ^^^
  
     Conflicting definitions at
      
     * C.hs:12:19
      
     * /root/C.hs:13:12
```
I was able to find a workaround. This works:
```haskell
{-@ assume bar :: {a: String | amPred1 a} -> {y: String | amPred1 y} @-}
bar :: String -> String
bar a = if pred1 a then foo a else undefined
```
But I think this solution is ugly.

I use latest version available in Hackage, i. e. 0.8.6.2.

I can describe my real task if you want, i. e. why I actually need this functionality

**Comment by ranjitjhala** [comment]
Hi @safinaskar,

A few things.

First, I'd suggest you simplify your code a bit as shown below; 
just define the function `amPred1` and use `reflect` to turn it 
into something you can use in specs. This may be easier than 
having two things floating around but if your code for `amPred1` 
is super complex and not in the fragment of Haskell that LH can 
`reflect` then you can still use your `measure` approach.

(http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1594478221_10784.hs)

```haskell
{-@  reflect amPred1 @-} 
amPred1 :: String -> Bool
amPred1 a = True

{-@ foo :: {x: String | amPred1 x} -> String @-}
foo :: String -> String
foo a = a

{-@ assume bar :: {a: String | amPred1 a} -> {y: String | amPred1 y} @-}
bar :: String -> String
bar a = foo a

{-@ use :: {x: String | amPred1 x} -> {y: String | amPred1 y} @-}
use :: String -> String
use a = bar a
```

Second, even in the code above, as in your original code, 
LH reports an error for the `a` in `foo a` in the definition of `bar`.
This error *goes away* and is replaced by another error when you 
remove the `assume` or add another signature for `bar`.

This sounds wrong but is in fact the correct semantics of `assume bar :: T` 
which means -- use the signature `T` _at clients_ of `bar` (i.e. at _usages_ of `bar`)
but not when checking `bar` itself. Consequently, when LH analyzes the body of `bar`
it _does not know_ the signature `T` and so the `a` is just an arbitrary `String` 
and hence the type error for `foo a`.

When you _remove_ the assume (or add the extra signature without the assume) the 
body is being checked with the signature `T` hence that error goes away. However, 
now you get a different error which says that the _output_ of `bar a` is not an `amPred1`
because your signature of `foo` does not say that its output is an `amPred1`.

Does that make sense?

I would suggest just removing the `assume` and writing something like the below, which is safe

```haskell
{-@ LIQUID "--reflection" @-} 

module Blank where

{-@  reflect amPred1 @-} 
amPred1 :: String -> Bool
amPred1 a = True

{-@ foo :: {x: String | amPred1 x} -> {v:String | amPred1 v} @-}
foo :: String -> String
foo a = a

{-@ bar :: {a: String | amPred1 a} -> {y: String | amPred1 y} @-}
bar :: String -> String
bar a = foo a

{-@ use :: {x: String | amPred1 x} -> {y: String | amPred1 y} @-}
use :: String -> String
use a = bar a
```

Does this help? Best! Ranjit.

**Comment by safinaskar** [comment]
@ranjitjhala, thanks a lot!
> use reflect to turn it into something you can use in specs

`reflect` doesn't work even in simple cases. For example, it fails if I use `null` in my function (even if I import `Language.Haskell.Liquid.Prelude`) with message `Unbound symbol Data.Foldable.null --- perhaps you meant: Data.Either.Left ?`. (I use Hackage Liquid Haskell version, i. e. 0.8.6.2, my ghc version is 8.6.5.) Same with `head`. Maybe there is some way to fix this, but it seems I don't need reflecting. (Adding `{-@ LIQUID "--reflection" @-}` doesn't help, too.)

Okey, what I want? I want consumers of `bar` to see `bar` as function which expects `amPred1` and returns `amPred1`. And I want to be able to use in `bar` definition fact that its argument satisfies `amPred1`. But I don't want Liquid Haskell to try to prove that `bar`'s result satisfies `amPred1`, I want Liquid Haskell just to trust me here. This example is artificial. In real code `foo` doesn't establish `amPred1` property. And in real code `bar` establishes `amPred1` property (and calls `foo` somewhere in its definition), but I want Liquid Haskell just to trust me in that `bar` establishes this property.

> I would suggest just removing the assume and writing something like the below, which is safe

This will not go. In my real code `foo` doesn't establish `amPred1`

**Comment by safinaskar** [comment]
I can give you good example. Consider function `sanitize`, which sanitizes some string input from untrusted user. This function establishes property `sanitized`, and I want to express this in LH. But I don't want to give definition of `sanitized`, I want LH just to threat it as opaque property. Of course, I cannot prove that `sanitize` establishes `sanitized` (because LH doesn't know what is `sanitized`). So (as it seems for me) the only way to express this idea is this:
```haskell
{-@ measure sanitized :: String -> Bool @-}
{-@ assume sanitize :: String -> {y: String | sanitized y} @-}
sanitize :: String -> String
sanitize = ...
```
Now we can write various functions, which works with strings, and be sure that only sanitized data is passed to them (cool!):
```haskell
{-@ f :: {x: String | sanitized x} -> ... @-}
f :: String -> ...
f = ...
```
Okey, but let's imagine that our function `sanitize` requires another string property, for example, its non-emptiness. We want somehow change `sanitize` definition such the following hold:
- Outer code can call `sanitize` only for non-empty strings
- We can use non-emptiness of strings in `sanitize` implementation (for example, we can call `head` on input string)

Unfortunately, it seems this is not possible. If I write `{-@ assume sanitize :: {x: String | len x > 0} -> {y: String | sanitized y} @-}`, then `len x > 0` will not be available to `sanitize` definition. If I write same, but without `assume`, LH will unable to check `sanitized` property. So I have to use this hack:
```haskell
{-@ assume sanitize :: {x: String | len x > 0} -> {y: String | sanitized y} @-}
sanitize :: String -> String
sanitize x = case x of {
  [] -> undefined;
  _ -> ...
}
```
Okey, if you still think LH behavior is correct, then you may just close the ticket. I am satisfied with this workaround.

Also, maybe I just chose wrong tool? I. e. maybe I need something different from LH? I don't need to actually prove anything, I just want some way to track various phantom properties, such as `santized`. I don't want express them at logic level, I just want Haskell to trust me that functions a and b establish this property, and functions c and d need this property. And I want to check that c and d called only on input came from a and b. And I don't want to use ugly wrapper types, such as NonEmpty from Data.List.NonEmpty , i. e. I don't want `newtype Sanitized = Sanitized String` and mess with wrapping/unwrapping. It seems LH can give me this

**Comment by ranjitjhala** [comment]
Hi @safinaskar -- got it -- in that case I suggest you do as described here

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1594503347_10803.hs

**Step 1: Define `sanitized` as a measure**

```haskell
{-@ measure sanitized :: String -> Bool @-}

{-@ type SanString = {v:String | sanitized v} @-}
```

**Step 2: Assert a type for the IMPLEMENTATION of `sanitize`** 

Tell LH to use check IMPLEMENTATION of `sanitize` using the below signature
whose output just says `String` so we don't *verify* that the output is `sanitized`
because of course we cannot.

```haskell
{-@ sanitize :: {x: String | len x > 0} -> String @-}
sanitize :: String -> String
sanitize x = case x of {
  -- [] -> undefined;   -- not required as LH "knows" the input is not-empty
  h:t -> t 
}
```

**Step 3: Assume a type for the USES of `sanitize`** 

Tells LH to use the below signature at USES of `sanitize`; the signature requires the input is non-empty and 
ensures the output is in fact `sanitized`.

```haskell
{-@ assume sanitize :: {x: String | len x > 0} -> SanString @-}

-- | Client Code that REQUIRES a sanitized string

{-@ useSanString :: SanString -> Int @-}
useSanString :: String -> Int
useSanString x = 10

-- | Client code that takes any string; checks/sanitizes it and then uses it.

sanitizeThenUse :: String -> Int
sanitizeThenUse str = case str of 
  [] -> 0                      {- 1 -} 
  _  -> useSanString (sanitize {- 2 -} str)
```

Hopefully this can work? Best!

-- | {- 1 -} if you comment this out, LH will complain 
--           as `str` may be empty in the call to `sanitize`

-- | {- 2 -} if you comment out the call to `sanitize` then 
--           again LH will complain as `useSanString` may get 
--           an un-sanitized string.

**Comment by safinaskar** [comment]
Unfortunately, your solution doesn't work across modules. I used Blank.hs you published at http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1594503347_10803.hs as-is. And added the following Use.hs:
```haskell
import Blank

sanitizeThenUse2 :: String -> Int
sanitizeThenUse2 str = case str of 
  [] -> 0                      {- 1 -} 
  _  -> useSanString (sanitize {- 2 -} str)

main = return ()
```
Then I got this error:
```text
LiquidHaskell Version 0.8.6.2 no git information
Copyright 2013-19 Regents of the University of California. All Rights Reserved.

Targets: ./Blank.hs
         Use.hs

**** [Checking: ./Blank.hs] ****************************************************

**** DONE:  A-Normalization ****************************************************
 
WARNING: Assume Overwrites Specifications for Blank.sanitize : /root/Blank.hs:22:24

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  Transformed Core ***************************************************
 
Working 175% [===============================================================
===================================================]

**** DONE:  annotate ***********************************************************
 

**** RESULT: SAFE **************************************************************

**** [Checking: Use.hs] ********************************************************

**** DONE:  A-Normalization ****************************************************
 

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


 /root/Blank.hs:13:1-8: Error: Multiple specifications for `Blank.sanitize` :
  
 13 | sanitize x = case x of {
      ^^^^^^^^
  
     Conflicting definitions at
      
     * /root/Blank.hs:22:24
      
     * /root/Blank.hs:11:17
```
If I move `{-@ assume @-}` to Use.hs, then everything works. But this will mean that I have to put `{-@ assume @-}` to every module where I use `sanitize`! I don't want this

**Comment by ranjitjhala** [comment]
Ah yes, you are right -- across modules, LH will complain. You can do this instead

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1594508959_10812.hs

## Define a `Sanitize` Module

1. Split the actual implementation into a separate (non-exported) function, 
2. Only export `sanitize` with the `assume` signature 
3. Tell LH to `ignore` checking the implementation of `sanitize` 

```haskell
module Sanitize  where 
-- | Tells LH to use check IMPLEMENTATION of `sanitize` using the below signature
--   note the output just says `String` so we dont VERIFY that it is `sanitized`
--   because of course we cannot.

{-@ sanitizeImpl :: {x: String | len x > 0} -> String @-}
sanitizeImpl :: String -> String
sanitizeImpl x = case x of {
  -- [] -> undefined;   -- not required as LH "knows" the input is not-empty
  h:t -> t 
}

{-@ assume sanitize :: {x: String | len x > 0} -> SanString @-}
{-@ ignore sanitize @-}
sanitize :: String -> String
sanitize = sanitizeImpl
```

## Use `Sanitize` in a Client

Now you should be able to define a separate "client" where you only use `sanitize` without any conflicts

```haskell
module Client

import Sanitize (sanitize)


-- | Client Code that REQUIRES a sanitized string

{-@ useSanString :: SanString -> Int @-}
useSanString :: String -> Int
useSanString x = 10

-- | Client code that takes any string; checks/sanitizes it and then uses it.

sanitizeThenUse :: String -> Int
sanitizeThenUse str = case str of 
  [] -> 0                      {- 1 -} 
  _  -> useSanString (sanitize {- 2 -} str)
  
-- | {- 1 -} if you comment this out, LH will complain 
--           as `str` may be empty in the call to `sanitize`

-- | {- 2 -} if you comment out the call to `sanitize` then 
--           again LH will complain as `useSanString` may get 
--           an un-sanitized string.
```

I think the above should work? Can you let me know? thanks!
```

**Comment by safinaskar** [comment]
Yes, it works! Thanks a lot, I'm closing bug

**Comment by kosmikus** [comment]
Does this bug really deserve to be closed? What is the reason why LH should complain in the cross-module scenario, when apparently it is ok in a single-module scenario?

**Comment by ranjitjhala** [comment]
I agree; I wonder what happens in develop? Does LH complain? IMO if there
is an assume then that should be the exported signature. Alternately we can
make it complain even in the single module case (duplicate signatures)
since the right thing may be to split into two binders as discussed
above...?

**Comment by safinaskar** [comment]
In single-module case I see a warning. This is output of LH on http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1594572631_10837.hs :
```text
LiquidHaskell Version 0.8.6.2 no git information
Copyright 2013-19 Regents of the University of California. All Rights Reserved.

Targets: Blank.hs

**** [Checking: Blank.hs] ******************************************************

**** DONE:  A-Normalization ****************************************************
 
WARNING: Assume Overwrites Specifications for Blank.sanitize : /root/Blank.hs:22:24

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  Transformed Core ***************************************************
 
Working 175% [===============================================================
===================================================]

**** DONE:  annotate ***********************************************************
 

**** RESULT: SAFE **************************************************************
```
