### ISSUE TITLE
Liquid fails when use import GHC.Num

### ISSUE THREAD

**Issue by racherb** [ucsd-progsys/liquidhaskell#1707]
### Liquid fails when I import GHC.Num

The detail of the error is shown below:

#### Error

```
**** RESULT: ERROR *************************************************************

 ../.cabal/share/x86_64-linux-ghc-8.6.3/liquidhaskell-0.8.6.0/include/Prelude.spec:26:59-75: Error: Unknown type constructor `GHC.Integer.Type`
  
 26 | assume GHC.Integer.smallInteger :: x:GHC.Prim.Int# -> { v:GHC.Integer.Type | v = (x :: int) }
                                                                ^^^^^^^^^^^^^^^^^
  
     matchTyCon: GHC.Integer.Type
*** Exception: ExitFailure 2
```
#### How to reproduce it?

**$ ghc --version**
`The Glorious Glasgow Haskell Compilation System, version 8.6.3`

**$ liquid --version**
`LiquidHaskell Version 0.8.6.0, Git revision fe4062f339f11d4390f0b0803062f2a8f0d23dea [develop@fe4062f339f11d4390f0b0803062f2a8f0d23dea (Thu Apr 25 11:04:59 2019 -0700)] `

Generate an arbitrarily named haskell file prelude_spec_26_59_75.hs and add the following line:

`import GHC.Num as Export`

Save the file and execute the command 'liquid':

`$ liquid prelude_spec_26_59_75.hs`

**Comment by ranjitjhala** [comment]
Dear @racherb -- can you try with the latest `develop` (there are lots of changes and its for GHC 8.10 but the import/resolution code is much improved.) Specifically, I tried the below code and it works fine:

```haskell
module T1707 where

import GHC.Num as Export

{-@ foo :: x:Int -> {v:Int | v > x} @-}
foo :: Int -> Int
foo x = x + 1
```

Maybe there is some other modification that triggers the error?

**Comment by racherb** [comment]
Dear @ranjit, I have been using the Custom Preludes option and, so far, I have been able to exclude the import of GHC.Num.

On the other hand, I haven't been able to compile the development version yet but I'll keep an eye on its evolution.

```
src/Language/Haskell/Liquid/GHC/API.hs:32:5: error:
    Not in scope: 'tyConRealArity
```

**Comment by ranjitjhala** [comment]
How are you trying to build?

**Comment by racherb** [comment]
I'm trying to build with "cabal". This is the error message:

```
src/Language/Haskell/Liquid/GHC/API.hs:32:5: error:
    Not in scope: ‘tyConRealArity’
    Perhaps you meant ‘tyConArity’ (imported from GHC)
   |
32 |   , tyConRealArity
   |     ^^^^^^^^^^^^^^
cabal: Leaving directory '.'
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:994:15 in main:Distribution.Client.Install
cabal: Error: some packages failed to install:
liquidhaskell-0.8.10.1-IPYBHzPLEaqAbmh9EHIMcI failed during the building
phase. The exception was:
ExitFailure 1

```
