### ISSUE TITLE
[plugin] Annotations in some modules ignored, possible race in parallel builds

### ISSUE THREAD

**Issue by plredmond** [ucsd-progsys/liquidhaskell#1710]
Sometimes annotations in modules aren't checked. I've made a repro of the issue here: https://github.com/plredmond/liquidhaskell-uscd-progsys-tut/tree/d021a33f90713dbce3f1e895b63ef9944df7c82e
* On the branch there are two modules, `A` and `B`.
* `A` uses `{-# LANGUAGE PackageImports #-}` to `import "liquid-base" Prelude`.
* `B` contains an invalid annotation (a value 3 is annotated as not being 3).

EXPECTED:

* LiquidHaskell should check both modules and find the incorrect annotation in `B`.

ACTUAL:

* I'm seeing inconsistent behavior when I run `nix-build` on a computer with several CPU cores. About 75% of the builds succeed and report SAFE (incorrectly) while the other 25% of builds find the invalid annotation and fail (correctly).

WORKAROUNDS:

1. When I run `nix-build --core 1` it always finds the invalid annotation and fails (correctly).
1. When I run `nix-shell --run 'cabal v2-build'` it always finds the invalid annotation and fails (correctly).

Affected Versions:

* https://github.com/ucsd-progsys/liquidhaskell/commit/3bc467162ba285bf2c1529dafce21a20bb9aab8e

**Comment by plredmond** [comment]
Originally reported [in slack](https://liquidhaskell.slack.com/archives/C54QAL9RR/p1595059256088400?thread_ts=1595059172.088200&cid=C54QAL9RR) and copied here:

> **rjhala  3 hours ago**
> Hi patrick yes a GH issue would be great.,Thanks! The 75/25 split is random? Or is there some pattern?

> **patrick  24 minutes ago**
> rjhala It seemed random to me. I didn't look closely because the nix build environment is pretty good at preventing leaks between subsequent builds.
>
> ~I talked to some folks in the nix IRC and they suggested nix-build --cores 1 , for which the build consistently succeeds (incorrectly).~
>
> This might indicate it's a race in the parallel build (nix's default)
>
> How does liquidhaskell obtain mutual exclusion when reading and writing files in the .liquid/ directories?

**Comment by plredmond** [comment]
I'll check to see if the order of the two modules being compiled corresponds to the presence of the bug.

**Comment by srhb** [comment]
Sorry, I meant that the build appears to correctly *fail* with --cores 1

**Comment by plredmond** [comment]
Thanks for the correction @srhb. I've confirmed that with `--cores 1` the build fails consistently, which is a good workaround.

**Comment by plredmond** [comment]
Here is an example of how the output looks when the build succeeds and reports SAFE, incorrectly (reported ACTUAL behavior).
```
...
building
Preprocessing library for example-0.1.0.0..
Building library for example-0.1.0.0..
[1 of 2] Compiling A                ( lib/A.hs, dist/build/A.o, dist/build/A.dyn_o )

**** LIQUID: SAFE (0 constraints checked) **************************************

**** LIQUID: SAFE (0 constraints checked) **************************************
[2 of 2] Compiling B                ( lib/B.hs, dist/build/B.o, dist/build/B.dyn_o )
[1 of 2] Compiling A                ( lib/A.hs, dist/build/A.p_o )

**** LIQUID: SAFE (0 constraints checked) **************************************

**** LIQUID: SAFE (0 constraints checked) **************************************
[2 of 2] Compiling B                ( lib/B.hs, dist/build/B.p_o )
running tests
...
```
Here is an example of how the output looks when the build finds the invalid annotation and fails, correctly (reported EXPECTED behavior).
```
...
building
Preprocessing library for example-0.1.0.0..
Building library for example-0.1.0.0..
[1 of 2] Compiling A                ( lib/A.hs, dist/build/A.o, dist/build/A.dyn_o )

**** LIQUID: SAFE (0 constraints checked) **************************************

**** LIQUID: UNSAFE ************************************************************


 lib/B.hs:5:1-12: Error: Liquid Type Mismatch

 5 | notThree = 3
     ^^^^^^^^^^^^

   Inferred type
     VV : {v : GHC.Types.Int | v == 3}

   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV >= 0
                                && VV /= 3}

[2 of 2] Compiling B                ( lib/B.hs, dist/build/B.o, dist/build/B.dyn_o )

<no location info>: error: ExitFailure 1

builder for '/nix/store/njg83vivm84cs6xi6az00c2jliigp2r2-example-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/njg83vivm84cs6xi6az00c2jliigp2r2-example-0.1.0.0.drv' failed
```

**Comment by plredmond** [comment]
<details><summary>EXPECTED: Here is an example of how the <code>nix-build --cores 8</code> output looks when the build finds the invalid annotation and fails (correctly).</summary>

* Note that constraint checking output seems out of order with at the "Compiling B" message. (It's not clear if this ordering is expected, but I'm calling it out to contrast with below.)

```
...
building
Preprocessing library for example-0.1.0.0..
Building library for example-0.1.0.0..
[1 of 2] Compiling A                ( lib/A.hs, dist/build/A.o, dist/build/A.dyn_o )

**** LIQUID: SAFE (0 constraints checked) **************************************

**** LIQUID: UNSAFE ************************************************************


 lib/B.hs:5:1-12: Error: Liquid Type Mismatch

 5 | notThree = 3
     ^^^^^^^^^^^^

   Inferred type
     VV : {v : GHC.Types.Int | v == 3}

   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV >= 0
                                && VV /= 3}

[2 of 2] Compiling B                ( lib/B.hs, dist/build/B.o, dist/build/B.dyn_o )

<no location info>: error: ExitFailure 1

builder for '/nix/store/njg83vivm84cs6xi6az00c2jliigp2r2-example-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/njg83vivm84cs6xi6az00c2jliigp2r2-example-0.1.0.0.drv' failed
```

</details>

<details><summary>ACTUAL: Here is an example of how the <code>nix-build --cores 8</code> output looks when the build succeeds and reports SAFE (incorrectly).</summary>

* Note that compilation shows up twice: A and B then again A and B.
* Note that constraint checking output seems out of order with at the "Compiling B" messages.

```
...
building
Preprocessing library for example-0.1.0.0..
Building library for example-0.1.0.0..
[1 of 2] Compiling A                ( lib/A.hs, dist/build/A.o, dist/build/A.dyn_o )

**** LIQUID: SAFE (0 constraints checked) **************************************

**** LIQUID: SAFE (0 constraints checked) **************************************
[2 of 2] Compiling B                ( lib/B.hs, dist/build/B.o, dist/build/B.dyn_o )
[1 of 2] Compiling A                ( lib/A.hs, dist/build/A.p_o )

**** LIQUID: SAFE (0 constraints checked) **************************************

**** LIQUID: SAFE (0 constraints checked) **************************************
[2 of 2] Compiling B                ( lib/B.hs, dist/build/B.p_o )
running tests
...
```

</details>

<details><summary>WORKAROUND 1: Here is an example of  how the <code>nix-build --cores 1</code> output looks when the build finds the invalid annotation and fails (correctly).</summary>

* Note that compared with EXPECTED output (above) the constraint checking output for B doesn't occur until after the notification "Compiling B".

```
...
building
Preprocessing library for example-0.1.0.0..
Building library for example-0.1.0.0..
[1 of 2] Compiling A                ( lib/A.hs, dist/build/A.o, dist/build/A.dyn_o )

**** LIQUID: SAFE (0 constraints checked) **************************************
[2 of 2] Compiling B                ( lib/B.hs, dist/build/B.o, dist/build/B.dyn_o )

**** LIQUID: UNSAFE ************************************************************


 lib/B.hs:5:1-12: Error: Liquid Type Mismatch

 5 | notThree = 3
     ^^^^^^^^^^^^

   Inferred type
     VV : {v : GHC.Types.Int | v == 3}

   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV >= 0
                                && VV /= 3}

builder for '/nix/store/njg83vivm84cs6xi6az00c2jliigp2r2-example-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/njg83vivm84cs6xi6az00c2jliigp2r2-example-0.1.0.0.drv' failed
```

</details>

<details><summary>WORKAROUND 2: Here is an example of  how the <code>nix-shell --run 'cabal v2-build'</code> output looks when the build finds the invalid annotation and fails (correctly).</summary>

* Note that compared with EXPECTED output (above) the constraint checking output for B doesn't occur until after the notification "Compiling B".

```
Building library for example-0.1.0.0..
[1 of 2] Compiling A                ( lib/A.hs, /home/mote/lsd-lab/projects/liquidhaskell-ucsd-progsys-tut/dist-newstyle/build/x86_64-linux/ghc-8.10.1/example-0.1.0.0/build/A.o, /home/mote/lsd-lab/projects/liquidhaskell-ucsd-progsys-tut/dist-newstyle/build/x86_64-linux/ghc-8.10.1/example-0.1.0.0/build/A.dyn_o )

**** LIQUID: SAFE (0 constraints checked) **************************************
[2 of 2] Compiling B                ( lib/B.hs, /home/mote/lsd-lab/projects/liquidhaskell-ucsd-progsys-tut/dist-newstyle/build/x86_64-linux/ghc-8.10.1/example-0.1.0.0/build/B.o, /home/mote/lsd-lab/projects/liquidhaskell-ucsd-progsys-tut/dist-newstyle/build/x86_64-linux/ghc-8.10.1/example-0.1.0.0/build/B.dyn_o )

**** LIQUID: UNSAFE ************************************************************


 lib/B.hs:5:1-12: Error: Liquid Type Mismatch

 5 | notThree = 3
     ^^^^^^^^^^^^

   Inferred type
     VV : {v : GHC.Types.Int | v == 3}

   not a subtype of Required type
     VV : {VV : GHC.Types.Int | VV >= 0
                                && VV /= 3}
```

</details>

**Comment by ranjitjhala** [comment]
Puzzling! I wonder if this is a known issue with GHC plugins?

however with a plain, single threaded build there is no problem, right?

Also the module A seems to not be relevant (as in there are no specs in it
that matter) — yet, does deleting it make the misbehavior go away?

**Comment by plredmond** [comment]
@ranjitjhala 

> Also the module A seems to not be relevant (as in there are no specs in it that matter) — yet, does deleting it make the misbehavior go away?

Yes, deleting `A` or removing `import "liquid-base" Prelude` from `A` fixes the issue.

> however with a plain, single threaded build there is no problem, right?

Yes, as described in the (updated) github issue. (Since you're on email you probably cannot see my edits to the github issue description).

---

Update:

I upgraded from liquidhaskell@https://github.com/ucsd-progsys/liquidhaskell/commit/3bc467162ba285bf2c1529dafce21a20bb9aab8e to liquidhaskell@https://github.com/ucsd-progsys/liquidhaskell/commit/26cad4f05171669949fd92fa5a5f584a4950ca7b (the version of [liquid-fixpoint](https://github.com/ucsd-progsys/liquid-fixpoint) did not change) and the problem is resolved.

**Comment by plredmond** [comment]
I'm closing this because it was resolved by using a newer version of LH.
