### ISSUE TITLE
SMT crashes on diverging Int functions

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1721]
The following 

```
module Foo where 

incr :: Int -> Int
incr n = incr n 
```

Crashes with 
```
:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 13 column 13: invalid sort definition, sort already declared/defined"
```

It is SAFE with `--no-terminantion`. SMT version `Z3 version 4.8.8 - 64 bit`

**Comment by ranjitjhala** [comment]
Wow this is without reflection/ple or similar???

**Comment by nikivazou** [comment]
It seems I had a wrong fixpoint link, which is even more confusing, because I clean build it... 
Still trying to understand what I am doing wrong.
