### ISSUE TITLE
Building documentation fails when the plugin is enabled

### ISSUE THREAD

**Issue by adinapoli** [ucsd-progsys/liquidhaskell#1727]
I was trying to manually build the docs for `liquid-base` by typing:

```
cabal v2-haddock --html --hyperlink-source liquid-base
```

Unfortunately, that didn't go through and instead failed with:

```
**** LIQUID: SAFE (0 constraints checked) **************************************
  50% (  1 /  2) in 'Foreign.StablePtr'
  Missing documentation for:
    Module header
**** LIQUID: SAFE (0 constraints checked) **************************************
  50% (  1 /  2) in 'GHC.Arr'
  Missing documentation for:
    Module header
**** LIQUID: SAFE (0 constraints checked) **************************************
  50% (  1 /  2) in 'GHC.Base'
  Missing documentation for:
    Module header
src/Data/Tuple.spec:3:8: error:
    • Illegal type specification for `Data.Tuple.fst`
    Data.Tuple.fst :: forall a b . x:(a, b) -> {VV : a | VV == fst x}
    Sort Error in Refinement: {VV : a##agwI | VV == fst x}
    Unbound symbol fst --- perhaps you meant: VV, x ?
    • 
  |
3 | fst :: {f:(x:(a,b) -> {v:a | v = (fst x)}) | f == fst }
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
src/Data/Tuple.spec:4:8: error:
    • Illegal type specification for `Data.Tuple.snd`
    Data.Tuple.snd :: forall a b . x:(a, b) -> {VV : b | VV == snd x}
    Sort Error in Refinement: {VV : b##agwL | VV == snd x}
    Unbound symbol snd --- perhaps you meant: head, VV, x ?
    • 
  |
4 | snd :: {f:(x:(a,b) -> {v:b | v = (snd x)}) | f == snd }
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build documentation for liquid-base-4.14.0.0.
```

This is interesting, as in theory it shouldn't fail.

**Comment by adinapoli** [comment]
I have done a bit of research on this issue, and conceptually, the culprit is very simple: the `SpecFinder` can't find any cached (serialised) `LiftedSpec` for `GHC.Base`, which contains the `fst` and `snd` measures used in the definition of `fst` and `snd`. If we compare the debug output for a _normal_ `v2-build`:

```
Module { unitId = base, name = Data.Tuple }
Module { unitId = liquid-base-4.14.1.0-inplace, name = GHC.Base }

Module ==> Module { unitId = liquid-base-4.14.1.0-inplace, name = Data.Tuple }
[T:Module { unitId = liquid-base-4.14.1.0-inplace, name = Data.Tuple }] Spec not found for Module { unitId = base, name = Data.Tuple }
[T:Data.Tuple] Lib found for Module { unitId = liquid-base-4.14.1.0-inplace, name = GHC.Base }
, at location InterfaceLocation
Redundant dependencies ==> []
Found 5 dependencies:
$liquid-base-4.14.1.0-inplace$GHC.Base
$liquid-ghc-prim-0.6.1-inplace$GHC.CString
$liquid-ghc-prim-0.6.1-inplace$GHC.Tuple
$liquid-ghc-prim-0.6.1-inplace$GHC.Types
$liquid-ghc-prim-0.6.1-inplace$GHC.Classes
```

vs the one for `cabal v2-haddock` (or similarly `stack build --haddock`):

```
Module { unitId = base, name = Data.Tuple }
Module { unitId = liquid-base-4.14.1.0-inplace, name = GHC.Base }

Module ==> Module { unitId = liquid-base-4.14.1.0-inplace, name = Data.Tuple }
[T:Module { unitId = liquid-base-4.14.1.0-inplace, name = Data.Tuple }] Spec not found for Module { unitId = base, name = Data.Tuple }
[T:Module { unitId = liquid-base-4.14.1.0-inplace, name = Data.Tuple }] Spec not found for Module { unitId = liquid-base-4.14.1.0-inplace, name = GHC.Base }
Redundant dependencies ==> []
Found 0 dependencies:
```

I think that a key insight might come from this comment from the [cabal source](https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/Simple/Haddock.hs#L397-L405): 

```haskell
mkHaddockArgs verbosity tmp lbi clbi htmlTemplate haddockVersion inFiles bi = do
    ifaceArgs <- getInterfaces verbosity lbi clbi htmlTemplate
    let vanillaOpts = (componentGhcOptions normal lbi bi clbi (buildDir lbi)) {
                          -- Noooooooooo!!!!!111
                          -- haddock stomps on our precious .hi
                          -- and .o files. Workaround by telling
                          -- haddock to write them elsewhere.
                          ghcOptObjDir     = toFlag tmp,
                          ghcOptHiDir      = toFlag tmp,
                          ghcOptStubDir    = toFlag tmp
                      } `mappend` getGhcCppOpts haddockVersion bi
```

My suspect is that somehow Haddock is messing up the final `.hi` and that is causing no `Annotation` to be written in the final `.hi` file, or something along those lines. Maybe @phadej has more nuggets of wisdom to share? 

I have tried running `cabal -j1 -v2 v2-haddock ...` and check out the final `ghc` command that Cabal produces, comparing it with the output of `cabal -j1 -v2 v2-build`.At glance I don't see anything immediately wrong; yes, `v2-build` performs an extra call to `ghc --make` to _actually build_ the library, passing a _different_ `-hidir`, but for the initial setup command both pass as `-hidir` something like `dist-newstyle/build/x86_64-osx/ghc-8.10.2/liquid-base-4.14.1.0/setup`.


Given how complicated this seems, I wonder if it would be simpler to just disable the plugin in case we need to build the documentation. Unfortunately I don't see an easy way to do this, as apparently there is an `__HADDOC_VERSION` macro that `Cabal` supposedly create (although reports are that it's not working very well) but this wouldn't scale for `nix` or `stack`, so I don't think is an option.

**Comment by kosmikus** [comment]
Yes, I think not using the plugin for Haddock runs is the way to go. There must be a way to detect running via Haddock.

**Comment by facundominguez** [comment]
I can still reproduce a similar error with
```
cabal v2-haddock --html --hyperlink-source liquid-base
```

There have been changes to the referred cabal source code: https://github.com/haskell/cabal/pull/9177

Disabling LH when running haddock does not work well in configurations that both build and generate documentation on the same pass as in #2557.
