### ISSUE TITLE
Set union with Empty Set in measure doesn't yield expected result?

### ISSUE THREAD

**Issue by hafizhmakmur** [ucsd-progsys/liquidhaskell#1728]
I'm playing around trying to solve the last practices of [the LH tutorial](http://ucsd-progsys.github.io/liquidhaskell-tutorial/Tutorial_12_Case_Study_AVL.html) and I think I found some problem relating to measure and union of Sets, as I try to isolate as much as possible in [this code.](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1596118642_11417.hs) 

So it seems like in this case Liquid can't reconcile that `x = Set_cup x (emptySet Leaf')` eventhough `emptySet Leaf'` is supposed to be equal to `Set_empty 0` and that `x = Set_cup x (Set_empty 0)` is deemed true by LH.  I can't reduce the `emptySet` measure further to `emptySet :: a -> Set a` or `emptySet :: Set a` to eliminate the need of `data AVL'` because `Does not have a case-of at the top-level` for some reason.

**Comment by ranjitjhala** [comment]
Dear @hafizhmakmur -- the `measure` is an "uninterpreted function" which means that when LH sees `emptySet Leaf'` in a refinement, it knows nothing about the "meaning" of `emptySet`.

You can solve your problem by either:

- replace `measure` with `inline`  which tells LH to "inline" the definition of `emptySet`, but this only works for *non-recursive* functions like `emptySet`, or

- replace `emptySet Leaf'` with `S.empty` in all the type specifications.

Either of these changes will make your code pass.

Hope this helps!

- Ranjit.
