### ISSUE TITLE
Please support Diff-0.4.x

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquidhaskell#1729]
Current release versions of `liquidhaskell` cannot be built in an LTS-16.x environment because the package does not support `Diff-0.4.x`. Would that be difficult to rectify?

**Comment by ranjitjhala** [comment]
Hmm let me see if we can fiddle around with this to get LH to build on
LTS-16.x ...

**Comment by ranjitjhala** [comment]
Hi @peti -- I just made a PR that should hopefully fix this issue! Thanks, Ranjit.
