### ISSUE TITLE
LH produces duplicate specifications for measures whose type contains String

### ISSUE THREAD

**Issue by nilehmann** [ucsd-progsys/liquidhaskell#1735]
This simple code below produces an error when checking `B.hs`

```haskell
module A where
{-@ measure f :: String @-}
```

```haskell
module B where
import A
```

```bash
$ liquid B.hs
A.hs:3:13: error:  Multiple specifications for `f` :
                        Conflicting definitions at
                        .
                        * A.hs:3:13
                        .
                        * /home/nlehmann/temp/A.hs:3:13
```

I did some digging and noticed that one of the measures has type `String` while the other has type `[GHC.Types.Char]`

**Comment by adinapoli** [comment]
Hi @nilehmann !

We are in the process of transitioning to a new GHC plugin architecture, as described [here](https://hackage.haskell.org/package/liquidhaskell-0.8.10.1/docs/Language-Haskell-Liquid-GHC-Plugin-Tutorial.html), and the executable is now deprecated.

Are you in a position to test out the GHC plugin, and report if you still get the error?

**Comment by ranjitjhala** [comment]
Hi @alfredo - I will try it out! Ranjit

**Comment by ranjitjhala** [comment]
Ok, I can confirm that the bug *does not* happen in `plugin-mode`. 

Specifically, if you check this branch out:

https://github.com/ucsd-progsys/lh-plugin-demo/tree/measure-string-bug

(`Lib.hs` exports the `measure` and is imported by `Client.hs`)

Then 

- *plugin-mode* via `stack build` (etc.) finishes just fine, BUT
- *executable-mode* complains:

```
rjhala@khao-soi ~/r/lh-demo (measure-string-bug)> liquid -i src src/Demo/Client.hs

**** LIQUID: SAFE (2 constraints checked) **************************************

**** LIQUID: ERROR  ************************************************************
/Users/rjhala/research/lh-demo/src/Demo/Lib.hs:13:13: error:  Multiple specifications for `f` :
                                                                  Conflicting definitions at
                                                                  .
                                                                  * /Users/rjhala/research/lh-demo/src/Demo/Lib.hs:13:13
                                                                  .
                                                                  * /Users/rjhala/research/lh-demo/src/Demo/Lib.hs:13:13
```

**Comment by nilehmann** [comment]
ok, if the fix is then to use plugin mode, may I ask if there's a recommended way to turn refinement checking on and off? The code I'm currently working on takes several seconds to check a single module. This is beyond what I'm willing to accept in my regular edit check flow. So, I'd like to get fast feedback just from ghc and only check refinements after the code is more stable.

**Comment by ranjitjhala** [comment]
The easiest is to comment out the line


https://github.com/ucsd-progsys/lh-plugin-demo/blob/main/lh-plugin-demo.cabal#L25

in the cabal file? There's probably some clever way to use stack/cabal
flags too but I don't recall
the syntax off the top of my head. Still, let me look into this, since it
is independently very important!

**Comment by adinapoli** [comment]
> The code I'm currently working on takes several seconds to check a single module.

To complement what Ranjit said already, perhaps a middle-ground solution is to add the `--compile-spec` option as a pragma to the single module taking several seconds to refine (if that's an option)? Something like:

```haskell
{-@ LIQUID "--compile-spec" @-}

module MySlowModule where

..
```

`--compile-spec` will skip verification for that module, and should be faster.

**Comment by facundominguez** [comment]
Is this issue good to close?

**Comment by ranjitjhala** [comment]
Yup thanks!

**Comment by nilehmann** [comment]
I still think there ought to be a recommended way to quickly turn on and off liquid type checking depending on the use case. I'm not currently working in the original code now, but back then it was very painful. For example, back then Haskell lsp just crashed with LH on. Some support/guidelines for turning off LH in ide mode would be nice. This is orthogonal to the original issue though.

**Comment by ranjitjhala** [comment]
I agree but the catch is that LSP issue is a bug in LSP (surprisingly!) 

Is the way to switch on and off is to toggle the fplugin mode?

**Comment by nilehmann** [comment]
In the specific use case of Storm I would like to disable the LH plugin by default (lsp would work out of the box) and have an option to turn it on when I run it in the command line (maybe passing an extra flag to stack). This is because running LH is too slow, so I have a quick plain Haskell development cycle + a slower "verification" cycle.
