### ISSUE TITLE
Verification does not terminate when reflected function used instead of measure

### ISSUE THREAD

**Issue by zgrannan** [ucsd-progsys/liquidhaskell#1737]
LiquidHaskell does not terminate on the following code:

```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--ple" @-}

{-@ reflect length' @-}
{-@ length' :: [a] -> Int @-}
length' :: [a] -> Int
length' []     = 0
length' (_:xs) = 1 + length' xs

{-@ type ListX  a X = {l:[a] | length' l == length' X } @-}

{-@ reflect zw @-}
{-@ zw :: (a -> b -> c) -> xs:[a] -> ListX b xs -> ListX c xs @-}
zw :: (a -> b -> c) -> [a] -> [b] -> [c]
zw f (x:xs) (y:ys) = f x y : zw f xs ys
zw _ _      _      = []
```

However is `reflect length'` is replaced with `measure length'` (as it ought to be), verification works.

**Comment by ranjitjhala** [comment]
Wow, that's a bit of a surprise. (Has it always been the case?)

I assume its `ple` that's doing the diverging?

Can you take a look since you're working on it?

**Comment by zgrannan** [comment]
@ranjitjhala Sure I will take a look. I think it does have to do with PLE.

It seems like a regression: this code works on an arbitrary commit I chose from the past (d6ed10575062f861c62eb3afe238f7755d9dec99)

**Comment by ranjitjhala** [comment]
Interesting! probably a good idea to git bisect to find the breaking commit?

**Comment by zgrannan** [comment]
I'm no longer convinced that this is an PLE issue necessarily. This works with
`--oldple` option, but I suspect that it may be due to the logic in the old ple
to prevent recursive function applications in `if` branches.

The issue here is that every time the "length" function is applied in PLE, it
takes the recursive branch.

I've created a more simple example:

```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--ple" @-}

data Lis = LNil | LCons Int Lis

{-@ reflect length' @-}
{-@ length' :: Lis -> Int @-}
length' :: Lis -> Int
length' LNil          = 0
length' (LCons _ xxs) = 99 + length' xxs

{-@ type ListX  X = {l:Lis | length' l == length' X } @-}

{-@ reflect zw @-}
{-@ zw ::  xs:Lis -> ListX xs -> ListX xs @-}
zw :: Lis -> Lis -> Lis
zw _    thelist@(LCons _ _) = thelist
zw LNil LNil                = LNil
```

I tried to figure out why this is happening and judging from the SMT output I
think this is what's happening:

LiquidHaskell performs a case split on `xs`. In the case that `xs` is `LNil`, is
tries to prove that the length of `thelist` is the same as `xs`. By reflection
`length xs` is `0`. It seems like this equality should be disproven but in fact
it can't: in theory `length` could also return 0 for a nonempty list . Thus PLE
attempts to calculate the length of `thelist`, which is known to be a `LCons`. At
the first unfolding of the `length` in `PLE`, it proves that the tail of
`thelist` is not `LNil`, otherwise by the definition of `length`, it would be
`99`. Thus `PLE` takes the recursive path. And this continues at each
unfolding.

So if I understand correctly, the issue has to do with some automatic case-split
that LiquidHaskell is doing. Is this plausible?

I've attached a cleaned-up version of the .evals.smt file that highlights the
issue, but it may be challenging to interpret. The relevant parts starts at line 287.

[example.smt2.txt](https://github.com/ucsd-progsys/liquidhaskell/files/5091149/example.smt2.txt)

**Comment by ranjitjhala** [comment]
🧐

I think your hypothesis is correct.

As a test, if you change the output of length to say Nat instead of Int it
should finish. (Also to test your hypothesis you could explicitly put in
the nil case?)

Also, this is consistent with the ple termination theorem, which requires
that ple be invoked on a SATisifiable (inhabited) set of constraints, which
is not the case here.

**Comment by zgrannan** [comment]
Surprisingly the code still does not terminate when the output type of `length` is `Nat`. I suspect this is because `Nat` being `>=` 0 is encoded in PLE at applications of length, and it's not encoded at the right point. : i.e `length (tail xs) >= 0` and `length (tail xs) = 99 + length (tail (tail xs))` are compatible.  And I think these assertions are being bracketed (in `push` and `pop` statements), so the unsatisfiable set of constraints  `length xs = 0`, `length xs = 99 + length (tail xs)` and `length (tail xs) >= 0` never appear together.

However, PLE does terminate if the `length` function is represented using peano numbers (`data N = Z | S N`)

However maybe this is not important. Talking with @nikivazou today we discussed that such `reflect`ed functions should automatically be converted into `measure` if defined over one ADT, which would eliminate this particular issue.

**Comment by facundominguez** [comment]
I cannot reproduce this issue with the latest LH.
