### ISSUE TITLE
Can't use imported `inline` inside a `reflected` function

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1738]
LH complains 

If you create a *module* with an `inline`d function `incr`

```haskell
module InlineA where

{-@ inline incr @-}
incr :: Int -> Int
incr x = x + 1
```

and then *import* that `module` and try to use `incr` in a reflected function

```haskell
{-@ LIQUID "--reflection" @-}

module InlineB where

import InlineA

{-@ reflect bar @-}
bar :: Int -> Int
bar n = incr n
```

Then LH complains that `error:  Illegal type specification for 'InlineB.bar'` because `Unbound symbol 'InlineA.incr'`

Clearly we're not suitably serializing `inline` -- I don't think this is a regression per se, I suspect this was _always_ an issue because I didn't see a test like this in `tests/import`. (e.g. `tests/import/lib/ReflectClient0.hs` should also use an `inline` in reflected code, not just in the spec where it seems fine.)

**Comment by ranjitjhala** [comment]
@adinapoli if you want to reproduce this above -- you can use this branch:

https://github.com/ucsd-progsys/lh-plugin-demo/blob/inline-import-bug/

**Comment by adinapoli** [comment]
Ok, I have started investigating this issue and here is what I have found. I have added this test case as part of the testsuite, in the classic `lib/client` split. When LH compiles the _library_, we have the following `BareSpec` and `LiftedSpec` (I have omitted the empty fields):

```
MkBareSpec {
    getBareSpec = Spec {
      inlines = fromList [
        \"incr\" defined from: \"/lh/tests/import/client/../lib/T1738Lib.hs\" (line 3, column 12) to: \"/lh/tests/import/client/../lib/T1738Lib.hs\" (line 3, column 16)
    ]
  }
}
```

That gets turned into:

```
LiftedSpec {
  liftedSigs = fromList [
      (
        \"T1738Lib.incr\" defined from: \"/lh/tests/import/client/../lib/T1738Lib.hs\" (line 5, column 1) to: \"/lh/tests/import/client/../lib/T1738Lib.hs\" (line 5, column 5)
      ,x##1:GHC.Types.Int -> {VV : GHC.Types.Int | VV == x##1 + 1} defined from: \"/lh/tests/import/client/../lib/T1738Lib.hs\" (line 5, column 1) to: \"/lh/tests/import/client/../lib/T1738Lib.hs\" (line 5, column 5)
    )
  ]
  , liftedEaliases = fromList [
      type T1738Lib.incr  \"x##aFs##rta##0\" = EBin Plus (EVar \"x##aFs##rta##0\") (ECon (I 1)) defined from: \"/lh/tests/import/client/../lib/T1738Lib.hs\" (line 3, column 12) to: \"/lh/tests/import/client/../lib/T1738Lib.hs\" (line 3, column 16)
  ]
}
```

This looks OK to me, as we are turning the `inline` into a signature in the lifted spec, which is what we want, I think.

Back to the original problem, I think the error stems from the fact that `checkSortedReftFull` fails because the input `Symbol` `T1738Lib.incr` is **not** in the `SEnv SortedReft` we pass to `checkTy`. We construct the latter as part of this function:

```haskell
ghcSpecEnv :: GhcSpec -> SEnv SortedReft
ghcSpecEnv sp = fromListSEnv binds
  where
    emb       = gsTcEmbeds (_gsName sp)
    binds     = concat 
                 [ [(x,        rSort t) | (x, Loc _ _ t) <- gsMeas     (_gsData sp)]
                 , [(symbol v, rSort t) | (v, Loc _ _ t) <- gsCtors    (_gsData sp)]
                 , [(symbol v, vSort v) | v              <- gsReflects (_gsRefl sp)]
                 , [(x,        vSort v) | (x, v)         <- gsFreeSyms (_gsName sp), Ghc.isConLikeId v ]
                 , [(x, RR s mempty)    | (x, s)         <- wiredSortedSyms       ]
                 , [(x, RR s mempty)    | (x, s)         <- _gsImps sp       ]
                 ]
    vSort     = Bare.varSortedReft emb
    rSort     = rTypeSortedReft    emb
```

So I think we might have to find the magic incantation that allows `T1738Lib.incr` to end up in this environment. I have tried things like `tySigs`, but without success so far.

@ranjitjhala Does this ring any bell?

 I'll keep investigating in the meantime.

**Comment by ranjitjhala** [comment]
@adinapoli your theory sounds plausible! The LiftedSpec you show above is visible at the client right? (Just want to make sure the once shows up when imported to the client)

**Comment by ranjitjhala** [comment]
Actually the problem is not really in the SortedEnv — the inline means that incr is really a “macro” that should be expanded away in the signature. The liftedEaliases contains these macro definitions, so the problem is that this ealiases are not getting passed into the place where the expand happens.

**Comment by ranjitjhala** [comment]
Specifically see where Bare.Expand.mkRTEnv is defined and used. Does incr show up in that environment?

**Comment by adinapoli** [comment]
> Specifically see where Bare.Expand.mkRTEnv is defined and used. Does incr show up in that environment?

Yes, `incr` does show up in the final `mkRTEnv`, ~~but on why that would matter for the error at hand is not clear to me~~. 


EDIT: Oh, i see, your point is that really we shouldn't even _see_ `incr` being mentioned in the error. It should be expanded away before we actually reach that `checkBind` stage.

Original comment (for posterity):
Specifically, the offending check that is triggering the error is this one, inside `Bare.Check`:

```haskell
checkTargetSpec :: [Ms.BareSpec]
                -> TargetSrc
                -> F.SEnv F.SortedReft
                -> [CoreBind]
                -> TargetSpec
                -> Either Diagnostics ()
checkTargetSpec specs src env cbs sp
  | diagnostics == emptyDiagnostics = Right ()
  | otherwise                       = Left diagnostics
  where
    diagnostics      :: Diagnostics
    diagnostics      =  foldMap (checkBind allowHO bsc "measure"      emb tcEnv env) (gsMeas       (gsData sp))
                     <> condNull noPrune
                        (foldMap (checkBind allowHO bsc "constructor"  emb tcEnv env) (txCtors $ gsCtors      (gsData sp)))
                     <> foldMap (checkBind allowHO bsc "assume"       emb tcEnv env) (gsAsmSigs    (gsSig sp))
                     -- THIS ONE -->  <> foldMap (checkBind allowHO bsc "reflect"      emb tcEnv env) (gsRefSigs    (gsSig sp))
                     <> checkTySigs         allowHO bsc cbs            emb tcEnv env                (gsSig sp)
                     ...
```

If I uncomment that `checkBind` like in the example, the test passes. However, `checkBind` doesn't take as input a `BareRTEnv`, but only a `SEnv SortedReft`, and it's the latter that is used deep inside the guts of `checkTy`, and which ultimately triggers the error. Or are you saying that somehow we should also take into account a `BareRTEnv` and look for such `EAliases` ?

**Comment by adinapoli** [comment]
I think I have managed to come up with a sensible fix here: https://github.com/ucsd-progsys/liquidhaskell/pull/1745
