### ISSUE TITLE
SMT Sort mismatch

### ISSUE THREAD

**Issue by zgrannan** [ucsd-progsys/liquidhaskell#1749]
The following code:

```haskell
{-@ LIQUID "--ple" @-}
{-@ LIQUID "--reflection" @-}

data Value = B Bool | I Int

data Op = IF Op Op | NOP

{-@ reflect run @-}
{-@ run ::
       op : Op
  -> { is : [Value] | isValid op (stackType is) }
  -> [Value] @-}
run :: Op -> [Value] -> [Value]
run (IF o1 o2) ((B True):s)  = run o1 s
run (IF o1 o2) ((B False):s) = run o2 s
run NOP s                    = s

data StackType =
    AnyStack
  | IntValueAnd  StackType
  | BoolValueAnd StackType

{-@ reflect stackType @-}
stackType :: [Value] -> StackType
stackType []         = AnyStack
stackType ((I _):xs) = IntValueAnd (stackType xs)
stackType ((B _):xs) = BoolValueAnd (stackType xs)

{-@ reflect isValid @-}
isValid :: Op -> StackType -> Bool
isValid (IF lhs rhs)  (BoolValueAnd s)              = isValid lhs s && isValid rhs s
isValid NOP           _                             = True
isValid _             _                             = False
```

yields the following:

```
**** LIQUID: ERROR :1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 1962 column 8523: Sort mismatch at argument #1 for function (declare-fun is-Main.B (Main.Value) Bool) supplied sort is Int"
```

**Comment by zgrannan** [comment]
Ahh I just realized the liquid flag `--no-adt` appears to fix this... so I am not blocked anymore.

**Comment by ranjitjhala** [comment]
I was about to suggest that, still don't close it, because this is a
recurring thing and
I'd like to get to the bottom of it.

**Comment by nikivazou** [comment]
Yes, that is indeed strange... I though I fixed that by switching to the new encoding of data types in SMT...

**Comment by nikivazou** [comment]
Apparently, the `--no-adt` flag prevents proving totality in the original file. 
@zgrannan I am on trying to fix what goes wrong with the `--no-adt` flag off. 

For reference, this is an example that cannot be proved total with `no-adt` flag on: https://gist.github.com/nikivazou/37d1526a0027172e3ceb0d5ceb3ef635

(@ranjitjhala if I remember correctly, we were looking in the past to find an example what cannot be proved safe with the `no-adt` flag on)
