### ISSUE TITLE
Measure not generating suitable invariant

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1775]
(via @plredmond) LH seems to fail on the below

```haskell
{-@ measure listLength @-}
{-@ listLength :: xs:_ -> {n:Nat | n == len xs } @-}
listLength :: [a] -> Int
listLength [] = 0
listLength (_x:xs) = 1 + listLength xs

-- PASSES if we explicitly add the below 
{- invariant {xs:[a] | len xs == listLength xs} -}

{-@ foo :: xs:_ -> {ys:_ | listLength xs == len ys } @-}
foo :: [a] -> [a]
foo xs =  xs
```

Why is the `measure` definition not automatically generating the `invariant` (and only sticking to the `listLength v >= 0` ?)

/cc @nikivazou

**Comment by nikivazou** [comment]
I suspect because it turns into invariants only parts that do not contain free symbols, which actually looks the proper behaviour to me.

**Comment by ranjitjhala** [comment]
That seems too conservative? If the measure signature is:

```
{-@ f :: x:[a] -> {v:b | p} @-}
```

we should get an `invariant {x:[a] | p [v := f(x)]}` ?

**Comment by nikivazou** [comment]
This is an easy edit, let me PR it.

**Comment by ranjitjhala** [comment]
Thanks, though I suspect some test will break and will remind us why we didn’t do it the above way 🤪

**Comment by facundominguez** [comment]
Is this another resolved issue?

**Comment by ranjitjhala** [comment]
Hmm @nikivazou can you confirm?

**Comment by facundominguez** [comment]
Closing since it seems resolved.
