### ISSUE TITLE
Abstract Refinements getting lost?

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1790]
Why does this work

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1604390637_20296.hs

but this below one where `Pair a b` is polymorphic fail?

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1604421264_20433.hs

**Comment by jwiegley** [comment]
This version fails too: https://gist.github.com/e2b1c21f85c4cd3269f5a43021f58771

It's polymorphic, but not in a detail that I'm using.

**Comment by ranjitjhala** [comment]
Ok, looks like this has to do with some parsing oddity.

Even with the first example where I defined 

```haskell
data IntPair = IntPair Int Int
```

It turned out in the signature for `nubFst`

- Writing `IntPair<p>` *worked* but
- Writing `(IntPair)<p>` *failed* !

I was baffled by this of course, but then remembered this was due to 
some strangeness with parsing, and when you want to apply the refinement 
to the WHOLE constructed type, you must use `<< p >>` (!!!)

So the following works just fine:

```haskell
import Prelude hiding (filter)

{-@
filter :: forall <p :: a -> Bool, w :: a -> Bool -> Bool>.
                 {y :: a, b::{v:Bool<w y>|v} |- {v:a|v == y} <: a<p>}
                 (x:a -> Bool<w x>) -> xs:[a] ->
                 {ys:[a<p>] | len ys <= len xs}
@-}

filter :: (a -> Bool) -> [a] -> [a]
filter f (x : xs)
  | f x = x : filter f xs
  | otherwise = filter f xs
filter _ [] = []

{-@ data IntPair a b = IntPair { pFirst :: _, pSecond :: _ } @-}
data IntPair a b = IntPair { pFirst :: a, pSecond :: b }
  deriving (Eq)

{-@ nubFst ::
      forall <p :: IntPair a b -> Bool>.
      xs:[IntPair a b <<p>>] ->
      {ys:[IntPair a b <<p>>]<{\x y -> ncmp x y}> | len ys <= len xs}
      / [len xs] @-}
nubFst :: (Eq a) => [IntPair a b] -> [IntPair a b]
nubFst [] = []
nubFst (x : xs) = x : nubFst (filter (ncmp x) xs)

{-@ inline ncmp @-}
ncmp :: (Eq a) => IntPair a b -> IntPair a b -> Bool
ncmp x y = pFirst x /= pFirst y
```

**Comment by jwiegley** [comment]
Is there a version of this that works for direct tuple types like `(a, b)`?

**Comment by jwiegley** [comment]
It appears that `Tuple a b` is already a type alias within LH, and allows this syntax to do what I wanted.

**Comment by ranjitjhala** [comment]
Ah, perfect, I did this:

```
type IntPair a b = (a, b)

{-@ measure pFirst @-}
pFirst :: (a, b) -> a
pFirst (x, _) = x
```

**Comment by nikivazou** [comment]
> Is there a version of this that works for direct tuple types like `(a, b)`?

Pairs (and tuples of any arity) indeed come by default with abstract refinements, like lists!
