### ISSUE TITLE
Diff mode ignores errors

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1796]
In https://github.com/ucsd-progsys/lh-plugin-demo/tree/diff

Running `cabal v2-build` the first time produces the error, but the second time the error goes away...
 
The post-plugin LH is somehow _ignoring_ the previously saved errors, which makes this mode  unusable...

**Comment by ranjitjhala** [comment]
Fixed by https://github.com/ucsd-progsys/liquidhaskell/pull/1791

**Comment by facundominguez** [comment]
Hello, can this issue be closed?

**Comment by ranjitjhala** [comment]
Oops I thought the comment would automatically close it!
