### ISSUE TITLE
Symbol (FromJSON instance for Stats) not found

### ISSUE THREAD

**Issue by sertel** [ucsd-progsys/liquidhaskell#1797]
I'm trying to debug a problem that I have with termination metrics. My plan was to extend the error message a little bit to get some more details (`RefType.makeLexReft on invalid input.`). Therefore, I forked the repository and build the sources locally. 

The `liquidhaskell` code base builds successfully. 
However, when I try to build my project with references to the local `liquidhaskell` code base, I get the following error:
```
../libHSliquidhaskell-0.8.10.2.1-1maLBrwlml3Hd1Kt5AlRay-ghc8.10.2.dylib, 5): Symbol not found: _liquidzmfixpointzm0zi8zi10zi2zi1zm1kdSPJ58FSlD6PvFOZZeDXA_LanguageziFixpointziSolverziStats_zdfFromJSONStats_closure
```
I wonder if this has something to do with the latest commit (46c284e55f7e37cccc2f7c568c5ca4abaffbb633) that moved these Aeson instances from `src/Language/Haskell/Liquid/UX/DiffCheck.hs` to `src/Language/Fixpoint/Solver/Stats.hs`.

**Comment by ranjitjhala** [comment]
Hmm that is possible! Did you do `--recursive` clone, so you also have the latest fixpoint?

**Comment by ranjitjhala** [comment]
also, sometimes I get these odd `Symbol not found` errors and can clear them just by doing a `stack clean` or `cabal clean`

**Comment by sertel** [comment]
I managed to make it work. Apparently, this seems to be a stack problem (https://github.com/commercialhaskell/stack/issues/3559). Currently, the only way around this problem seems to be to sweep all the stack caches.
