### ISSUE TITLE
Strengthen Invariant in subtyping

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#182]
It would be nice to strengthen using "invariants" in any position of the subtyping, not just binders. See for example:

https://github.com/ucsd-progsys/liquidhaskell/tree/master/tests/todo/invlhs.hs

which works if we do 

  let z = e in z

but not if we leave it as
   
  e

Because in the former case, the invariant gets added when we add z into the environment.

**Comment by nikivazou** [comment]
fixed at e32be38

**Comment by ranjitjhala** [comment]
AWESOME!!!
