### ISSUE TITLE
Totality checker fails with exhaustive pattern match

### ISSUE THREAD

**Issue by jvanbruegge** [ucsd-progsys/liquidhaskell#1839]
The following snippet is seen (correctly) as total by GHC, but LiquidHaskell fails:
```haskell
data Foo = One | Two | Three

foo :: Foo -> Foo -> ()
foo One _ = ()
foo _ One = ()
foo Two _ = ()
foo _ Two = ()
foo Three Three = ()
```
Playground link: https://liquid-demo.programming.systems/index.html#?demo=permalink%2F1618069549_32372.hs

**Comment by ranjitjhala** [comment]
Very interesting and surprising as the LH checker is a “refinement” of GHCs
... wonder what’s going on in the core...

**Comment by nikivazou** [comment]
@jvanbruegge you can add the `{-@ LIQUID "--max-case-expand=5" @-}` pragma to make it pass. 

There needs to be some expansion of the internal core to make the checking (here totality checking) precise and this leads to code explosion, so LH by default does not expand all the cases. 
This flag is not required if your top-level case is on only one argument (as happens in most of the cases).

**Comment by jvanbruegge** [comment]
Yes indeed that works, but I also see the code explosion ^^
```
[3 of 7] Compiling Seq

**** LIQUID: SAFE (3763 constraints checked) ***********************************
[4 of 7] Compiling Proofs.Snoc [Seq changed]

**** LIQUID: SAFE (24 constraints checked) *************************************
[5 of 7] Compiling Proofs.Cons [Seq changed]

**** LIQUID: SAFE (30 constraints checked) *************************************
```

**Comment by nikivazou** [comment]
Yeap, I am quite sure we could do something smart to avoid the explosion, but till then my suggestion is to use one top-lever case split.
