### ISSUE TITLE
Nuke liquid-ghc-prim and liquid-base from this repo

### ISSUE THREAD

**Issue by adinapoli** [ucsd-progsys/liquidhaskell#1846]
As we discussed numerous times in the past, now we have moved `liquid-base` and `liquid-ghc-prim` into their own repo so that they can evolve separately from `liquidhaskell` itself:

* https://github.com/liquidhaskell/liquid-base
* https://github.com/liquidhaskell/liquid-ghc-prim

We should now modify this project so that we don't vendor `liquid-base` and `liquid-ghc-prim` from this repo, but rather we use the uploaded versions of Hackage. The risk of not doing that is that of course people might accidentally contribute to the versions committed into this mega repo, with the other versions falling behind / drifting apart.

**Comment by googleson78** [comment]
We can't straightforwardly do this, because `liquid-base`s on hackage are pinned to their corresponding `base` versions, but there is no `liquid-base-4.14.3.0`, which would correspond to `base-4.14.3.0` which is in our stack resolver. So maybe there need to be some hackage releases first?

**Comment by facundominguez** [comment]
`liquid-base` and `liquid-ghc-prim` have been incorporated into `liquidhaskell` since this ticket was created.
