### ISSUE TITLE
Produce human-readable constraint environment dumps

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#1848]
So far using `--savequery`, or inspecting `.smt2` files, or pretty printing [constraints](https://github.com/ucsd-progsys/liquidhaskell/blob/d4744993ff8214e24a22a1f99e48660f1abe221c/src/Language/Haskell/Liquid/Constraint/Types.hs#L157) yields the environment of formulas in which verification conditions are checked. I expect this to be useful to catch missing facts from the environment when LH rejects a constraint. However, all of these dumping mechanisms produce output that is hard to read for a few reasons.

1. Auxiliary definitions hide constants and other conditions. For instance

        lq_anf$##7205759403792799627##d1zd := {lq_tmp$x##138 : GHC.Prim.Int# | lq_tmp$x##138 == 0}

        lq_anf$##7205759403792799628##d1ze :=
            {lq_tmp$x##141 : GHC.Types.Int | lq_tmp$x##141 == lq_anf$##7205759403792799627##d1zd}

    In this example the bindings are as informative as the shorter

        lq_anf$##7205759403792799628##d1ze := { x : GHC.Types.Int | x == 0 }

2. The variable names are too long, as also illustrated with the previous example.

3. Conditions require simplification to understand them

        lq_anf$##7205759403792799629##d1zf := {lq_tmp$x##150 : GHC.Types.Bool | lq_tmp$x##150 <=> x##a1yp >= 
        lq_anf$##7205759403792799628##d1ze}

        lq_anf$##7205759403792799630##d1zg :=
             {lq_tmp$x##196 : GHC.Types.Bool | (lq_tmp$x##196 <=> x##a1yp >= lq_anf$##7205759403792799628##d1ze)
                                                                        && lq_tmp$x##196 == lq_anf$##7205759403792799629##d1zf
                                                                        && lq_tmp$x##196}

    Which is as informative as

        lq_anf$##7205759403792799630##d1zg := {v : GHC.Types.Bool | v && x##a1yp >= 0 }

4. In some dumps, formulas in a condition appear duplicated

        lq_anf$##7205759403792804861##d2VD : {lq_tmp$x##516 : Language.Stitch.LH.Type.Ty |
            [(Language.Stitch.LH.Type.isFunTy lq_tmp$x##516);
             ((Language.Stitch.LH.Type.isFunTy lq_tmp$x##516) <=> (Language.Stitch.LH.Type.isFunTy lq_tmp$x##516));
             (lq_tmp$x##516 = ds_d2V3);
             ((Language.Stitch.LH.Type.isFunTy lq_tmp$x##516) <=> (Language.Stitch.LH.Type.isFunTy lq_tmp$x##516));
             ((lqdc##$select##Language.Stitch.LH.Type.TFun##1 lq_tmp$x##516) = b##a26y);
             ((lqdc##$select##Language.Stitch.LH.Type.TFun##2 lq_tmp$x##516) = ds_d2Ve);
             ((Language.Stitch.LH.Type.funArgTy lq_tmp$x##516) = ds_d2Ve);
             ((Language.Stitch.LH.Type.isFunTy lq_tmp$x##516) <=> true);
             (lq_tmp$x##516 = (Language.Stitch.LH.Type.TFun ds_d2Ve b##a26y));
             ((lqdc##$select##Language.Stitch.LH.Type.TFun##1 lq_tmp$x##516) = b##a26y);
             ((lqdc##$select##Language.Stitch.LH.Type.TFun##2 lq_tmp$x##516) = ds_d2Ve);
             ((Language.Stitch.LH.Type.funArgTy lq_tmp$x##516) = ds_d2Ve);
             ((Language.Stitch.LH.Type.isFunTy lq_tmp$x##516) <=> true);
             ((Language.Stitch.LH.Type.isFunTy lq_tmp$x##516) <=> (Language.Stitch.LH.Type.isFunTy lq_tmp$x##516))]}

5. Environments include apparently irrelevant bindings. The environment of a constraint like

        ||- {v : GHC.Types.Int | v > x} <: {v : GHC.Types.Int | v > 1}

    includes bindings for `GHC.Base.return`, `strLen`, `len`, `GHC.Num.+`, `GHC.Classes.>=` and others.

 After looking at the code for a while, the only practical solution that I'm finding for (1), (2), and (3), is to post-process the environments to try to eliminate some of the redundancy. But I'm making this issue in case people more familiar with LH can come up with other ideas. (4) and (5) look like they could be addressed either with post-processing the environment or maybe by avoiding the redundancy when constructing the environment to begin with.

**Comment by ranjitjhala** [comment]
Hi @facundominguez -- I think this would be excellent! Avoiding (4) and (5) up front is tricky for various reasons so I find the post-processing idea more promising. Look at 

[`Language.Fixpoint.Solver.Sanitize`](https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Solver/Sanitize.hs)

which does a bunch of pre-processing steps; it would be awesome if you can add some of (1)-(5) to this step?

**Comment by facundominguez** [comment]
I'm finding puzzling that sometimes bindings appear defined multiple times in the environment

See below how `d1zg` is defined multiple times with ids 40, 41, 42, 45 and 46. Moreover, note that not all of these bindings are identical. For instance, 42 has an extra negation.

Now, if this is a valid environment, then what binding is meant when `d1zg` appears in a formula?

A single constraint environment does reference multiple bindings of `d1zg` sometimes. Maybe I should just consider them equivalent to a single binding that contains the conjunction of all of them (?)

```
bind 40 lq_anf$##7205759403792799630##d1zg : {lq_tmp$x##165 : bool | [(lq_tmp$x##165 <=> (x##a1yp >= lq_anf$##7205759403792799628##d1ze));
                                                                      (lq_tmp$x##165 = lq_anf$##7205759403792799629##d1zf)]}
bind 41 lq_anf$##7205759403792799630##d1zg : {lq_tmp$x##167 : bool | [(lq_tmp$x##167 <=> (x##a1yp >= lq_anf$##7205759403792799628##d1ze));
                                                                      (lq_tmp$x##167 = lq_anf$##7205759403792799629##d1zf)]}
bind 42 lq_anf$##7205759403792799630##d1zg : {lq_tmp$x##167 : bool | [(lq_tmp$x##167 <=> (x##a1yp >= lq_anf$##7205759403792799628##d1ze));
                                                                      (lq_tmp$x##167 = lq_anf$##7205759403792799629##d1zf);
                                                                      (~ (lq_tmp$x##167))]}
bind 43 lq_anf$##7205759403792799631##d1zh : {lq_tmp$x##172 : int | [(lq_tmp$x##172 = 0)]}
bind 44 lq_anf$##7205759403792799632##d1zi : {lq_tmp$x##175 : int | [(lq_tmp$x##175 = (lq_anf$##7205759403792799631##d1zh  :  int))]}
bind 45 lq_anf$##7205759403792799630##d1zg : {lq_tmp$x##196 : bool | [(lq_tmp$x##196 <=> (x##a1yp >= lq_anf$##7205759403792799628##d1ze));
                                                                      (lq_tmp$x##196 = lq_anf$##7205759403792799629##d1zf)]}
bind 46 lq_anf$##7205759403792799630##d1zg : {lq_tmp$x##196 : bool | [(lq_tmp$x##196 <=> (x##a1yp >= lq_anf$##7205759403792799628##d1ze));
                                                                      (lq_tmp$x##196 = lq_anf$##7205759403792799629##d1zf);
                                                                      lq_tmp$x##196]}
```

**Comment by facundominguez** [comment]
> Maybe I should just consider them equivalent to a single binding that contains the conjunction of all of them (?)

I'm running with this for now. Which means that I'm prettifying the environments of constraints independently from each other.

[Here's](https://github.com/ucsd-progsys/liquid-fixpoint/compare/develop...facundominguez:fd/prettier-fq) the work in progress. And here is an example output to compare with the conditions discussed in this issue:
```
constraint:
  lhs {VV##F##4 : int | [(VV##F##4 = x##a1yp)]}
  rhs {VV##F##4 : int | [(VV##F##4 >= 0)]}
  id 4 tag [2]
  // META constraint id 4 : test.hs:11:31
  
...

  lq_anf$##7205759403792799630##d1zg : {lq_tmp$x##196 : bool | [(lq_tmp$x##196 <=> (x##a1yp >= 0)); lq_tmp$x##196]}
...
```
I'll be working on further simplifications before submitting a PR.

**Comment by ranjitjhala** [comment]
Hi Facundo,

Sorry have been busy with a paper deadline! Do you have a small code
snippet that illustrates this?

One reason this happens is GHC reuses names, another that pattern matching
"strengthens" the type of a binder.

The semantics IIRC is to take "the most recent binding" -- I think some of
this is dealt with in the "uniqify" pass in the `Sanitize` module in
`liquid-fixpoint` ... ?

**Comment by facundominguez** [comment]
Thanks, will check the uniqify pass.

Here's the example I'm using. It doesn't pass verification, but that is expected. If you look at the .fq file, you should be able to find the duplicated bindings.
```
import Language.Haskell.Liquid.Prelude(choose, liquidAssertB)
import Prelude(Int, IO, (>=), return, (+), (-))

{-@ assert incr :: x:{v: Int | v >= 0} -> {v: Int | v > x} @-}
incr   :: Int -> Int
incr x = x + 1

{-@ myabs :: x:Int -> {v:Int | v > 1 } @-}
myabs :: Int -> Int
myabs x = if x >= 0 then incr x else (0 - x)

main :: IO ()
main = return ()
```

> Sorry have been busy with a paper deadline!

No problem. I have plenty of other things to figure out. Good luck with that!

Update1: I didn't find an obvious unification pass in Sanitize, but there is a `uniq` function in `Language/Fixpoint/Horn/Transformations.hs` which seems to do what you described. I'll dig more.
Update2: Printing the environment after sanitization shows that the duplicated bindings are preserved.

**Comment by facundominguez** [comment]
All of this work has been merged. I'm finding things that can be improved or extended but I rather let that be addressed in new issues.
