### ISSUE TITLE
How do I inspect Liquid Types?

### ISSUE THREAD

**Issue by yanhasu** [ucsd-progsys/liquidhaskell#1853]
The [online demo](http://goto.ucsd.edu:8090/index.html) shows you what type Liquid Haskell infers for identifiers when you hover the mouse over them.

This is great, and I'd like to be able to do it offline too.

Is there a way to ask GHCi for this information?
Currently the only option is to break something nearby and hope that the type I want appears in the error message.

(I'm running LH as a GHC (8.10.4) plugin, in a `cabal v2-repl`, on top of the [old tutorial repo](https://ucsd-progsys.github.io/liquidhaskell-tutorial/))

**Comment by ranjitjhala** [comment]
Hi @yanhasu -- there are various modes for emacs, vim, vscode etc. that do support this -- but they are quite flaky (as various things keep changing in the modes...) The most robust solution is that if your source is in `path/to/file.hs` then inside `path/to/.liquid/file.hs.html` you can see an HTML version of the source that you can just open up in a web browser and then you will get the types as tooltips.

can you let me know if this works for you?

**Comment by yanhasu** [comment]
@ranjitjhala yes it works for me.

Tested on top of the [old tutorial repo](https://github.com/ucsd-progsys/liquidhaskell-tutorial), using both `stack repl` and the [Simple GHC extension](https://marketplace.visualstudio.com/items?itemName=dramforever.vscode-ghc-simple) in VSCode. 
Hover functionality when viewing the generated `.liquid/file.hs.html` is just like the [online demo](http://goto.ucsd.edu:8090/index.html).
(additionally, the file `.liquid/file.hs.cst.html` is generated, which is similar but with less human readable variable names)
