### ISSUE TITLE
Imprecise Pattern-Completeness Checking

### ISSUE THREAD

**Issue by yanhasu** [ucsd-progsys/liquidhaskell#1854]
Pasting the following code:
```
module Peano where

data Peano = Z | S Peano

-- Totality Error
maxP :: Peano -> Peano -> Peano
maxP Z x = x
maxP x Z = x
maxP (S x) (S y) = S (maxP x y)

-- Passes
maxP' :: Peano -> Peano -> Peano
maxP' Z Z = Z
maxP' Z (S x) = S x
maxP' (S x) Z = S x
maxP' (S x) (S y) = S (maxP' x y)

```

in the [online demo](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1625669429_36714.hs) (GHC 8.6.0) highlights all of `maxP` in red with the error:

```
Error: Totality Error
Your function is not total: not all patterns are defined.

HINT: use "--no-totality" to deactivate totality checking.
```

However the patterns for `maxP` *are* complete, and GHC's own pattern-completeness checker (enabled with `-Wall`) is perfectly fine with them.

Perhaps such annoyances could be resolved by querying the GHC pattern checker for cases that the LH totality checker isn't sure about. There might even be an opportunity for code simplification.

**Comment by yanhasu** [comment]
Oops, it seems like this is a duplicate of #1839

**Comment by ranjitjhala** [comment]
Yes it’s strange that GHC is able to prove it safe because LH only checks
when GHC introduces an “irrefutablePatternError” call ... ? Hmm.
