### ISSUE TITLE
LiquidHaskell binary does not work with LinearTypes

### ISSUE THREAD

**Issue by njayinthehouse** [ucsd-progsys/liquidhaskell#1887]
Running the binary for liquidhaskell-0.8.10.2 on any file containing a pragma for the LinearTypes language extension returns this:
```
» liquid <File>.hs
liquid: Unsupported extension: LinearTypes
```
Is there some interaction between liquid types and linear types that prevents us from using liquid haskell to verify properties of programs which have linear types?

**Comment by nikivazou** [comment]
This is a `ghc` error and `liquidhaskell-0.8.10.2` uses `ghc-8.10`. 
Do you know if `ghc-8.10` allows this language extension? Because, compiling with `ghc-8.10` gives me exactly the same error `Unsupported extension: LinearTypes` while `ghc-9.0.1` accepts it.

**Comment by ranjitjhala** [comment]
in short we need to use GHC 9 + Plugin to compile with linear types?
