### ISSUE TITLE
LH demo is down

### ISSUE THREAD

**Issue by yanhasu** [ucsd-progsys/liquidhaskell#1900]
The online demo for LiquidHaskell is offline at the moment.

The [currently-deployed website](https://ucsd-progsys.github.io/liquidhaskell/)  has two separate links to the online demo:
* The "play" link in the nav-bar points to <https://liquid-demo.programming.systems/index.html>, which gives a "Service Unavailable" error from the Apache web server
* The "try online in your browser" link in the description points to <http://goto.ucsd.edu:8090/index.html>, which Firefox says it can't connect to

This has been the case for several days now.

(regarding the fact that we have two different links, this is fixed #1862 and #1896)

**Comment by ranjitjhala** [comment]
Hmm there's something odd going on -- because both sites seem to be up and working now?

**Comment by yanhasu** [comment]
They are working for me too now -- very strange!

**Comment by ranjitjhala** [comment]
The server has been quite strange of late unfortunately ... :-/
