### ISSUE TITLE
Abstract refinements: Unsound behaviour using lists and helper function

### ISSUE THREAD

**Issue by lbartl** [ucsd-progsys/liquidhaskell#1907]
LH checks the following code and marks it as SAFE:
```haskell
{-@ foldr' :: forall a b <inv :: [a] -> b -> Bool>.
              (a -> b -> b) -> b<inv []> -> xs:[a] -> b<inv xs>
  @-}
foldr' op b = go
  where
    {-@ go :: forall <inv :: [a] -> b -> Bool>.
              xs:[a] -> b<inv xs>
      @-} 
    go []    = b
    go (h:t) = op h (go t)
```

But it's not safe:
```haskell
{-@ length :: zs:[a] -> {v:_ | v == 42*(len zs)} @-}
length = foldr' (\_ n -> n + 1) 0
```
The `length` function obviously returns `len zs` and not `42*(len zs)` but LH checks the code and marks it as SAFE.

Context:
I was trying to write a `foldr` using Bounded Refinements.
I came up with the following signature (inspired by the ICFP'15 paper):
```haskell
{-@ foldr' :: forall a b <inv :: [a] -> b -> Bool, step :: a -> b -> b -> Bool>.
              {xs :: [a], x :: a, acc :: b<inv xs> |- b<step x acc> <: b<inv (x:xs)>}
              (x:a -> acc:b -> b<step x acc>) -> b<inv []> -> xs:[a] -> b<inv xs>
  @-}
```
Unfortunately it didn't work because LH treated `(x:xs)` as a cast (maybe you could fix this, too).
So I came up with my own list type, but it also didn't work (I don't know why, maybe this is a bug or maybe my signature is wrong?).

Then I introduced a helper function like the above `go` and it worked. To test if this was really the solution, I removed the `step` thing and came up with the code above. Because LH checked the code and marked it as SAFE, I wrote the above `length`.

**Comment by lbartl** [comment]
I think the problem is, that the abstract refinements have the same name (`inv`). If you change one name, LH reports an error.

**Comment by ranjitjhala** [comment]
Wow, this is surprising! Thanks for pointing this out @hanswurst862 ! 

I *think* what's happening is some confusion with the names so that

1. The `forall` in the inner `go` gets instantiated to `false` at the application 
   `go t` thereby giving `go t` the type `{b|false}`, and yet
   
2. In the `[]` case, it magically uses the type of `b` from the environment (which has type `b<inv[]>` to 
    "prove" the post-condition.

The  fix is to make sure the abs-refs are alpha-renamed of course, @nikivazou  does this sound plausible? 

Do you think you can do it?

**Comment by ranjitjhala** [comment]
To be more concrete -- I think even when parsing the type sigs, we should give each bound abs-ref (here `inv`) a distinct name, and that should be that. (I suspect the checker implicitly assumes these names are distinct, leading to this bug.)

**Comment by ranjitjhala** [comment]
I started a fix which works for this, lets see what CI says.
