### ISSUE TITLE
type for `dropWhile`

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#191]
I was wondering if there exists any type for `dropWhile` that makes the below code safe:

~~~
foo xs x = if x `elem` xs
                then tail . dropWhile (`notElem` [x]) $ xs
                else xs
~~~

ie., proving that the result of `dropWhile` is not empty.

The above code appears in [hscolour/Language/Haskell/HsColour/Anchors.hs](https://github.com/nikivazou/hscolour/blob/master/Language/Haskell/HsColour/Anchors.hs#L161)

**Comment by nikivazou** [comment]
@ranjitjhala is closing this issue using bounded refinement types via 

https://github.com/ucsd-progsys/liquidhaskell-tutorial/issues/36

**Comment by ranjitjhala** [comment]
While this should not have been an "issue" in the first place, I dont see how it is actually solved by that trick above (which just says that the `dropWhile` returns an empty list OR a list whose head satisfies `p`)

**Comment by ranjitjhala** [comment]
IMO the code above should be rewritten as

```
foo xs x = case dropWhile ... of 
                   [] -> xs 
                   ys -> tail ys 
```

anyway, seems just as efficient!
