### ISSUE TITLE
REST blocks indefinitely

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#1912]
I've got a minimal reproducer for the strange behavior I was finding when verifying stitch-lh with the latest changes to Liquid Haskell.

Inserting print statements it looks as if the function `Language.Fixpoint.Solver.PLE.evalREST` from `liquid-fixpoint` never returns.

I'm sharing a branch with a new failing test [here](https://github.com/ucsd-progsys/liquidhaskell/compare/develop...facundominguez:fd/rest-bug). This version is from before the interpreter-related changes in `liquid-fixpoint`.

Trivial changes make the verification pass, so your best chance to reproduce it is using `nix` and `stack`. But perhaps you can make it work with `cabal-install` too.

I run the test with either
```
stack exec liquidhaskell -- tests/pos/Rest.hs
```
or
```
stack exec -- $(stack path --dist-dir)/build/test/test -p Tests.Macro.unit-pos.Rest.hs
```

As one would expect, I can reproduce the failure with the generated `Rest.hs.bfq` file
```
stack exec fixpoint -- --eliminate=some --rewriteaxioms tests/pos/.liquid/Rest.hs.bfq
```

The file `Rest.hs.fq` can't be fed to `fixpoint` because of parsing errors. Though maybe I could work on fixing the pretty printer if necessary.

**Comment by zgrannan** [comment]
I will investigate this, but it will probably be next week.

**Comment by facundominguez** [comment]
Thanks!

**Comment by facundominguez** [comment]
I was debugging this a bit today. Turns out that `deANF` sometimes fails to terminate. The algorithm tries to apply a substitution on an expression until a fixpoint is achieved:
```Haskell
deANF ctx = subst'
  where
    subst' ee =
      let ee' = subst su ee
      in if ee == ee'
          then ee
          else subst' ee'
```
This strategy doesn't terminate because the substitutions that are produced sometimes contain mutually referencing substitutions like
```
[lq_anf$##7205759403792805575##d379:=e##a1Qi]
[lq_anf$##7205759403792805583##d37h:=
   Language.Stitch.LH.Check.Cons##lqdc##$select##Language.Stitch.LH.Check.Cons##1
      lq_anf$##7205759403792805584##d37i
]
[lq_anf$##7205759403792805584##d37i:=
   Language.Stitch.LH.Check.Cons lq_anf$##7205759403792805583##d37h ctx0##a1Qg
]
```
I think our options are either to break this mutually referencing substitutions or to use a strategy as [undoANF](https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Solver/EnvironmentReduction.hs#L563). The later would have the advantage of making only one pass over the expressions.

**Comment by ranjitjhala** [comment]
Interesting! Can we switch to `undoAnf` and see if it has any dire
consequences?

**Comment by facundominguez** [comment]
I'm trying it in [this work-in-progress branch](https://github.com/ucsd-progsys/liquid-fixpoint/compare/fd/undoanf).
