### ISSUE TITLE
tests/pos/anftest.hs fails verification without the empty export list

### ISSUE THREAD

**Issue by Fizzixnerd** [ucsd-progsys/liquidhaskell#1954]
As stated, if the line `module AnfWierd () where` is changed to `module AnfWierd where`, the module no longer passes verification.

**Comment by ranjitjhala** [comment]
Am AFK right now so can’t see specific test but in general this edit
changes what is exported, which changes the “default” spec for a function,
which can affect verification…

**Comment by Fizzixnerd** [comment]
#### /tests/pos/:
- `anish1.hs`
- `BST.hs`
- `cmptag0.hs`
- `comprehensionTerm.hs`
- `cut00.hs`
- `dataConQuals.hs`
- `datacon0.hs`
- `deptup.hs`
- `deptup1.hs`
- `deptup3.hs`
- `deptupW.hs`
- `div000.hs`
- `ex1.hs`
- ... and about 100 others.

Each have similar issues, with export lists limiting the scope of verification.

`comprehensionTerm.hs`, `cut00.hs`, `div000.hs` additionally have the property that one of the exported values fails verification _without_ the export list, which seems even more problematic to me at first glance.

However, if this is desired behavior then I suggest closing this issue.

EDIT: I find this behavior highly unintuitive, however.

**Comment by Fizzixnerd** [comment]
Closing, as this behavior seems intended.
