### ISSUE TITLE
Remove -Wno-name-shadowing from liquidhaskell.cabal

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#1962]
In a similar spirit to https://github.com/ucsd-progsys/liquid-fixpoint/issues/538, enabling this warning would help preventing some mistakes. But please, let me know if there are reasons to keep it disabled.

**Comment by tbidne** [comment]
If no one else is interested, I'd be happy to get started on this.

**Comment by ranjitjhala** [comment]
That would be fantastic, thank you so much!
