### ISSUE TITLE
Ambigous module name Prelude

### ISSUE THREAD

**Issue by PhilippRonchen** [ucsd-progsys/liquidhaskell#1985]
I built Liquid from Source using Stack.

Running liquid from command line on a file I get the following error:

liquid: Language.Haskell.Liquid.Prelude: Ambiguous module name ‘Prelude’:
  it was found in multiple packages:
  base-4.14.3.0 liquid-base-4.14.3.0

The error occurs both when I import Prelude explicitly and when I do not import Prelude explicitly. I can hide Prelude using the NoImplicitPrelude but then Liquid does not recognize prelude functions and types.

I have not specified base as as in a dependency in package.yaml or my cabal file (however I added liquid-base as a dependency).

**Comment by ranjitjhala** [comment]
1. Have you tried `stack exec -- liquid ...` ? 

2. Hmm have you tried the `plugin` mode as described here?
 https://github.com/ucsd-progsys/lh-plugin-demo

**Comment by PhilippRonchen** [comment]
Yes, I get the same the error when I
a) clone https://github.com/ucsd-progsys/lh-plugin-demo and build it with "stack build"
b) Run stack exec -- liquid ... on a source file

Command : stack exec -- liquid src/Demo/Lib.hs
Error message:
liquid: Demo.Lib: Ambiguous module name ‘Prelude’:
  it was found in multiple packages:
  base-4.14.1.0 liquid-base-4.14.1.0

**Comment by PhilippRonchen** [comment]
I can work around the problem by using both "NoImplicitPrelude" and "PackageImports" and importing the Liquid versions of Prelude, Containers explicitly like so:
~~~
import "liquid-base" Prelude
import "liquid-containers" Set
~~~

Then the program builds and type-checks correctly. Have not yet discovered if this approach will lead to any unexpected errors in bigger projects.

**Comment by ranjitjhala** [comment]
Hi Philipp,

In the plugin mode, you _only_ run `stack build` (or `cabal v2-build`).

That runs LH on the source files on its own, there is no need to then run
`liquid` separately.

If you want to recheck a file after editing, you just rerun `stack build
(or `cabal v2-build`).

Does that work?

Ranjit.
