### ISSUE TITLE
Provide more accurate timing measures for benchmarks

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#2000]
The times given from `-ddump-timings` in the `Renamer/typechecker` phase differ a lot in my experiments from the total time that it takes to run LH.

There is a `withTiming` function in the GHC API that we could use to report the time it takes to run the plugin
```
withTiming :: MonadIO m
           => DynFlags     -- ^ DynFlags
           -> SDoc         -- ^ The name of the phase
           -> (a -> ())    -- ^ A function to force the result
                           -- (often either @const ()@ or 'rnf')
           -> m a          -- ^ The body of the phase to be timed
           -> m a
```
Stealing from GHC the invocation for the "Renamer/typechecker" pass, it could be
```
withTiming dflags
              (text "LiquidHaskell"<+>brackets (ppr this_mod))
              (const ()) $ ... main hook ...
```

**Comment by ranjitjhala** [comment]
This is a great find!

**Comment by Fizzixnerd** [comment]
https://www.haskell.org/ghc/blog/20190924-eventful-ghc.html more information which may prove useful.

**Comment by Fizzixnerd** [comment]
I'm looking into this issue.
