### ISSUE TITLE
The output from `--time-binds` option has been disabled

### ISSUE THREAD

**Issue by michaelborkowski** [ucsd-progsys/liquidhaskell#2006]
@ljz-1109 and I have noticed that `--time-binds` is no longer producing any output at any level of verbosity. But it's still actually running because the runtimes are significantly longer with it enabled because there's no parallelism. 

This commit 29a4ec8a3421e395549da4247961e8bd030803e0 by @Fizzixnerd called `Change the test framework to Cabal` disabled the output of --time-binds in `Language.Haskell.Liquid.Misc` among a lot of other changes.

Before we had:
https://github.com/ucsd-progsys/liquidhaskell/blob/b1f4ba70ea54decda87449076dfde23bb44ffbab/src/Language/Haskell/Liquid/Misc.hs#L39-L48

Now the line with `printf` has been commented out:
https://github.com/ucsd-progsys/liquidhaskell/blob/29a4ec8a3421e395549da4247961e8bd030803e0/src/Language/Haskell/Liquid/Misc.hs#L40-L50

Looks like this might have slipped into the commit accidentally?

**Comment by facundominguez** [comment]
> Looks like this might have slipped into the commit accidentally?

It is possible, @Fizzixnerd may be able to confirm. Still, if recovering that back doesn't make CI fail we could merge it straight away.
