### ISSUE TITLE
`map (f . g) == map f . map g` incorrectly considered safe 

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#2070]
When trying to prove `map (f . g) == map f . map g`, I came at the following program that passes verification but it shouldn't. I think it is considered safe because `false` is in the environment (assigned to a liquid variable occurring in the binding of `xs` in `lemmaMapMap`).

```
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--save" @-}

import Prelude hiding (map)

{-@ reflect map @-}
map :: (a -> b) -> [a] -> [b]
map f [] = []
map f (x:xs) = f x : map f xs

{-@ reflect c @-}
c :: (b -> c) -> (a -> b) -> a -> c
c f g x = f (g x)

{-@ reflect h @-}
h :: [a] -> [a]
h [] = []
h (x:xs) = x : x : xs

{-@
lemmaMapMap
  :: f:_
  -> g:_
  -> xs:_
  -> { map (c f g) xs == h (map f (map g xs)) }
@-}
lemmaMapMap :: (b -> c) -> (a -> b) -> [a] -> ()
lemmaMapMap f g xs = ()

main :: IO ()
main = return ()
```

**Comment by ranjitjhala** [comment]
Does this happen if you remove the “main” ?

**Comment by facundominguez** [comment]
It doesn't! What's up with defining main?

**Comment by ranjitjhala** [comment]
(Ignore main - that was irrelevant)

what’s going on here is the the xs:_ in the signature says “synthesize the
strongest type for xs such that this code type checks” which LH synthesize
“false” (as the function is not called anywhere.)

Perhaps we should have a different annotation that says “fill in the GHC
type and don’t synthesize refinements”?

**Comment by nikivazou** [comment]
Does not directly apply to this code, but it applies in the title of the issue. 
@facundominguez if you actually want to check the equality on functions, things will get very complicated: https://nikivazou.github.io/static/Haskell22/equality.pdf

**Comment by facundominguez** [comment]
I should have paid more attention to the meaning of the underscores. Yes, it would be nice not having to spell the Haskell types a second time. In the meantime, I'm closing this.

> if you actually want to check the equality on functions, things will get very complicated

Thanks Niki. I'm struggling with it and considering what to do actually.
