### ISSUE TITLE
Why are abstract refinements attached to data types

### ISSUE THREAD

**Issue by andrewthad** [ucsd-progsys/liquidhaskell#2075]
This is not a issue, just a question about an implementation decision. In the Abstract Refinement Types paper and in the LH implementation, abstract refinements have to be attached to data types. As a simple minimal example:

```
{-@
  data Collection a <p :: a -> Bool>
    = Branch (Collection <p> a) (Collection <p> a)
    | Leaf a<p>
@-}

data Collection a = Branch (Collection a) (Collection a) | Leaf a

{-@ smallNumbers :: Collection Int <{\x -> x >= 0 && x < 100}> @-}
smallNumbers :: Collection Int
smallNumbers = Branch (Leaf 50) (Leaf 20)
```

However, it should be possible to accomplish the same thing by allowing abstract refinements to be passed around in functions. For example (LH rejects this, but it illustrates the point):

```
data Collection a = Branch (Collection a) (Collection a) | Leaf a

{-@ reflect allSatisfy @-}
allSatisfy : (a -> Bool) -> Collection a -> Bool
allSatisfy pred collection = case collection of
  Leaf x -> pred x
  Branch y z -> allSatisfy pred y  && allSatisfy pred z

{-@ smallNumbers :: {c :: Collection Int | allSatisfy (\x -> x >= 0 && x < 100) c} @-}
smallNumbers :: Collection Int
smallNumbers = Branch (Leaf 50) (Leaf 20)
```

LH cannot reflect `allSatisfy` (fails error message about something not being in scope), which I think is by design.

What I'm wondering though is why the datatype-oriented design was chosen over a design that pushes abstract refinements out of datatypes and into reflected recursive functions. I think that they both work and have similar expressive power. Is there an advantage in type inference/synthesis that the datatype-oriented approach offers, or was it considered ergonomically better for users, or is there a more fundamental problem with trying to do this kind of thing without the tight coupling to datatypes?

Thanks in advance for any insights into this.

**Comment by nikivazou** [comment]
There is an advantage in more precise type checking when information (here abstract refinements) is part of the data type definition. The way refinement types of LH work when you do case analysis (resp apply data constructors) you open (resp use) all the information embedded in the definition of the type. So you can type check programs without having to case split on your `allSatisfy`-style function. 

But, there is also the historic reason that abstract refinements were introduced in LH before reflection, so putting in the logic functions like `allSatisfy` was not an option back then.

**Comment by ranjitjhala** [comment]
As Niki points out abstract refinements predated reflection by 5+ years and
more importantly we wanted to see how far we could get without adding
recursive functions to the specs because those fall outside the SMT
decidable fragment.

Put another way, if you can express your properties with abstract
refinements then checking is a lot easier and more predictable, as you are
using the datatype constructors (easy) instead of arbitrary recursion
(hard).

**Comment by andrewthad** [comment]
Thanks for the insights. I didn't realize that reflection was a relatively late addition to LH since it has existed the whole time that I've known about LH. I can see how having to do case splitting  on arbitrary reflected refinements would complicate things.

I've also thought of a situation where the user experience is worse. With the datatype-oriented approach, you could have a `first` function (crashes on empty collection):

    first :: Collection <p> Int -> Int<p>

And since `p` is attached to the argument, the user does not have to mention it explicitly when calling the function. However, with the hypothetical reflected function, we would need  something like this:

    first :: (p :: a -> Bool) -> {c :: Collection Int | allSatisfy p c} -> (out :: a | p out)

Here, `p` cannot be inferred, and it must be supplied by the user every time `first` is called.

Anyway, I think I've got the answer I was looking for. Thanks!

**Comment by andrewthad** [comment]
Adding a link to https://github.com/ucsd-progsys/liquidhaskell/issues/1264 for cross reference. There, Ranjit provides similar historical context and describes the difference between measures and reflected functions.
