### ISSUE TITLE
--no-adt breaks some data definitions

### ISSUE THREAD

**Issue by plredmond** [ucsd-progsys/liquidhaskell#2089]
This data definition doesn't check when `--no-adt` is enabled:
```haskell
{-@
data Pair a b = Pair a b @-}
data Pair a b = Pair a b
```

**Comment by plredmond** [comment]
I can't find documentation about `--no-adt` so I don't know whether this is a bug, or if I'm just doing something that's not allowed with that flag.

**Comment by plredmond** [comment]
Giving names to the fields in the datatype refinement corrects the issue.

```haskell
{-@
data Pair a b = Pair {foo::a, bar::b} @-}
data Pair a b = Pair a b

**Comment by nikivazou** [comment]
Yes, refinements on data types needs the second syntax, so I would not consider it a bug. 

BTW, --no-adt states that the Haskell data definitions will not be turned into SMT data types and it is used for, e.g., not inductive data types or GADTs.

**Comment by facundominguez** [comment]
This reminds me that since https://github.com/ucsd-progsys/liquid-fixpoint/pull/569, PLE can fail if `--no-adt` is enabled as it doesn't generate equations for constructor tests and selectors, it relies on the SMT solver to know what selectors and constructor tests are.

**Comment by plredmond** [comment]
Assuming PLE is off, would enabling `--no-adt` cause LH to be unable to see equalities through record-update syntax? 

```haskell
data X a = X { field :: a }

upd :: X a -> a -> X a
upd x a = x { field = a }
```

I have a bunch of proofs where I had to inline (to the proof) uses of record-update syntax like the above. It seems from this discussion that enabling `--no-adt` might be the cause.

**Comment by ranjitjhala** [comment]
Am not quite following the question .. can you make the two
Scenarios explicit? Eg file 1 where some proof fails, file 2 where it
succeeds by “inlining”?

**Comment by plredmond** [comment]
I don't have time to produce a minimal example right now (which would probably clarify the issue significantly), but I have loads of examples of this in the cbcast-lh repo. Here's a function with three "why does this step require PLE?" comments: https://github.com/lsd-ucsc/cbcast-lh/blob/84b4e63e728fa169cd790ecf62f73d7d198817c1/lib/CBCAST/Transitions.hs#L151

This is getting off-topic though, so I'm happy to take this to email. If that's preferred, feel free to close this issue.

**Comment by ranjitjhala** [comment]
Ah got it, so there are some proofs with this "field update" code that
break without PLE?

That is odd. Lets take to email, I expect staring at the CORE will explain
why,
perhaps it's not the "field update" stuff but the functions called inside
it?

**Comment by plredmond** [comment]
Yes, let's go to email.
