### ISSUE TITLE
"The sort Natural is not numeric" when using a newtype over Natural

### ISSUE THREAD

**Issue by gergoerdi** [ucsd-progsys/liquidhaskell#2093]
I am importing the following definitions (among other things):

```
newtype Unsigned (n :: Nat) = U Natural
instance KnownNat n => Num (Unsigned n)
instance Ord (Unsigned n)
```

and then I try to make a refinement on `Unsigned 4` using its ordering and its `Num`-ness:

```
type Hex = Unsigned 4
{-@ type Digit = {v : Hex | v <= 9 } @-}
```

This, so far, is accepted by LH. But when I then try to use `Digit`, it breaks down:

```
{-@ x :: Digit @-}
x :: Hex
x = 3
```

```
    • Illegal type specification for `Main.x`
    Main.x :: {VV : (Clash.Sized.Internal.Unsigned.Unsigned GHC.Types.Int) | VV <= 9}
    Sort Error in Refinement: {VV : GHC.Natural.Natural | VV <= 9}
    The sort GHC.Natural.Natural is not numeric
  because
The sort GHC.Natural.Natural is not numeric
    Just
    • 
   |
18 | {-@ x :: Digit @-}
   |          ^^^^^^
```

**Comment by nikivazou** [comment]
You can add 

```
{-@ embed GHC.Natural.Natural as int @-}
``` 

to tell LH to treat `GHC.Natural.Natural ` as numeric, since you are doing numeric operations with them

**Comment by gergoerdi** [comment]
Adding 

```
{-@ embed GHC.Natural.Natural as int @-}
```

results in a new error message:

```
  elaborate solver elabBE 22 "lq_anf$##7205759403792934203##dAzN" {lq_tmp$x##148 : GHC.Integer.Type.Integer | [(lq_tmp$x##148 = 3)]} failed on:
      lq_tmp$x##148 == 3
  with error
      The sort GHC.Integer.Type.Integer is not numeric
  because
Cannot unify GHC.Integer.Type.Integer with int in expression: lq_tmp$x##148 == 3 
  because
Elaborate fails on lq_tmp$x##148 == 3
  in environment
      lq_tmp$x##148 := GHC.Integer.Type.Integer
```

so I thought I'd just add `Integer` as another numeric type, following your example:

```
{-@ embed GHC.Integer.Type.Integer as int @-}
```

but then when I try

```
{-@ x :: Digit @-}
x :: Hex
x = 3
```

again, I get this new error:

```
    Liquid Type Mismatch
    .
    The inferred type
      VV : (Clash.Sized.Internal.Unsigned.Unsigned GHC.Types.Int)
    .
    is not a subtype of the required type
      VV : {VV : (Clash.Sized.Internal.Unsigned.Unsigned GHC.Types.Int) | VV <= 9}
```

(BTW I am really weirded out by how `Unsigned 4` is rendered as `Clash.Sized.Internal.Unsigned.Unsigned GHC.Types.Int`, it suggests there's an "off-by-kind" error lurking somewhere)

**Comment by gergoerdi** [comment]
Hmm, it seems if I import instances from the `Prelude`, then things go through with just the `Natural` embedding specified by hand:

```
import Clash.Prelude -- For Unsigned etc.
import Prelude () -- To make LH happy

{-@ embed GHC.Natural.Natural as int @-}

type Hex = Unsigned 4
{-@ type Digit = {v : Hex | v <= 9 } @-}

{-@ x :: Digit @-}
x :: Hex
x = 3
```

**Comment by nikivazou** [comment]
@gergoerdi this passes for me: https://github.com/ucsd-progsys/liquidhaskell/blob/347b933c52931debe63f47f6c3b1aa4082ede4a6/tests/pos/T2093.hs

Are you on the develop branch?

**Comment by gergoerdi** [comment]
I think this might have been PEBKAC -- I was using Clash's `Clash.Prelude` instead of the default `Prelude`, and the latter seems to be overridden in `liquid-base`. With instances from (`liquid-base`'s) `Prelude` imported, my program works now.
