### ISSUE TITLE
LH plugin prevents other TC plugins from firing?

### ISSUE THREAD

**Issue by gergoerdi** [ucsd-progsys/liquidhaskell#2095]
Let's say I have the following Haskell code (note: no LH annotations anywhere):

```
{-# LANGUAGE GADTs, DataKinds, TypeOperators, KindSignatures #-}
module Main where

import GHC.TypeLits

data Unary (n :: Nat) where
    Zero :: Unary 0
    Succ :: Unary n -> Unary (n + 1)

foo :: Unary n -> Unary n -> Unary n
foo Zero Zero = Zero
foo (Succ xs) (Succ ys) = Succ (foo xs ys)
```

This module is rejected by GHC (at least as of 8.10.7), because it cannot figure out the right arithmetic proofs:

```
/home/cactus/prog/haskell/liquid-haskell/bugs/plugin-conflict/src/main.hs:12:40: error:
    • Could not deduce: n2 ~ n1
      from the context: n ~ (n1 + 1)
        bound by a pattern with constructor:
                   Succ :: forall (n :: Nat). Unary n -> Unary (n + 1),
                 in an equation for ‘foo’
        at src/main.hs:12:6-12
      or from: n ~ (n2 + 1)
        bound by a pattern with constructor:
                   Succ :: forall (n :: Nat). Unary n -> Unary (n + 1),
                 in an equation for ‘foo’
        at src/main.hs:12:16-22
   |
12 | foo (Succ xs) (Succ ys) = Succ (foo xs ys)
   |                                        ^^
```

We can then use [`ghc-typelits-natnormalise`](https://hackage.haskell.org/package/ghc-typelits-natnormalise) to help out the GHC typechecker: using `-fplugin GHC.TypeLits.Normalise` makes the above program pass the typechecker.

However, if we then *also* turn on `-fplugin LiquidHaskell`, we are suddenly back to square one, and GHC again rejects the above program with the same error message about `n2 ~ n1`.

**Comment by mboes** [comment]
The offending line might be [here](https://github.com/ucsd-progsys/liquidhaskell/blob/dc35e4e20340b46af7b759931e2305a91dc73b91/src/Language/Haskell/Liquid/GHC/Plugin.hs#L244-L249). The LH plugin gets called by the type checker, but it then itself calls the type checker at some point. To avoid an infinite loop, LH first disables all plugins. That seems overly blunt to me - would be better to selectively disable the LH plugin only.

**Comment by gergoerdi** [comment]
Lol I ended up encountering this again (#2366) in a completely different context (Clash vs. Mu), didn't remember I have come across this two years ago, and now I fixed it -- "good first issue" indeed :)
