### ISSUE TITLE
Consider only supporting a single GHC version

### ISSUE THREAD

**Issue by mboes** [ucsd-progsys/liquidhaskell#2116]
I didn't find a GHC support policy documented anywhere. I propose changing it as follows, and documenting it.

Liquid Haskell claims to support GHC versions 8.6 through to 9.0. The cost of this support is many pre-processor directives and much code duplication in the thin compatibility layer found in `src-ghc/Liquid/GHC/API.hs` but also throughout the codebase. This makes the code harder to read, harder to maintain, and complicates porting GHC to new versions. Adding support for newer GHC versions would be easier if there no longer was a need to adapt the code in ways that minimize the amount of code duplication necessary to continue supporting older versions.

_One way to fix this problem would be to support only one GHC version at any given time._ The upside is more maintainable code and easier porting, and for users marginally more features and big fixes shipped since Liquid Haskell developer time is a limited resource. The downside is Liquid Haskell users stuck on old GHC versions don't get the benefit of bug fixes and new features, unless these get backported to previous versions of Liquid Haskell.

Keep in mind that Liquid Haskell relies heavily on the GHC API throughout its codebase. The API itself provides no backwards compatibility guarantees, in practice changes fairly drastically from version to version, and comes with no release notes explaining the changes and how to adapt to them. In short, there is no release management around the GHC API. The API exposes the internal guts of GHC to any external consumer, who uses them the way any GHC-internal module would. In effect, heavy users of a large cross-section of the GHC API, like Liquid Haskell does, are effectively part of GHC itself. Right now the code happens to live in a repo separate to GHC's, with its own release cadence. If the repos were merged, then newer Liquid Haskell would only support newer GHC anyway - as in the above proposed policy.

**Comment by mboes** [comment]
Anecdotally, I'm trying to port Liquid Haskell to GHC 9.2, and the API churn with 9.0 is significant. 9.0 itself introduced many breaking changes (reorganized module hierarchy). We can expect similar churn in later releases. Keeping up with this churn would be easier without the backward compatibility constraint.

**Comment by ranjitjhala** [comment]
Dear @mboes - first, thank you!!! It would be amazing to port to the 9.2 api! Second, I wholly agree in fact I’d move it up to 8.8 (not 8.6). Would be glad to get a PR with that text in a particular file - maybe we can add that policy to thr README? Ranjit.
