### ISSUE TITLE
Panic when inlining a recursive function

### ISSUE THREAD

**Issue by mgritter** [ucsd-progsys/liquidhaskell#2125]
I understand from the documentation that recursive functions shouldn't be inlined.  But I made the mistake of typing "inline" instead of "reflect" on a recursive function, which produces a GHC panic:

```
   |
10 | maximum (x:[]) = x
   | ^^^^^^^^^^^^^^^^^^...
ghc: panic! (the 'impossible' happened)
  (GHC version 8.10.1:
	[Cyclic type alias definition for `Maximum.member`
    The following alias definitions form a cycle:
    .
    * `Maximum.member` (defined at: src/Maximum.hs:26:12-17)]
```

This would ideally be a more specific error message stating that recursive functions can't be inlined.

Reproduction case:
```
module Maximum where

import Language.Haskell.Liquid.ProofCombinators
import Prelude hiding (maximum)

{-@ LIQUID "--reflection" @-}

{-@ maximum :: {xs:[a] | len xs > 0 } -> a @-}
maximum :: Ord a => [a] -> a
maximum (x:[]) = x
maximum (x:xs) = let m = maximum xs in
  if x > m then x else m

{-@ inline maximum @-}
```

**Comment by nikivazou** [comment]
That is a great suggestion! Thanks!

**Comment by Genlight** [comment]
I think this issue is solved, i.e. I tried to recreate it and the error msg (for the inline case) was: 
```bash
/home/master/lhTest/src/Maximum.hs:8:12: error:
    • Cyclic type alias definition for `Maximum.maximum`
    The following alias definitions form a cycle:
    .
    * `Maximum.maximum` (defined at: src/Maximum.hs:8:12-19)
    • 
   |
8 | {-@ inline maximum @-}
   |   
```
while the reflect case passed the LH check. 

tested on GHC 9.0.2 with the according LH version.

**Comment by facundominguez** [comment]
I can't reproduce either. @mgritter, please let us know if this is still an issue for you in more recent versions.
