### ISSUE TITLE
`liquid-base` 4.15.0.0 on Hackage, but Git has 4.14.3.0

### ISSUE THREAD

**Issue by NicolasT** [ucsd-progsys/liquidhaskell#2127]
The latest release of `liquid-base` on Hackage is 4.15.0.0 ([link](https://hackage.haskell.org/package/liquid-base-4.15.0.0)). However, at the time of writing, the version of `liquid-base` in Git (currently `develop` is at 492cd97c18f4037e241f26b281a79acbf59b7bff) is 4.14.3.0 ([link](https://github.com/ucsd-progsys/liquidhaskell/blob/492cd97c18f4037e241f26b281a79acbf59b7bff/liquid-base/liquid-base.cabal#L3)). Since there doesn't seem to be some corresponding tag of the version found on Hackage, is it safe to use said version?

**Comment by ranjitjhala** [comment]
I hadn’t noticed that, thanks! Yes should be ok!
