### ISSUE TITLE
Publish liquid-base 4.14.3 to Hackage

### ISSUE THREAD

**Issue by mboes** [ucsd-progsys/liquidhaskell#2130]
Hackage carries liquid-base versions 4.14.1.0 (for GHC 8.10.2) and 4.15.0.0 (for GHC 9.0.1). But neither versions work when compiling with GHC 8.10.7. Version 4.14.3.0 exists in the Git history, but not on Hackage. It should be published on Hackage.

**Comment by amigalemming** [comment]
It seems that the version of `liquidhaskell` must match the one of the GHC release exactly. That is, GHC-9.0.2 requires `liquidhaskell-0.9.0.2.*`.

**Comment by facundominguez** [comment]
For the historical record, I uploaded `liquid-base-4.14.3` and added a tag for `liquidhaskell-0.8.10.7.1` in the repo (I couldn't find a tag for `liquidhaskell-0.8.10.7`).
