### ISSUE TITLE
Unhelpful error when not using liquid-base

### ISSUE THREAD

**Issue by mboes** [ucsd-progsys/liquidhaskell#2131]
In a Cabal package with `base` as a dependency, not `liquid-base`, pretty much all snippets in https://liquid.kosmikus.org/ fail with a very obscure elaboration error similar to the following:

```
**** LIQUID: ERROR: Sorry, unexpected panic in liquid-fixpoint! ****************

/tmp/Bug.hs:1:1: error:
    Uh oh.
    elaborate solver elabBE 15 "lq_anf$##7205759403792802718##d2n4" {lq_tmp$x##63 : GHC.Prim.Addr# | [(lq_tmp$x##63 = "main")]} failed on:
        lq_tmp$x##63 == "main"
    with error
        Cannot unify GHC.Prim.Addr# with Str in expression: lq_tmp$x##63 == "main" 
      because
    Elaborate fails on lq_tmp$x##63 == "main"
    in environment
        lq_tmp$x##63 := GHC.Prim.Addr#
  |
1 | module Bug where
  | ^
```

The fix is to depend on `liquid-base`, not `base`. But that is not obvious from the above error message.

This affects standalone invocations as well. For example,

```
$ ghc -fplugin=LiquidHaskell /tmp/Bug.hs
# Fails
$ ghc -package liquid-base -fplugin=LiquidHaskell /tmp/Bug.hs
# Succeeds
```

Incidentally, I would assume that LH is usable even without liquid-base for users that only need simple specs. That does not seem to be the case currently.

**Comment by facundominguez** [comment]
`liquid-base` contains a directive `embed GHC.Prim.Addr#    as Str`, which probably is necessary to avoid the error in question.

`liquid-base` has been removed now. The `liquidhaskell` plugin now includes all of the specs that used to be in `liquid-base` so they are harder to skip.
