### ISSUE TITLE
Hole `_` causes proof of a contradiction

### ISSUE THREAD

**Issue by RobinWebbers** [ucsd-progsys/liquidhaskell#2141]
# Context
Consider the following contradication:
```Haskell
{-@ type Contradict = {_:() | false} @-}

{-@ contradiction :: a -> Contradict @-}
contradiction :: a -> ()
contradiction _ = ()
```
LH rightfully rejects the program. Great!

# The Problem
Now consider the following function, where the only difference is that the polymorphic type `a` is replaced by the hole `_` inside the LH definition. (The type doesn't need to be polymorphic to trigger this bug btw)
```Haskell
{-@ shouldError :: _ -> Contradict @-}
shouldError :: a -> ()
shouldError _ = ()
```
Suddenly, Liquid Haskell see's no problem in accepting this definition. When I look at the output towards the SMT solver, the culprit can be found in the following line:
```
(assert (and false b$36$$35$$35$102 b$36$$35$$35$108 b$36$$35$$35$530))
```
Disregarding all the bindings, the key part here is the `(and false`, which of course is always unsatisfiable. This in turn always satisfies the proof. For the first example, it correctly contains `(and true`. This is as far as I can tell the only difference between the two outputs to the SMT solver.

This bug also triggers for other, more complex functions where I used a hole `_` btw. This was the simplest example where I could recreate the bug.

# Solution
I have no clue where the problem originates from, but perhaps you do? I am willing to patch this, but I have no clue where to start. A nudge in the right direction would be great!

**Comment by nikivazou** [comment]
I do not believe this is a soundness problem that needs to be fixed. 
The semantics of `_` is there exists a type that satisfies the hole. In your case the inferred type is `{v:a | false}`. 
So, Liquid Haskell is doing the correct thing. To confirm that, I hope, if you try to call `shouldError` with any (non void) value, you should get an error.

**Comment by RobinWebbers** [comment]
Ah, I wasn't aware that `_` had this semantic. I thought it was just a simple shorthand to omit writing a type. :sweat_smile: I'll close the issue now
