### ISSUE TITLE
Wrong pinned commit liquid-fixpoint in liquidhaskell v9.0.2-final 

### ISSUE THREAD

**Issue by zlonast** [ucsd-progsys/liquidhaskell#2150]
In [liquidhaskell v9.0.2-final](https://github.com/ucsd-progsys/liquidhaskell/tree/v9.0.2-final) liquid-fixpoint commit is 11a773a08e66cea13d8ddbf203ca32bd5cea97b2, 
but [liquid-fixpoint v9.0.2-final](https://github.com/ucsd-progsys/liquid-fixpoint/tree/v9.0.2-final) is a45f8fe9f6ac2533228f9149926bf884a3525945

**Comment by facundominguez** [comment]
Fixed. Thanks @zlonast!
