### ISSUE TITLE
higherorder flag and inference

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#2155]
The following example passes (concretely, the loop invariant is inferred) when the reflection flag is off, but fails when it is on. 

Since nothing is reflected, I did not expect that turning on the reflection flag would make any difference... (observed by @felixridoux). 

```
{-@ LIQUID "--maxparams=3" @-}
{- LIQUID "--reflection" @-}
module Example where 
{-@ euclDiv :: x:Nat -> { q:Nat | q >=1 } -> (p1::{v:Int |  0 <= v  && v < q },{p2:Int | p1 + p2 * q == x } ) @-} 
euclDiv :: Int -> Int -> (Int,Int)
euclDiv x q  = f x 0
   where      
      f :: Int -> Int -> (Int,Int)
      f r k = 
         if r < q 
            then (r, k) 
            else f (r-q) (k+1)
```

**Comment by facundominguez** [comment]
`--reflection` implies `--higherorder`.

Enabling `--higherorder` instead of `--reflection` also causes verification to fail. I'm changing the title to the more specific flag.

**Comment by ranjitjhala** [comment]
switching on `--reflection` disables all KVAR inference IIRC

**Comment by nikivazou** [comment]
So, it is intentional and I am closing the issue. 

(Now I remember we discussed in the past, it is kind of not the predictable behaviour, but can definitely see why it is needed to speed up proofs.)
