### ISSUE TITLE
Has project changed its structure recently?

### ISSUE THREAD

**Issue by avanov** [ucsd-progsys/liquidhaskell#2214]
Hi,

It's been a few years since I worked with LH last time, and now I see that the `develop` branch has significant structural changes to the project. There's no `liquid-base` and I'd like to know how one would approach bumping constraints introduced by `liquid-base` dependencies in their projects (namely for experimentations with GHC 9.4). Where could I find a detailed description of the changes?

**Comment by facundominguez** [comment]
Hello @avanov. [This post](https://www.tweag.io/blog/2023-06-22-lh-assumption-imports/) explains the motivation for the changes. The specifics of configuring LH are in [the install page](https://ucsd-progsys.github.io/liquidhaskell/install/) of the documentation.

If playing with GHC 9.4, maybe have a look at the upgrade tasks in the [call for sponsors](https://discourse.haskell.org/t/call-for-sponsors-first-class-liquid-haskell/6973#tg-1).

Please, let me know if you have more questions.

**Comment by avanov** [comment]
@facundominguez Thank you!
