### ISSUE TITLE
Reasoning steps with inequality

### ISSUE THREAD

**Issue by josedusol** [ucsd-progsys/liquidhaskell#2220]
Hello. Module `Equational` provides the `==.` operator to do equational reasoning. What about inequaility?.

For example, suppose we want to prove something like:

`{-@ filterLength ::  p:(a -> Bool) -> l:List a -> { length (filter p l) <= length l } @-}`

Then the reasoning chain would involve `==.` steps but also "<=" steps. Is this possible?

**Comment by ranjitjhala** [comment]
Hi! Odd -- there certainly used to be -- see these:

https://github.com/ucsd-progsys/liquidhaskell/blob/369a7a63b97d313db4ea558f4847ebd3f82edce6/tests/benchmarks/popl18/lib/Proves.hs#L101-L117

I think you can just write your own following that template.

So

```haskell
{-@ (<=.) :: x:a -> y:{a | x  <=  y} -> {v:a | v == y} @-}
(<=.) :: a -> a -> a 
_ ==. y = y 
{-# INLINE (<=.) #-} 
```

**Comment by josedusol** [comment]
Thanks @ranjitjhala . But unfortunately, i can't use the proof combinator with an intermediate justification:

```
module Test where
import Language.Haskell.Liquid.Equational
import Prelude hiding (length,filter)

{-@ (<=.) :: x:a -> y:{a | x <= y} -> {v:a | v == x} @-}
(<=.) :: a -> a -> a 
x <=. y = x 
{-# INLINE (<=.) #-} 

{-@ reflect length @-}
{-@ length :: [a] -> Int @-}
length :: [a] -> Int
length = \l -> case l of { [] -> 0; x:xs -> length xs + 1 }  

{-@ reflect filter @-}
{-@ filter :: (a -> Bool) -> [a] -> [a] @-}
filter :: (a -> Bool) -> [a] -> [a]
filter = \p l -> case l of { [] -> []; x:xs -> case p x of { False -> filter p xs; True -> x:filter p xs }}

{-@ assume leqZero :: n:Nat -> { 0 <= n } @-}
leqZero :: Int -> Proof
leqZero n = ()

{-@ filterLength ::  p:(a -> Bool) -> l:[a] -> { length (filter p l) <= length l } @-}
filterLength :: (a -> Bool) -> [a] -> Proof  
filterLength p [] =
      length (filter p [])             
      ? filter p []
  ==. length []                        
      ? length []  
  ==. 0                               
      ? leqZero (length [])    -- TYPE ERROR if present
  <=. length []               
  *** QED 
filterLength p (x:xs) = undefined
```
The intermediate justification `? leqZero (length [])` raises
```
error:
    * Couldn't match type `Int' with `()'
      Expected: Proof
        Actual: Int
    * In the second argument of `(<=.)', namely `length []'
      In the second argument of `(?)', namely
        `leqZero (length []) <=. length []'
      In the first argument of `(***)', namely
        `length (filter p []) ? filter p [] ==. length [] ? length [] ==. 0
           ? leqZero (length []) <=. length []'
   |
37 |   <=. length []
```
From my understanding, the justification should be optional just like in ` ==.`, but sometimes it may be neccesary.

**Comment by ranjitjhala** [comment]
Ah that's just a matter of the "parsing/precedence" see this

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1694706430_580.hs

**Comment by ranjitjhala** [comment]
in fact, adding 

`infixl 3 <=.` 

to the file makes it work directly.

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1694706535_584.hs
