### ISSUE TITLE
LH type aliases are not used in Measures

### ISSUE THREAD

**Issue by csgordon** [ucsd-progsys/liquidhaskell#223]
```
module MeasureAliases where

data T = X
{-@ type Cheese = {v:Int | v > 1 } @-}
-- Cheese works in specifications
{-@ cheeseId :: Cheese -> Cheese @-}
cheeseId :: Int -> Int
cheeseId x = x
{-@ measure something :: T -> Cheese
    something (X) = 3
@-}
```

I know refinements are ignored on measure types, and shorthands for types with lots of refinements are the intended use case for LH type aliases.  So this is more of a feature request than a bug, since you usually shouldn't need shorthand for refinements where refinements are ignored!  But it was certainly surprising to get a GHC error about a missing type on the line for the measure, which isn't actual Haskell code, and it seems nice to be able to use the same LH shorthands any time you're interacting with LH.

**Comment by ranjitjhala** [comment]
fixed a while back.
