### ISSUE TITLE
Are we maintaining the packages that are not included in the project?

### ISSUE THREAD

**Issue by philderbeast** [ucsd-progsys/liquidhaskell#2245]
Are we maintaining the packages that are not included in the project?

https://github.com/ucsd-progsys/liquidhaskell/blob/a54d3289d2fd7336855aafa0feff9182e700e069/cabal.project#L3-L14

```
$ tree -P '*.cabal' --prune
.
├── benchmark-timings
│   └── benchmark-timings.cabal
├── liquid-fixpoint
│   └── liquid-fixpoint.cabal
├── liquidhaskell-boot
│   └── liquidhaskell-boot.cabal
├── liquidhaskell.cabal
├── liquid-parallel
│   └── liquid-parallel.cabal
├── liquid-platform
│   └── liquid-platform.cabal
├── liquid-prelude
│   └── liquid-prelude.cabal
├── liquid-vector
│   └── liquid-vector.cabal
├── scripts
│   ├── plot-benchmarks
│   │   └── plot-benchmarks.cabal
│   ├── plot-performance
│   │   └── plot-performance.cabal
│   └── profiling-driver
│       └── profiling-driver.cabal
└── tests
    ├── benchmarks
    │   ├── base-4.5.1.0
    │   │   └── base.cabal
    │   ├── containers-0.5.0.0
    │   │   └── containers.cabal
    │   ├── hmatrix-0.15.0.1
    │   │   └── hmatrix.cabal
    │   ├── kmeans-0.1.2
    │   │   └── kmeans.cabal
    │   ├── llrbtree-0.1.1
    │   │   └── llrbtree.cabal
    │   ├── popl18
    │   │   └── lib
    │   │       └── prover-ple-lib.cabal
    │   ├── stitch-lh
    │   │   └── stitch-lh.cabal
    │   ├── text-0.11.2.3
    │   │   └── text.cabal
    │   ├── unordered-containers-0.2.1.0
    │   │   └── unordered-containers.cabal
    │   ├── vector-0.10.0.1
    │   │   └── vector.cabal
    │   ├── vector-algorithms-0.5.4.2
    │   │   └── vector-algorithms.cabal
    │   └── xmonad-0.10
    │       └── xmonad.cabal
    └── tests.cabal

26 directories, 24 files
```

I've added `liquidhaskell` as an [Updo example](https://github.com/up-do), saw these other packages and was wondering what to do with them. I've added `./scripts/plot-benchmarks` but there are many others. As we're on `ghc-9.4.7` should we have a `./tests/benchmarks/base-base-4.17.2.0` package?

I think Updo could maybe help with upgrades but thought I'd stop to ask about these packages before trying that out.

**Comment by facundominguez** [comment]
* `benchmark-timings`: This produces csv reports from measures produced by GHC, which are then used by `plot-performance`.
* `scripts/plot-benchmarks`: Haven't use this one. @nikivazou?
* `scripts/profiling-driver`: A wrapper over ghc to profile Liquid Haskell.
* `tests/benchmarks`: These are run for every PR. I would think we want to keep the source code, but tests don't use the .cabal files, and they are not built as packages.

**Comment by philderbeast** [comment]
With `plot-benchmarks`, I'm seeing a warning:

```
Building executable 'plot-benchmarks' for plot-benchmarks-0.2.0.0...

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules
    for ‘plot-benchmarks-0.2.0.0-inplace-plot-benchmarks’ :
        Benchmark Config Parse Plot
```

**Comment by facundominguez** [comment]
@clayrat, any remarks about `scripts/plot-benchmarks`? Is it still needed?

**Comment by clayrat** [comment]
@facundominguez No, I don't think so; I used it as a template to implement the `plot-performance` tool, but decided to keep it around in case somebody else still needed it.

**Comment by facundominguez** [comment]
Hello @philderbeast, should we close this issue? Or would you like to accomplish something in advance?

**Comment by philderbeast** [comment]
Thanks for reviewing the packages, commenting on what they're used for and thanks for deleting `plot-benchmarks` @facundominguez.
