### ISSUE TITLE
Falsity introduced by shadowing symbols of the logic

### ISSUE THREAD

**Issue by jarctan** [ucsd-progsys/liquidhaskell#2319]
I think there is a way to introduce falsity by shadowing names used in the logic. An example:

```Haskell
{-@ LIQUID "--ple"    	@-}

module Test where

import Prelude hiding (not)

not :: Bool -> Bool
not = id

{-@ reflect shouldBeId @-}
shouldBeId :: Bool -> Bool
shouldBeId x = not x

{-@ lemma :: {shouldBeId False} @-}
lemma = ()
```
The .fq file tells us the reflection of `shouldBeId` which is incorrect:
```
define Test.shouldBeId (lq1 : bool) : bool = {((~ (lq1)))}
```

The issue seemingly comes from the `toPredApp` function of `CoreToLogic` which is not matching against the fully-qualified name of symbols, but just against their local name, hence allowing for "puns" to pretend to be the original function. I might have a PR for this soon.

**Comment by facundominguez** [comment]
Fixed in #2327
