### ISSUE TITLE
Failing to use liquidhaskell v9.8.2

### ISSUE THREAD

**Issue by matheussbernardo** [ucsd-progsys/liquidhaskell#2321]
I am trying to get started with liquidhaskell and my build is failing with

`
src/Language/Haskell/Liquid/Parse.hs:1291:8: error: [GHC-88464]
    Variable not in scope:
      fTyConP :: StateT PState (Parsec Void String) FTycon
    Suggested fix:
      Perhaps use one of these:
        data constructor ‘TyConP’ (imported from Language.Haskell.Liquid.Types),
        ‘bTyConP’ (line 479),
        data constructor ‘BTyCon’ (imported from Language.Haskell.Liquid.Types)`
        
        
     Do I need to put liquid-fixpoint in my cabal file?

**Comment by facundominguez** [comment]
Hello @matheussbernardo. Thanks for the report. That was caused by liquidhaskell-0.9.8.2 depending on liquid-fixpoint-0.9.6.3, where it should have been liquid-fixpoint-0.9.6.3.1. I have fixed the dependency on hackage now.

**Comment by matheussbernardo** [comment]
It worked thanks!
