### ISSUE TITLE
Assertion failure in `mkUserLocal`

### ISSUE THREAD

**Issue by gergoerdi** [ucsd-progsys/liquidhaskell#2363]
Given the following input:

```
{-# LANGUAGE NoImplicitPrelude #-}
{-# OPTIONS -fplugin=LiquidHaskellBoot #-}
module TyEq where

data Foo

class Cls a where
    withDef :: a -> Foo

instance (a ~ Foo) => Cls a where
    withDef x = x
```

and a built of GHC with assertions enabled, Liquid Haskell crashes with:

```
[1 of 1] Compiling TyEq             ( input/TyEq.hs, input/TyEq.o )

<no location info>: error:
    ASSERT failed!
  CallStack (from HasCallStack):
    assert, called at compiler/GHC/Types/Id.hs:366:33 in ghc-9.8.2-inplace:GHC.Types.Id
```

The assertion in questin is this one:

```
mkUserLocal :: OccName -> Unique -> Mult -> Type -> SrcSpan -> Id
mkUserLocal occ uniq w ty loc = assert (not (isCoVarType ty)) $
                                mkLocalId (mkInternalName uniq occ loc) w ty
```

So in other words, this goes wrong because it is asked to make an `Id` with the name `lq_anf$##7205759403792794700` and the type `a_ahh ~# Foo`, which is *the* canonical example of a coercion variable type, see the comment above `isCoVarType`:

> Does this type classify a core (unlifted) Coercion?
>
> At either role nominal or representational `(t1 ~# t2)` or `(t1 ~R# t2)`
> See Note _Types for coercions, predicates, and evidence_ in `GHC.Core.TyCo.Rep
>

**Comment by gergoerdi** [comment]
The call in question comes from `Language.Haskell.Liquid.Transforms.ANF`'s `freshNormalVar` by way of `normalize`.

**Comment by gergoerdi** [comment]
Doing the obvious thing and changing the call to `mkUserLocalOrCoVar` makes the assertion failure go away (of course...), but I don't know if that's the right thing to do. Can someone in the know comment on what LH in general does with coercion types?

**Comment by facundominguez** [comment]
I don't know what LH does with coercion types. In the absence of other insights, I would think that it is fine to change the GHC API call as long as the tests continue to pass.

The github history doesn't speak much to me about this call. It is there since 2016 (4b15a33).
