### ISSUE TITLE
Using the reflection annotation without the "--reflection" flag should throw an error

### ISSUE THREAD

**Issue by AlecsFerra** [ucsd-progsys/liquidhaskell#2402]
The following code

```Haskell
{-# Language GADTs #-}

{-@ LIQUID "--ple"                @-}
{-@ LIQUID "--save"               @-}

module Views where

data Three
    = COne
    | CTwo
    | CThree
    deriving Eq

{-@ reflect discrThree @-}
discrThree :: Three -> Bool
discrThree COne = False
discrThree _    = True
```

Will throw this rather unhelpfull error:
```
equations/dpm/Views.hs:14:13: error:
    Illegal type specification for `Views.discrThree`
    Views.discrThree :: lq1:Views.Three -> {VV : GHC.Types.Bool | VV == Views.discrThree lq1
                                                                  && VV == (if is$Views.COne lq1 then false else (if is$Views.CTwo lq1 then true else true))}
    Sort Error in Refinement: {VV : bool | VV == Views.discrThree lq1
                                           && VV == (if is$Views.COne lq1 then false else (if is$Views.CTwo lq1 then true else true))}
    Unbound symbol is$Views.COne --- perhaps you meant: Views.COne ?
    Just reflect
```

An error like `Can't reflect function definitions without enabling the reflect flag` would be clearer on whats the issue

The issue becomes even more confusing as the following
```Haskell
{-# Language GADTs #-}

{-@ LIQUID "--ple"                @-}
{-@ LIQUID "--save"               @-}

module Views where

{-@ reflect id @-}
id :: a -> a
id x = x
```

Won't lead to an error but only silently ignore the reflection annotation

**Comment by facundominguez** [comment]
> Unbound symbol is$Views.COne --- perhaps you meant: Views.COne ?

:wave: This seems to be solved with `--exctdc`.

> Won't lead to an error but only silently ignore the reflection annotation

The reflected function appears in the `.fq` file for me:
```
define Test.id (lq1 : a##aDN) : a##aDN = {(lq1)}
```

Alessio, what behavior would you rather expect in these cases? Turning on `--exactdc` by default has been discussed in some other issues but it is not entirely trivial.

**Comment by AlecsFerra** [comment]
Yeah but if you don't enable the reflection flag PLE is not going to use reflected definitions

**Comment by AlecsFerra** [comment]
I would expect an error stating that you cant reflect functions if you don't have the reflection flag on

**Comment by facundominguez** [comment]
> Yeah but if you don't enable the reflection flag PLE is not going to use reflected definitions

I don't think this is how LH works at the moment. The effect of `--reflection` is to enable more functions to be reflected, but it isn't needed to reflect `id`.

**Comment by AlecsFerra** [comment]
Ah
