### ISSUE TITLE
Unable to use proofcombinators library

### ISSUE THREAD

**Issue by iirekm** [ucsd-progsys/liquidhaskell#2453]
I wanted to `import Language.Haskell.Liquid.ProofCombinators` in order to use more advanced proofs (e.g. ` -> Proof`). Unfortunately when I add `proofcombinators` library which seems to contain this import, I get cabal conflicts. And no wonder why - `proofcombinators` wasn't updated since 2018 and uses legacy versions of dependencies.

**Comment by iirekm** [comment]
Partial workaround (so this library can be skipped):
```
{-@ _check :: {x: Bool | x} @-}
_check :: Bool
_check = 1 == 2
```

**Comment by facundominguez** [comment]
:wave: I don't know a `proofcombinators` library, but there is [liquid-prelude](https://hackage.haskell.org/package/liquid-prelude) which is supposed to work with liquidhaskell.

**Comment by iirekm** [comment]
Thanks, indeed. When you type `ProofCombinators` in Google, the first result is this broken library, not the valid one.

**Comment by facundominguez** [comment]
I discovered I was added as a maintainer of [proof-combinators](https://hackage.haskell.org/package/proof-combinators), so I marked that package as deprecated now.
