### ISSUE TITLE
Error messages should use original binder names?

### ISSUE THREAD

**Issue by gibiansky** [ucsd-progsys/liquidhaskell#248]
I have the following code:

``` haskell
 {-@ test :: v:Int -> {r:Int | r < 0} @-}
 test     :: Int   -> Int
 test x = x - 1
```

This is clearly an error, since there's nothing that says that `test` should return negative numbers. So I get the following error:

```
   Inferred type
     VV : Int | VV == x - ?a

   not a subtype of Required type
     VV : Int | VV < 0

   In Context
     ?a : Int | ?a == (1  :  int)
     x  : Int
```

This error uses strange new names for the binders, instead of reusing `v` and `r` from the `test` type declaration. A better error would be

```
   Inferred type
     r : Int | r == x - ?a

   not a subtype of Required type
     r : Int | r < 0

   In Context
     ?a : Int | ?a == (1  :  int)
     x  : v:Int
```

The changes that I think would be helpful are that `VV` has been changed to `r` and the type of `x` is now `v:Int` instead of just `Int`. This would make it much easier to debug LiquidHaskell errors, especially when more complex error messages arise.

What do you think? Is this possible / valid / a good idea?

**Comment by ranjitjhala** [comment]
This would be great to do, but seems _very_ hard as GHC doesn't tell us what the original names are by the time we get to core... :(
