### ISSUE TITLE
A couple enhancements I was reminded of during a brief pair-programming LH session

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquidhaskell#267]
- auto-derive types for record selectors using the derived measures
  - ideally even without the liquid data definition, but this would almost certainly cause name-conflicts at the moment
- refer to other top-level values in type signatures, very useful for constants

**Comment by ranjitjhala** [comment]
the former is done; the latter is possible now with `{-@ reflect @-}`
