### ISSUE TITLE
Liquid Haskell doesn't accept Haskell names containing ' (single-quote)

### ISSUE THREAD

**Issue by david-christiansen** [ucsd-progsys/liquidhaskell#273]
In the Idris code base, we have a datatype `Err' :: * -> *` where `Err' t` is a type of error messages containing terms of type `t`. Liquid Haskell couldn't parse the specification:

```
{-@ data Err' [errSize] @-}
```

because of this. @gridaphobe and I worked around the issue by manually applying it at use sites. Additionally, the same thing happened when using the name `n'` in the name of a Liquid Haskell binder.

**Comment by nikivazou** [comment]
Assigned to @Kyly

**Comment by nikivazou** [comment]
Assigned to @Kyly

**Comment by nikivazou** [comment]
Fixed at #397
