### ISSUE TITLE
Feature request: allow .spec files for the file being checked

### ISSUE THREAD

**Issue by david-christiansen** [ucsd-progsys/liquidhaskell#274]
It would be nice to be able to define some of the bulkier LH machinery (size measures, etc) in a separate file, to de-noise the main Haskell file so that only the LH specifications that serve as documentation for the functions are included.

I understand that `.spec` files are used for imports. It would be nice to use them for the module presently being checked.

**Comment by spinda** [comment]
I believe you can already do this.

**Comment by ranjitjhala** [comment]
Good point! I guess we just haven't exercised this for a while but it is how the "prelude" is implemented...
