### ISSUE TITLE
Bad error messages in expression type parameters

### ISSUE THREAD

**Issue by spinda** [ucsd-progsys/liquidhaskell#287]
Expression type parameters can be abused in various ways to produce strange behavior.

You can use them to refer to non-existent type parameters:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1418421723.hs

...which causes a strange crash in plugHoles when used as a function signature:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1418421674.hs

You can also use them to create cyclic type aliases:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1418421814.hs

...which causes a crash in the same area of plugHoles when used as a signature:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1418421839.hs

---

The problem area is in [expandRTApp in Bare.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/Bare.hs#L422), where expression type parameters are handled differently than regular type parameters, and don't have any checks performed on them. [exprArg](https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/Bare.hs#L440) is involved here, which is marked as a "HORRIBLE HACK", likely the cause of the issue.

**Comment by ranjitjhala** [comment]
@spinda are you working on this by any chance? (i.e. will these be addressed by your `Bare` refactoring?)

**Comment by spinda** [comment]
The pull request that I just submitted doesn't address this, but I have partial work done on a future PR that will.
