### ISSUE TITLE
Bad type for measure

### ISSUE THREAD

**Issue by csgordon** [ucsd-progsys/liquidhaskell#296]
This is a regression: this worked fine a couple months ago.

    module BadMeasureType where 
    
    {-@ measure fwd_extends :: IO () -> IO () -> Prop @-}
    {-@ assume fwd_extends_refl :: m:IO () -> {v:Bool | (fwd_extends m m)} @-}
    fwd_extends_refl :: IO () -> Bool
    fwd_extends_refl = undefined

prduces the error:

    LiquidHaskell Copyright 2009-14 Regents of the University of California. All Rights Reserved.
    
    
    **** DONE:  Extracted Core using GHC *******************************************
     
    
    **** DONE:  generateConstraints ************************************************
     
    
    **** START: fixpoint ***********************************************************
     
    
    
    ========================================================
    © Copyright 2009 Regents of the University of California.
    All Rights Reserved.
    ========================================================
    No type for fwd_extends([fix##126#A0; fix##126#A0])z3Pred: error converting fwd_extends(fix##126#A0, fix##126#A0)
    Fatal error: exception Assert_failure("tpGen.ml", 346, 24)
    
    **** DONE:  fixpoint ***********************************************************
     
    
    **** DONE:  solve **************************************************************
     
    
    **** DONE:  annotate ***********************************************************
     
    
    **** CRASH: Unknown Error ******************************************************

**Comment by ranjitjhala** [comment]
Yikes, thanks for pointing it out , will look into it ASAP!

**Comment by ranjitjhala** [comment]
Seems to be fixed now, see `tests/pos/csgordon_issue_296.hs` Thanks @csgordon !
