### ISSUE TITLE
Allow `CoreToLogic` definitions inside type specifications

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#301]
@nikivazou since you've done all the hard work with `CoreToLogic` we should be able to use it in *all* type specifications, not just measure definitions. In short, can you get this to work:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/errmsg.hs

I should not have to write `Set_cup` or `Set_mem` but instead I should be able to write `union` and `intersection` in the type signatures...

**Comment by nikivazou** [comment]
Fixed, see [tests/neg/errmsg.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/neg/errmsg.hs)
