### ISSUE TITLE
Support partial measures

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#303]
Would be nice to have the lifted measures also support partial measures 
(as used to happen in "old-style" measure definitions)...

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/partialmeasure.hs

we *do* support this for "old-style" measures...

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/partialmeasureOld.hs

**Comment by nikivazou** [comment]
fixed! See [tests/pos/partialmeasure.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/partialmeasure.hs)
