### ISSUE TITLE
Inline Code Inside Measure Definitions

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#312]
It would be nice to support *inlining* inside measure definitions. For example, to allow:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/InlineMeasure.hs

**Comment by ranjitjhala** [comment]
Btw, I tried doing the above as a tuple so `mmax :: (Int, Int) -> Int` but that fails for some reason...
Also, am pretty sure it doesn't actually *inline* the definition of `mmax` at the usage site, which is what
we'd really want.

**Comment by ranjitjhala** [comment]
@nikivazou -- Btw, just noticed we can use `where` (and hence, presumably) `let` inside measure functions.  Nice!

**Comment by ranjitjhala** [comment]
Hmm. Actually, `if-then-else` in lifted measures does not work, we really want it to be "inlined" which is not happening.

**Comment by ranjitjhala** [comment]
Ideally, we'd want to allow you to do something like the below, where:

1. You can write & lift ordinary Haskell functions e.g. `max1`
2. You can use `max1` inside data definitions,
3. You can use `max1` inside other measure definitions,
4. All of the above works via *inlining* -- much like the bare expansion thing.

We can imagine a variant of `measure` called `inline` if that makes it easier.

```
{-@ 
data AVK k v = Leaf | Node { key :: _, val :: _ , lt  :: _ , rt  :: _  
, ht :: {v:Int | v = max1 (height lt) (height rt)}
                           }
@-}

{-@ measure max1 @-}
max1 x y = 1 + if x > y then x else y

{-@ measure height @-}
height                  :: AVL k v -> Int
height (Node _ _ l r _) = max1 (height l) (height r)
height _                = 0
```

**Comment by nikivazou** [comment]
Interesting, so `max1` should not be marked as `measure` but something like `macro` or `inline`. 

What do you mean `if-then-else` does not work? In your `InlineMeasures.hs` examples `foo` works fine.

**Comment by gridaphobe** [comment]
I think `max1` should be marked as a measure, but inlined as @ranjitjhala suggests. (I think that would do away with the need for expression aliases, btw)

**Comment by nikivazou** [comment]
But, `measures` have clear semantics (ie they behave as axioms) that `max1` will not have.

**Comment by gridaphobe** [comment]
@nikivazou I'm not sure I follow, are you concerned about the use of class methods in `max1`? If so, I would assume that we would just map `+` and `>` to their logical equivalents, after which `max1` can certainly be axiomatized. I guess that would make it a bit ad-hoc, but there are only a handful of symbols we'd need to look for :/

Also, you must already be doing this, e.g. for lifting `length` to a measure.

**Comment by ranjitjhala** [comment]
Ok, sorry. Looks like the if-then-else *IS* working properly. thanks!

**Comment by ranjitjhala** [comment]
No @nikivazou  is not worried about classes etc. but the fact that measures are things that yield strengthened data constructors (of course, not *entirely* true e.g. the measures for  `ByteString`)
but still I get the idea.

There are two things going on: INLINING functions and MEASURES and best to keep the notions apart...

**Comment by nikivazou** [comment]
@ranjitjhala should I close this? It is address in #325
