### ISSUE TITLE
Cannot Debug this Error (!)

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#313]
See:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/baffled.hs

I am TOTALLY stumped by what is going on. The cases seem symmetric. 
I don't know why the left case (mickey) is fine but the right case (mouse) is not.

Anyway, doing these kinds of things seems IMPOSSIBLY hard at the moment.

Help!

**Comment by gridaphobe** [comment]
@ranjitjhala can we consider this fixed now?

**Comment by ranjitjhala** [comment]
Yes. I guess. :)

On Wed, Jan 21, 2015 at 11:09 AM, Eric Seidel <notifications@github.com>
wrote:

> @ranjitjhala <https://github.com/ranjitjhala> can we consider this fixed
> now?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/313#issuecomment-70900746>
> .
>



-- 
Ranjit.
