### ISSUE TITLE
Diff check crashes with mysterious error

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#314]
See this:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/diff-crash.hs

(Run it twice to see the crash.)

**Comment by gridaphobe** [comment]
here's an even simpler version https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/diff-crash-simple.hs

**Comment by gridaphobe** [comment]
Note that adding an explicit (Haskell) type-signature (for isEven or isOdd in my example, or for insL or insR in yours) prevents the crash.

**Comment by gridaphobe** [comment]
This is quite interesting.

Without the explicit type-signatures, GHC generates the following Core

```
ds_d10E =
  \ (@ a_a103)
    ($dNum_a104 :: GHC.Num.Num a_a103)
    ($dEq_a105 :: GHC.Classes.Eq a_a103) ->
    letrec {
      isOdd_aID =
        \ (ds_d10B :: a_a103) -> ...

      isEven_aIB =
        \ (ds_d10y :: a_a103) -> ...
    } in
    (isEven_aIB, isOdd_aID)

Foo.isOdd =
  \ (@ a_a10i)
    ($dNum_a10j :: GHC.Num.Num a_a10i)
    ($dEq_a10k :: GHC.Classes.Eq a_a10i) ->
    case ds_d10E @ a_a10i $dNum_a10j $dEq_a10k
    of _ [Occ=Dead] { (_ [Occ=Dead], isOdd_aID) ->
    isOdd_aID
    }

Foo.isEven =
  \ (@ a_a107)
    ($dNum_a108 :: GHC.Num.Num a_a107)
    ($dEq_a109 :: GHC.Classes.Eq a_a107) ->
    case ds_d10E @ a_a107 $dNum_a108 $dEq_a109
    of _ [Occ=Dead] { (isEven_aIB, _ [Occ=Dead]) ->
    isEven_aIB
    }
```

and LH subsequently dies when it can't find any location info for `ds_d10E`.

With an explicit type-signature, however, GHC generates

```
Rec {
Foo.isOdd =
  \ (ds_dXl :: GHC.Types.Int) -> ...

Foo.isEven =
  \ (ds_dXp :: GHC.Types.Int) -> ...
end Rec }
```

No intermediate tuple of functions, no crash.

**Comment by gridaphobe** [comment]
fixed in 964976b

**Comment by simonpj** [comment]
I can elaborate on why GHC does this desugaring, if it’d help.

Simon

**Comment by gridaphobe** [comment]
No need to write anything in depth, as we were able to simply ignore the additional binder GHC created. But I'd happily accept a pointer to a relevant paper or wiki page, just to satisfy my curiosity :)

**Comment by ranjitjhala** [comment]
@simonpj -- alternatively, we can try to Skype at some point.
We've been doing a bunch of things here to generally improve
the user experience. One of them is @nikivazou has made great
progress in letting us write "measures" as just plain haskell
functions, which has made me want to figure out how to tie
things in more closely with GHC e.g. to avoid having
to reinvent the module/namespace wheel.

Other than that it would be nice if we could somehow use LH
specs instead of GHC types (where present) e.g. right now,
we have to say:

   {-@ abs :: Int -> Nat @-}

as well as

   abs :: Int -> Int

while really it should be enough to omit the abs :: Int -> Int
as it is redundant given the former.

Anyways, if there is some time that is convenient, it would be
good to chat! (Another option is to drop in and visit GHC HQ
some time around ESOP -- which is going to be in nearby London...)

Thanks!

Ranjit.


On Wed, Jan 21, 2015 at 1:51 PM, Eric Seidel <notifications@github.com>
wrote:

> No need to write anything in depth, as we were able to simply ignore the
> additional binder GHC created. But I'd happily accept a pointer to a
> relevant paper or wiki page, just to satisfy my curiosity :)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/314#issuecomment-70928905>
> .
>



-- 
Ranjit.

**Comment by simonpj** [comment]
Ranjit

Skype is better than email; higher bandwidth, more fun.  I'm buried in email.

Do come around ESOP.  Edward Yang is here the week after; Richard Eisenberg may come the week before.  But my time is relative uncommitted, so I can spend time with both of you ;-).

Let me know!

Simon
________________________________
