### ISSUE TITLE
Documentation issues with emacs editor integration

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#322]
While trying to install and get running with liquid haskell, I had to work through some issues with flycheck and flycheck-liquid.el

Step two of the emacs integration section of README.md states: 

> Ensure that the checker haskell-liquid is in the chain of flycheck checkers used in haskell-mode.

Unfortunately, how exactly to do this is not stated. Turns out that this isn't super-obvious. To get this going, I added to my .emacs:

    (add-hook 'flycheck-mode-hook 
          (lambda ()(require 'flycheck-liquid)
            (flycheck-add-next-checker 'haskell-ghc 'haskell-hlint)
            (flycheck-add-next-checker 'haskell-hlint 'haskell-liquid)))

I also added `haskell-liquid` to `flycheck-checkers` in the flycheck customize group.

Additionally, flycheck-liquid has `(require 'flycheck-liquid)` towards the top. However, my emacs throws an error on this. If I delete this require, then everything works fine. 

I've installed flycheck from melpa rather than just having it sitting in my .emacs.d folder, and I think this may have something to do with it. This may or may not be a real problem, as I could just be misconfigured.

**Comment by ranjitjhala** [comment]
@christetreault thanks for pointing out. I have pulled out the files into a separate repo with its own instructions. 

https://github.com/ucsd-progsys/liquid-types.el

Can you see if that makes sense?

**Comment by gridaphobe** [comment]
@ranjitjhala why not leave the emacs stuff in `syntax` and just add (and link to) a separate README inside `syntax`? As it stands, we now have two copies of the emacs files, which is a recipe for divergence :( Furthermore, keeping the syntax files in this repo allows us to distribute them *with* LH, which we currently do.

**Comment by ranjitjhala** [comment]
1 to make it easier for eventual Melpa packaging
2 I will delete the files from the LH repo
3 I found the whole cabal path copying thing to be rather tedious, the instructions now are much simpler -- "add a path" and "git clone"

**Comment by gridaphobe** [comment]
Distributing the files with LH allows us to ensure they will be compatible (of course this matters much less for us than for, e.g. the major mode for a language). But my main concern is really the possible divergence :)

**Comment by ranjitjhala** [comment]
I just deleted all the .el and .vim files from the repo (and put them
elsewhere) so divergence will not be a problem :-)
