### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by abakst** [ucsd-progsys/liquidhaskell#324]
Code here: https://gist.github.com/abakst/b46f7ef6f481cc096af2
Message:

"safeZip called on non-eq-sized lists (nxs = 1, nys = 0) : addRefSortMono"

**Comment by nikivazou** [comment]
The error now is 
~~~
1st argument of Fixme.FIO is "p" that expects 0 arguments, but it has 1
~~~

Still crashing, but with a better error message
