### ISSUE TITLE
Cannot use inline functions in data definitions?

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#327]
@nikivazou take a look at: 

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/fixme.hs

I can't seem to use `boo` inside the data definitions, perhaps those are still created with the old "uninlined" environment? Is this easy to fix?

(related to #325)

**Comment by nikivazou** [comment]
You are right the inlining was not happening in the refined data definitions, fixed.

**Comment by ranjitjhala** [comment]
awesome!!!

On Sat, Feb 7, 2015 at 5:45 PM, Niki Vazou <notifications@github.com> wrote:

> Closed #327 <https://github.com/ucsd-progsys/liquidhaskell/issues/327>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/327#event-232032876>
> .
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
Btw, as @spinda pointed out, there are a couple of "trace" things left, cf:

Trace: [coreToLogic] : EIte (PAtom Gt (EVar "x#a1IN") (EVar "y#a1IO"))
(EVar "x#a1IN") (EVar "y#a1IO")


Trace: [coreToLogic] : EBin Plus (ECon (I 1)) (EApp "max" defined at
"Fixpoint.Types.dummyLoc" (line 0, column 0) [EApp "realHeight" defined at
"Fixpoint.Types.dummyLoc" (line 0, column 0) [EVar "l#a1IJ"],EApp
"realHeight" defined at "Fixpoint.Types.dummyLoc" (line 0, column 0) [EVar
"r#a1IK"]])


Trace: [coreToPred] : PAnd [PAtom Le (EBin Minus (ECon (I 0)) (EVar
"n#a1IU")) (EBin Minus (EApp "realHeight" defined at
"Fixpoint.Types.dummyLoc" (line 0, column 0) [EVar "l#a1IS"]) (EApp
"realHeight" defined at "Fixpoint.Types.dummyLoc" (line 0, column 0) [EVar
"r#a1IT"])),PAtom Le (EBin Minus (EApp "realHeight" defined at
"Fixpoint.Types.dummyLoc" (line 0, column 0) [EVar "l#a1IS"]) (EApp
"realHeight" defined at "Fixpoint.Types.dummyLoc" (line 0, column 0) [EVar
"r#a1IT"])) (EVar "n#a1IU")]


Trace: [coreToPred] : PAtom Eq (EVar "v#a1IP") (EApp "nodeHeight" defined
at "Fixpoint.Types.dummyLoc" (line 0, column 0) [EVar "l#a1IQ",EVar
"r#a1IR"])

On Sat, Feb 7, 2015 at 6:33 PM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> awesome!!!
>
> On Sat, Feb 7, 2015 at 5:45 PM, Niki Vazou <notifications@github.com>
> wrote:
>
>> Closed #327 <https://github.com/ucsd-progsys/liquidhaskell/issues/327>.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ucsd-progsys/liquidhaskell/issues/327#event-232032876>
>> .
>>
>
>
>
> --
> Ranjit.
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
Ok I removed these traces too.
