### ISSUE TITLE
liquidhaskell-0.2.1.0 does not compile

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquidhaskell#328]
Citing from http://hydra.cryp.to/build/537016/nixlog/1/raw:

    src/Language/Haskell/Liquid/GhcMisc.hs:183:19:
        Ambiguous occurrence ‘L’
        It could refer to either ‘Language.Haskell.Liquid.GhcMisc.L’,
                                 defined at src/Language/Haskell/Liquid/GhcMisc.hs:180:18
                              or ‘Language.Fixpoint.Types.L’,
                                 imported from ‘Language.Fixpoint.Types’ at src/Language/Haskell/Liquid/GhcMisc.hs:34:1-67

    src/Language/Haskell/Liquid/GhcMisc.hs:289:22:
        Ambiguous occurrence ‘L’
        It could refer to either ‘Language.Haskell.Liquid.GhcMisc.L’,
                                 defined at src/Language/Haskell/Liquid/GhcMisc.hs:180:18
                              or ‘Language.Fixpoint.Types.L’,
                                 imported from ‘Language.Fixpoint.Types’ at src/Language/Haskell/Liquid/GhcMisc.hs:34:1-67

    src/Language/Haskell/Liquid/GhcMisc.hs:290:22:
        Ambiguous occurrence ‘L’
        It could refer to either ‘Language.Haskell.Liquid.GhcMisc.L’,
                                 defined at src/Language/Haskell/Liquid/GhcMisc.hs:180:18
                              or ‘Language.Fixpoint.Types.L’,
                                 imported from ‘Language.Fixpoint.Types’ at src/Language/Haskell/Liquid/GhcMisc.hs:34:1-67

**Comment by gridaphobe** [comment]
Oh dear, turns out we fixed this a while ago in master but I forgot to try building the current release of liquidhaskell against the new release of liquid-fixpoint :flushed: 

Fixed in the newly minted `liquidhaskell-0.3.0.0`, thanks for the report!

**Comment by peti** [comment]
Very nice, now it works: http://hydra.cryp.to/build/537205.
