### ISSUE TITLE
Auto Scrape Qualifiers from Dataconstructors

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#329]
See tests/todo/dataConQuals.hs

(In general, if we use data cons to encode invariants heavily, then it makes sense to use the refinements from those invariants in qualifiers.)

**Comment by nikivazou** [comment]
I believe that we should just treat Refined Data Definitions as type signatures, 
if we did so, neither this issue, nor #327 would exist.

**Comment by gridaphobe** [comment]
I thought we already did put the refined types for datacons in the list of type-sigs, but perhaps something is going wrong earlier..

**Comment by ranjitjhala** [comment]
Yes I also thought we did that and hence was especially puzzled that these two things were not working...

**Comment by ranjitjhala** [comment]
nice! thanks.

On Tue, Feb 10, 2015 at 10:13 AM, Eric Seidel <notifications@github.com>
wrote:

> Closed #329 <https://github.com/ucsd-progsys/liquidhaskell/issues/329>
> via b7bf06b
> <https://github.com/ucsd-progsys/liquidhaskell/commit/b7bf06bf88bf4097e5ac72a4776a61d011087e4f>
> .
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/329#event-233403431>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
@gridaphobe this commit breaks many tests

**Comment by gridaphobe** [comment]
@nikivazou I'm aware, most of the were instances of #333 with one instance of #335. All have been fixed now though :)

**Comment by nikivazou** [comment]
Hmm it seems that I pulled exactly after the failing commit... ok!
