### ISSUE TITLE
Cannot Inline Booleans?

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#331]
See:

tests/todo/implies.hs

I get a sort error that I can't quite follow. Perhaps some issue with the interaction between bool and prop?

**Comment by nikivazou** [comment]
Yes, The exact issue is that when a variable `x` has (haskell) type `Bool` we should "translate" it to `Prop v`.

I pushed a tmp fix for this example, but I suspect this issue will re appear soon.

Can you remind me if there was a concrete reason to distinguish between Bool and Prop?

**Comment by ranjitjhala** [comment]
The reason is that fix point (and SMT) 'bool' type are
special, the ONLY way to create it is via refinements,
and nothing else.

(This is a "sacred" invariant, we cannot break it.)

On Tue, Feb 10, 2015 at 1:21 PM, Niki Vazou <notifications@github.com>
wrote:

> Yes, The exact issue is that when a variable x has (haskell) type Bool we
> should "translate" it to Prop v.
>
> I pushed a tmp fix for this example, but I suspect this issue will re
> appear soon.
>
> Can you remind me if there was a concrete reason to distinguish between
> Bool and Prop?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/331#issuecomment-73786196>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
Isn't fixpoint 'int' also special? 
Why don't we have a `toInt :: Int -> int` (like Prop:: Bool -> bool) function?

**Comment by ranjitjhala** [comment]
Because by default everything is an int :) -- we need the prop to say "these are not int and you can do Boolean stuff with them". We could/should also do as you suggest except we can get away with treating everything As int by default.
