### ISSUE TITLE
Problem with qualification, name Resolution & Core2Logic

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#332]
See:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/elems.hs
https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/eqelems.hs
Why is the `S.member` NOT getting translated by core-to-logic?

**Comment by nikivazou** [comment]
Yes, it just translates the unqualified `member`. 
I will fix it soon

**Comment by nikivazou** [comment]
fixed!

**Comment by ranjitjhala** [comment]
Nice!! Thanks!
