### ISSUE TITLE
Auto-derived measures for function fields

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquidhaskell#333]
are causing failures now that we scrape qualifiers from the datacons, see e.g. https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/State.hs because the measure claims to take two arguments instead of one.

I think the simplest answer is to not generate field accessor measures for function fields, what do you think @nikivazou ?

**Comment by nikivazou** [comment]
not generating field accessor measures for function fields should be good (I also wanted to apply this restriction). 
I am not sure it is sufficient though, but you can definitely try it.

**Comment by gridaphobe** [comment]
Fixed in 4bb4e2f43ac0d2a404642a46be7556e890346ada
