### ISSUE TITLE
Parse Propositional Variables in Refinements 

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#338]
See:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/boolparse.hs

**Comment by kosmikus** [comment]
I think without the `Prop` (which AFAICS has been removed), this is working already, right?

This seems in some way related to the name resolution issues covered by #1688, but I don't think there currently is a parsing problem at this point?

**Comment by ranjitjhala** [comment]
Correct, let me close!

**Comment by ranjitjhala** [comment]
thanks @kosmikus !!
