### ISSUE TITLE
PANIC: Unexpected Error: plugHoles: unhandled case! In ex 3.2 of liquidhaskell-tutorial

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#339]
While doing exercise 3.2 of the Programming With Refinement Types tutorial, I ended up typing:

    {-@ unsafeLookup :: Int -> v:VectorN 0 vlen -> a @-}

Before I could type the argument to vlen, I got this flycheck error:

```
^[[1;94m
**** DONE:  annotate ***********************************************************
^[[0m^[[1;90m 
^[[0m^[[1;95m
**** PANIC: Unexpected Error: plugHoles: unhandled case! ***********************
^[[0m^[[1;95m
**** t  = a ********************************************************************
^[[0m^[[1;95m
**** st = {0} ******************************************************************
^[[0m

Please submit a bug report at: https://github.com/ucsd-progsys/liquidhaskell

Checker definition probably flawed.
```

Same error occurs with:

    {-@ unsafeLookup :: Int -> v:VectorN 0 (vlen) -> a @-}

...and...

    {-@ unsafeLookup :: Int -> v:VectorN 0 (vlen v) -> a @-}

checking the source from the command line yields:

```
$ liquid 02-poly.lhs 
LiquidHaskell Copyright 2009-14 Regents of the University of California. All Rights Reserved.


**** DONE:  annotate ***********************************************************
 

**** PANIC: Unexpected Error: plugHoles: unhandled case! ***********************

**** t  = a ********************************************************************

**** st = {0} ******************************************************************


Please submit a bug report at: https://github.com/ucsd-progsys/liquidhaskell
```

**Comment by gridaphobe** [comment]
Yikes! None of these are valid as you've passed in `0` where a type variable was expected, but we certainly need to fix the error message... Thanks for the report!

**Comment by christetreault** [comment]
Yeah, this one is giving me some problems. But I did notice that after submitting the bug. The choice: look like an idiot and submit the bug? Or not say anything...

**Comment by ranjitjhala** [comment]
Please always submit the bug! They are very helpful indeed. Thanks! Ranjit

**Comment by gridaphobe** [comment]
Yep, there's no such thing as a dumb bug report :smile:
