### ISSUE TITLE
Fixpoint crash reported as Liquid Type Mismatch

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#344]
See [tests/todo/BadError0.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/89caa266d2a6c638105c6d93a40895c9aff70b28/tests/todo/BadError0.hs)

That gives
~~~
Fixpoint: Bad Constraint! id = 2 (FixConstraint.BadConstraint(_)) tag = tag [1] //

**** DONE:  fixpoint ***********************************************************


**** DONE:  solve **************************************************************


**** DONE:  annotate ***********************************************************


**** CRASH: (FixConstraint.BadConstraint(_)) ***********************************

****  **************************************************************************


 tests/todo/BadError0.hs:9:11-13: Error: Liquid Type Mismatch
   Inferred type
     VV : a | papp1 p VV

   not a subtype of Required type
     VV : a | papp1 p VV

   In Context
     VV : a | papp1 p VV
     p  : (Pred a)
~~~

**Comment by ranjitjhala** [comment]
Is this a minimized form if the thing we discussed on sat? Or something else? Actually must be something else because there was no crash on sat. But do you know why FP is crashing?

**Comment by nikivazou** [comment]
It is the same as on Sat and we can catch it at liquidHaskell.
FP is crashing because the environment is not well formed, because `p` has type `p :: a -> Prop` 
but in the environment it is used as `p :: b -> Prop`.

**Comment by nikivazou** [comment]
fixed
