### ISSUE TITLE
LH crashes when types are assumed

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#345]
In [tests/todo/Crash.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/Crash.hs)
liquidHaskell crashes with 

~~~
liquid:
**** ERROR *********************************************************************
**** ERROR *********************************************************************
**** ERROR *********************************************************************
Constraint.Generate.fromAsserted called on invalid inputs
**** ERROR *********************************************************************
**** ERROR *********************************************************************
**** ERROR *********************************************************************
~~~

**Comment by ranjitjhala** [comment]
huh. puzzling.

On Wed, Feb 18, 2015 at 3:11 PM, Niki Vazou <notifications@github.com>
wrote:

> In tests/todo/Crash.hs
> <https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/Crash.hs>
> liquidHaskell crashes with
>
> liquid:
> **** ERROR *********************************************************************
> **** ERROR *********************************************************************
> **** ERROR *********************************************************************
> Constraint.Generate.fromAsserted called on invalid inputs
> **** ERROR *********************************************************************
> **** ERROR *********************************************************************
> **** ERROR *********************************************************************
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/345>.
>



-- 
Ranjit.

**Comment by spinda** [comment]
* foo is recursive

Enter Constraint/Generate.hs

* [consCBTop calls consCB](https://github.com/ucsd-progsys/liquidhaskell/blob/e7560445fa44de595cee1ca2fc74cc5c87330607/src/Language/Haskell/Liquid/Constraint/Generate.hs#L991)
* CoreBind is recursive and must be checked for termination; [consCBSizedTys is called from consCB](https://github.com/ucsd-progsys/liquidhaskell/blob/e7560445fa44de595cee1ca2fc74cc5c87330607/src/Language/Haskell/Liquid/Constraint/Generate.hs#L1087)
* [consCBSizedTys calls fromAsserted](https://github.com/ucsd-progsys/liquidhaskell/blob/e7560445fa44de595cee1ca2fc74cc5c87330607/src/Language/Haskell/Liquid/Constraint/Generate.hs#L1010) with something [generated from varTemplate](https://github.com/ucsd-progsys/liquidhaskell/blob/e7560445fa44de595cee1ca2fc74cc5c87330607/src/Language/Haskell/Liquid/Constraint/Generate.hs#L1005)
* [varTemplate has returned an Assumed, not an Asserted](https://github.com/ucsd-progsys/liquidhaskell/blob/e7560445fa44de595cee1ca2fc74cc5c87330607/src/Language/Haskell/Liquid/Constraint/Generate.hs#L1210)
* [crash in fromAsserted](https://github.com/ucsd-progsys/liquidhaskell/blob/e7560445fa44de595cee1ca2fc74cc5c87330607/src/Language/Haskell/Liquid/Constraint/Generate.hs#L1199)

**Comment by gridaphobe** [comment]
@nikivazou hmm, so the problem is that `consCBSizedTys` expects to only receive asserted types, which sort of makes sense given that it's going to figure out the decreasing parameters. Should we allow assumed specs in recursive groups? It feels a bit odd, but perhaps there's nothing really wrong with it.

**Comment by nikivazou** [comment]
I think we should allows assumed specs in recursive groups, but if we do not we need a better error message:)

**Comment by gridaphobe** [comment]
The problem then is that LH flags `foo` as unsafe because it doesn't have a decreasing parameter, which is a bit silly :)

**Comment by nikivazou** [comment]
But when I assume a signature I should not check termination right?

**Comment by nikivazou** [comment]
@spinda _if_ you want you can try to fix it, since you traced the error.

**Comment by gridaphobe** [comment]
I already have a partial fix

**Comment by spinda** [comment]
I'm short on time right now anyway.

**Comment by nikivazou** [comment]
Nice, thanks!
