### ISSUE TITLE
CRASH: Specified Type Does Not Refine Haskell Type

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#349]
While working through Exercise 5.4 of the tutorial, I tried the following:
```
{-@ wtAverage :: NEList (Pos, Pos) -> Int @-}
wtAverage wxs = if totWeight == 0
                then divide totElems 1
                else divide totElems totWeight
  where
    {-@ elems :: NEList a @-}
    elems     = map (\(w, x) -> w * x) wxs
    {-@ weights :: NEList a @-}
    weights   = map (\(w, _) -> w    ) wxs
    totElems  = sum elems
    totWeight = sum weights
```

When running liquid on this file, I get the following

```
$ liquid 04-measure-bool.lhs 
LiquidHaskell Copyright 2009-14 Regents of the University of California. All Rights Reserved.


**** DONE:  annotate ***********************************************************
 

**** CRASH:  *******************************************************************


 04-measure-bool.lhs:315:9: Error: Specified Type Does Not Refine Haskell Type for elems
 Haskell: [GHC.Types.Int]
 Liquid : forall a. [a]
```

If I change the specification for `weights` and `elems` from `NEList a` to `NEList Int`, liquid doesn't crash.

liquid-fixpoint version: 0.2.2.0, liquid-haskell version: 0.3.0.0, GHC version: 7.4.1

**Comment by gridaphobe** [comment]
This is expected behavior. We require the liquid types to be strict refinements of the haskell types, i.e. we don't try to unify the two. GHC doesn't generalize inferred types inside `where` clauses, so it infers that `weights` and `elems` have type `[Int]`.

"CRASH" is perhaps a bit extreme here, we're really just reporting an error in the provided specification. Do you have any thoughts on how to make the error message more informative? Thanks!

**Comment by christetreault** [comment]
For me, the main issue with this is that it is actually preventing LH from parsing the rest of the file. I feel that this in and of itself qualifies this as a legitimate issue.

As for your question, I think the error message is reasonable; certainly a lot better than many I've seen. It should just not crash the parser.

**Comment by spinda** [comment]
It's not crashing the parser. This is part of a set of sanity checks that
happen after all parsing and pre-processing and before constraints are
generated for the solver. See checkMismatch in Bare/Check.hs.

Errors generated from these checks are grouped together and thrown, and
LiquidHaskell's way of describing such fatal errors is "CRASH".

**Comment by christetreault** [comment]
So any sort of parse error has this behavior? I just tried

```
{-@ wtAverage :: NEList (Pos, Pos)} -> Int @-}
```

...and it seems to check out. I suppose this makes sense.

As for what I think it should say: I'd think the word "CRASH" should be reserved for huge problems like liquid-haskell not being installed correctly, file IO errors, segfaults, or things like this.

Maybe it should say "PARSE FAILURE" in red, similar to how "UNSAFE" works. Then it should print the failures as it does, then a message that says something to the effect of "Unable to verify program due to parse failures..."

As it stands, the output gives the impression that the tool is broken.

**Comment by gridaphobe** [comment]
That makes sense, we should more clearly delineate user errors from actual crashes.

**Comment by spinda** [comment]
@christetreault That's not quite it.

    {-@ wtAverage :: NEList (Pos, Pos)} -> Int @-}

is a parse error, but your original example is not. They just appear the same to the user at the moment. Except that, like GHC, you'll only ever get one parse error at a time, but you can get multiple of these sanity checking errors at once.

**Comment by ranjitjhala** [comment]
Awesome! Thanks for pointing out chris and thanks for fixing Eric!!!
