### ISSUE TITLE
Name resolution problem with non-top level functions

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#354]
This is a major problem that is blocking the 230 Final :( 

see `tests/todo/MM.hs` (which imports `tests/todo/LL.hs`) and fails with:

```
 /Users/rjhala/research/liquid/liquidhaskell/tests/todo/LL.hs:8:9: Error: GHC Error
     Not in scope: variable `LL.go'
```

(the problem goes away if I just make `go` a top-level function.)

I'm guessing this has to do with @spinda's recent changes?

**Comment by nikivazou** [comment]
Until @spinda takes a look, as a temporal fix for the final, you can make `go` global.

**Comment by spinda** [comment]
Yipes, looking at this now. I don't think I've pushed anything related to this to `master`, though.

**Comment by spinda** [comment]
Looks like it's a failure in `lookupGhcVar`, possibly in `varSymbols` in `Bare/Spec.hs`.

**Comment by spinda** [comment]
Odd, I can't reproduce this on the latest `master`.

**Comment by spinda** [comment]
Ah, it's `lookupIds` failing in `makeSpec`, which is called (as opposed to `makeLocalSpec`) for imported modules. `makeSpec` never had the local spec / `where` clause changes applied to it.

**Comment by spinda** [comment]
This is fixable if `makeLocalSpec` is used in both contexts, but for that it's necessary (with the current code) to extract `Var`s from imported modules' `CoreBind`s in addition to the primary module. @nikivazou, does that sound okay?

**Comment by spinda** [comment]
I have a branch with a somewhat-ugly fix [here](https://github.com/spinda/liquidhaskell/tree/where-vars) (in that it uses a 4-tuple; I will clean it up).

Tests currently running [here](https://travis-ci.org/spinda/liquidhaskell/builds/53515976).

**Comment by ranjitjhala** [comment]
Nice!!! Thanks @spinda

**Comment by spinda** [comment]
My first attempt failed a few tests. The latest version on that branch is now passing. I'll clean it up and submit a pull request tomorrow.

**Comment by gridaphobe** [comment]
I'm a bit amazed that none of the existing tests or benchmarks triggered this issue.

**Comment by spinda** [comment]
I think we're lacking in tests that deal with imports.

**Comment by ranjitjhala** [comment]
Yes, basically all the tests are single module.

On Sun, Mar 8, 2015 at 2:44 PM, Michael Smith <notifications@github.com>
wrote:

> I think we're lacking in tests that deal with imports.
>
> On Mar 8, 2015 11:27 AM, "Eric Seidel" <notifications@github.com> wrote:
>
> > I'm a bit amazed that none of the existing tests or benchmarks triggered
> > this issue.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ucsd-progsys/liquidhaskell/issues/354#issuecomment-77765996
> >
>
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/354#issuecomment-77776323>
> .
>



-- 
Ranjit.

**Comment by gridaphobe** [comment]
I remember adding a few to test the cross-module resolution logic, but that was probably before the local-specs were added..

**Comment by nikivazou** [comment]
I too remember having this issue before, maybe we added test in the todo.

@spinda I am a bit confused with what exactly is going on. 
Can you come by my office tomorrow afternoon?

**Comment by spinda** [comment]
Sure! Is 11:10am okay?

**Comment by nikivazou** [comment]
Yes. See you tomorrow!
