### ISSUE TITLE
Mysterious error in tests/todo/12-AV

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#366]
See:

tests/todo/12-case-study-AVL.lhs

I can't figure out what the problem is. What does

```
 12-case-study-AVL.lhs:600:5: Error: Bad Type Specification
 AVL.insR :: x:a -> t:(AVL a) -> (AVL a)
     Sort Error in Refinement: {t : FAppTy AVL.AVL  a_a268 | [key t < x && 0 < realHeight t]}
     Sort [GHC.Types.Char] is not a function
```

mean? Which binder or thing is supposed to be `[GHC.Types.Char]` or function?

Worse, when I copy the signature from `insL` for `insR` that ALSO complains but its fine if the binder is called `insL` -- the problem has to do with `key t` but I don't know what it is. Please take a look ASAP.

Clearly a regression of some sort...

**Comment by gridaphobe** [comment]
Seems somehow related to the choice of `key` as the field name, changing it to `foo` fixes the issue, sigh..

**Comment by gridaphobe** [comment]
Specifically, the issue only appears when we use the *same* name as the haskell datatype for the field accessor.

Here's a minimal example
```haskell
data AVL a =
    Leaf
  | Node { key :: a }

{-@ data AVL a = Leaf
               | Node { key :: a }
@-}

{-@ insL :: x:a
         -> t:{AVL a | (x < (key t))}
         -> AVL a
  @-}
insL :: a -> AVL a -> AVL a
insL a t = t
```
If you change `key` in the haskell or liquid definition, **or** if you remove the `Leaf` constructor, LH says SAFE.

**Comment by ranjitjhala** [comment]
Oh grief looks like more binder issues. Perhaps @nikivazou knows what's happening.

At any rate the error message is not very helpful because it should say what part of the refinement is bad, not just that SOMETHING is inconsistent...

**Comment by spinda** [comment]
Is `[GHC.Types.Char]` coming from the string support that was added in recently?

**Comment by gridaphobe** [comment]
Good catch @spinda I had forgotten all about that PR. That's precisely the issue, if I revert that PR the issue goes away.

**Comment by ranjitjhala** [comment]
btw, "key" is not special, search-and-replace "key" --> "root" triggers the same problem for me.

**Comment by ranjitjhala** [comment]
Which PR is that, and can we please just undo it?

(Is this the one @nikivazou put in pre-ICFP to get the string literal thing working? That was going to be tossed out anyway for a more *principled* treatment of literals, now supported by FIXPOINT.)

**Comment by spinda** [comment]
Yes, that's the pre-ICFP string literals one.

**Comment by spinda** [comment]
#348

**Comment by ranjitjhala** [comment]
ha ha!

https://github.com/ucsd-progsys/liquidhaskell/pull/348/files#diff-25171d56fedc2b786e9a5aefc8bc6c89L9

ahem @nikivazou ... :)

**Comment by ranjitjhala** [comment]
@nikivazou can you remove the thing in #348 and instead encode string-literals using this:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Types.hs#L422 

So the string `"cat"` becomes `L (T.pack "cat") t` where `t` is the `Sort` representing Haskell `String`

**Comment by nikivazou** [comment]
Yes my fault. I will change it.

**Comment by spinda** [comment]
It'd be a good idea to add a test case for this, too, if it isn't covered already.

**Comment by nikivazou** [comment]
We have tests/post/AVLRJ.hs for this specific issue

On Wed, Apr 1, 2015 at 8:07 PM, Michael Smith <notifications@github.com>
wrote:

> It'd be a good idea to add a test case for this, too, if it isn't covered
> already.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/366#issuecomment-88710784>
> .
>



-- 
Niki Vazou

**Comment by spinda** [comment]
Okay. Is this closeable, then?

**Comment by nikivazou** [comment]
Lets see, @ranjitjhala, can you see if the tutorial examples pass now, so that we close this issue?

**Comment by ranjitjhala** [comment]
seems to be ok now!
