### ISSUE TITLE
[7.10] LH and lenses,  "No match in record selector tyConTyVars"

### ISSUE THREAD

**Issue by marcinmrotek** [ucsd-progsys/liquidhaskell#375]
Hello,

I've tried to write some code using lenses and check it with LH. I managed to condense it to this code, which checks properly:
````haskell
{-# LANGUAGE NoMonomorphismRestriction, FlexibleContexts #-}
module Main where

import Control.Lens

{-@ double :: Int -> Even @-}
double :: Int -> Int
double x = x + x

{-@ half :: Even -> Int @-}
half :: Int -> Int
half = (`div` 2)

{-@ doubling :: Iso Int Int Even Even @-}
doubling :: Iso' Int Int
doubling = iso double half

main = return ()
````

Adding this:
````haskell
{-@ bar :: Iso Even Even Int Int @-}
bar = from doubling
````
LH still works, but considers the code unsafe:
````
**** UNSAFE ********************************************************************


 Main.hs:19:1-19: Error: Liquid Type Mismatch
   Inferred type
     VV : Int
  
   not a subtype of Required type
     VV : Int | VV mod 2 == 0
  
   In Context
     VV : Int


 Main.hs:19:12-19: Error: Liquid Type Mismatch
   Inferred type
     VV : Int
  
   not a subtype of Required type
     VV : Int | VV mod 2 == 0
  
   In Context
     VV : Int
````

When trying to actually use the isomorphism somehow, like:
````haskell
{-@ foo :: (Even -> Even) -> Int -> Int @-}
foo = over doubling
````
LH crashes just after extracting Core:
````
**** DONE:  Extracted Core using GHC *******************************************
 
liquid: No match in record selector tyConTyVars
````
Looking at GHC API for `TyCon` (https://downloads.haskell.org/~ghc/latest/docs/html/libraries/ghc/src/TyCon.html) I guess LH is trying to get the `tyConTyVars` field from either `FunTyCon` or `PrimTyCon` somewhere?

Core "dumps" made with ghc-core:
* first version: http://pastebin.com/xcpFUPtJ
* failed check: http://pastebin.com/m9S9km97
* error: http://pastebin.com/cg79revc

**Comment by nikivazou** [comment]
Hey @marcinmrotek, I pushed a fix for your second issue, the liquid crash. 

Re your first issue, I just minimized your example: the following should be safe but is not:

~~~
{-@ doubling' :: Iso Even Even Even Even @-}
doubling' :: Iso Int Int Int Int
doubling' = undefined

{-@ bar :: Iso Even Even Even Even @-}
bar :: Iso Int Int Int Int
bar = from doubling'
~~~

At first I suspected that we could blame contravariant for the imprecision (following the definition of the type `Iso` some of its arguments are variant and others contra-variant),
but the above example implies that it is not related to contravariance. 

I suspect that the source of imprecision is the class contraints in the type definition of `Iso`

~~~
type Iso s t a b = forall p f. (Profunctor p, Functor f) => p a (f b) -> p s (f t)
~~~

But how liquidHaskell can precisely support such types seems feasible but not obvious to me.
