### ISSUE TITLE
Refinements on function signatures?

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#384]
See: 

```
tests/todo/fixme.hs
```

When I run it in emacs and click on `bob` I get the refinement `v=bob` on the function type for `bob` ?

Why? We should NOT have this (as all function refinements should be TRUE) and even if we do, we should NOT be printing it. 

Please fix asap! (Am assigning @spinda as I _think_ it has do do with the recent issues about functions and refinements, but otherwise @nikivazou can you take a look?)

**Comment by nikivazou** [comment]
Just deactivated the printing of refinements in functions. It should be good now.

**Comment by ranjitjhala** [comment]
super, thanks!

On Thu, Apr 23, 2015 at 4:02 PM, Niki Vazou <notifications@github.com>
wrote:

> Just deactivated the printing of refinements in functions. It should be
> good now.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/384#issuecomment-95741256>
> .
>



-- 
Ranjit.

**Comment by spinda** [comment]
@nikivazou This change breaks the error message when you have a refinement on `(->)`, as the bad refinement won't show up when the type gets printed out. My code was set up to not print these when the refinement was TRUE&mdash;why do we have the case where one isn't TRUE?

**Comment by nikivazou** [comment]
Can you print "Functions cannot be refined" instead of printing the refinement? You can have a check if it is a function with an non-trivial refinement print "Functions cannot be refined".

The case that on is not true is when we look up variable functions from the environment. 
When you do so you return the "singleton" type stating that the variable is exactly equal to itself.

~~~
b:a -> b, Γ  |- b: {v:a -> b | v = b}
~~~

Makes sense?

**Comment by spinda** [comment]
I see. It does say "functions cannot be refined", but without the type it can be confusing to figure out why this is happening (eg. when `plugHoles` adds a function refinement).

Maybe this could be an optional flag somewhere to print the refinements? I'm not sure how to do this without complicating PrettyPrint's interface, though.
