### ISSUE TITLE
mysterious error in tests/todo/WBL0.hs

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#389]
@nikivazou this seems to have something to do with abstract predicates. Can you take a look? The error gives no clue as to what the problem is...

This test is basically `tests/pos/WBL.hs` with the measures `okRank` and `realRank` now converted to Haskell functions...

**Comment by nikivazou** [comment]
Just push a fix. Though the error does not seem related to the lifting of Haskell measures.
