### ISSUE TITLE
Termination Error (no decreasing parameter) with Num type class

### ISSUE THREAD

**Issue by hasufell** [ucsd-progsys/liquidhaskell#390]
Given a function like this
```haskell
{-@ fak1 :: {x: Int | x >= 0} -> Int @-}
fak1 :: Int -> Int
fak1 0 = 1
fak1 x = x * fak1 (x - 1)
```
everything checks fine.

If I set the types to be more general
```haskell
{-@ fak2 :: (Ord a, Eq a, Num a) => {x: a | x >= 0} -> a @-}
fak2 :: (Ord a, Eq a, Num a) => a -> a
fak2 0 = 1
fak2 x = x * fak2 (x - 1)
```
Then I get
```
Error: Termination Error on fak2
No decreasing parameter
```

**Comment by gridaphobe** [comment]
@nikivazou I believe we embed any concrete type that implements `Num` as an smt `int`, right? If so, we should treat `Num a => a` the same.

**Comment by nikivazou** [comment]
Correct, but until we do so, I believe we can use metrics. Can you try Tge
following type?

{-@ fak2 :: (Integral a, Ord a, Eq a, Num a) => y:{x: a | x >= 0} -> a /
[y]@-}

That says explicitly that the first argument y is decreasing.

**Comment by hasufell** [comment]
```
{-@ fak2 :: (Integral a, Ord a, Eq a, Num a) => y:{x: a | x >= 0} -> a / [y]@-}
fak2 :: (Integral a, Ord a, Eq a, Num a) => a -> a
fak2 0 = 1
fak2 x = x * fak2 (x - 1)
```
yields
```
 Error: Bad Termination Specification
 termination expression is not numeric :: y
     FObj sort a_a1aM is not numeric
```
Did I copy-paste it correctly?

**Comment by nikivazou** [comment]
Yes you copy paste it currently, but still does not work ...
I will try to fix it ASAP

**Comment by nikivazou** [comment]
@hasufell your initial example should work now on master! 
Thanks for the feedback, and let us know if you further break liquidHaskell:)

**Comment by ranjitjhala** [comment]
Yes @hasufell many thanks for bringing this to our attention!
