### ISSUE TITLE
Paring Refined Data Definitions

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#399]
See 

[tests/todo/Parse.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/406e046c88eeb4edb5802017394154e4f97890ac/tests/todo/Parse.hs)

**Comment by nikivazou** [comment]
Assigned to @Kyly

**Comment by gridaphobe** [comment]
@nikivazou can this be closed?

**Comment by nikivazou** [comment]
Sure!
