### ISSUE TITLE
Ghc Error due to "hidden packages"

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#403]
I am trying to get `liquid` to run on itself (in general, to get it running on arbitrary serious code bases.)

However, all of the below:

    liquid src/Language/Haskell/Liquid/GhcMisc.hs
    liquid  -isrc src/Language/Haskell/Liquid/GhcMisc.hs
    liquid -g"-package-db /Users/rjhala/research/liquid/liquidhaskell/.cabal-sandbox/x86_64-osx-ghc-7.8.3-packages.conf.d/" -isrc src/Language/Haskell/Liquid/GhcMisc.hs 

yield errors of the form:

    /Users/rjhala/research/liquid/liquidhaskell/src/Language/Haskell/Liquid/Desugar/Desugar.lhs:14:8-16: Error: GHC Error
     Could not find module ‘TcRnTypes’
It is a member of the hidden package ‘ghc-7.8.3’.
Use -v to see a list of the files searched for.

What is going on? What **other** magic options does GHC have when it compiles `liquid`?

**Comment by ranjitjhala** [comment]
I should add that doing a `ghc-pkg expose ghc` solves the problem but that seems shady.

**Comment by gridaphobe** [comment]
@ranjitjhala `ghc` is a hidden package by default (I guess because it exposes a bunch of unqualified modules). You need to either `ghc-pkg expose ghc` (which is what I do) or add `-g"-package ghc"` to the liquid options.

**Comment by ranjitjhala** [comment]
presumably this is -g"-package ghc" is in our makefile or cabal?
​

**Comment by ranjitjhala** [comment]
its not, so how does cabal figure out that it should be exposed?
​

**Comment by gridaphobe** [comment]
because we have `ghc` in our `build-depends`, cabal adds `-package foo` for each package in the `build-depends` list

**Comment by ranjitjhala** [comment]
Ok got it
