### ISSUE TITLE
Clean up test suite (make it run faster)

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquidhaskell#406]
Our unit tests take far too long to run, probably because we have a habit of dumping large files like `RBTree-Ord` into the test suite before paring them down to a minimal example.

We should do some spring cleaning on our test suite, separating the unit tests from things that really belong in benchmarks. In particular, I want the unit tests to fit in a single travis job :)

**Comment by nikivazou** [comment]
I was thinking about cleaning test suite too. I am sure there is also a lot of duplication there!

**Comment by gridaphobe** [comment]
Yes, that too :)
