### ISSUE TITLE
"Unknown flag: -f" from fixpoint

### ISSUE THREAD

**Issue by notcome** [ucsd-progsys/liquidhaskell#409]
I just compiled `liquidhaskell` and installed Z3 with Homebrew. I then tried to run `liquid` against an arbitrary Haskell file, but it reported this error:

```
**** START: fixpoint ***********************************************************
 
Unknown flag: -f

**** DONE:  fixpoint ***********************************************************
 
liquid: ./.liquid/b.hs.fqout: openFile: does not exist (No such file or directory)
```

I believe something went wrong with `fixpoint`. What does this error message mean? How to fix it?

I am running GHC 7.10.1 on OS X El Capitan. The tested Haskell file is just `main = return ()`.

**Comment by ranjitjhala** [comment]
Oops! Sorry! Did you build from github or hackage?

**Comment by ranjitjhala** [comment]
Also can you run in verbose mode:

   liquid -v file.hs

And paste that output?

**Comment by notcome** [comment]
I built it from GitHub. The verbose mode doesn't tell me much more about `fixpoint`:

```
EXEC: LD_LIBRARY_PATH=/usr/local/bin/ /usr/local/bin/fixpoint.native -v 1  -notruekvars -refinesort -nosimple -strictsortcheck -sortedquals -no-gen-qual-sorts -smtsolver z3 -out ./.liquid/b.hs.fqout ./.liquid/b.hs.fq

**** START: fixpoint ***********************************************************
 
Unknown flag: -f

**** DONE:  fixpoint ***********************************************************
 
liquid: ./.liquid/b.hs.fqout: openFile: does not exist (No such file or directory)
```

Couldn't find any flag named `-f`. Above those message I pasted was the core produced by GHC but I couldn't find `-f` neither by text matching. Really weird.

By the way, professor Jhala are you still on campus right now? Can I personally visit you? I am Minsheng Liu, the incoming freshman who sent you an email several weeks ago. I am now in La Jolla for the Summer Session I.

**Comment by ranjitjhala** [comment]
Bizarre! Can you run just:

/usr/local/bin/fixpoint.native ./.liquid/b.hs.fq

and see if you get the same error?

PS: I am in town but not on campus atm, we can meet on Friday maybe? Thanks!

**Comment by notcome** [comment]
Sorry, forget to reply...

I did have run fixpoint directly and confirmed that it's this program who reported this error.

I planned to check whether this has anything to do with the SMT solver. So I installed CVC4 but it reported the same error. Then I typed a wrong SMT solver name:

```
➜  Desktop  PlayLH/liquidhaskell/dist/dist-sandbox-f084ed23/build/liquid/liquid --smtsolver=cvc b.hs 
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.


**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  generateConstraints ************************************************
 

**** START: fixpoint ***********************************************************
 
Unknown flag: -f

**** DONE:  fixpoint ***********************************************************
```

Still the same error. I guess it didn't enter into the phase of calling a SMT solver.

Anyway, I am not familiar with the internal things. Hope this could help you a bit!

By the way, when will you be free and on campus tomorrow? Will you be at the Computer Science and Engineering Building?

**Comment by spinda** [comment]
To clarify, does running this on its own produce the same error?

```
EXEC: LD_LIBRARY_PATH=/usr/local/bin/ /usr/local/bin/fixpoint.native -v 1  -notruekvars -refinesort -nosimple -strictsortcheck -sortedquals -no-gen-qual-sorts -smtsolver z3 -out ./.liquid/b.hs.fqout ./.liquid/b.hs.fq
```

**Comment by ranjitjhala** [comment]
Bizarre -- are you on windows by any chance?

Also I will be in my office 2-3p today you are around?

See you soon !

**Comment by notcome** [comment]
@spinda Yes, a single line of "Unknown flag: -f"

@ranjitjhala see you soon! I am running El Capitan.

**Comment by spinda** [comment]
This is kind of bizarre, but I think you have `fixpoint` (the Haskell frontend) installed where `fixpoint.native` should be. In other words, your `/usr/local/bin/fixpoint.native` is the same as your `/usr/local/bin/fixpoint`, when they should be two different executables.

The single-line `Unknown flag: -s` message comes from the [`cmdargs` Haskell package](https://github.com/ndmitchell/cmdargs/blob/e413adda95691a6069a802c49170b032c2a75abe/System/Console/CmdArgs/Explicit/Process.hs#L86) that `liquid-fixpoint` uses to parse its command-line arguments. The `-f` arises from the ` -refinesort` argument passed to `fixpoint.native`. The OCaml backend's argument parser treats this as a single longform flag. However, `cmdargs`, used by the Haskell frontend, requires longform flags to start with `--`, and treats `-abcdefg| as a sequence of single-letter flags. So `-refinesort` expands to `-r -e -f -i -n -e -s -o -r -t`. The frontend is erroring out when it hits the invalid flag `-f`.

To confirm this, can you try `fixpoint.native --help` and `fixpoint.native --version`? I expect they will print out messages corresponding to the Haskell frontend.

**Comment by notcome** [comment]
@spinda I guess you are right. I checked the build directory of liquid-fixpoint's sandbox and it turns out that fixpoint and fixpoint.native have the same file size.
```
fixpoint Copyright 2009-15 Regents of the University of California.

fixpoint [OPTIONS] [FILE]
  Predicate Abstraction Based Horn-Clause Solver

Common flags:
  -o --outfile=ITEM      Output file
     --srcfile=ITEM      Source File from which FQ is generated
     --solver=SMTSOLVER  Name of SMT Solver
  -g --gensorts          Generalize qualifier sorts
  -u --ueqallsorts       Use UEq on all sorts
  -n --native            (alpha) Haskell Solver
  -r --real              (alpha) Theory of real numbers
  -e --eliminate         (alpha) Eliminate non-cut KVars
  -m --metadata          Print meta-data associated with constraints
     --stats             Compute constraint statistics
  -p --parts             Partition constraints into indepdendent .fq files
  -? --help              Display help message
  -V --version           Print version information
     --numeric-version   Print just the version number
  -v --verbose           Loud verbosity
  -q --quiet             Quiet verbosity
```
So something must went wrong during the compilation phase. I will do it again. Thank you!

**Comment by notcome** [comment]
I made a really stupid mistake: instead of going to the cabal sandbox for compiled binaries, I used ones inside the build directory. Problem solved, and sorry for your wasted time.
