### ISSUE TITLE
Bogus annots with GHC 7.10

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#419]
see the mouse-over type for 'malloc' in lh-workshop/06-bytestring.lhs

**Comment by ranjitjhala** [comment]
The "fix" here is to port the ANF code from ghc 7.8 versions to 7.10.

**Comment by gridaphobe** [comment]
I think you mean the Desguar code :)

I filed a bug with GHC about the missing Ticks (https://ghc.haskell.org/trac/ghc/ticket/10506) a while ago.

**Comment by ranjitjhala** [comment]
Ah yes.

On Tue, Jul 14, 2015 at 4:49 PM, Eric Seidel <notifications@github.com>
wrote:

> I think you mean the Desguar code :)
>
> I filed a bug with GHC about the missing Ticks (
> https://ghc.haskell.org/trac/ghc/ticket/10506) a while ago.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/419#issuecomment-121402122>
> .
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
btw I've started fiddling around with this. Looks like we really need one super tiny change, namely:

```.haskell
-- dsLExpr (L loc e) = putSrcSpanDs loc $ dsExpr e
dsLExpr (L loc e)
  = do ce <- putSrcSpanDs loc $ dsExpr e
       m  <- getModule
       return $ Tick (srcSpanTick m loc) ce

srcSpanTick :: Module -> SrcSpan -> Tickish a
srcSpanTick m loc = ProfNote (AllCafsCC m loc) False True
```

but have to do a whole bunch of crap just to fit it into the context in which the above happens.

**Comment by gridaphobe** [comment]
@ranjitjhala Ack, I just started fiddling around with it too. Was about to send a PR..

**Comment by gridaphobe** [comment]
(see #422)

**Comment by ranjitjhala** [comment]
should be fixed by https://github.com/ucsd-progsys/liquidhaskell/pull/422/
