### ISSUE TITLE
Lookup.hs build failure

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#420]
While trying to rebuild `liquid` I get the following error while compiling `src/Language/Haskell/Liquid/Bare/Lookup.hs`:

```
[39 of 59] Compiling Language.Haskell.Liquid.Bare.Lookup ( src/Language/Haskell/Liquid/Bare/Lookup.hs, interpreted )

src/Language/Haskell/Liquid/Bare/Lookup.hs:109:48:
    Couldn't match type ‘RdrName.RdrName’
                   with ‘GenLocated SrcSpan RdrName.RdrName’
    Expected type: SrcLoc.Located RdrName.RdrName
      Actual type: RdrName.RdrName
    In the second argument of ‘tcRnLookupRdrName’, namely ‘rn’
    In a stmt of a 'do' block:
      (_, lookupres) <- tcRnLookupRdrName env rn
```

versions:
cabal: 1.22.4.0
ghc: 7.10.1.20150715
kernel: 3.19.0-21-generic x64
branch: master 
commit: 8ae41baccf6bc64f24d131a8b8649c6bd9316bf8

**Comment by gridaphobe** [comment]
Is ghc-7.10.1.20150715 the actual 7.10.1 release or a release candidate for 7.10.2?

LH should build without issue against the official 7.10.1 release :(

**Comment by christetreault** [comment]
It's the 7.10.1 From the Herbert V. Riedell GHC PPA:

https://launchpad.net/~hvr/+archive/ubuntu/ghc

ghc --version lists:
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1.20150715
```

but the binary is installed as 7.10.2. I'll See about getting a newer version and let you know how it goes.

**Comment by christetreault** [comment]
I just downgraded to the actual 7.10.1, and it now compiles.

**Comment by gridaphobe** [comment]
Thanks. I looked into it and 7.10.2 has a small API change that we'll need to account for when it comes out.

**Comment by hannes-landeholm** [comment]
+1

I am new to Haskell and have no idea how to downgrade my GHC, been fruitlessly struggling with it for one hour. They don't bother making GHC pkgs for OS X anymore, as you're simply supposed to use the latest Haskell bundle.

**Comment by ranjitjhala** [comment]
Also can you try to install "stack" and then do "stack install" ?
I think that is wired to automatically download and build with ghc 7.10.1

**Comment by hannes-landeholm** [comment]
`stack install` installs ghc 7.10.2 for some reason even though that's not the ghc version specified by the `nightly-2015-06-16` snapshot. I have no idea why. Bug in stack? 

It installed ghc to `/Users/user/.stack/programs/x86_64-osx/ghc-7.10.2/bin` which works but it's the wrong version.

**Comment by hannes-landeholm** [comment]
I think the main problem is that stack does not recognise ghc version differences that small. "ghc-7.10" is the smallest possible resolver it accepts. It doesn't really give me a good impression that the ghc maintainers think back compatibility breaking changes only deserve a build/revision increment.

You can clearly see the change here:
https://downloads.haskell.org/~ghc/7.10.1/docs/html/libraries/ghc/TcRnDriver.html

https://downloads.haskell.org/~ghc/7.10.2/docs/html/libraries/ghc-7.10.2/TcRnDriver.html

**Comment by gridaphobe** [comment]
The GHC developers take API compatibility very seriously, generally refusing to change APIs in minor releases. In this case there was a feature (the implicit call-stacks) that multiple people asked to have back-ported to 7.10.2 that caused the API change. GHC HQ compiled all of stackage against the change before consenting to the back-port and found only a single package that was affected. So they decided in this case that the benefits outweighed the cost of fixing a few packages. 

I'll have a patch for LH and 7.10.2 on Monday, sorry for the inconvenience!

**Comment by hannes-landeholm** [comment]
Ah, very interesting. Thanks for the insightful response.

**Comment by ranjitjhala** [comment]
Thanks a ton Eric!

**Comment by gridaphobe** [comment]
LH should now compile against 7.10.2 as of 949d52af15aea6b5e2f9531d10b17c5bfb0c28ec, but **not** against 7.10.1.

This is because 7.10.2 includes some changes in the desugarer and using `CPP` to work around the differences would require cabal's `MIN_VERSION_*` macros, which IME tends to break things like `gcc-mod` and `hdevtools`.

@ranjitjhala if you and/or Ben can put together a few notes about the work you've been doing with fixpoint's `CHANGES.md`, I'll push a new release of everything to hackage.

**Comment by ranjitjhala** [comment]
Eric, the stuff Ben and I are doing is *NOT* in fixpoint master so should
not affect this release IMO?

On Tue, Aug 11, 2015 at 4:59 AM, Eric Seidel <notifications@github.com>
wrote:

> Closed #420 <https://github.com/ucsd-progsys/liquidhaskell/issues/420>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/420#event-378574662>
> .
>



-- 
Ranjit.

**Comment by gridaphobe** [comment]
The --native flag and a bunch of changes to the SmtLib2 module are in master. Is that stuff not ready to be mentioned in the Readme/Changelog?

**Comment by ranjitjhala** [comment]
Yes not ready -- probably there by mistake...

**Comment by gridaphobe** [comment]
@ranjitjhala here are all the commits in fixpoint's master since the last release, FYI

https://github.com/ucsd-progsys/liquid-fixpoint/compare/liquid-fixpoint-0.3.0.1...master#diff-d434977ac1a410b490aedf45f2ee7598

**Comment by ranjitjhala** [comment]
Ah ok thanks! 

So here's the deal: all the stuff actually belongs in cut solver but we've been pulling into master periodically to make sure we don't drift too far. But none of the changes are really "user facing" hence I thought no need to put anything into changes.md

Does that make sense?
