### ISSUE TITLE
Should test suite ignore LIQUIDHASKELL_OPTS environment variable

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#433]
While testing my fix for I had set `export LIQUIDHASKELL_OPTS=--no-termination`, and imagine my surprise when half the test suite failed.

Should the test suite ignore this environment variable?

**Comment by gridaphobe** [comment]
Seems reasonable, and not too hard to accomplish (I guess just add an `unset LIQUIDHASKELL_OPTS` to https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/test.hs#L146)

**Comment by christetreault** [comment]
I was thinking we could do some `withEnv` trickery before we shell out?

**Comment by gridaphobe** [comment]
You can specify an environment in the `createProcess` call at https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/test.hs#L123. I suppose running the test in an empty environment (i.e. `env = Just []`) should be fine.

**Comment by christetreault** [comment]
I'm running the tests for your first suggestion right now. If that doesn't work I'll give your second a shot.

**Comment by christetreault** [comment]
Your first solution worked, PR submitted: #434

**Comment by christetreault** [comment]
Fix is merged, closing issue.
