### ISSUE TITLE
Dead code in CmdLine.hs

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#442]
While trying to reduce duplication in the configs today, I found [this gem](https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/CmdLine.hs#L208-L213):

```
  case smtsolver cfg of
    Just _  -> return cfg
    Nothing -> do smts <- mapM findSmtSolver [Z3, Cvc4, Mathsat]
                  case catMaybes smts of
                    (s:_) -> return (cfg {smtsolver = Just s})
                    _     -> exitWithPanic noSmtError
```

It seems to me that the `Nothing` case is dead code. Since there is a default value for `smtsolver cfg` (should be `Just Z3`) this code will always take the `Just _` branch. This is bad because there is logic in the `Nothing` branch that will attempt to find an alternative solver on the system. Incidentally, I believe that this may be the explanation for some behavior I saw [a long time ago](https://github.com/ucsd-progsys/liquidhaskell-tutorial/issues/1) where liquid haskell wouldn't see MathSat on my system.

That said, I believe we can do something like this:

```
  solverExists <- findSmtSolver $ smtsolver cfg
  case solverExists of
    Just _  -> return cfg
    Nothing -> do smts <- mapM findSmtSolver [Z3, Cvc4, Mathsat]
                  case catMaybes smts of
                    (s:_) -> return (cfg {smtsolver = Just s})
                    _     -> exitWithPanic noSmtError
```

...which has the benefit of actually helping the user if they picked the wrong solver. (or the default Z3 isn't installed)

Additionally, I think we can change the `smtsolver :: Maybe SMTSolver` field of `Config`  to be `smtsolver :: SMTSolver` since this should either return with a `Just` value or throw an exception. Since you use `fromJust` in [Liquid.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/Liquid.hs#L102) to pass this value to fixpoint, it seems you already expect this to always be `Just` anyways.

**Comment by ranjitjhala** [comment]
sounds good to me!


On Thu, Sep 3, 2015 at 4:37 PM, Chris Tetreault <notifications@github.com>
wrote:

> While trying to reduce duplication in the configs today, I found this gem
> <https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/CmdLine.hs#L208-L213>
> :
>
>   case smtsolver cfg of
>     Just _  -> return cfg
>     Nothing -> do smts <- mapM findSmtSolver [Z3, Cvc4, Mathsat]
>                   case catMaybes smts of
>                     (s:_) -> return (cfg {smtsolver = Just s})
>                     _     -> exitWithPanic noSmtError
>
> It seems to me that the Nothing case is dead code. Since there is a
> default value for smtsolver cfg (should be Just Z3) this code will always
> take the Just _ branch. This is bad because there is logic in the Nothing
> branch that will attempt to find an alternative solver on the system.
> Incidentally, I believe that this may be the explanation for some behavior
> I saw a long time ago
> <https://github.com/ucsd-progsys/liquidhaskell-tutorial/issues/1> where
> liquid haskell wouldn't see MathSat on my system.
>
> That said, I believe we can do something like this:
>
>   solverExists <- findSmtSolver $ smtsolver cfg
>   case solverExists of
>     Just _  -> return cfg
>     Nothing -> do smts <- mapM findSmtSolver [Z3, Cvc4, Mathsat]
>                   case catMaybes smts of
>                     (s:_) -> return (cfg {smtsolver = Just s})
>                     _     -> exitWithPanic noSmtError
>
> ...which has the benefit of actually helping the user if they picked the
> wrong solver. (or the default Z3 isn't installed)
>
> Additionally, I think we can change the smtsolver :: Maybe SMTSolver
> field of Config to be smtsolver :: SMTSolver since this should either
> return with a Just value or throw an exception. Since you use fromJust in
> Liquid.hs
> <https://github.com/ucsd-progsys/liquidhaskell/blob/master/Liquid.hs#L102>
> to pass this value to fixpoint, it seems you already expect this to always
> be Just anyways.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/442>.
>



-- 
Ranjit.

**Comment by gridaphobe** [comment]
@christetreault I don't follow your reasoning, we use `def` [1] [2] to instantiate the default `smtsolver` value. The `smtsolver` field takes a `Maybe SmtSolver` and

```
ghci> def :: Maybe Int
Nothing
```

A simple way to definitively check whether the branch is dead code is to replace it with `undefined` and not provide a `--smtsolver` flag :)

[1]: https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/CmdLine.hs#L159
[2]: https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/CmdLine.hs#L341

**Comment by christetreault** [comment]
Ah yes, right you are. However, I still don't understand why we have to carry around this maybe value for the smt solver. Why not just default to Z3, and handle the case where it's not on the system?

```
  solverExists <- findSmtSolver $ smtsolver cfg
  case solverExists of
    Just _  -> return cfg
    Nothing -> do smts <- mapM findSmtSolver [Z3, Cvc4, Mathsat]
                  case catMaybes smts of
                    (s:_) -> return (cfg {smtsolver = s})
                    _     -> exitWithPanic noSmtError
```

Having this maybe implies that we can leave this function with a `Nothing` value, but it seems we never do...

**Comment by gridaphobe** [comment]
How would you then distinguish between no `--smtsolver` argument, in which case we should look for any solver, and `--smtsolver=z3`, in which case we should only look for z3?

This is one of those cases where LH itself would be very handy, the final `Config` will always have a `Just` in the solver field, and we could easily prove it.

**Comment by christetreault** [comment]
The first line `solverExists <- findSmtSolver $ smtsolver cfg` ensures that what they picked is installed. If we default to Z3, and the user doesn't provide a value for `--smtsolver`, then the value will be Z3. 

In any case, we check for the value of `--smtsolver` (Either the default Z3, or whatever other solver they specify), and if it is installed, we enter the just branch. If it's not installed, we enter the nothing branch and look for all 3 solvers.
