### ISSUE TITLE
Function call to non-constant

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquidhaskell#443]
See:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/ResolvePred.hs

In the fq file, the function ResolvePred.C#rpw is not a Constant but it is applied in refinements.

**Comment by ranjitjhala** [comment]
Should be fixed by:

https://github.com/ucsd-progsys/liquidhaskell/commit/9dcaaae944611145898cf39dc89a6b5e340d69b1#diff-6409f1f998798a468b29e8bb8e2a82e3R203

in particular, [this PR](https://github.com/ucsd-progsys/liquidhaskell/pull/444).

**Comment by bmcfluff** [comment]
The fix worked; closing. (ResolvePred still fails but for an unrelated reason now.)
