### ISSUE TITLE
Cabal file versioning needs to be maintained

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#461]
The problem:

In our `liquidhaskell.cabal` file, we don't have version number requirements on any of our dependencies. This means that for any dependency, `cabal-install` will attempt to install the latest version of it, probably resulting in breakage as you try to install older versions of Liquid Haskell.

This is especially a problem with Liquid Fixpoint, as it seems that we introduce breaking api changes every version. Fixpoint has a lower bound, but no upper bound. So, the current version of Liquid Haskell will install the correct version of Fixpoint, but all prior versions will try to install the newest version of Fixpoint, and fail to compile.

The solution:

At the very least, we need to change the line in `liquidhaskell.cabal`'s `Build-Depends` list from `liquid-fixpoint >= [some_version]` to be `liquid-fixpoint == [some_version]`. This will probably allow us to install a few versions back.

Above and beyond that, it would be good to add some upper and lower bounds to all the other packages. I expect that it might be too much work to strictly follow the PVP, but I think we can do better than we are. I don't think it'd be a big deal to add `foo >= X.0 && < Y.0`.

I'd be willing to take this on for the current version, assuming I have the go-ahead. I suspect that there is little need to or interest in fixing older versions, other than making my performance monitor work.

**Comment by ranjitjhala** [comment]
Yes please go ahead with this! It will be super valuable!

**Comment by christetreault** [comment]
OK, I'll make it happen. This is blocking the performance monitor anyways, so it'll help me progress to get this done.

**Comment by christetreault** [comment]
Do we follow the PVP guidlines when setting version numbers for liquid and fixpoint? i.e., can I assume that fixpoint version A.B.(C + 1) doesn't break anything from A.B.C?

**Comment by gridaphobe** [comment]
I try to follow them, yes.

**Comment by christetreault** [comment]
@gridaphobe: We currently have breakage with fixpoint. If we install 0.4.0 from hackage, we get a compilation failure. If we install "0.4.0" from github, it works.

Should we bump the version of the github version to 0.5 now? I assume you intend to make the next version 0.5 rather than 0.4.1 since there is breakage? I'll make liquidhaskell in the repo depend on 0.5 so it won't try to install from hacakge.

Moving forward, whenever we make a breaking change to the repo fixpoint, we can bump its version number then, rather than upon release.

**Comment by gridaphobe** [comment]
> Moving forward, whenever we make a breaking change to the repo fixpoint, it might be good to bump its version number then, rather than upon release.

YES, that would be wonderful, but perhaps hard to remember when you're hacking on fixpoint in-the-moment. What I used to to (and apparently forgot this time) is pre-emptively bump the major version after tagging a release.

**Comment by christetreault** [comment]
I think that would work too, except in the case where you need to do a "whoops, forgot something! better push a minor version bump to hackage". Though it'd likely be much easier to remember to do.

Shall I bump fixpoint's version number for you?

**Comment by christetreault** [comment]
Do we actually support GHC 7.8.3? https://github.com/ucsd-progsys/liquidhaskell/blob/master/liquidhaskell.cabal#L104

It doesn't seem like we have travis checking it any more...

**Comment by christetreault** [comment]
This is implemented in PR https://github.com/ucsd-progsys/liquidhaskell/pull/464
