### ISSUE TITLE
Name Resolution and Type Alias Expansion

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#468]
In `tests/todo/append-bug-name.hs` the check for
`prop_app_nil_ok` works fine, but `prop_app_nil_bad` doesn't.

The only difference is the type of axiom_append_nil_{bad, ok},
in which the only difference is that one uses the {...N...} while
the other does not. For some reason this yields two **different** 
refinements, one with `Append.N` and one with `N`, which 
causes the problem. 

In short, there is some odd name resolution bug that interacts 
with the type alias expansion code. 

@spinda -- any idea whats going on?

**Comment by nikivazou** [comment]
It turns out that there is no well formed-ness check in the "assumed" types. 
If you remove the `assume` from the type and have 

```
{-@ axiom_append_nil_bad :: xs:L a -> Equal {append N xs} {xs} @-}
```

You will get the real name resolution error, that is 

```
 tests/todo/append-name-bug.hs:23:5: Error: Bad Type Specification
 Append.axiom_append_nil_bad :: xs:(L a) -> {v : Proof | append N xs == xs}
     Sort Error in Refinement: {v : Append.Proof | append N xs == xs}
     Unbound Symbol N
 Perhaps you meant: v
```
