### ISSUE TITLE
Drop support for GHC 7.8.4

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#490]
As decided in our meeting, we are dropping support for GHC 7.8.4. To this end, we need to:

* Remove it from `liquidhaskell.cabal`
* Remove CPP macros supporting 7.8.4

If anybody can think of anything else, feel free to add it to the comments.

**Comment by ranjitjhala** [comment]
You mean ghc 784?

**Comment by christetreault** [comment]
Lol, no, we're only supporting hugs now, remember? :P

Fixed

**Comment by christetreault** [comment]
Should be closed by: https://github.com/ucsd-progsys/liquidhaskell/pull/500
