### ISSUE TITLE
Unknown Constant

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquidhaskell#494]
Hopefully-final instance of https://github.com/ucsd-progsys/liquid-fixpoint/issues/134: tests/todo/pair0.hs crashes with --native

**Comment by nikivazou** [comment]
Will look at it asap!

**Comment by bmcfluff** [comment]
DBMovies.hs seems to have the same problem

**Comment by nikivazou** [comment]
Fixed on https://github.com/ucsd-progsys/liquidhaskell/commit/c98647fd44653d11893734819e05a38bfcc62256
