### ISSUE TITLE
Bug in Name Resolution in Type aliases

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#495]
The code in [todo/LambdaDeBruijn0.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/d32671517e3eb859e1f5512fb3d5de4bf9eb8e31/tests/todo/LambdaDeBruijn0.hs) is UNSAFE, but turns safe I change the refinement variable [e -> v] in [line 27](https://github.com/ucsd-progsys/liquidhaskell/blob/d32671517e3eb859e1f5512fb3d5de4bf9eb8e31/tests/todo/LambdaDeBruijn0.hs#L27-L28) (i.e. replace line 27 with 28)

**Comment by gridaphobe** [comment]
What is the bug, some kind of variable capture? Is the code expected to be safe or unsafe?

**Comment by nikivazou** [comment]
I expect it to be safe. 

See https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/LambdaDeBruijn0.hs#L26-L30

**Comment by nikivazou** [comment]
@gridaphobe the issue does not seem fixed. `pos/LamdaDeBrujin0.hs` is still failing.

**Comment by gridaphobe** [comment]
@nikivazou did you `git submodule update` after pulling master? The fix was in fixpoint, so a submodule bump is necessary.

**Comment by nikivazou** [comment]
But, it failed in Travis

**Comment by gridaphobe** [comment]
Oh wait, the fixpoint commit was changed again...

**Comment by gridaphobe** [comment]
fixed for real now

**Comment by nikivazou** [comment]
Thanks!

On Thu, Oct 22, 2015 at 10:13 AM, Eric Seidel <notifications@github.com>
wrote:

> fixed for real now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/495#issuecomment-150294290>
> .
>



-- 
Niki Vazou
