### ISSUE TITLE
Diffcheck not rechecking caller of updated function

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#508]
Consider the following:

```
{-@ type Zero = {v:Int | v == 0} @-}
{-@ type Three = {v:Int | v == 3} @-}

{-@ badFn :: Zero -> Bool @-}
badFn :: Int -> Bool
badFn 0 = badDep 0
badFn _ = False

{-@ badDep :: Three -> Bool @-}
badDep :: Int -> Bool
badDep 3 = True
badDep _ = False
```

`badFn` calls `badDep` with 0, but its liquid type signature expects 3. This is not safe. Suppose calling `badDep 0` is actually the correct behavior, and we want to fix the real bug: its type signature. So we give it the liquid type `{-@ badDep :: Zero -> Bool @-}`:

```
{-@ type Zero = {v:Int | v == 0} @-}
{-@ type Three = {v:Int | v == 3} @-}

{-@ badFn :: Zero -> Bool @-}
badFn :: Int -> Bool
badFn 0 = badDep 0
badFn _ = False

{-@ badDep :: Zero -> Bool @-}
badDep :: Int -> Bool
badDep 3 = True
badDep _ = False
```

If we now rerun liquid, it will check badDep, and will not check badFn. Due to this, it will declare badDep unsafe, which is clearly not correct.

When a piece of code changes, liquidhaskell should find all callers of this code and recheck them.

**Comment by gridaphobe** [comment]
Can you split the example into a *before-* and *after-* edit? I'm a bit confused.

**Comment by christetreault** [comment]
Done.

**Comment by christetreault** [comment]
I have a preliminary fix in for this issue. It still needs more extensive testing, but it passes the case that I cited above as being a failure and all others that I've tried so far. Since our test suite isn't really set up to test this sort of thing, I'd like to ask @ranjitjhala, @gridaphobe, @nikivazou and whoever else to please take a look and see if you can find any issues with the fix. Important bits are:

* This change to `thinWith`: https://github.com/ucsd-progsys/liquidhaskell/compare/fix-diffcheck#diff-f44725f9ce8dc06f537852495e7893f7L172
* Which calls this new function `dependsOn`: https://github.com/ucsd-progsys/liquidhaskell/compare/fix-diffcheck#diff-f44725f9ce8dc06f537852495e7893f7R185

The basic idea is that when some function `f` changes, we need to go through and find all functions that call `f` and check them as well. `dependsOn` returns this set of functions that is unioned with the set being returned by `txClosure`.

There are a lot of changes throughout the file that basically amount to giving things more descriptive names to help me pick through it. I can back them out or leave them, though I don't think they're hurting anything by staying.

**Comment by ranjitjhala** [comment]
Super, thanks -- will look at this ASAP! (Would probably have helped to go
over in person -- if nothing else need to page in DiffCheck -- but won't be
in tomorrow natch.) Perhaps Friday?



On Tuesday, November 10, 2015, Chris Tetreault <notifications@github.com>
wrote:

> I have a preliminary fix in for this issue. It still needs more extensive
> testing, but it passes the case that I cited above as being a failure and
> all others that I've tried so far. Since our test suite isn't really set up
> to test this sort of thing, I'd like to ask @ranjitjhala
> <https://github.com/ranjitjhala>, @gridaphobe
> <https://github.com/gridaphobe>, @nikivazou <https://github.com/nikivazou>
> and whoever else to please take a look and see if you can find any issues
> with the fix. Important bits are:
>
>    - This change to thinWith:
>    https://github.com/ucsd-progsys/liquidhaskell/compare/fix-diffcheck#diff-f44725f9ce8dc06f537852495e7893f7L172
>    - Which calls this new function dependsOn:
>    https://github.com/ucsd-progsys/liquidhaskell/compare/fix-diffcheck#diff-f44725f9ce8dc06f537852495e7893f7R185
>
> The basic idea is that when some function f changes, we need to go
> through and find all functions that call f and check them as well.
> dependsOn returns this set of functions that is unioned with the set
> being returned by txClosure.
>
> There are a lot of changes throughout the file that basically amount to
> giving things more descriptive names to help me pick through it. I can back
> them out or leave them, though I don't think they're hurting anything by
> staying.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/508#issuecomment-155631353>
> .
>


-- 
Ranjit.

**Comment by christetreault** [comment]
I responded on the slack. I just wanted to throw the can over the fence on this one. We can talk in person. I'll clean up the code in the meantime and do some more testing to make sure nothing broke.

**Comment by christetreault** [comment]
PR #516 is merged, so this issue should be resolved.
