### ISSUE TITLE
div doesn't work?

### ISSUE THREAD

**Issue by sorawee** [ucsd-progsys/liquidhaskell#514]
I got the following Liquid Type Mismatch

```
 ra-list.hs:42:31-47: Error: Liquid Type Mismatch
   Inferred type
     VV : {VV : Int | VV == ?c}

   not a subtype of Required type
     VV : {VV : Int | tree_size ?e == VV}

   In Context
     VV : {VV : Int | VV == ?c}
     f  : {f : (FullBinaryTree a) | tree_size f > 1}
     s  : {s : Int | tree_size f == s}
     ?e : {?e : (FullBinaryTree a) | 2 * tree_size ?e + 1 == tree_size f}
     ?d : {?d : Int | ?d == s - ?b}
     ?a : {?a : Int | ?a == 2}
     ?b : {?b : Int | ?b == 1}
     ?c : {?c : Int | ?c == ?d / ?a && (?d >= 0 && ?a >= 0 => ?c >= 0) && (?d >= 0 && ?a >= 1 => ?c <= ?d)}
```

Let's substitute:

```
VV == tree_size ?e =>
VV == (tree_size f - 1) / 2 =>
?c == (tree_size f - 1) / 2 =>
?d / ?a == (tree_size f - 1) / 2 =>
(s - ?b) / 2 == (tree_size f - 1) / 2 =>
(tree_size f - 1) / 2 == (tree_size f - 1) / 2
```

and they are indeed equal. Yet, I got a Liquid Type Mismatch.

**Comment by ranjitjhala** [comment]
In general, no -- as this is non-linear arithmetic. But In this case, the divisor is a constant `2` and I thought we'd fixed this issue, but clearly not! Can you send a link to the source (that generates the 
above error?) Thanks!

**Comment by sorawee** [comment]
Oh, maybe it's because I'm using 0.5.0.1, then. I will pull the latest version and try again. Thanks for a quick response!

**Comment by ranjitjhala** [comment]
Nope that's unlikely to solve it ... :( I think this goes further back...

However: can you try running with "--real" which  runs the (experimental) non linear arithmetic theory?

**Comment by sorawee** [comment]
Yup, `--real` works!

**Comment by sorawee** [comment]
Well, no, I could replace the number with _anything_, and the result will still be SAFE. Here's the code: http://pastebin.com/0taqWLYS

**Comment by ranjitjhala** [comment]
Hmm, just tried it out -- seems to be doing the right thing for me. e.g. if I change `s-1` to `s-10` or the divisor from `2` to `3`. Did you mean something else? (Could of course be some bug that has been fixed -- I'm running `github:master`)

<img width="1280" alt="screen shot 2015-11-17 at 5 41 42 am" src="https://cloud.githubusercontent.com/assets/1650232/11212994/5868b19e-8cee-11e5-87f0-7b0c9673b456.png">

<img width="1280" alt="screen shot 2015-11-17 at 5 42 06 am" src="https://cloud.githubusercontent.com/assets/1650232/11213002/6879e116-8cee-11e5-9d6d-cad355f1e728.png">

**Comment by ranjitjhala** [comment]
PS: I also get errors if I do the above i.e. `1` --> `10`  or `2` --> `3` on the other constructor on the line...

**Comment by sorawee** [comment]
I just pull the latest version from the repo. It works even without `--real`. I also notice the following:

- `((s) `div` 2)` -> SAFE
- `((s - 1) `div` 2)` -> SAFE
- `((s - 2) `div` 2)` -> SAFE
- `((s - 3) `div` 2)` -> UNSAFE
- `((s - 4) `div` 2)` -> UNSAFE
- `((s - 5) `div` 2)` -> UNSAFE
- `((s - 6) `div` 2)` -> UNSAFE
- `((s - 7) `div` 2)` -> UNSAFE
- `((s - 8) `div` 2)` -> SAFE
- `((s - 9) `div` 2)` -> UNSAFE
- `((s - 10) `div` 2)` -> SAFE
- `((s - 11) `div` 2)` -> UNSAFE

Previously I use `((s - 10) `div` 2)`, so I thought that any number works. Now I know that some of them result in UNSAFE, so that's good. However, I still don't understand why `((s - 2) `div` 2)`, `((s - 8) `div` 2)`, and `((s - 10) `div` 2)` are SAFE. Maybe my invariant is too weak.

However, something is definitely wrong. Liquid should be able to infer that `s` is in the form of 2^x - 1 -- an odd number. Thus, if `((s - k) `div` 2)` is SAFE where k is an odd number, then `((s - k + 1) `div` 2)` should be SAFE as well. But this is clearly not the case for  `((s - 8) `div` 2)` and `((s - 10) `div` 2)`.

Note that I didn't change anything at all from the above code (in pastebin.com) except the said number.

**Comment by ranjitjhala** [comment]
Hmm... When I try `s - 2`, `s - 8` or  `s - 10` I still get 
UNSAFE (in either of the two positions at that same line.)
However, `s div 2` is SAFE, which seems right.

<img width="1280" alt="screen shot 2015-11-17 at 8 47 07 am" src="https://cloud.githubusercontent.com/assets/1650232/11218102/5f5d8b86-8d08-11e5-8970-af7517c35235.png">

I wonder if somehow you are running a stale version? Are you building with `stack` ?

**Comment by sorawee** [comment]
Yup, I built it with stack, literally an hour ago.

--

**Comment by nikivazou** [comment]
Same here...

I just tried the example, for me only `s div 2` and `(s-1) div 2` are SAFE and all the other `(s - *) div 2` that you have above are UNSAFE. This is quite strange. 

How are you running liquid? (via terminal or interactively?) 

Also, the type of `div` is 
```
x:a -> y:{v:a | v /= 0} -> {v:a | (v = (x / y)) &&
                                              ((x >= 0 && y >= 0) => v >= 0) &&
                                              ((x >= 0 && y >= 1) => v <= x) }
```
You could try give `div` a different type that captures more precisely what you want to prove.

**Comment by ranjitjhala** [comment]
wonder if _my_ version is stale let me rebuild :)

On Tue, Nov 17, 2015 at 8:53 AM, sorawee <notifications@github.com> wrote:

> Yup, I built it with stack, literally an hour ago.
>
> --
> Sent from phone. Please pardon terseness and mistakes.
> On Nov 17, 2015 11:52 AM, "Ranjit Jhala" <notifications@github.com> wrote:
>
> > Hmm... When I try s - 2, s - 8 or s - 10 I still get
> > UNSAFE (in either of the two positions at that same line.)
> > However, s div 2 is SAFE, which seems right.
> >
> > [image: screen shot 2015-11-17 at 8 47 07 am]
> > <
> https://cloud.githubusercontent.com/assets/1650232/11218102/5f5d8b86-8d08-11e5-8970-af7517c35235.png
> >
> >
> > I wonder if somehow you are running a stale version? Are you building
> with
> > stack ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ucsd-progsys/liquidhaskell/issues/514#issuecomment-157429086
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/514#issuecomment-157429513>
> .
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
@nikivazou, the first conjunct is as precise as we want. The latter ones we
should probably remove...

How recent is your build...? (I wonder if this is a recent bug, let me
rebuild...)





On Tue, Nov 17, 2015 at 8:55 AM, Niki Vazou <notifications@github.com>
wrote:

> Same here...
>
> I just tried the example, for me only s div 2 and (s-1) div 2 are SAFE
> and all the other (s - *) div 2 that you have above are UNSAFE. This is
> quite strange.
>
> How are you running liquid? (via terminal or interactively?)
>
> Also, the type of div is
>
> x:a -> y:{v:a | v /= 0} -> {v:a | (v = (x / y)) &&
>                                               ((x >= 0 && y >= 0) => v >= 0) &&
>                                               ((x >= 0 && y >= 1) => v <= x) }
>
> You could try give div a different type that captures more precisely what
> you want to prove.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/514#issuecomment-157429973>
> .
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
hmm... latest version is also working fine (i.e. reporting errors for `s-2`, `s-8`, `s-10` for me...)

**Comment by nikivazou** [comment]
My build is master. What bug? The results you and me are getting seem the expected ones. I suspect a diff-check error. This is why I asked @sorawee  how he runs liquid.

**Comment by ranjitjhala** [comment]
I meant *maybe* there is a recent bug, but it seems not because I get the correct results with my master build too. I don't think there is any diff-check going in (its not there in the code in the paste-bin.)

**Comment by sorawee** [comment]
I run it via terminal on Mac OS X 10.11.1. I use Z3 version 4.4.2 as the SMT solver (built four days ago from the Z3 repo). Here's the full result in case you want to see it: http://pastebin.com/ftKa3jxx

**Comment by ranjitjhala** [comment]
Hmm. When I copy your exact file, I get a rather different result:

http://pastebin.com/YRnacYhv

I wonder if its a z3 bug (I'm on Z3 4.3.1) -- not unlikely given
the specific issue here -- the different outcomes if we plug in
10, 8, 2 etc. (which should really just change the constants in
the VCs).

@sorawee: can you try with z3 - 4.3.1?

@nikivazou: can you try with z3 - 4.4.1?




On Tue, Nov 17, 2015 at 10:00 AM, sorawee <notifications@github.com> wrote:

> I run it via terminal on Mac OS X 10.11.1. I use Z3 version 4.4.2 as the
> SMT solver (built four days ago from the Z3 repo). Here's the full result
> in case you want to see it: http://pastebin.com/ftKa3jxx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/514#issuecomment-157453876>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
I get unsafe too. 
Can you add the following line in your code (just in case)

```
{-@ div :: x:a -> y:{v:a | v /= 0} -> {v:a | v = (x / y)}@-}
```

**Comment by nikivazou** [comment]
Also, can you show us the liquid error that you get when you get UNSAFE?

**Comment by sorawee** [comment]
Adding a refinement for `div` doesn't help. It's still SAFE.

I don't know if I interpret your question correctly or not. I couldn't show you the liquid error for `s - 10` because the problem is that I get SAFE (and thus no error), while it shouldn't.

However, if you want to see errors in general case, here it is (with `s - 9`):

```
**** RESULT: UNSAFE ************************************************************


 ra-list.hs:35:29-45: Error: Liquid Type Mismatch
   Inferred type
     VV : {VV : Int | VV == ?d}

   not a subtype of Required type
     VV : {VV : Int | tree_size ?b == VV}

   In Context
     VV : {VV : Int | VV == ?d}
     f  : {f : (FullBinaryTree a) | tree_size f > 0}
     s  : {s : Int | tree_size f == s}
     ?c : {?c : Int | ?c == s - ?e}
     ?e : {?e : Int | ?e == 9}
     ?b : (FullBinaryTree a)
     ?d : {?d : Int | ?d == ?c / ?a && (?c >= 0 && ?a >= 0 => ?d >= 0) && (?c >= 0 && ?a >= 1 => ?d <= ?c)}
```

I will try different version of Z3 soon.

**Comment by ranjitjhala** [comment]
Yes the signature for `div` is not relevant here IMO (as long as you leave
the `/` in).

I'm willing to put money on this being a Z3 problem...

​

**Comment by nikivazou** [comment]
This is the answer to my question, but it did not help me understand what is going wrong.. You should have one more line like 
```
     ?a : {?a : Int | ?a == 9}
```
right? 


A next attempt to find what is going wrong: can you run liquid with `--extsolver`. 
Then go to the `.liquid` directory, find an `name-of-your-haskell-file.hs.fq` file and send it to us?
Alternatively, you can just try another SMT solver. 


@ranjitjhala with the native solver is there a way for us to run the ".fq" file that sorawee creater?

**Comment by ranjitjhala** [comment]
@nikivazou -- yes, just do:

```
fixpoint --extsolver foo.fq
```



On Tue, Nov 17, 2015 at 10:33 AM, Niki Vazou <notifications@github.com>
wrote:

> This is the answer to my question, but it did not help me understand what
> is going wrong.. You should have one more line like
>
>      ?a : {?a : Int | ?a == 9}
>
> right?
>
> A next attempt to find what is going wrong: can you run liquid with
> --extsolver.
> Then go to the .liquid directory, find an name-of-your-haskell-file.hs.fq
> file and send it to us?
> Alternatively, you can just try another SMT solver.
>
> @ranjitjhala <https://github.com/ranjitjhala> with the native solver is
> there a way for us to run the ".fq" file that sorawee creater?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/514#issuecomment-157462835>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
But there is no `.fq` file created when I run liquid

**Comment by sorawee** [comment]
Yup, problem with Z3! 4.4.2 is incorrect, while 4.3.2 works correctly.

Can you file a bug report on the Z3 repo? I don't know how constraints are generated inside LH.

```
~/haskell$ PATH=~/haskell/z3-z3-4.3.2/build/:$PATH liquid ra-list.hs
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.


**** DONE:  Extracted Core using GHC *******************************************


**** DONE:  generateConstraints ************************************************


**** DONE:  solve **************************************************************

WARNING: Found false in ra-list.hs:1:5-7

**** DONE:  annotate ***********************************************************


**** RESULT: UNSAFE ************************************************************


 ra-list.hs:35:29-46: Error: Liquid Type Mismatch
   Inferred type
     VV : {VV : Int | VV == ?d}

   not a subtype of Required type
     VV : {VV : Int | tree_size ?b == VV}

   In Context
     VV : {VV : Int | VV == ?d}
     f  : {f : (FullBinaryTree a) | tree_size f > 0}
     s  : {s : Int | tree_size f == s}
     ?c : {?c : Int | ?c == s - ?e}
     ?e : {?e : Int | ?e == 10}
     ?b : (FullBinaryTree a)
     ?d : {?d : Int | ?d == ?c / ?a && (?c >= 0 && ?a >= 0 => ?d >= 0) && (?c >= 0 && ?a >= 1 => ?d <= ?c)}
     ?a : {?a : Int | ?a == 2}
nullzero@MacBook-Pro-9:~/haskell$ liquid ra-list.hs
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.


**** DONE:  Extracted Core using GHC *******************************************


**** DONE:  generateConstraints ************************************************


**** DONE:  solve **************************************************************

WARNING: Found false in ra-list.hs:1:5-7

**** DONE:  annotate ***********************************************************


**** RESULT: SAFE **************************************************************
~/haskell$ z3 -version
Z3 version 4.4.2
```

**Comment by nikivazou** [comment]
Great!!!!! We will do! Thanks for insisting:)

**Comment by ranjitjhala** [comment]
Great, thanks @sorawee !

Yes, will file a bug. Before that I need to extract the exact SMT queries
(so we can send them a minimal failing test...)



On Tue, Nov 17, 2015 at 10:58 AM, Niki Vazou <notifications@github.com>
wrote:

> Closed #514 <https://github.com/ucsd-progsys/liquidhaskell/issues/514>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/514#event-467062766>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
I was thinking just to send the `tests/pos/.liquid/TreesDiv.hs.smt2` file. The two versions of z3 report different result (z3-4 reports one sat, which z3-3 has only unsat)

**Comment by ranjitjhala** [comment]
​Oh, ok that works!

Do you have the file @nikivazou?
​
Ideally we'd "minimize" it by repeatedly deleting queries (here, lines),
while still maintaining the divergence...



On Tue, Nov 17, 2015 at 11:08 AM, Niki Vazou <notifications@github.com>
wrote:

> I was thinking just to send the tests/pos/.liquid/TreesDiv.hs.smt2 file.
> The two versions of z3 report different result (z3-4 reports one sat, which
> z3-3 has only unsat)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/514#issuecomment-157473229>
> .
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
Perhaps you can use only the "last" SAT query ?

On Tue, Nov 17, 2015 at 11:16 AM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> ​Oh, ok that works!
>
> Do you have the file @nikivazou?
> ​
> Ideally we'd "minimize" it by repeatedly deleting queries (here, lines),
> while still maintaining the divergence...
>
>
>
> On Tue, Nov 17, 2015 at 11:08 AM, Niki Vazou <notifications@github.com>
> wrote:
>
>> I was thinking just to send the tests/pos/.liquid/TreesDiv.hs.smt2 file.
>> The two versions of z3 report different result (z3-4 reports one sat, which
>> z3-3 has only unsat)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ucsd-progsys/liquidhaskell/issues/514#issuecomment-157473229>
>> .
>>
>
>
>
> --
> Ranjit.
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
Do you really think it will make difference? I will submit an issue in the z3 github repo.

**Comment by ranjitjhala** [comment]
Yes it will make a difference.

Which LH issue are *you* likely to look at and fix (first): one that has a 5 line failing test or which has a 50000 line failing test? 

"Do unto others as you would have them do unto you..." :)

**Comment by sorawee** [comment]
@nikivazou I have this version (http://pastebin.com/xNW3zRMm) which generates .smt2 file with less than 700 lines but still demonstrates the bug.

One weird thing, though, is that both 4.4.2 and 4.3.2 generate exactly the same file (I diff .smt2 files from both version and found nothing). Yet, the result is SAFE for one but UNSAFE for the other.

**Comment by nikivazou** [comment]
@NikolajBjorner got into it. (though initially I gave bad description of the bug)

https://github.com/Z3Prover/z3/issues/323#issuecomment-157488527

**Comment by ranjitjhala** [comment]
@sorawee, this is because set of SMT queries are those needed to:

1. *compute* the fixpoint solution, and then
2. *check* that the solution proves the desired invariants.

While (1) depends on the actual results returned by the SMT solver,
(2) is "fixed" by the source file/specifications. Thus, from your
observation, it seems that the issue is localized to the queries made
in the second phase (which is good, because its probably a lot easier
to debug!)

​

**Comment by sorawee** [comment]
Uh huh, actually there's a comment which indicates the result from SMT solver. There is one line which is different from different version of Z3, but I look at the wrong file so I didn't see it.
