### ISSUE TITLE
New prover dependency has broken the performance monitor

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#515]
The addition of the new submodule prover dependency has broken the performance monitor. Cabal is failing its build because prover isn't on hacakge.

I need to think of a way to make the script only attempt to use prover if it actually needs it. Perhaps I should get over it and just use stack? Perhaps there is some mechanism, similar to stack.yaml, that will ensure the proper add-source dependencies are used by cabal? Requires investigation.

**Comment by ranjitjhala** [comment]
You can point stack to individual GH repos IIRC.

(Yes, please use stack.)

​

**Comment by ranjitjhala** [comment]
this is fixed, right?

**Comment by christetreault** [comment]
Yes, this is no longer an issue.
