### ISSUE TITLE
Assume type signatures can lead to unsoundness 

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#517]
The [following](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1447961903_4571.hs) is unsoundly SAFE 

```
{-@ assume magic :: {v:() | false} @-}
magic :: ()
magic = undefined 

bar = head []
```

If I remove the `assume` keyword the code is UNSAFE. 
We need to be more careful on how we put assumed types in the environment.

**Comment by gridaphobe** [comment]
I don't see the problem here. Assumed signatures are precisely that.

**Comment by nikivazou** [comment]
The problem is that assume puts the false into the environment and then all your program is just SAFE.

**Comment by gridaphobe** [comment]
I understand that, but you *assumed* false at the top level.

**Comment by gridaphobe** [comment]
We definitely want to put top-level values in the global environment to handle e.g. constants. We could add a sanity check that no top-level value is refined with something inconsistent, but I don't really think it's necessary :/

**Comment by nikivazou** [comment]
Fine! But I filed the issue, because I had a definition like `magic` and all my code was unexpectedly safe. 
It is quite confusing it you do not expect this behavior.
