### ISSUE TITLE
Precise dependencies

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquidhaskell#518]
On Nov 9 (e488a60) our build was passing (except for one timed out test). On Nov 16 (854eda6) it was failing. Why? Because on Nov 10, ascii-progress 0.3 got uploaded to Hackage.

Could the cabal/stack/travis gurus please comment on how best to prevent this kind of issue in the future (assuming it's worth preventing)?

**Comment by nikivazou** [comment]
A solution is to explicitly provide version numbers is cabal/stack dependencies.
