### ISSUE TITLE
Mysterious Crash When using GADTs

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#519]
@nikivazou -- this program seems to just _crash_ LH (with one of those unpleasant length of FOO not equal to length of BAR errors...)

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1448327307_4618.hs

**Comment by nikivazou** [comment]
Ok, will look into it. Is it urgent?

**Comment by ranjitjhala** [comment]
Ok, now it became urgent, see `tests/neg/AbsApp.hs`

**Comment by ranjitjhala** [comment]
Also:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/neg/Ast.hs

**Comment by ranjitjhala** [comment]
Moved to:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/neg/Ast.hs
https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/neg/AbsRef.hs

as unlikely to get addressed in short term.

**Comment by nikivazou** [comment]
There are many many things in this issue, most of them fixed:


- GADTs generally work, see [tests/pos/GADTs.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/GADTs.hs) and [tests/neg/GADTs.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/neg/GADTs.hs)

- You can soundly use Abstract Refinements on unrefined Data Types, see [tests/neg/AbsApp.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/neg/AbsApp.hs). We used to ignore them leading to unsoundness, but not any more. 

- Application of Abstract Refinements should be enclosed by `< ... >`, so the following file that applies the abstract refinement `p` in `AstF` as `AstF p` treats `p` as a type variable/type argument and creates an error:  [tests/crash/Ast.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/crash/Ast.hs#L53)

- Recursive types are sound. The following is not UNSAFE [tests/neg/Ast.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/neg/Ast.hs#L54)

- But, recursive types are not precise. For example, see the file [tests/todo/Ast.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/Ast.hs#L54)

I can prove 

```
{-@ astExprF :: AstF <{\ix -> isExprIndex ix}> (Fix (AstF <{\ix -> isExprIndex ix}>)) @-}
astExprF :: AstF Ast
astExprF = Lit 10 IxExpr
```

But I cannot prove 
```
{-@ astExpr :: Fix (AstF <{\ix -> isExprIndex ix}>)  @-}
astExpr :: Ast
astExpr = In astExprF
```

The above code translates to a coercion `astExpr = astExprF `cast` ... ` which does not give us enough info to prove the desired type.
