### ISSUE TITLE
Haskell modules do not export measures

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#521]
Here is a simple reproducing example.  Just create the following two modules:

``` haskell
module Test where

{-@ type Nat = { v : Int | 0 <= v } @-}

{-@ measure size @-}
{-@ size    :: xs:[a] -> {v:Nat | v = size xs} @-}
size :: [a] -> Int
size []     = 0
size (_:rs) = 1 + size rs
```

``` haskell
module Test2 where

import Test

{-@ bar :: { xs : [a] | size xs > 1 } -> [a] @-}
bar :: [a] -> [a]
bar xs = xs
```

If you run `liquid` on module `Test2`, then you will get the following error:

``` bash
$ liquid Test2.hs
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.

**** DONE:  annotate ***********************************************************

**** ERROR:  *******************************************************************

 Test2.hs:5:5: Error: Bad Type Specification
 Test2.bar :: {v : [a] | size v > 1} -> [a]
     Sort Error in Refinement: {xs : [a_awu] | size xs > 1}
     Unbound Symbol size
 Perhaps you meant: snd
```

However, if you move the definition of `bar` to module `Test1` then that module type-checks correctly.

**Comment by gridaphobe** [comment]
Yikes! It appears this is specifically related to the lifting haskell functions to logical measures functionality.

Should be a straightforward fix, but in the meantime you can work around it by defining the `size` measure as

```
{-@ 
measure size :: [a] -> Int
size []     = 0
size (r:rs) = 1 + size rs
@-}
```

instead.

Thanks for the report!

**Comment by Gabriel439** [comment]
Yeah, I have no problem using the workaround for now.  Thanks for figuring this out! :)

**Comment by nikivazou** [comment]
Not entirely sure how to fix this, but will get into it!

Thanks @Gabriel439!

**Comment by Gabriel439** [comment]
You're welcome! :)

**Comment by ranjitjhala** [comment]
@nikivazou The fix I imagine should essentially be to get the lifting method to behave identically to what Eric suggested fix -- that is behave identically to using the old measure mechanism?

**Comment by nikivazou** [comment]
Then liquidHaskell should automatically rewrite the file `Test.hs`. 
The main problem is that when we import `Test` we are not supposed to look into the core, but just the exported signatures. 

The fix would be easy if liquidHaskell produced intermediate `.lhi` files to store all the exported information that we need.

**Comment by Gabriel439** [comment]
For the record, I think the workaround is actually a perfectly fine way of using Liquid Haskell.  Programming within a Liquid Haskell comment doesn't bother me at all since I don't reuse that code within Haskell anyway.

**Comment by gridaphobe** [comment]
For a long time, programming inside the comments was the only thing we supported. But you inevitably find yourself rewriting simple Haskell functions -- that you do want want to use -- as Liquid Haskell measures.

@nikivazou making LH rewrite the Haskell file is a non-starter IMO, I think we need to just bite the bullet and produce `.lhi` files.

**Comment by ranjitjhala** [comment]
This was "fixed" a while back by

https://github.com/ucsd-progsys/liquidhaskell/pull/930

See the tests

https://github.com/ucsd-progsys/liquidhaskell/blob/16ea4072c01afcd58b784242776a981360e8fdf1/tests/pos/Client521.hs

https://github.com/ucsd-progsys/liquidhaskell/blob/16ea4072c01afcd58b784242776a981360e8fdf1/tests/pos/Lib521.hs
