### ISSUE TITLE
Proving tricky type with ordering on nested constructor

### ISSUE THREAD

**Issue by michaelbeaumont** [ucsd-progsys/liquidhaskell#522]
Hi guys,

I'm trying to prove the ordering invariant on the AVL tree example.

```haskell
data Tree k = Nil
            | Branch k (Tree k) (Tree k) deriving Show

{-@ data Tree [ht] k <l :: k -> k -> Prop, r :: k -> k -> Prop>
    = Nil
    | Branch (key::k)
             (left::Tree (k <l key>) <l,r>)
             (right::Tree (k <r key>) <l,r>) @-}

{-@ type Orded k = Tree <{\key l -> key > l}, {\key r -> key < r}> k @-}
```

I ran into trouble with the balancing functions and I've boiled down the problem to the following function which just gives back the untouched tree:

```haskell
{-@ f :: key: k
          -> Orded {tv:k | tv < key}
          -> Orded {tv:k | tv > key}
          -> Orded k @-}
f key (Branch lv ll lr) r = Branch key (f lv ll lr) r
f v l r = Branch v l r
```

Typechecking gives:

```haskell
 avlplus.hs:87:54-55: Error: Liquid Type Mismatch
   Inferred type
     VV : a
  
   not a subtype of Required type
     VV : {VV : a | key > VV}
  
   In Context
     VV  : a
     key : a


 avlplus.hs:87:57-58: Error: Liquid Type Mismatch
   Inferred type
     VV : a
  
   not a subtype of Required type
     VV : {VV : a | key > VV}
  
   In Context
     VV  : a
     key : a
```

This is for `ll` and `lr`. The 2nd argument to `f` is `Orded` so `ll` and `lr` have keys less than `lv` and thus satisfy the constraints on `f`, though. This should be visible because of the pattern match on the left `Branch`. What's preventing LH from seeing this? Or am I missing something obvious?

**Comment by nikivazou** [comment]
Hello @michaelbeaumont, 

Actually liquidHaskell cannot prove that your `ll` and `lr` trees are ordered, because there is a syntactic error in your refined definition of `Tree`. The abstract refinements go between the Type Constructor and the type variables. Replace your definition with 

```
{-@ data Tree [ht] k <l :: k -> k -> Prop, r :: k -> k -> Prop>
    = Nil
    | Branch (key::k)
             (left::Tree <l, r> (k <l key>))
             (right::Tree <l, r> (k <r key>)) @-}
```

Totally our fault for suppressing this syntactic error. We should fix it soon...

**Comment by michaelbeaumont** [comment]
Of course it's something like that, thanks :). 
The thing that tripped me up then is that this doesn't match with how the type is declared on the first line...

**Comment by nikivazou** [comment]
You are 100% right! We made instantiation of abstract refinements infix because it was easier to parser, but we should definitely reconsider this choice...
