### ISSUE TITLE
Bogus documentation for --no-case-expand

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquidhaskell#528]
```
     --no-case-expand --nocaseexpand         Disable Termination Check
```

That's clearly wrong, what does that flag actually do?

**Comment by gridaphobe** [comment]
```
     --exact-data-cons --exactdc             Exact Type for Data Constructors
```

This one is also confusing. There should be an example in the README.

**Comment by nikivazou** [comment]
Would a "Do not expand all data constructors in case statement" be more explanatory?

By default if `F = A1 | A2 |  .. |  A10`, then liquidHAskell will expand  `case f of {A1 -> True; _ -> False}` to  `case f of {A1 -> True; A2 -> False; ...; A10 -> False}`

**Comment by gridaphobe** [comment]
"Don't expand the default case in a case-expression" would be my suggestion.

**Comment by gridaphobe** [comment]
*with your example in the README

**Comment by nikivazou** [comment]
Sounds good!

On Sat, Dec 5, 2015 at 11:45 AM, Eric Seidel <notifications@github.com>
wrote:

> "Don't expand the default case in a case-expression" would be my
> suggestion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/528#issuecomment-162240580>
> .
>



-- 
Niki Vazou

**Comment by ranjitjhala** [comment]
Is this fixed?

**Comment by gridaphobe** [comment]
ping @nikivazou
