### ISSUE TITLE
Type-checking incorrectly succeeds when using a very large upper bound

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#529]
I found that the following program succeeds when it should not:

```haskell
{-@
type Foo = { v : Integer | 0 <= v && v < 4611686018427387903 * 8 }
@-}

{-@ f :: i : Foo -> { o : Foo | i < o } @-}
f :: Integer -> Integer
f i = i * 2
```

The above program should not succeed because when `i = 0`, `o = i * 2 = 0` which is not greater than `i`.  However, if you change the program slightly to decrease the upper bound then the type checker correctly fails the program:

```haskell
-- The only difference is multiplying the large number by 7 instead of 8
{-@
type Foo = { v : Integer | 0 <= v && v < 4611686018427387903 * 7 }
@-}

{-@ f :: i : Foo -> { o : Foo | i < o } @-}
f :: Integer -> Integer
f i = i * 2
```

Another surprising result is that this program still fails:

```haskell
{-@
type Foo = { v : Integer | 0 <= v && v < 4611686018427387903 * 7 + 4611686018427387903 }
@-}

{-@ f :: i : Foo -> { o : Foo | i < o } @-}
f :: Integer -> Integer
f i = i * 2
```

... even though I expect it to be equivalent to the first program.

This only occurs for large numbers so I expect it is due to some sort of overflow.

**Comment by ranjitjhala** [comment]
Ouch! Will look as soon as at a computer -- but can you try with
i + I instead of *2 ?

**Comment by Gabriel439** [comment]
Using `i + 1` works correctly, meaning that both versions of the program now fail to type-check.

**Comment by ranjitjhala** [comment]
Oops sorry, typed from phone, I'd meant (i + i),
but I find that that passes (when it shouldn't).

(i + 1) _should_ type check right (as it is > i).

I fear this may be some overflow issue in Z3, but need to confirm!

On Sat, Dec 5, 2015 at 5:40 PM, Gabriel Gonzalez <notifications@github.com>
wrote:

> Using i + 1 works correctly, meaning that both versions of the program
> now fail to type-check.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/529#issuecomment-162262415>
> .
>



-- 
Ranjit.

**Comment by Gabriel439** [comment]
Using `i + i` gives the same behavior as `i * 2`

**Comment by ranjitjhala** [comment]
Hmm, the good news is that turns out that the very first of the
examples, namely,

```

{-@ type Foo = { v : Integer | 0 <= v && v < 4611686018427387903 * 8 } @-}

{-@ f :: i : Foo -> { o : Foo | i < o } @-}
f :: Integer -> Integer
f i = i * 2

```

is in fact correctly rejected by the latest LH (i.e. by the native
haskell solver, which is the default in master) but is accepted by
the ocaml solver.

@gridaphobe I think after a few of the current issues are squished,
perhaps we should do a release with the new solver?

**Comment by ranjitjhala** [comment]
To be clear: @Gabriel439 this issue appears to be a(n awful!) bug 
in the deprecated ocaml solver, but does not arise in `master`

https://github.com/ucsd-progsys/liquidhaskell/blob/master/INSTALL.md#build-with-stack-recommended

@gridaphobe we should put LH on `stackage` on next release too.

**Comment by ranjitjhala** [comment]
Added a regression test: 

tests/neg/BigNum.hs

**Comment by Gabriel439** [comment]
Thanks!  That's a perfectly fine resolution for me :)

**Comment by gridaphobe** [comment]
@ranjitjhala yep I definitely want to make a new release (and may as well put it on stackage), was just waiting for the native solver to stabilize.
