### ISSUE TITLE
Support GHC 7.10.3

### ISSUE THREAD

**Issue by FranklinChen** [ucsd-progsys/liquidhaskell#540]
When I tried to install from Hackage with Stack, I ran into the problem that I'm now on GHC 7.10.3 by default but `liquidhaskell.cabal` requires `ghc == 7.10.2`.

**Comment by gridaphobe** [comment]
Thanks for the report! It looks like `7.10.3` doesn't affect us, so I've updated the `build-depends` on hackage, you should just need to run `cabal update` (or the stack equivalent).

**Comment by ranjitjhala** [comment]
Thanks @franklinchen!

@gridaphobe: nice, so it just builds against 7.10.3?

**Comment by gridaphobe** [comment]
fixed in d8dca5e

**Comment by gridaphobe** [comment]
@ranjitjhala Yep!

**Comment by FranklinChen** [comment]
Hmm, not working for me.

```
$ stack update; stack install liquidhaskell intern liquid-fixpoint
Fetched package index.                                                                                  Run from outside a project, using implicit global project config
Using resolver: lts-3.19 from implicit global project's config file: /Users/chen/.stack/global-project/stack.yaml
Populated index cache.
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:
      ghc: needed (==7.8.3 || ==7.8.4 || ==7.10.2), 7.10.3 found
    needed for package: liquidhaskell-0.5.0.1
```

**Comment by ranjitjhala** [comment]
@franklinchen: does stack work with GHC-7.10.3? AFAICT, LTS 3.19
is still for GHC 7.10.2?

  https://www.stackage.org/lts-3.19

@gridaphobe: did you manage to get GHC 7.10.3 for the mac? The good folks
at ghcformacos don't seem to have it yet...

**Comment by FranklinChen** [comment]
It's working for me now; index must not have been updated yet earlier.

I'm using GHC 7.10.3 on Mac through Homebrew.

Also, I have in my `~/.stack/config.yaml` the line `compiler-check: newer-minor` in order to use 7.10.3 with LTS.

**Comment by gridaphobe** [comment]
According to https://github.com/commercialhaskell/stack/issues/227#issuecomment-110365360 it can take some time for `stack`'s index to update wrt hackage. It seems to be compiling for me now.

**Comment by ranjitjhala** [comment]
Ah, ok, thanks! So all good right?
​

**Comment by FranklinChen** [comment]
@ranjitjhala Yes, all good for me. P.S. I think ghcformacos is no longer being maintained so well.
