### ISSUE TITLE
Incorrect inference with top-level functions

### ISSUE THREAD

**Issue by lastland** [ucsd-progsys/liquidhaskell#541]
First, I'm quite new to both Haskell and LiquidHaskell so perhaps it's just that I have misunderstood something. :smile: 

To replicate the bug:

    {-@ type NEList a = {v: [a] | len v > 0} @-}
    {-@ idList :: NEList a -> NEList a @-}
    idList :: [a] -> [a]
    idList x = x

    a = idList [1, 2]
    b = 3 `div` (length a)

The log:

    Unsafe!
    resources/custom/liquidhaskell/sandbox/1450789460_5585.hs:7:14-21: Error: Liquid Type Mismatch
      Inferred type
        VV : Int | VV == ?a && VV == len Main.a
 
      not a subtype of Required type
        VV : Int | VV /= 0
 
      In Context
        VV     : Int | VV == ?a && VV == len Main.a
        ?a     : Int | ?a == len Main.a
        Main.a : [Integer] | len Main.a >= 0

It seems somehow LiquidHaskell fails to figure out that `len Main.a > 0`.

The same applies to:

    f x = x:(idList [1, 2])
    b = 3 `div` (length $ f 1)

However, the problem can be solved by replacing the last two lines with:

    b = 3 `div` (length a)
        where a = idList [1, 2]

or

    b = let a = idList [1, 2]
        in 3 `div` (length a)

or

    {-@ a :: NEList Integer @-}
    a = idList [1, 2]
    b = 3 `div` (length a)

**Comment by ranjitjhala** [comment]
Hi @lastland, 

this is a subtle design decision that we should perhaps make more explicit. In brief: all (top level) exported names of a module default to their unrefined haskell types if no explicit refinement signature is given. That is we do not perform inference for exported names like 'a' in your example. As you saw, making it a non top level name suffices; also hiding 'a' from the module exports would suffice if you did want to use it globally within the module.

Does that make sense? 

Thanks!

Ranjit.

Ps: @nikivazou and @gridaphobe is the above made explicit somewhere in the docs? It's a tricky point...

**Comment by nikivazou** [comment]
@lastland, as another solution you can give an explicit refined type signature for top-level binder `a`, for example 

```
{-@ a :: {v:[Int] | len v > 0} @-}
```

@ranjitjhala I do not see any mention for top level unrefined binders in the documentation, I will add it

**Comment by lastland** [comment]
@ranjitjhala @nikivazou Thanks for the explanation!

I see that "do not perform inference for exported names" suffices, but it's still not very clear to me why not to make inferences on them. Will that cause problems with multiple modules? Or it's for simplicity (perhaps this use case is rarely seen)?

**Comment by gridaphobe** [comment]
@lastland multiple modules are indeed the problem. LiquidHaskell infers types based on how the function is used, in addition to examining the function itself. This allows us to infer very precise types, but can easily lead to a scenario where the inferred type is **overly** precise. Consider

```haskell
mydiv x y = x `div` y

two = 10 `mydiv` 5
```

In this example LiquidHaskell might infer

```
mydiv :: Int -> {v:Int | v = 5} -> Int
```

which is perfectly fine for proving the `div` safe, but almost certainly **not** the type you want to export. So we disallow inference for exported functions and only check them against the types you have written.

P.S. there's a separate issue in that we don't currently have a mechanism to export inferred types, so if we let LH infer the above type for `mydiv` and then called `mydiv 1 2` in a different module, LH would not flag the call as unsafe. This could be fixed, but it wouldn't address the first issue.

**Comment by lastland** [comment]
@gridaphobe Thanks! That's a very clear explanation!

**Comment by ranjitjhala** [comment]
Nice explanation! Lets add it to the README ? :)
