### ISSUE TITLE
`liquid` doesn't work with `stack`'s package DB

### ISSUE THREAD

**Issue by pseudonom** [ucsd-progsys/liquidhaskell#548]
Create a project with `stack` and add a dependency for a package not in `base`. Running `liquid src/Lib.hs` will give an error like:

```
Invalid Source


 src/Lib.hs:4:8-19: Error: GHC Error
     Could not find module ‘Control.Lens’
Use -v to see a list of the files searched for.
```

This can be worked around with an incantation like 
```sh
liquid --ghc-option="-clear-package-db" --ghc-option="-global-package-db" --ghc-option="-package-db $(stack path --snapshot-pkg-db)" --ghc-option="-package-db $(stack path --local-pkg-db)" src/Lib.hs
```
, but it would be nice to have some better support for `stack`.

At the very least, I thought I'd document the workaround by posting here.

**Comment by gridaphobe** [comment]
Can you try `stack exec -- liquid src/Lib.hs`? That ought to make the right package db visible.

**Comment by pseudonom** [comment]
Ah, yup. Forgot about that. That also works. I might open a PR on https://github.com/ucsd-progsys/liquid-types-spacemacs for that.

**Comment by ranjitjhala** [comment]
Thanks @pseudonom !  A PR would be *greatly* appreciated ... have been meaning to do it, but my e-lisp has gotten rusty again :)
