### ISSUE TITLE
Subtyping does not seem to work with logical multiplication

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#550]
So I was playing around with a different refinement for `GHC.Num.*`:

```haskell
{-@
assume (*?)
    :: Num a
    => x : a
    -> y : a
    -> { z : a | z == x * y }
@-}
(*?) :: Num a => a -> a -> a
(*?) = (*)
```

However, small experiments with this new refinement seem to indicate that logical multiplication does not support subtyping correctly.  Here is one example:

```haskell
{-@ example :: { v : Int | v == 2 * 3 } @-}
example :: Int
example = 2 *? 3
```

This fails with:

```
 minimize.hs:13:11-16: Error: Liquid Type Mismatch
   Inferred type
     VV : {VV : Int | VV == ?a * ?b}
  
   not a subtype of Required type
     VV : {VV : Int | VV == 2 * 3}
  
   In Context
     VV : {VV : Int | VV == ?a * ?b}
     ?a : {?a : Int | ?a == 2}
     ?b : {?b : Int | ?b == 3}
```

... which seems like a weird type error.  I'd expect that to type-check because Liquid Haskell knows from the context that `?a == 2` and `?b == 3`.

**Comment by Gabriel439** [comment]
As a control, I repeated the same experiment for addition and there were no issues.  Both of the following programs type-check:

```haskell
{-@
assume (+?)
    :: Num a
    => x : a
    -> y : a
    -> { z : a | z == x + y }
@-}
(+?) :: Num a => a -> a -> a
(+?) = (+)

{-@ example :: { v : Int | v == 2 + 3 } @-}
example :: Int
example = 2 +? 3
```

... or just:

```haskell
{-@ example :: { v : Int | v == 2 + 3 } @-}
example :: Int
example = 2 + 3
```

**Comment by ranjitjhala** [comment]
@Gabriel439  -- thanks! 

1. Can you add `{-@ LIQUID "--real" @-}` to the top of the file, and it works for me.

2. However, in your case, if you really only want "uninterpreted" multiplication, then 
    oddly, for me this works when I replace your infix `(*?)` with just `mul`, which is 
    quite odd. @nikivazou any idea?

(Either way, can you confirm that the above work for you? Thanks!)

**Comment by Gabriel439** [comment]
The `{-@ LIQUID "--real" @-}` flag worked!

Could you clarify what you mean about using `mul`?  I tried using it both at the term-level and type-level and in both cases it says the symbol is not in scope

**Comment by ranjitjhala** [comment]
Oh, I meant just replace the string `(*?)` with `mul` and `2 *? 3` with `mul 2 3`.

Oddly, the following file (verbatim) works for me now. (I can swear it wasn't a moment ago!)

```
module Goo where

{-@
assume (*?) 
    :: Num a
    => x : a
    -> y : a
    -> { z : a | z == x * y }
@-}
(*?) :: Num a => a -> a -> a
(*?) = (*) 

{-@ example :: { v : Int | v == 2 * 3 } @-}
example :: Int
example = 2 *? 3

```

Does it work for you? (Btw, with `--real` you should get commutativity, associativity, etc. and also be able to, e.g. replace `2 * 3` with `6`)

**Comment by Gabriel439** [comment]
That still doesn't type-check for me (even if I rename `(*?)` to `mul`).  Maybe I need to install a newer version since mine seems to be version `2009-15`

**Comment by Gabriel439** [comment]
Actually, I just built `liquid` off of `master` and the program still does not type-check (and the version is still the same: `2009-15`).

**Comment by ranjitjhala** [comment]
Yes, I just checked it works with a fresh clone of master...

**Comment by Gabriel439** [comment]
I wonder if it's a difference in the `z3` version.  Mine is version `4.4.2`

**Comment by ranjitjhala** [comment]
Oh! Thats possible too. I'm on 4.3.2. It shouldn't matter though, but still let me check!

**Comment by ranjitjhala** [comment]
Just tried with z3-4.4.1 from here:

https://github.com/Z3Prover/z3/releases

and it seems to do the right thing. 

@Gabriel439, can you do a fresh clone & build as described here:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/INSTALL.md#build-with-stack-recommended

(We recently did a bunch of spring cleaning so that may have thrown various things off...)

Sorry about the hassle!

**Comment by Gabriel439** [comment]
I already followed those exact instructions (fresh checkout of SHA 13cce997d5df44e8a52d0567f8bbed9cce30c8a4) and built with `stack install` and verified that I'm using the newly created executable.

I will try to build `z3-4.4.1` to see if the minor version is responsible for the difference.

**Comment by ranjitjhala** [comment]
Ok, I'll try with 4.4.2 too. Did you build that version from source? (I can't seem to find a pre-built binary on GH)

**Comment by ranjitjhala** [comment]
Also, assuming you're running this in a file called `/path/to/$FILE.hs` can you post the contents of:
`path/to/.liquid/$FILE.hs.smt2` (thats the trace of SMT interactions, just want to check if there's something odd over there...)

Thanks!

**Comment by nikivazou** [comment]
Both examples are safe for me (both `Int` and `Num`). 

@ranjitjhala how do we encode **integer multiplication** in `z3`? I suspect there is a "bug" related to this one https://github.com/Z3Prover/z3/issues/323, i.e., they change the behavior of integer multiplication from z3-3 to z3-4.

**Comment by ranjitjhala** [comment]
(In the version I am running) with `--real` we encode it as:

```
(define-fun Z3_OP_MUL ((x Real) (y Real)) Real (* x y))
```

and _without_ it we encode it as: 

```
(declare-fun Z3_OP_MUL (Real Real) Real)
```

i.e. as an uninterpreted function (UIF). In @Gabriel439's example, it is used just as an UIF,
so it should work in both cases (and does, for me), i.e. with or without `--real` so I am puzzled and the `.smt2` trace should help to pinpoint if it is indeed some z3 oddness.

**Comment by nikivazou** [comment]
I see. Btw, the example fails in the online demo too 
http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1451326243_6114.hs

Is there a way to extract the .fq file from there?

**Comment by ranjitjhala** [comment]
Aha! Yes, I will get it from there, thanks!

**Comment by ranjitjhala** [comment]
Oops. Unfortunately, the web demo used a rather old version of LH.

The reason that it fails on the old version is that the `2 * 3` 
in the signature gets replaced with `6` prior to the SMT 
query (due to some "optimizations" in the old ocaml solver.)

However, this (shouldn't and) doesn't happen with the current 
solver, so I suspect the reason for failure is different.

**Comment by Gabriel439** [comment]
Alright, so when I run `liquid` on this file:

```haskell
module Goo where

{-@
assume (*?)
    :: Num a
    => x : a
    -> y : a
    -> { z : a | z == x * y }
@-}
(*?) :: Num a => a -> a -> a
(*?) = (*)

{-@ example :: { v : Int | v == 2 * 3 } @-}
example :: Int
example = 2 *? 3
```

... then the type-checking fails as described above and I get this output in `.liquid/reproduce.hs.fqout.smt2`: 

```
(set-option :auto-config false)
(set-option :model true)
(set-option :model.partial false)
(set-option :smt.mbqi false)
(define-sort SMT_Elt () Int)
(define-sort SMT_Set () (Array SMT_Elt Bool))
(define-fun smt_set_emp () SMT_Set ((as const SMT_Set) false))
(define-fun smt_set_mem ((x SMT_Elt) (s SMT_Set)) Bool (select s x))
(define-fun smt_set_add ((s SMT_Set) (x SMT_Elt)) SMT_Set (store s x true))
(define-fun smt_set_cup ((s1 SMT_Set) (s2 SMT_Set)) SMT_Set ((_ map or) s1 s2))
(define-fun smt_set_cap ((s1 SMT_Set) (s2 SMT_Set)) SMT_Set ((_ map and) s1 s2))
(define-fun smt_set_com ((s SMT_Set)) SMT_Set ((_ map not) s))
(define-fun smt_set_dif ((s1 SMT_Set) (s2 SMT_Set)) SMT_Set (smt_set_cap s1 (smt_set_com s2)))
(define-fun smt_set_sub ((s1 SMT_Set) (s2 SMT_Set)) Bool (= smt_set_emp (smt_set_dif s1 s2)))
(define-sort SMT_Map () (Array SMT_Elt SMT_Elt))
(define-fun smt_map_sel ((m SMT_Map) (k SMT_Elt)) SMT_Elt (select m k))
(define-fun smt_map_sto ((m SMT_Map) (k SMT_Elt) (v SMT_Elt)) SMT_Map (store m k v))
(declare-fun z3v63 () Int)
(declare-fun z3f64 (Int) Int)
(declare-fun z3v65 () Int)
(declare-fun z3v66 () Int)
(declare-fun z3v67 () Int)
(declare-fun z3v68 () Int)
(declare-fun z3f69 (Int Int) Int)
(declare-fun z3v70 () Int)
(declare-fun z3v71 () Int)
(push 1)
(assert (= z3v71 (z3f69 z3v67 z3v68)))
(assert (= z3v68 3))
(assert (= z3v67 2))
(assert (= z3v70 (z3f69 z3v67 z3v68)))
(assert (= (z3f64 z3v66) z3v66))
(assert (= (z3f64 z3v65) z3v65))
(assert (= (z3f64 z3v63) z3v63))
(push 1)
(assert (not (= z3v71 6)))
(check-sat)
(pop 1)
(pop 1)
```

When I add the `{-@ LIQUID "--real" @-}` pragma to the top of the file then type-checking succeeds and the contents of the `.liquid/reproduce.hs.fqout.smt2` file change to:

```
(set-option :auto-config false)
(set-option :model true)
(set-option :model.partial false)
(set-option :smt.mbqi false)
(define-sort SMT_Elt () Int)
(define-sort SMT_Set () (Array SMT_Elt Bool))
(define-fun smt_set_emp () SMT_Set ((as const SMT_Set) false))
(define-fun smt_set_mem ((x SMT_Elt) (s SMT_Set)) Bool (select s x))
(define-fun smt_set_add ((s SMT_Set) (x SMT_Elt)) SMT_Set (store s x true))
(define-fun smt_set_cup ((s1 SMT_Set) (s2 SMT_Set)) SMT_Set ((_ map or) s1 s2))
(define-fun smt_set_cap ((s1 SMT_Set) (s2 SMT_Set)) SMT_Set ((_ map and) s1 s2))
(define-fun smt_set_com ((s SMT_Set)) SMT_Set ((_ map not) s))
(define-fun smt_set_dif ((s1 SMT_Set) (s2 SMT_Set)) SMT_Set (smt_set_cap s1 (smt_set_com s2)))
(define-fun smt_set_sub ((s1 SMT_Set) (s2 SMT_Set)) Bool (= smt_set_emp (smt_set_dif s1 s2)))
(define-sort SMT_Map () (Array SMT_Elt SMT_Elt))
(define-fun smt_map_sel ((m SMT_Map) (k SMT_Elt)) SMT_Elt (select m k))
(define-fun smt_map_sto ((m SMT_Map) (k SMT_Elt) (v SMT_Elt)) SMT_Map (store m k v))
(declare-fun z3v62 () Int)
(declare-fun z3f63 (Int) Int)
(declare-fun z3v64 () Int)
(declare-fun z3v65 () Int)
(declare-fun z3v66 () Int)
(declare-fun z3v67 () Int)
(declare-fun z3v68 () Int)
(declare-fun z3v69 () Int)
(push 1)
(assert (= z3v69 (* z3v67 z3v66)))
(assert (= z3v66 3))
(assert (= z3v67 2))
(assert (= z3v68 (* z3v67 z3v66)))
(assert (= (z3f63 z3v65) z3v65))
(assert (= (z3f63 z3v64) z3v64))
(assert (= (z3f63 z3v62) z3v62))
(push 1)
(assert (not (= z3v69 6)))
(check-sat)
(pop 1)
(pop 1)
```

**Comment by ranjitjhala** [comment]
From the contents of the file, I'm pretty sure thats the
"old" ocaml fixpoint thats running, not the new (haskell) one.

Can you tell me if:

1. There is a file created called `.liquid/reproduce.hs.fq` ?

2. There is a binary file called `fixpoint.native` anywhere on your path?

3. If the answer to either of the above is "yes" then can you
   just _delete_ the `fixpoint.native` file and see if things
   work (it shouldn't).

My hunch is that you're running the latest LH but against an
older "liquid-fixpoint" which is causing this?

To avoid any submodule weirdness, can you try this:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/INSTALL.md#build-with-stack-recommended

I just did the above, and it generates a very different .smt2 file.

Apologies again for the hassle!

Thanks!

**Comment by Gabriel439** [comment]
1.  Yes, there is a file called `.liquid/reproduce.hs.fq`
2.  Yes, there is a binary called `fixpoint.native` on my path

I followed your instructions and deleted the `fixpoint.native` on my path and reinstalled using `stack install` and now everything works.  Thanks!
