### ISSUE TITLE
Missing binder in Error Message

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#558]
In [tests/todo/TypeError.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/c85d0b2d358e39070c11781794387ed56b39e9cc/tests/todo/TypeError.hs) the type error does not print the binder `pr1`

```
tests/todo/TypeError.hs:41:26-54: Error: Liquid Type Mismatch
   Inferred type
     VV : {VV : Proof | VV == pr1 && VV >= pr1 && VV <= pr1}

   not a subtype of Required type
     VV : {VV : Proof | runFun (runFun bind (Append.N)) return == Append.N}

   In Context
     return := (Arrow a (L b))

     VV := {VV : Proof | VV == pr1 && VV >= pr1 && VV <= pr1}

     bind := (Arrow (L b) (Arrow a (L c)))

     Append.N := (L a)
```

**Comment by ranjitjhala** [comment]
Looks like this is due to the various uniqify/renaming done by fixpoint. 

Currently working on it in `tidy`, see `UX.Errors.tidyCtx`.

**Comment by ranjitjhala** [comment]
See:

https://github.com/ucsd-progsys/liquidhaskell/pull/562

however, @nikivazou -- the binder `pr1` does't have a 
non-trivial refinement even in the `.fq` file... hence that 
is what is getting printed out? Please explain!

**Comment by nikivazou** [comment]
Do you mean that `pr1` has a true refinement?
