### ISSUE TITLE
`assume` should fail to compile if it references unbound symbols

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#569]
First, let's begin with an example program without `assume`:

```haskell
a :: Int
a = 0

{-@ b :: { b : Int | a < b } @-}
b :: Int
b = 1

{-@
f :: a : Int -> { b : Int | a < b } -> ()
@-}
f :: Int -> Int -> ()
f _ _ = ()

g :: ()
g = f a b
```

The above program correctly fails with an unbound symbol error:

```
 test3.hs:4:5: Error: Bad Type Specification
 Main.b :: {b : Int | a < b}
     Sort Error in Refinement: {b : int | a < b}
     Unbound Symbol a
 Perhaps you meant: b
```

However, if I add an `assume` to the type of `b` like this:

```haskell
{-@ assume b :: { b : Int | a < b } @-}
```

... the type-checker does not complain and instead produces an seemingly contradictory type-checking error:

```haskell
 test3.hs:15:9: Error: Liquid Type Mismatch
   Inferred type
     VV : {VV : Int | VV == Main.b}
  
   not a subtype of Required type
     VV : {VV : Int | Main.a < VV}
  
   In Context
     VV     : {VV : Int | VV == Main.b}
     Main.a : Int
     Main.b : {Main.b : Int | a < Main.b}
```

The real issue is that the `a` in the type signature for `Main.b` is the unbound symbol and not the same as the `a` in the required type.

**Comment by nikivazou** [comment]
Thanks @Gabriel439! As usual great bug report! assumed and specified types should be treated exactly the same! I am fixing it!

**Comment by ranjitjhala** [comment]
Fixed by PR #570

**Comment by Gabriel439** [comment]
Thank you! :)

**Comment by Gabriel439** [comment]
Marking this closed since this was fixed
