### ISSUE TITLE
Building via stack fails on Fixpoint dependency issue

### ISSUE THREAD

**Issue by spinda** [ucsd-progsys/liquidhaskell#571]
Building via `stack` fails when trying to build `liquid-fixpoint`:

```
➜  liquidhaskell git:(master) ✗ stack build
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:
      cereal: needed (>=0.5), 0.4.1.1 found (latest applicable is 0.5.1.0)
    needed for package: liquid-fixpoint-0.6.1

--  Failure when adding dependencies:
      liquid-fixpoint: needed (>=0.6.1 && <0.7), couldn't resolve its dependencies
      prover: needed (-any), couldn't resolve its dependencies
    needed for package: liquidhaskell-0.6.0.0

--  Failure when adding dependencies:
      liquid-fixpoint: needed (>=0.5), couldn't resolve its dependencies
    needed for package: prover-0.1.0.0
```

This is because the [`nightly-2016-01-06` resolver](https://www.stackage.org/nightly-2016-01-06) that `liquidhaskell` is using in its `stack.yaml` is on `cereal-0.4.1.1`, and `liquid-fixpoint` specifies `cerea >= 0.5`.

One (bad, temporary) fix is to add `- cereal-0.5.1.0` to the `extra-deps` section of `liquidhaskell`'s `stack.yaml` fie. Another (better) fix is to relax `liquid-fixpoint`'s dependency to `cereal >= 0.4`, if there are no compatibility issues.

**Comment by ranjitjhala** [comment]
Can you relax it and see if its ok?

(I'm building against 2015-09-*)

**Comment by spinda** [comment]
Sure, trying it now.

**Comment by spinda** [comment]
Relaxing the bound and switching `liquid-fixpoint` over to the same resolver as LH (so it tries to build with `cereal-0.4.1.1`) seems to work fine.
