### ISSUE TITLE
Endless loop passes termination check

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#577]
The following code loops endlessly, but passes the termination checker:

```haskell
{-@ LIQUID "--real" @-}

{-@ search :: { hi : Int | 0 < hi } -> Int @-}
search :: Int -> Int
search hi = search (hi `div` 2)
```

This seems like an incorrect interaction between the termination checker and the `--real` flag.  The type-checker doesn't seem to realize that the precondition for the recursive call is not satisfied for the case where `hi = 1`.

**Comment by ranjitjhala** [comment]
Oops -- thanks for pointing out!  Wonder if this is more Z3 weirdness, because I get the right behavior on the below file. @Gabriel439 what do you get when you do `z3 --version` ?

```
module Main where

{-@ LIQUID "--real" @-}

{-@ search :: { hi : Int | 0 < hi } -> Int @-}
search :: Int -> Int
search hi = search (hi `div` 2)
```

the result 


```
rjhala@borscht ~/r/s/l/liquidhaskell (master)> stack exec -- liquid tests/neg/TermReal.hs 
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.

**** RESULT: UNSAFE ************************************************************

 tests/neg/TermReal.hs:7:21-30: Error: Liquid Type Mismatch
 
 7 | search hi = search (hi `div` 2)
                         ^^^^^^^^^^
 
   Inferred type
     VV : {VV : Int | VV == ?b}
  
   not a subtype of Required type
     VV : {VV : Int | 0 < VV && VV < hi && VV >= 0}
  
   In Context
     VV := {VV : Int | VV == ?b}

     hi := {hi : Int | 0 < hi}

     ?b := {?b : Int | ?b == hi / ?a && (hi >= 0 && ?a >= 0 => ?b >= 0) && (hi >= 0 && ?a >= 1 => ?b <= hi)}

     ?a := {?a : Int | ?a == 2}
```

**Comment by Gabriel439** [comment]
I appeared to have `z3-4.4.2` installed.  I downgraded to 4.4.1 but I still encounter the same issue.

**Comment by ranjitjhala** [comment]
Actually I know what the issue is -- its our overloading of `Int` and `Real` in 
 
`Language.Fixpoint.Smt.Theories.uifDef`

In the version @Gabriel439 has, rather than failing, its treating it as `Real` and
so the result is actually non-zero...

**Comment by ranjitjhala** [comment]
Hold on, I have an easy fix, but someone changed the stack resolver so its now downloading GHC 7.10.3 :)

**Comment by Gabriel439** [comment]
No hurry :)

**Comment by ranjitjhala** [comment]
@Gabriel439 this should be fixed in the new master, can you confirm? I'd suggest a fresh clone per:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/INSTALL.md#build-with-stack-recommended

to avoid any submodule hassles...

**Comment by Gabriel439** [comment]
I can confirm that `master` now works correctly!
