### ISSUE TITLE
Data refinement error messages

### ISSUE THREAD

**Issue by abakst** [ucsd-progsys/liquidhaskell#587]
Running `liquid` on the following:

~~~~{.haskell}
module Boo where
{-@ data T = C { x :: Int } @-}
data T = C { x :: Int, y :: Int }
~~~~~

Produces the error message `safeZipWith called on non-eq-sized lists (nxs = 1, nys = 2) : defRefType dc = Boo.C` which presumably is a complaint that the number of arguments given to `C` in the refinement do not match the "base" definition. This could be made more clear in the error output, e.g. along the lines of "Number of arguments given to `C` in spec (1) do not match the definition (2)."

**Comment by ranjitjhala** [comment]
Super, thanks! On it!

**Comment by ranjitjhala** [comment]
Should be fixed by https://github.com/ucsd-progsys/liquidhaskell/pull/589
