### ISSUE TITLE
Cyclic Alias Definitions

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#592]
In `genEApp2` branch the predicate alias definition  from [todo/gadtEval.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/f113f7d95dd5d348e8e018f416e5e0a45f06bb16/tests/todo/gadtEval.hs)

```
{-@ predicate TInt X   = ((eType X) = TInt)  @-}
```

crashes as cyclic 

```
 tests/todo/gadtEval.hs:62:15: Error: Cyclic Alias Definitions
 The following alias definitions form a cycle:
     Type alias: TInt
     Defined at: tests/todo/gadtEval.hs:62:15


 tests/todo/gadtEval.hs:63:15: Error: Cyclic Alias Definitions
 The following alias definitions form a cycle:
     Type alias: TBool
     Defined at: tests/todo/gadtEval.hs:63:15
```

@spinda is this expected behavior of the cyclic check or did I break it now? How do you distinguish between Data Constructors and predicate aliases?

**Comment by gridaphobe** [comment]
Regardless of what the behavior was, can we just declare that having separate namespaces for datacons and predicates is a BAD THING?

In other words, I would mark 

```
{-@ predicate TInt X   = ((eType X) = TInt)  @-}
```
as bad, not because of a cyclic definition, but because there's already a `TInt` in scope.

**Comment by ranjitjhala** [comment]
Sure, if it helps to have separate names then let's just do that and move on...

**Comment by nikivazou** [comment]
Sure, this solves the problem, I just found it weird that my edits fired this test to break, because my edits seem totally irrelevant.

**Comment by ranjitjhala** [comment]
Can we close this?

**Comment by nikivazou** [comment]
Sure, different name space "fixes" the issue.
