### ISSUE TITLE
Using GHC generics causes liquid haskell to panic

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#598]
If I try to type-check this program:

```haskell
{-# LANGUAGE DeriveGeneric #-}

import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))

data Point = Point
    { x :: {-# UNPACK #-} !Int
    } deriving (Generic)

instance NFData Point
```

... it fails with a panic at the core extraction step:

```
**** DONE:  Extracted Core using GHC *******************************************
 
liquid: <no location info> Unexpected panic (!)
    (Another Broken Test!!!) splitc unexpected:
{lq_tmp$x##1409 : (Control.DeepSeq.GNFData (GHC.Generics.M1 GHC.Generics.D Main.D1Point (GHC.Generics.M1 GHC.Generics.C Main.C1_0Point (GHC.Generics.M1 GHC.Generics.S Main.S1_0_0Point (GHC.Generics.K1 GHC.Generics.R GHC.Types.Int))))) | lq_tmp$x##1409 == $dGNFData_a4BT}

lq_tmp$x##1391:(GHC.Generics.Rep Main.Point a) -> ()
gabriel@wind:~/proj/succinct-vector$ xsel --clipboard < test.hs
```

This occurs when deriving other classes, too, like `Binary`.

**Comment by ranjitjhala** [comment]
Thanks Gabriel!!

Folks we should fix this right away, we need to support auto derived generics for another reason that just occurred to me yesterday too...

@nikivazou or @gridaphobe do you have some cycles? Or shall I take a look?

**Comment by gridaphobe** [comment]
I can take a look. Is the other reason Target?

**Comment by Gabriel439** [comment]
Oh, I forgot to mention that the strictness/`UNPACK` annotations don't matter.  I just forgot to remove them when minimizing the example

**Comment by Gabriel439** [comment]
Thank you! :)
