### ISSUE TITLE
`false` after bind type-checks for some monads but not others

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#638]
The following code correctly fails to type-check:

```haskell
{-@
error :: { x : String | false } -> a
@-}

example :: Maybe ()
example = do
    _ <- return ()
    error "URK"
```

... but if you replace `Maybe` in the above example with `Data.Binary.Get` then the code successfully type-checks.

I tested a variety of monads to see which ones type-checked and which ones did not.

Monads that do not type-check for the above code:

* `Maybe`
* `Either e`
* `[]`
* `Identity`
* `Proxy`
* `Monad m => m` (i.e. generalizing the constraint to any `Monad`)
* `State`
* `Cont`
* `Managed`

Monads that type-check for the above code:

* `Turtle.Shell`
* `Data.Binary.Get`
* `Data.Serialize.Get`

Note that the last few monads **do** fail to type-check if you change the code to:

```haskell
example :: Shell ()
example = do
    return () -- (i.e. use `(>>)` instead of `(>>=)`)
    error "URK"
```

In my particular case I was interested in `Data.Serialize.Get`, which is why I'm trying to figure out why it does not detect an `error`-induced failure after a `(>>=)`.

**Comment by ranjitjhala** [comment]
Yikes! Thanks very much for pointing this out! For my own reference, here's a single file that demonstrates the soundness bug. Will look into this right away!

```
module Example (example) where

import qualified Data.Binary

{-@ myerror :: { x : String | false } -> a @-}
myerror = error

-- This WRONGLY is marked SAFE
-- type M = Data.Binary.Get

-- This (correctly) is marked UNSAFE
type M = Maybe

example :: M ()
example = return () >>= \_ -> myerror "URK"
```

**Comment by ranjitjhala** [comment]
@nikivazou here's the CORE in the two cases, looks very similar:

```
[Example.example :: Example.M ()
 [LclIdX, Str=DmdType]
 Example.example =
   let {
     lq_anf$ :: GHC.Base.Maybe ()
     [LclId, Str=DmdType]
     lq_anf$ =
       GHC.Base.return
         @ GHC.Base.Maybe GHC.Base.$fMonadMaybe @ () GHC.Tuple.() } in
   let {
     lq_anf$ :: () -> GHC.Base.Maybe ()
     [LclId, Str=DmdType]
     lq_anf$ =
       \ _ [Occ=Dead] ->
         let {
           lq_anf$ :: GHC.Prim.Addr#
[Example.example :: Example.M ()
 [LclIdX, Str=DmdType]
 Example.example =
   let {
     lq_anf$ :: GHC.Base.Maybe ()
     [LclId, Str=DmdType]
     lq_anf$ =
       GHC.Base.return
     lq_anf$ =
       GHC.Base.return
         @ GHC.Base.Maybe GHC.Base.$fMonadMaybe @ () GHC.Tuple.() } in
   let {
     lq_anf$ :: () -> GHC.Base.Maybe ()
     [LclId, Str=DmdType]
     lq_anf$ =
       \ _ [Occ=Dead] ->
         let {
           lq_anf$ :: GHC.Prim.Addr#
           [LclId, Str=DmdType]
           lq_anf$ = "URK"# } in
         let {
           lq_anf$ :: [GHC.Types.Char]
           [LclId, Str=DmdType]
           lq_anf$ = GHC.CString.unpackCString# lq_anf$ } in
         GHC.Err.error @ (GHC.Base.Maybe ()) lq_anf$ } in
   GHC.Base.>>=
     @ GHC.Base.Maybe GHC.Base.$fMonadMaybe @ () @ () lq_anf$ lq_anf$]


*************** Transform Rec Expr CoreBinds *****************
[Example.example :: Example.M ()
 [LclIdX, Str=DmdType]
 Example.example =
   let {
     lq_anf$ :: Data.Binary.Get.Internal.Get ()
     [LclId, Str=DmdType]
     lq_anf$ =
       GHC.Base.return
         @ Data.Binary.Get.Internal.Get
         Data.Binary.Get.Internal.$fMonadGet
         @ ()
         GHC.Tuple.() } in
   let {
     lq_anf$ :: () -> Data.Binary.Get.Internal.Get ()
     [LclId, Str=DmdType]
     lq_anf$ =
       \ _ [Occ=Dead] ->
         let {
           lq_anf$ :: GHC.Prim.Addr#
           [LclId, Str=DmdType]
           lq_anf$ = "URK"# } in
         let {
           lq_anf$ :: [GHC.Types.Char]
           [LclId, Str=DmdType]
           lq_anf$ = GHC.CString.unpackCString# lq_anf$ } in
         GHC.Err.error @ (Data.Binary.Get.Internal.Get ()) lq_anf$ } in
   GHC.Base.>>=
     @ Data.Binary.Get.Internal.Get
     Data.Binary.Get.Internal.$fMonadGet
     @ ()
     @ ()
     lq_anf$
     lq_anf$]
```

**Comment by ranjitjhala** [comment]
May have to look at the generated constraints ... something weird is going on...

**Comment by gridaphobe** [comment]
Here's a diff of the constraints https://gist.github.com/gridaphobe/4a27a71253499cc30bf6.

A couple of things stand out immediately:
1. there's a whole constraint missing in the `maybe` version
2. https://gist.github.com/gridaphobe/4a27a71253499cc30bf6#file-gistfile1-diff-L140-L150 has the subtyping relation swapped between `k_96` and `k_73` (!)

**Comment by ranjitjhala** [comment]
Wonder if some co / contra variant thing is going on...

**Comment by gridaphobe** [comment]
That was my initial thinking too, but looking closer at the constraints, I think the swapping *may* be a red herring. The binders don't have the same allocation of kvars either

https://gist.github.com/gridaphobe/4a27a71253499cc30bf6#file-gistfile1-diff-L47-L70

Does the new fixpoint support printing a dot file? I wonder if that might be easier to look at than a textual diff?

**Comment by ranjitjhala** [comment]
--savequery

**Comment by Gabriel439** [comment]
Another thing that I forgot to mention is that Liquid Haskell infers the refinement `false` for the bound value.  If you give the bound value a name then Liquid Haskell gives the following warning:

```
WARNING: Found false in test.hs:13:5
```

... and if you look at inferred type of the bound value it has a refined type of `{ x : () | false }`.

**Comment by gridaphobe** [comment]
@ranjitjhala sorry, I meant a `.dot` file, ie for graphviz.

@Gabriel439 yep, that's why LH is able to "prove" the `error` call safe. It infers false and can then prove anything it that branch. But it shouldn't be able to prove false here!

**Comment by ranjitjhala** [comment]
@gridaphobe sorry, thats `--elimstats` (to get the .dot) file. The resulting graphs look like this:

(for the MAYBE case)
[bob-maybe.pdf](https://github.com/ucsd-progsys/liquidhaskell/files/175277/bob-maybe.pdf)

(for the BINARY case)
[bob-serial.pdf](https://github.com/ucsd-progsys/liquidhaskell/files/175278/bob-serial.pdf)

digging further, I see that LH generates the same subtyping constraints, in particular:

for the MAYBE case `RENV |- Maybe K72 <: Maybe K131`
 
and the BINARY case `RENV |- Get K72 <: Get K131`

the MAYBE yields a (correct) fq constraint `... |- K72 => K131`

the BINARY yields an (incorrect?) fq constraint `... |- K131 => K72` (which is why `K131` is solved to `False`.)

This is the source for [Data.Binary.Get](http://hackage.haskell.org/package/binary-0.8.2.1/docs/src/Data.Binary.Get.Internal.html#Get), namely 

```
newtype Get a = C { runCont :: forall r.
                               B.ByteString ->
                               Success a r ->
                               Decoder   r }

type Success a r = B.ByteString -> a -> Decoder r
```

I believe that the `a` is actually appearing *positively* i.e.

```
newtype Get a = C { runCont :: forall r.
                               B.ByteString ->
                               ( B.ByteString -> a -> Decoder r )  ->
                               Decoder   r }
```

@nikivazou are we computing the *wrong* polarity for the type variable `a` here ? Or am I missing something?



```
RENV
Example.myerror##roZ := lq_tmp$x##51:{VV : [(GHC.Types.Char <>)]<\fldList VV -> (GHC.Types.Char <>)> | false} -> a

lq_anf$##dzD := (GHC.Base.Maybe <> {lq_tmp$x##74 : ()<>^"lq_tmp$x##73" "lq_tmp$x##27" | $k_##72[VV##71:=lq_tmp$x##74][lq_tmp$x##24:=GHC.Tuple.$40$$41$$35$$35$70]})

lq_anf$##dzG := ds_dzC:{VV##77 : ()<>^"lq_tmp$x##79" | $k_##78} -> {VV##84 : (GHC.Base.Maybe <> {VV##81 : ()<>^"lq_tmp$x##83" | $k_##82})^"lq_tmp$x##86" | $k_##85}
||- {lq_tmp$x##139 : (GHC.Base.Maybe <> {lq_tmp$x##138 : ()<>^"lq_tmp$x##73" "lq_tmp$x##27" | $k_##72[VV##71:=lq_tmp$x##138][lq_tmp$x##74:=lq_tmp$x##138][lq_tmp$x##68:=lq_tmp$x##139][lq_tmp$x##24:=GHC.Tuple.$40$$41$$35$$35$70]})^"lq_tmp$x##67" "lq_tmp$x##26" | lq_tmp$x##139 == lq_anf$##dzD}
    <:
    (GHC.Base.Maybe <> {lq_tmp$x##133 : ()<>^"lq_tmp$x##132" "lq_tmp$x##14" | $k_##131[VV##130:=lq_tmp$x##133]})
```

for the BINARY case
```
RENV
lq_anf$##dIu := ds_dIq:{VV##77 : ()<>^"lq_tmp$x##79" | $k_##78} -> {VV##84 : (Data.Binary.Get.Internal.Get <> {VV##81 : ()<>^"lq_tmp$x##83" | $k_##82})^"lq_tmp$x##86" | $k_##85}

Example.myerror##roZ := lq_tmp$x##51:{VV : [(GHC.Types.Char <>)]<\fldList VV -> (GHC.Types.Char <>)> | false} -> a

lq_anf$##dIr := (Data.Binary.Get.Internal.Get <> {lq_tmp$x##74 : ()<>^"lq_tmp$x##73" "lq_tmp$x##27" | $k_##72[VV##71:=lq_tmp$x##74][lq_tmp$x##24:=GHC.Tuple.$40$$41$$35$$35$70]})
||- {lq_tmp$x##139 : (Data.Binary.Get.Internal.Get <> {lq_tmp$x##138 : ()<>^"lq_tmp$x##73" "lq_tmp$x##27" | $k_##72[VV##71:=lq_tmp$x##138][lq_tmp$x##74:=lq_tmp$x##138][lq_tmp$x##68:=lq_tmp$x##139][lq_tmp$x##24:=GHC.Tuple.$40$$41$$35$$35$70]})^"lq_tmp$x##67" "lq_tmp$x##26" | lq_tmp$x##139 == lq_anf$##dIr}
    <:
    (Data.Binary.Get.Internal.Get <> {lq_tmp$x##133 : ()<>^"lq_tmp$x##132" "lq_tmp$x##14" | $k_##131[VV##130:=lq_tmp$x##133]})
```

**Comment by ranjitjhala** [comment]
@nikivazou 
my hunch is the bug is in `Language.Haskell.Liquid.Types.RefType.mkTyConInfo` 
in particular, in https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/Types/RefType.hs#L1074-L1079
(which is in dire need of cleaning up...) In the `AppTy t1 t2` case, can odd things can happen? e.g. if you don’t “expand” the type-alias before descending? 

Assuming that GHC represents the type of `Get a` as:

```
B.ByteString -> (AppTy (TyConApp Success a) r) -> Decoder   r
```

+ If you *don’t expand*  the `TyConApp` then `a` appears “negatively” (contra-variant) but 
+ If you *do expand* the `TyConApp` then `a` is in fact "positive" (co-variant). 

Could this be the problem?

**Comment by nikivazou** [comment]
@ranjitjhala you are right, the variance information says that  the type variable of `Data.Binary.Get.Internal.Get` is contravariant. Looking now why this is inferred

**Comment by Gabriel439** [comment]
Some evidence in support of @ranjitjhala's hypothesis: if you look at `Get`, `Shell`, and `Cont`, all three of them have the type parameter in the double-negative position, but only the first two have the second negation hidden behind another type, which may be way `Get` and `Shell` behave incorrectly whereas `Cont` behaves correctly.

**Comment by nikivazou** [comment]
Yes! @ranjitjhala 's theory is  correct: variance is not computed correct, when it depends on variance of other type constructors. Will fix it very soon!

Thanks for the reports @Gabriel439!

**Comment by nikivazou** [comment]
This is fixed in the develop branch!

@Gabriel439 you can check out the develop branch or wait some more time to merge develop into master.

**Comment by nikivazou** [comment]
This is fixed in the develop branch

@Gabriel439 you can check out the develop branch or wait some more time to merge develop into master.

**Comment by Gabriel439** [comment]
Thank you!

**Comment by ranjitjhala** [comment]
Awesome! Thanks @nikivazou!!!
