### ISSUE TITLE
Liquid Haskell does not refine `Word` literals correctly

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#642]
This program:

```haskell
import Data.Word

main = print (quotRem (4 :: Word8) 128)
```

... fails to type-check with this error:

```
 test.hs:3:35-37: Error: Liquid Type Mismatch
 
 3 | main = print (quotRem (4 :: Word) 128)
                                       ^^^
 
   Inferred type
     VV : {VV : (GHC.Types.Word <>) | VV == ?a}
  
   not a subtype of Required type
     VV : {VV : (GHC.Types.Word <>) | VV /= 0}
  
   In Context
     ?a := (GHC.Types.Word <>)
```

However, it succeeds if you replace `Word` with `Word8` or `Int`.

**Comment by gridaphobe** [comment]
Here's a simpler example.

```haskell
import Data.Word

{-@ foo :: {v:Word | v = 4} @-}
foo :: Word
foo = 4
```

The core is

```
 Main.foo = GHC.Types.W# (__word 4)]
```

We must be missing a refinement for `W#` or `__word`.

**Comment by ranjitjhala** [comment]
So is this something to add to the LH prelude?

**Comment by nikivazou** [comment]
This is fixed in the develop branch by adding a singleton type signature for `W#`

@Gabriel439 you can check out the develop branch or wait some more time to merge develop into master.

**Comment by Gabriel439** [comment]
Thank you!

**Comment by ranjitjhala** [comment]
You can also just add the specification:

{-@ assume GHC.Types.W# :: w:_ -> {v:GHC.Types.Word | v == w } @-}

into the source for now, and then later at some point we can gather
all the relevant things and add them to the LH prelude, right @nikivazou ?
​

**Comment by nikivazou** [comment]
sure, that should work too
