### ISSUE TITLE
nofalse is not implemented?

### ISSUE THREAD

**Issue by sorawee** [ucsd-progsys/liquidhaskell#660]
Under "Ignore False Predicates", README file, it shows a use of:

```
liquid --nofalse test.hs
```

I am not totally sure what this does (I `git rev-list --all | xargs git grep nofalse` to see the usage of it, but it only exists in the README file). `tests/neg/lazy.lhs` does not exist too. However, I think that it is used to suppress a warning like:

```
WARNING: Found false in test.hs:10:5-7
```

on refinement like

```
{-@ die :: {v : _ | false } -> a @-}
die msg = error msg
```

Note: seems that this used to be encouraging, see https://youtu.be/vYh27zz9530?t=17m26s.

So, I guess this should be implemented, or removed from README, or changed to `--nowarnings` which has the same effect.

**Comment by ranjitjhala** [comment]
Hmm I thought this was a dead option -- we certainly use false eg for the reasons below. @nikivazou any idea why it's still there? Can we remove it?

**Comment by nikivazou** [comment]
It is indeed a dead option. I used it when trying to figure out the soundness under laziness. I removed it! Thanks @sorawee!

**Comment by sorawee** [comment]
Then I guess another issue is that the following code

```
{-@ die :: {v : _ | false } -> a @-}
die msg = error msg
```

gives

```
WARNING: Found false in test.hs:10:5-7
```

But @ranjitjhala said that `{-@ die :: {v : _ | false } -> a @-}` is an encouraging way to indicate a "dead code". So I guess it should not be a warning?

**Comment by ranjitjhala** [comment]
Indeed! @nikivazou do you see why that warning is pointless now :)

**Comment by nikivazou** [comment]
But @ranjitjhala that is why it is a warning and not an error. The following code produces a non-pointless warning

```
{-@ LIQUID "--no-termination" @-}

{-@ liquidAssert :: {v:Bool | Prop v} -> Bool @-}
liquidAssert :: Bool -> Bool 
liquidAssert x = x

f x = f x 

unsound = liquidAssert ((\_ -> 0==1) (f ()))
```

**Comment by ranjitjhala** [comment]
Actually 

1. this example is pointless too; after all you've put in "--no-termination" ...

2. Regardless, the "false" thing is an adhoc indication of unsoundness -- ie it is neither sufficient nor necessary, and so

3. In general this "warning" is only useful to the *developers* of LH who may be "sanity checking" something or making sure something wierd is not happening and it is quite incomprehensible and useless to *users*.

Thus: lets please *not* show it by default but show them only when some option is triggered (--show-warnings).





At any rate of there
