### ISSUE TITLE
Make a neomake checker for liquid

### ISSUE THREAD

**Issue by tswilkinson** [ucsd-progsys/liquidhaskell#667]
This would allow support for using liquid with Neovim.

I have tried to make one myself but I can't make head or tail of vim's error message formatting...

**Comment by ranjitjhala** [comment]
Good idea. Btw, does the syntastic plugin work for neovim? [ moved away from vim because of the lack of "asynchronous" checking in syntastic, but perhaps this is addressed by neomake? ] /cc @spinda

**Comment by tswilkinson** [comment]
The neomake checker has a different layout to syntastic, but it's similar I think (see the README).  Neomake works on both vim and neovim, and has very good asynchronous checking on neovim.

**Comment by bonds** [comment]
I started using this with neomake...it's not great, but its a start, and it at least tells when when there's a LH error in my code:

````
let g:neomake_haskell_enabled_makers = ['stackhlint', 'stackhdevtools', 'stackgh
cmod', 'stackliquid', 'tags']
let g:neomake_haskell_stackliquid_maker = {
    \ 'exe': 'stack',
    \ 'args': ['--verbosity', 'silent', 'exec', '--', 'liquid'],
    \ 'errorformat':
        \ '\ %f:%l:%c-%.%#Error:%m'
    \ }
````

I'm scratching my head over what would be a good one-line format for LH error messages, for use in Vim...

**Comment by bonds** [comment]
And on the error format in vim, try ````:help errorformat```` from within vim. After you're done crying, read this: https://flukus.github.io/2015/07/03/2015_07_03-Vim-errorformat-Demystified/

**Comment by bonds** [comment]
Ok, I made one. Here's the PR:

https://github.com/neomake/neomake/pull/522

**Comment by ranjitjhala** [comment]
Awesome!!! Thanks @bonds !!!

**Comment by tswilkinson** [comment]
@bonds Brilliant!  Thanks so much.
