### ISSUE TITLE
Refinements for fields brought into scope by case analysis but not by destructuring let

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#670]
The following example correctly type-checks:

```haskell
{-@
test
    :: l : { l : Int | 0 <= l }
    -> y : { y : Int | y < l * 64 }
    -> { b : Bool | Prop b}
@-}
test :: Int -> Int -> Bool
test l y = q < l `div` 32 + 1
  where
    q = y `div` 2048
```

... but if I change the final line to a destructing `where` or `let` then the refinement is lost and this program does not type-check:

```haskell
{-@
test
    :: l : { l : Int | 0 <= l }
    -> y : { y : Int | y < l * 64 }
    -> { b : Bool | Prop b}
@-}
test :: Int -> Int -> Bool
test l y = q < l `div` 32 + 1
  where
    (q, _) = y `quotRem` 2048
```

... but if I destructure the result of `quotRem` using case analysis then the refinement is correctly preserved and this program does type-check:

```haskell
{-@
test
    :: l : { l : Int | 0 <= l }
    -> y : { y : Int | y < l * 64 }
    -> { b : Bool | Prop b}
@-}
test :: Int -> Int -> Bool
test l y = case y`quotRem` 2048 of
    (q, _) -> q < l `div` 32 + 1
```

**Comment by ranjitjhala** [comment]
Sorry about this @Gabriel439 (and thanks for pointing it out!) 

Its a tricky thing I've seen this before. If you add:

```
{-@ qualif Div(v:Int, x:Int, y:Int): v = (x / y) @-}
```

to the file then the second one *also* type checks (on develop).

The reason has to do with how GHC desugars the:

```
test l y = q < l `div` 32 + 1
  where
    (q, _) = y `quotRem` 2048
```

into something like:

```
test l y = 
  let q =  case  y `quotRem` 2048 of 
                (q1, _) -> q1
  in 
    q < l `div` 32 + 1
```
  
LH needs qualifiers to compute the value of the `case-of` 
(as it is the "join" or "least-upper-bound" of all the different 
branches -- in this case -- with a singleton case, its not needed 
but LH doesn't know this optimization!) 

Unfortunately the relevant qualifier is not in the source (and thus, 
has to be provided).

Mind you the qualifier _is_ in the spec of `quotRem` (and so
`--scrape-used-imports` should work but I can't run it currently 
@gridaphobe can you check why?)

In the other variants, one doesn't need the qualifier as there
are no "joins". This is a very common pattern thanks to how 
the GHC de-sugaring works, so perhaps we can just tweak
the solver so it treats the second case in a manner equivalent
to the first & third. 

(Also @bmcfluff: another problem that will be solved if we can 
get the `--eliminate` working...)

**Comment by nikivazou** [comment]
@ranjitjhala you are correct, `--scrape-used-imports` will just add the required qualifier and the code just works!

**Comment by ranjitjhala** [comment]
@nikivazou can you make a new tag "missingquals" and tag this (and others)
? Would like to keep an eye on these to find a proper solution to the
problem.

**Comment by nikivazou** [comment]
Done!
