### ISSUE TITLE
web crashed

### ISSUE THREAD

**Issue by sorawee** [ucsd-progsys/liquidhaskell#682]
Just a moment ago, suddenly the web doesn't work anymore:

```
module Blank where
-- This is a blank file
```

results in

```
Crash! Uh oh, there was a crash. See the log.
```

where the log is:

```
[0mliquid: /home/rjhala/research/stack/liquid/liquidhaskell/.stack-work/install/x86_64-linux/nightly-2015-09-24/7.10.2/share/x86_64-linux-ghc-7.10.2/liquidhaskell-0.6.0.0/include/CoreToLogic.lg: openFile: does not exist (No such file or directory)
```

**Comment by ranjitjhala** [comment]
oh dear. my fault, I was just upgrading it to the latest version. Give me a moment please!

**Comment by ranjitjhala** [comment]
hope this was not in the middle of lecture?!

**Comment by sorawee** [comment]
It's in a middle of the software demoing, but that's fine. I have a local version

**Comment by ranjitjhala** [comment]
should be fixed now! sorry about that!
