### ISSUE TITLE
Function in refinement

### ISSUE THREAD

**Issue by sorawee** [ucsd-progsys/liquidhaskell#685]
```
{-@ foo :: a: Int -> f: (Int -> Int) -> {v : Int | v = 123 + (f a) } @-}
foo :: Int -> (Int -> Int) -> Int
foo a f = f a
```

results in SAFE... I don't know if LH can reason about the above code or not. If it cannot, shouldn't it result in an error instead? Otherwise, this should obviously be UNSAFE.

**Comment by ranjitjhala** [comment]
Yikes! @nikivazou can you explain (and fix) ?! 

This is likely a consequence of pruned Unsorted...

**Comment by nikivazou** [comment]
Correct, the refinement is pruned out. I am taking a look!

**Comment by ranjitjhala** [comment]
Can we please not run prune on any user defined types? If anything gets pruned in such types it should be an error.

**Comment by nikivazou** [comment]
@sorawee I will push a fix soon, until then, if you want to soundly add functional arguments (like `f`) in your refinements use `--higherorder`. 


@ranjitjhala by user defined types you mean the specifications right?

**Comment by ranjitjhala** [comment]
> @ranjitjhala <https://github.com/ranjitjhala> by user defined types you
> mean the specifications right?
>

Yes

**Comment by nikivazou** [comment]
Fixed on develop: 

@sorawee your code now will crash with `Unbound Symbol f`. If you use the `--higherorder` flag then the code is unsafe. 

There is no documentation for the `higerorder
