### ISSUE TITLE
Missing source for build with cabal in INSTALL.md

### ISSUE THREAD

**Issue by frantisekfarka** [ucsd-progsys/liquidhaskell#697]
Current instructions in INSTALL.md for cabal build are incomplete 
and when installing with cabal 1.22.9 the "cabal install" produces the following
error:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: liquidhaskell-0.6.0.0 (user goal)
next goal: prover (dependency of liquidhaskell-0.6.0.0)
Dependency tree exhaustively searched.
```

However, adding the following source fixes the issue:

```
cabal sandbox add-source ./prover/
```

**Comment by ranjitjhala** [comment]
Thanks very much for pointing this out! 
I have update the instructions in fa92333d5b67c928af338d58ee7fe799bd440d32
