### ISSUE TITLE
Spec parser consumes extra tokens

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquidhaskell#707]
See https://github.com/ucsd-progsys/liquidhaskell/commit/31733db39f58e3bd88f7840cc2b45d907c8c2c94 and #706.

The problem is that when you have a set of specs like the following

```
uncons
    :: i : Data.ByteString.ByteString
    -> Maybe (Data.Word.Word8, { o : Data.ByteString.ByteString | bslen o == bslen i - 1 })

unsnoc
    :: i : Data.ByteString.ByteString
    -> Maybe ({ o : Data.ByteString.ByteString | bslen o == bslen i - 1 }, Data.Word.Word8)
```

the `BareType` parser consumes the `unsnoc` token, as

```
Maybe (Data.Word.Word8, { o : Data.ByteString.ByteString | bslen o == bslen i - 1 }) unsnoc
```

is a valid type.

Adding an extra parenthesis around the output type usually fixes these parse issues, e.g.

```
uncons
    :: i : Data.ByteString.ByteString
    -> (Maybe (Data.Word.Word8, { o : Data.ByteString.ByteString | bslen o == bslen i - 1 }))

unsnoc
    :: i : Data.ByteString.ByteString
    -> (Maybe ({ o : Data.ByteString.ByteString | bslen o == bslen i - 1 }, Data.Word.Word8))
```

but why is beyond me.

The root of the problem though, is that our parser is not indentation-sensitive, but Haskell is. The `unsnoc` token should force an end to the `BareType` parser as it is at the same indentation as the `uncons` token.

@spinda has a branch that reworks our parser to use MegaParsec, which supports indentation-sensitive parsing. That should eventually fix this bug.

**Comment by kosmikus** [comment]
Fixed via #1704.
