### ISSUE TITLE
annotating functions in typeclass should result in an error

### ISSUE THREAD

**Issue by sorawee** [ucsd-progsys/liquidhaskell#710]
Please see http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1463259507_10885.hs

It results in SAFE, while my friends expect it to be UNSAFE.

(Though it's true that if we annotate it with

```
{-@ class Add a b where
    add :: [a] -> [b] -> {v : [a] | len v > 0}
@-}
```

Then it's UNSAFE)

**Comment by ranjitjhala** [comment]
Yikes! @nikivazou and @gridaphobe is this related to the various other type class related issues.

**Comment by sorawee** [comment]
FYI: @avanhatt

Also, it seems she is trying to refine

```
instance (Num k) => Add k k where
    add x y = addVecWrap x y
```

but LH can't even parse `{-@ instance (Num k) => Add k k where ...`

**Comment by gridaphobe** [comment]
I suspect what's going on here is that the isolated spec for `add` is not being attached to the `Add` class the way the class-spec would be.

I think the most user-friendly solution would be to make the two specs @sorawee mentions equivalent, ie

```
class Add a b where
  {-@ add :: [a] -> [b] -> {v : [a] | len v > 0} @-}
  add :: [a] -> [b] -> [a]
```

would effectively desugar into

```
class Add a b where
  add :: [a] -> [b] -> [a]
{-@ class Add a b where
    add :: [a] -> [b] -> {v : [a] | len v > 0}
@-}
```

**Comment by nikivazou** [comment]
@avanhatt, @sorawee actually I recently extended class instances refinements to support the instance you want to refine. So, as of now in develop you can add 


```
instance (Num k) => Add k k where
{-@ instance (Num k) => Add k k where 
	 add :: [k] -> [k] -> {v : [k] | len v > 0}
  @-}

    add x y = addVecWrap x y
 ```

and your code is UNSAFE. 


Though indeed we should create an error for the initial code. I though `add` is not even a variable in the internal representation, so expected the specification to fail with unknown var....

**Comment by gridaphobe** [comment]
@nikivazou `add` is the dictionary selector, and is what appears at callsites, so we definitely need to give it a refined type.

**Comment by avanhatt** [comment]
@nikivazou @gridaphobe @sorawee 

Thank you for the advice! Now that the instance refinement is getting parsed correctly, though, the behavior seems to not be what we expect. 

As a minimal example, the following gives SAFE when we expect UNSAFE: 

```
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances #-}

class Add a b where
    rAdd :: [a] -> [b] -> [a]

{-@ instance (Num k) => Add k k where 
     rAdd :: 
        x : {v : [k] | len v > 0} 
        -> {v : [k] | (len v = len x) && len v > 0} 
        -> {v : [k] | len v > 0}

@-}
instance (Num k) => Add k k where
    rAdd x y = x

main = putStrLn (show (rAdd ([] :: [Double]) ([] :: [Double])))
```

And for reference, the same function without the use of a type class does give UNSAFE:

```
{-@ 
rAdd :: 
    x : {v : [a] | len v > 0} 
    -> {v : [b] | (len v = len x) && len v > 0} 
    -> {v : [a] | len v > 0}

@-}
rAdd :: [a] -> [b] -> [a]
rAdd x y = x

main = putStrLn (show (rAdd ([] :: [Double]) ([] :: [Double])))
```

**Comment by nikivazou** [comment]
Interesting! Seems that you hit a bug... As I said, I just added support for this feature. Taking a look now!

**Comment by nikivazou** [comment]
Should be fixed in develop now! Thanks for the report @avanhatt!

**Comment by ranjitjhala** [comment]
Just checking -- does @nikivazou's fix in `develop` work for you @avanhatt?
​

**Comment by avanhatt** [comment]
@ranjitjhala 
Yes, the fix is working for me so far, thanks!

**Comment by avanhatt** [comment]
@ranjitjhala @nikivazou 
Actually, I think I'm running into a related bug with parsing instance refinements. The following minimal example gives an LH parsing error on trying to refine instances with list types (in this case, we're trying to model adding vectors and matrices):

```
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances #-}

class Add a b c where
    rAdd :: [a] -> [b] -> [c]

{-@ instance (Num k) => Add k [k] [k] where
     rAdd :: 
        x : {v : [k] | len v > 0} 
        -> y : {v : [[k]] | len v > 0} 
        -> {v : [k] | len v > 0}
@-}
instance (Num k) => Add k [k] [k] where
    rAdd x y = y
```

Produces the error:
```
Error: Cannot parse specification:
 
 7 | {-@ instance (Num k) => Add k [k] [k] where
                                   ^
 
     unexpected "["
     expecting "where", letter, "_" or "("
```

**Comment by nikivazou** [comment]
@avanhatt can you try wrapping the list types into parenthesis?

**Comment by avanhatt** [comment]
@nikivazou 
Hm, so that stops the parse error, but now the Liquid type doesn't seem to correspond with the refinement (it loses the context and the output type should be [[k]], not [k]). 

```
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances #-}

class Add a b c where
    rAdd :: [a] -> [b] -> [c]

{-@ instance (Num k) => Add k ([k]) ([k]) where
     rAdd :: 
        x : {v : [k] | len v > 0} 
        -> y : {v : [[k]] | len v > 0} 
        -> {v : [k] | len v > 0}
@-}
instance (Num k) => Add k [k] [k] where
    rAdd x y = y
``` 

Gives the error:
```
Error: Specified Type Does Not Refine Haskell Type for $crAdd
 The Liquid type
  
     forall k. [k] -> [[k]] -> [k]
  
 is inconsistent with the Haskell type
  
     forall k. GHC.Num.Num k => [k] -> [[k]] -> [[k]]
```

**Comment by avanhatt** [comment]
@nikivazou  
Oops, sorry, the last part of my refinement is wrong so nevermind! Everything else is working now with the parenthesis, thanks.
