### ISSUE TITLE
GHC 8.0.1 support

### ISSUE THREAD

**Issue by wyager** [ucsd-progsys/liquidhaskell#726]
It looks like the current constraints for LiquidHaskell are `ghc>=7.10.2 && <7.11`.

Given that 8.0.1 is bundled with the current platform, it would probably be good to add support for this.

**Comment by gridaphobe** [comment]
Indeed!

We rely heavily on GHC's API (which often changes) so it may take some time to sort out though.

**Comment by proaralyst** [comment]
:+1: I'd love this to happen.

**Comment by nikivazou** [comment]
We are working on that!

**Comment by clayrat** [comment]
We should probably close this?

**Comment by facundominguez** [comment]
Indeed!
