### ISSUE TITLE
Distinct top level binds can lead to unsoundness 

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#746]
All top level binders are treated as literals in the logic. 
The logic assumes that literals are distinct [https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Solver/Monad.hs#L18](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Solver/Monad.hs#L180). 

Thus if top level binders are (provably) equal, we get unsound. [Eg](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1466641291_13276.hs)

```
foo :: Int 
foo = 1 

bar :: Int 
bar = 1 

{-@ unsound :: () -> {v:Bool |  false } @-}
unsound :: () -> Bool
unsound _ = 
 boo foo bar 

{-@ boo :: x:Int -> y:Int -> {v:Bool | x == y} @-}
boo :: Int -> Int -> Bool
boo = undefined 
```

**Comment by ranjitjhala** [comment]
Wow, this is surprising. Why/since when are top-level binders treated as
literals in the logic?

**Comment by ranjitjhala** [comment]
Think I have a fix, running tests now.

**Comment by ranjitjhala** [comment]
Fixed by 55bbec93a9205a1c0bd5b7490aa74bd362045a97

Was actually causing `AmericanFlag` to be unsoundly reported SAFE, now fixed.

**Comment by nikivazou** [comment]
Cool! So the bug was there forever! 

What is the fix? Wondering if it applies to top level functions too.

**Comment by ranjitjhala** [comment]
The *BUG* was that we just treat ALL top-level values (i.e. the "top-level"
fixpoint environment) as constants, which includes the `foo` and `bar` in
your example AND every import and ...

The *FIX* was to have a separate `litEnv` (literal-environment), and
populate it with

  + Literals in the source `coreBindLits` e.g. random strings etc.,
  + Data constructors.,
  + Measures.

Thus, far fewer things are declared as "constant", and in particular,
random user supplied binders are *not*, but when you have an enum like:

```
  data Blob = This | That
```

then those are still declared as constants, as are random string literals
`"cat"` ,`"dog"` etc.

**Comment by ranjitjhala** [comment]
Oops, the above "fix" causes the following to be "proved" as `Z` and `zero` are both "constants", the former as a data-con, the latter as a measure...

```
module Nats where

{-@ poo :: {v:Int | v == 0 } @-}
poo :: Int 
poo = 1

data Peano = Z 

{-@ axiomatize zero @-}
zero :: Peano
zero = Z
```

**Comment by ranjitjhala** [comment]
looks like this is fixed.
