### ISSUE TITLE
Liquid Haskell doesn't correctly refine variables beginning with the prefix "fail"

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#755]
Here's the minimal reproducing example:

```haskell
{-@ f :: x  : { Int | 0 <= x } -> ys : [a] -> () / [ len ys ] @-}
f :: Int -> [a] -> ()
f _    []  = ()
f x (y:ys) = let fail = 0 in f fail ys
```

This fails to type-check with:

```
 /Users/gabriel/proj/packet-analysis/src/test.hs:4:30-35: Error: Liquid Type Mismatch
 
 4 | f x (y:ys) = let fail = 0 in f fail ys
                                  ^^^^^^
 
   Inferred type
     VV : {VV : Int | VV == fail}
  
   not a subtype of Required type
     VV : {VV : Int | 0 <= VV}
  
   In Context
     fail : Int
```

If you rename `fail` to `failure` or any other variable name beginning with the prefix `fail` the problem persists.  If you change it to `fai` or any variable that does not begin with the prefix `fail` then the program typechecks.

**Comment by ranjitjhala** [comment]
Yikes!!!! @nikivazou this seems relevant:

```
rjhala@borscht ~/r/s/l/src (develop)> ack "fail"
...
Language/Haskell/Liquid/Constraint/Generate.hs
1000:       isDefLazyVar = L.isPrefixOf "fail" . shower
```

**Comment by ranjitjhala** [comment]
Looks like that was some random hack put in a long time ago. Just took it out, re-running tests to see if anything breaks.

**Comment by ranjitjhala** [comment]
Should be fixed by https://github.com/ucsd-progsys/liquidhaskell/pull/756 

Tests pass locally, will merge once CI okays it...
