### ISSUE TITLE
Unable to build on Windows due to 'unix' package dependency

### ISSUE THREAD

**Issue by alclub** [ucsd-progsys/liquidhaskell#806]
> setup.exe: Package unix-2.7.1.0 can't be built on this system.

I get a different but similar message on Cygwin. Is there any way to get liquidhaskell running on Windows, or is Windows no longer supported?

**Comment by gridaphobe** [comment]
Are you building from github? If so, can you try commenting out the `lhi` stanza in the cabal file?

https://github.com/ucsd-progsys/liquidhaskell/blob/master/liquidhaskell.cabal#L79-L104

The main `liquid` binary *should* build on windows, if it doesn't that's a bug!

**Comment by gridaphobe** [comment]
@ranjitjhala do you absolutely need `unix` for `lhi`? I would think there's a way to do the daemonized server on windows too.

**Comment by ranjitjhala** [comment]
Let's comment it out for now since its super dormant and will remain so for
several weeks at least...

**Comment by ranjitjhala** [comment]
Eric can you do it? Am rather laptop challenged atm -- my ssd crashed :(

We should ensure develop builds on windows always...

**Comment by alclub** [comment]
> Are you building from github? If so, can you try commenting out the lhi stanza in the cabal file?

Thanks for your assistance. Yes, I am building from github (using stack). I removed the 'lhi' block, now it quits with the error:

`<command line>: can't load .so/.DLL for: stdc++.dll (addDLL: could not load DLL)
    ghc.exe: stdc++: The specified module could not be found.`

There doesn't appear to be much information online about this issue except that references to "double-conversion" are causing some packages to fail to build on windows.

I've attempted [the fixes given here](https://github.com/commercialhaskell/stack/issues/754#issuecomment-165457815): 

but now I get the error:

` [ 38 of 105] Compiling Language.Haskell.Liquid.Types ( src\Language\Haskell\Liquid\Types.hs, .stack-work\dist\2672c1f3\build\Language\Haskell\Liquid\Types.o )
    ghc.exe: unable to load package 'double-conversion-2.0.1.0'
    ghc.exe: C:\x\xx\liquidhaskell\.stack-work\install\12018b8a\lib\x86_64-windows-ghc-7.10.3\double-conversion-2.0.1.0-9d4SFE0Uwt89cnl39kvRqX\HSdouble-conversion-2.0.1.0-9d4SFE0Uwt89cnl39kvRqX.o: unknown symbol '_Unwind_Resume'`

and also

`[ 38 of 105] Compiling Language.Haskell.Liquid.Types ( src\Language\Haskell\Liquid\Types.hs, .stack-work\dist\2672c1f3\build\Language\Haskell\Liquid\Types.o )
    ghc.exe: unable to load package double-conversion-2.0.1.0'
    ghc.exe: C:\x\xx\liquidhaskell\.stack-work\install\12018b8a\lib\x86_64-windows-ghc-7.10.3\double-conversion-2.0.1.0-9d4SFE0Uwt89cnl39kvRqX\HSdouble-conversion-2.0.1.0-9d4SFE0Uwt89cnl39kvRqX.o: unknown symbol '__cxa_guard_acquire'`

which I am still unable to resolve.

**Comment by gridaphobe** [comment]
@alclub I've fixed the initial issue with the `unix` package.

The second issue you linked seems to suggest the problem might be due to the use of Template Haskell. If that's the case, it's easy to remove the Template Haskell. I've done so in #807, can you try building that patch? I'm afraid I don't have access to a windows machine at the moment to test it myself.

**Comment by alclub** [comment]
Sorry for the late response, thanks for your help.

**It solved that issue**, but there are other references to Template Haskell which are causing errors:

` Configuring liquidhaskell-0.6.0.0...
    Preprocessing library liquidhaskell-0.6.0.0...
    [ 95 of 105] Compiling Test.Target.Monad ( src\Test\Target\Monad.hs, .stack-work\dist\2672c1f3\build\Test\Target\Monad.o )
    ghc.exe: unable to load package 'double-conversion-2.0.1.0'
    ghc.exe: C:\x\xx\liquidhaskell\.stack-work\install\12018b8a\lib\x86_64-windows-ghc-7.10.3\double-conversion-2.0.1.0-9d4SFE0Uwt89cnl39kvRqX\HSdouble-conversion-2.0.1.0-9d4SFE0Uwt89cnl39kvRqX.o: unknown symbol '_Unwind_Resume'
`

I'm not familiar enough with Haskell to be able to expand this myself:

`deriveLiftMany [''SMTSolver, ''TargetOpts]`

but I'll have some free time in a few hours, I'll see if I can do it, and I'll report back.

**Comment by gridaphobe** [comment]
@alclub I've reduced our dependence on TH as much as I can. We don't run any TH code any more, but we do require the `'name` syntax for looking up names in the TH splices that we provide.

I hope this is enough!

**Comment by alclub** [comment]
**It worked!** Thanks so much!

**Comment by ranjitjhala** [comment]
Super thanks Eric!
