### ISSUE TITLE
Refined GADTs

### ISSUE THREAD

**Issue by vikraman** [ucsd-progsys/liquidhaskell#818]
I'm trying to add refinements to a GADT, but LiquidHaskell doesn't understand GADTs.

``` haskell
{-# LANGUAGE GADTs #-}

{-@ data List a where
      Nil :: List a
      Cons :: a -> List a -> List a
@-}
data List a where
  Nil :: List a
  Cons :: a -> List a -> List a
```

results in a parse error.

```
Error: Cannot parse specification:
 18 | {-@ data List a where
                    ^
```

**Comment by ranjitjhala** [comment]
Yes, unfortunately LH doesn't support the GADT syntax yet. It _should_ be easy to add, but we haven't gotten around to it yet. Thanks for pointing this out!

**Comment by rrnewton** [comment]
In our upcoming ICFP paper one thing we found was in the ~17M lines of code on Hackage there are, surprisingly, thousands of datatypes that are not actually GADTs but are defined in GADT syntax.

**Comment by nikivazou** [comment]
Actually I am at a point that I do need to refine an actual GADT in my current work. So, soon I would need to add this feature (seems trivial/syntactic).

**Comment by nikivazou** [comment]
I am on this, but since we are not supporting indentation supporting exactly Haskell's syntax seems impossible. To start with, you can now write 

```
{-@ data List a where
     Nil    :: List a 
  | Cons :: listHead:a -> listTail:List a -> List a  
@-}
```


Another alternative (apart from indentation support) would be to require the types in parenthesis. That is
```
{-@ data List a where
     Nil    :: (List a)
   Cons :: (listHead:a -> listTail:List a -> List a)  
@-}
```


I am going to pull request my partial solution, and lets discuss what is a good alternative.

**Comment by ranjitjhala** [comment]
Hey, we can close this right? since you can now write what @nikivazou describes above?
