### ISSUE TITLE
Reasoning about length of concrete bytestrings 

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#822]
For example the [following](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1472583424_14895.hs) fails 

```
{-@ bar :: {v:ByteString | bslen v == 1 } @-}
bar = " "
```

With intermediate code 

```
Main.bar =
   (Data.String.fromString
      @ Data.ByteString.Internal.ByteString
      Data.ByteString.Internal.$fIsStringByteString)
     (GHC.CString.unpackCString# " "#)]
```

**Comment by Gabriel439** [comment]
I just ran into this issue.  The first thing I tried was:

```
{-@
Data.String.fromString 
    :: str : [Char] -> { bs : Data.ByteString.ByteString | bslen bs == len str }
@-}
```

... which fails with:

```
 /private/tmp/test/Test.hs:(12,8)-(13,0): Error: Specified Type Does Not Refine Haskell Type for Plugged Init types  forall a. Data.String.IsString a => [GHC.Types.Char] -> a 
VS
 str:[Char] -> {bs##1 : ByteString | bslen bs##1 == len str} Data.String.fromString
 The Liquid type
  
     [Char] -> ByteString
  
 is inconsistent with the Haskell type
  
     forall a. Data.String.IsString a => [GHC.Types.Char] -> a
  
 defined at <no location info>
```

The second thing I tried was:

```
{-@
Data.ByteString.Internal.packChars
    :: str : [Char] -> { bs : Data.ByteString.ByteString | bslen bs == len str }
@-}
```

... which leads to an ordinary failure to satisfy the refined type.  Note that `packChars` is how `fromString` is implemented for `ByteString`

I can work around this through an explicit `Data.ByteString.Char8.pack` for now

**Comment by ranjitjhala** [comment]
Hmm... So we would have to refine the dictionary method here?

**Comment by nikivazou** [comment]
Hey @Gabriel439, 
what ghc are you using? I do not see any call to `packChars` in the internal representation. 

The following type checks using a "fake" class measure. Let me know if it works for you. 

```
{-# LANGUAGE OverloadedStrings #-}
import Data.ByteString

{-@ bar :: {v:ByteString | bslen v == 1 } @-}
bar :: ByteString
bar = " "

-- LH knows the length of x, so declare that the length of the result string is the same as the length 
-- of the input list
{-@ Data.String.fromString 
      :: forall a. Data.String.IsString a => x:[GHC.Types.Char] 
      -> {v:a | len x == stringlen v} 
@-}

-- where stringlen is a function that returns the length of the string. 
-- for any string instance (thought this string instance restriction is not checked by LH)
{-@ measure stringlen :: a -> Int @-}

-- Finally, use an invariant to state that the stringlen for BS is bslen
{-@ invariant {v:ByteString | bslen v == stringlen v } @-}
```

**Comment by ranjitjhala** [comment]
hmm. looks like github is trying to be very clever? I didn't explicitly "close" this issue, but I merged @Gabriel439 ' PR which had the term "fixes" in the message, and so GH decided to close the issue!

**Comment by Gabriel439** [comment]
Yep!  GitHub supports automatically closing issues based on certain key words:

https://help.github.com/articles/closing-issues-using-keywords/

That's why I put "Fixes ..." in the commit description, so that it would mark this issue resolved once it was merged

**Comment by ranjitjhala** [comment]
Ooh nice, thanks!
