### ISSUE TITLE
Untrusted-code checking: needs `--termination-check` command line argument

### ISSUE THREAD

**Issue by rrnewton** [ucsd-progsys/liquidhaskell#832]
We're thinking about untrusted code execution a bit.  Currently, if we, the server, get a single file from the untrusted user, it may contain `{-@ LIQUID @-}` pragmas, including `--no-termination-check`.  

We could try to *strip* these ourselves before compiling the file.  But a more straightforward approach is to just make sure that command line arguments override in-file pragmas.  We already have a `--no-termination-check` command line flag, but we need its opposite, `--termination-check`.

Finally, note that currently a server needs to check every file separately, as checking a file with module imports does not imply that its imports have been been checked for nontermination (though it does scrape and import the specs).

**Comment by rrnewton** [comment]
Also, note that this is only for preventing nontermination-cheats within the submitted code.  To block cheats from base itself depends on #815.

At the same time, we also depend on Safe Haskell plus a suitable trust list to block other problems.

**Comment by nikivazou** [comment]
So, how about adding a `--safeLiquidHaskell` argument that for now just enforces termination check?

**Comment by rrnewton** [comment]
That would be great.  Would that be an alias for multiple flags?  If not, how about just calling it `--termination-check` for symmetry with `--no-termination-check`?

**Comment by nikivazou** [comment]
@rrnewton does #835 address what you had in mind?

**Comment by rrnewton** [comment]
Yep, sure, as long as `--totality` overrides a `{-@ LIQUID --no-termination-check @-}` in the file, it suffices to address this issue. I'll close this one in favor of that.
