### ISSUE TITLE
Literate Haskell to markdown messes up greek characters. 

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#845]
The below part of the .lhs file

```
\begin{code}
{-@ reflect ε  @-}
\end{code}
```

translates to 

```
<pre><span class=hs-linenum>125: </span><span class='hs-keyword'>{-@</span> <span class='hs-varid'>reflect</span> <span class='hs-varid'>µ</span>  <span class='hs-keyword'>@-}</span>
```

`ε` becomes `μ`. 
Not sure if this is a liquidHaskell bug, but @ranjitjhala should know.

**Comment by ranjitjhala** [comment]
Definitely not fixing this...

Suspect it's a bug in hscolour. Does just running hscolour directly on the
file produce the same result?

**Comment by nikivazou** [comment]
No running hscolour does not change ε, but ε -> μ happens in the .lhs.html generated liquid files

**Comment by ranjitjhala** [comment]
Well that's wierd ... I will take a look out of some perverse curiousity...
:)
