### ISSUE TITLE
hscolour dependency is GPL-licensed

### ISSUE THREAD

**Issue by crclark** [ucsd-progsys/liquidhaskell#849]
but LiquidHaskell is BSD3 licensed.

It looks like the latest version of `hscolour` is licensed as LGPL, however.

**Comment by gridaphobe** [comment]
Does the LGPL not allow us to release LiquidHaskell as BSD3? (I thought that was the point of it)

**Comment by nikivazou** [comment]
Apparently our dependency is on a previous release that is GPL. So, remove hscolour test suite?

**Comment by gridaphobe** [comment]
Oh I see, I thought @crclark was talking about the version we link against to highlight the source code. If it's just part of the test-suite does that even count as distributing?

**Comment by nikivazou** [comment]
I have edited hscolour to verify it, and my modified version does come as a submodule with Liquid Haskell. So, maybe license wise I am not allowed to do that, and we should remove it?

**Comment by ranjitjhala** [comment]
I thought we'd removed it anyway? If not: let's!

**Comment by nikivazou** [comment]
hscolour is removed in #850
