### ISSUE TITLE
Huge slowdowns when using `undefined` in proofs

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#862]
For example, the time to check the Ackermann proofs goes from `14s` to `473s` with the following `undefined` insertion 

https://github.com/ucsd-progsys/liquidhaskell/commit/5d6c0f3995a85bb566ea22b360c77ccf17313d28

**Comment by nikivazou** [comment]
@ranjitjhala you said you were interested in taking a look at that

**Comment by ranjitjhala** [comment]
wow! Thanks for finding this!

Will look at this post-PLDI!

**Comment by nikivazou** [comment]
Np! My current workaround is to use `trivial` and actually get the failing proof instead of `undefined`. 

Thanks @vikraman for forcing me to report this:)

**Comment by gridaphobe** [comment]
Does it also happen if you replace `undefined` with something like `let x = x in x`? It sounds very similar to an issue we had a few years ago in bytestring/text where having `false` in the environment would cause an explosion in the size of inferred types and a corresponding slowdown.

**Comment by ranjitjhala** [comment]
looks like `tests/pos/mapreduce.hs` also has this problem...

**Comment by ranjitjhala** [comment]
closed by #879
