### ISSUE TITLE
wrong example in README file

### ISSUE THREAD

**Issue by zilinc** [ucsd-progsys/liquidhaskell#872]
Under the "Modules WITH Code: Data" section of `README.md` file, `data Map k a <l :: k -> k -> Bool, r :: k -> k -> Bool>` should be `data Map k a <l :: k -> k -> Prop, r :: k -> k -> Prop>` otherwise it gives a parse error.

**Comment by ranjitjhala** [comment]
Thanks for pointing out -- fixed!
