### ISSUE TITLE
README gives non-existant prune flag

### ISSUE THREAD

**Issue by awstlaur** [ucsd-progsys/liquidhaskell#878]
Hello,

The README file references a `--no-prune-unsorted` flag, but the actual flag seems to be `--prune-unsorted`.

The inconsistency may be related to https://github.com/ucsd-progsys/liquidhaskell/issues/703

**Comment by nikivazou** [comment]
Fixed with fa0621dc8112a6425b37f206f0b18712354856a9

Thanks!
