### ISSUE TITLE
Cannot import ProofCombinators

### ISSUE THREAD

**Issue by awstlaur** [ucsd-progsys/liquidhaskell#883]
I have `Foo.hs` with the following contents:

```haskell
module Foo where

import Language.Haskell.Liquid.Prelude
import Language.Haskell.Liquid.ProofCombinators

main = putStrLn "hello"
```
If I comment out the second `import`, I can do `stack runghc Foo.hs` and it runs. Otherwise, it `Could not find module ‘Language.Haskell.Liquid.ProofCombinators’`

I assume this is because the file is only defined under the `include/` directory and not the `src/` directory, and/or because it's not explicitly listed in `liquidhaskell.cabal`.

**Comment by ranjitjhala** [comment]
oops -- good point! Perhaps we should put the proof combinators in a separate library in the same place that @spinda's quasi-quoter stuff lives `LiquidHaskell` ? 

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/LiquidHaskell.hs

but then the catch is that while we can import the _code_ we won't 
get _refinement types_. I suppose technically, as with `Data.Vector` 
and friends, we could put the code in `src/LiquidHaskell.hs` and put 
the specifications in the `include/...` ?

Aargh. I guess we really need to solve the module import story with 
`.lqhi` or such.

**Comment by nikivazou** [comment]
Should be fixed?

**Comment by awstlaur** [comment]
@nikivazou Seems like cabal wasn't happy with that :(

https://circleci.com/gh/ucsd-progsys/liquidhaskell/1134

**Comment by nikivazou** [comment]
Cabal is happy again
