### ISSUE TITLE
install via cabal: instructions inconsistent with circle.yml 

### ISSUE THREAD

**Issue by awstlaur** [ucsd-progsys/liquidhaskell#887]
INSTALL.md is missing these three from `circle.yml` ; is this intentional or an oversight?

`cabal sandbox add-source ./liquiddesugar`

`cabal install --upgrade-dependencies --reorder-goals --constraint="template-haskell installed" --dependencies-only --enable-tests` (just has `cabal install`)

`cabal configure --enable-tests -finclude -fdevel`

**Comment by nikivazou** [comment]
An oversight
