### ISSUE TITLE
Result of proof not being used in subsequent type inference? (Infinite list)

### ISSUE THREAD

**Issue by awstlaur** [ucsd-progsys/liquidhaskell#889]
```haskell
{-@ LIQUID "--higherorder"     @-}
{-@ LIQUID "--exact-data-cons" @-}
{-@ LIQUID "--no-termination" @-}

import Language.Haskell.Liquid.ProofCombinators

{-@ type LListN a N = {v:LList a | (sz v) = N} @-}

{-@ data LList [sz] a = Nil | Cons {hd :: a, tl :: LList a} @-}
data LList a = Nil | Cons a (LList a)

{-@ measure sz @-}
sz :: LList a -> Int
sz Nil         = 0
sz (Cons x xs) = 1 + sz xs

{-@ invariant {v:LList a | sz v >= 0} @-}

{-@ measure inf :: Int @-}
{-@ invariant {v:Int | v < inf} @-}

-- | sz (Cons x xs) == inf => sz xs = inf
{-@ tailInfProof :: l:(LListN a inf) -> {inf == sz (select_Cons_2 l)} @-}
tailInfProof :: LList a -> Proof
tailInfProof l@(Cons x xs)
    =   sz l
    ==. 1 + sz xs
    *** QED

{-@ takeFromInfList :: xs:(LListN a inf) -> n:Nat -> (LListN a n) @-}
takeFromInfList :: (LList a) -> Int -> (LList a)
takeFromInfList _ 0           = Nil
takeFromInfList l@(Cons x xs) n = Cons x (takeFromInfList xs (n - 1))

```
After the `sz` and `inf` stuff, we have a proof that the "tail" of an infinite list is still infinite. Then, we try to use that to refine `takeFromInfList`; the goal here is to have a version of `take` that only operates on infinite lists and then outputs a list of size `n`.

However, we get the following error message
```
**** RESULT: UNSAFE ************************************************************


Error: Liquid Type Mismatch
 
 33 | takeFromInfList l@(Cons x xs) n = Cons x (takeFromInfList xs (n - 1))
                                                ^^^^^^^^^^^^^^^^^^
 
   Inferred type
     VV : {VV : (LList a) | sz VV >= 0
                            && VV == xs
                            && sz VV >= 0}
  
   not a subtype of Required type
     VV : {VV : (LList a) | sz VV == inf}
  
   In Context
     xs : {v : (LList a) | sz v >= 0}

```
This suggests that either it's ignoring the result `tailInfProof`, or there's some complicated tomfoolery afoot. Maybe it shouldn't have accepted that proof? Any ideas?

**Comment by ranjitjhala** [comment]
interesting! will take a look tomorrow; in general all bets are off re: infinite lists -- since LH has limited support for those...

**Comment by ranjitjhala** [comment]
1. The result of  `tailInProof` is not used "automatically" you have to "instantiate it" on suitable inputs (using the `by` combinator in the reflection paper). So the following would work:

```
 takeFromInfList l@(Cons x xs) n = Cons (byTheorem x (tailInfProof l)) (takeFromInfList xs (n - 1)) 
```

where `byTheorem :: a -> Proof -> a` is a combinator in the `ProofCombinators` module.

2. That said: all of the above is **massively unsound** in general because of the the `invariant` on `inf`, in particular, it can let you assert that `inf < inf` which is a contradiction ...

3. In general *don't* use the `invariant` mechanism (we really should update the README...) instead to say that `sz` is non-negative do:

```haskell
{-@ sz :: LList a -> Nat @-}
```

which both checks that `sz` has the above property AND gets you the fact that its a nat where you need it.

**Comment by awstlaur** [comment]
Thanks for the detailed response! Integrating your suggestions led to `SAFE`.

Was there a paper about refinement reflection? I saw the couple of blog posts but as far as I could find, neither of those used `byTheorem`.

Also, just as an side, I actually got that measure definition plus invariant from a comment here: https://github.com/ucsd-progsys/liquidhaskell/issues/885

**Comment by atondwal** [comment]
The Refinement Reflection paper is [arxiv:1610.04641]. See also Chapter 5 of [Niki's thesis](http://goto.ucsd.edu/~nvazou/thesis/main.pdf).

**Comment by ranjitjhala** [comment]
Sorry yes it's super new!

**Comment by ranjitjhala** [comment]
Hi @awstlaur -- yes sorry for pointing you to the invariant thing -- its an old mechanism thats been suppressed in favor of newer (and sounder ones). Will clarify in the docs! Thanks!
