### ISSUE TITLE
Duplicate instance declaration. liquidhaskell-0.6.0.0 failed during the building phase

### ISSUE THREAD

**Issue by nau** [ucsd-progsys/liquidhaskell#894]
Hi. Sorry for likely a newby-dumb problem. Btw, is there any gitter, IRC to ask questions?
Can't install liquidhaskell-0.6.0.0. Got this error.
Could you please help?

OS: Mac OS Sierra
cabal-install version 1.22.6.0, 
The Glorious Glasgow Haskell Compilation System, version 7.10.3
I don't have GHC 8.x installed anywhere.
$ cabal install liquidhaskell-0.6.0.0

```
65 of 97] Compiling Language.Haskell.Liquid.UX.DiffCheck ( src/Language/Haskell/Liquid/UX/DiffCheck.hs, dist/build/Language/Haskell/Liquid/UX/DiffCheck.o )

src/Language/Haskell/Liquid/UX/DiffCheck.hs:460:10:
    Duplicate instance declarations:
      instance (ToJSON k, ToJSON v) => ToJSON (M.HashMap k v)
        -- Defined at src/Language/Haskell/Liquid/UX/DiffCheck.hs:460:10
      instance (ToJSON v, ToJSONKey k) => ToJSON (M.HashMap k v)
        -- Defined in ‘aeson-1.0.2.1:Data.Aeson.Types.ToJSON’

src/Language/Haskell/Liquid/UX/DiffCheck.hs:463:10:
    Duplicate instance declarations:
      instance (Eq k, Hashable k, FromJSON k, FromJSON v) =>
               FromJSON (M.HashMap k v)
        -- Defined at src/Language/Haskell/Liquid/UX/DiffCheck.hs:463:10
      instance (FromJSON v, FromJSONKey k, Eq k, Hashable k) =>
               FromJSON (M.HashMap k v)
        -- Defined in ‘aeson-1.0.2.1:Data.Aeson.Types.FromJSON’
cabal: Error: some packages failed to install:
liquidhaskell-0.6.0.0 failed during the building phase. The exception was:
ExitFailure 1

```

**Comment by nikivazou** [comment]
Hi! Looks like we do not support the current version of aeson.... 
I works well with aeson-0.11.2.1. 

Sorry, we would have to add this dependency. Can you install from git with stack? 
```
    git clone https://github.com/ucsd-progsys/liquidhaskell.git
    cd liquidhaskell
    stack install 
```

**Comment by ranjitjhala** [comment]
Yes this looks like some unfortunate cabal dependency hassle. Sorry about that!

Can you try either what @nikivazou says above or

    stack install liquidhaskell


I.e. Use stack instead of cabal?

**Comment by nau** [comment]
That worked fine. Thank you!
Great job on refinement types, guys!

**Comment by ranjitjhala** [comment]
Super, thanks!
