### ISSUE TITLE
Unsoundness under pattern-inline

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#895]
The following is unsoundly safe without the "no-pattern-inline" flag

https://github.com/nikivazou/APRICoT/blob/master/basic_lhs_tests/Users.hs#L4

**Comment by ranjitjhala** [comment]
What's the evidence of unsound mess?

**Comment by nikivazou** [comment]
@ranjitjhala how about this?

https://github.com/nikivazou/APRICoT/blob/master/basic_lhs_tests/UsersUnsound.hs

**Comment by nikivazou** [comment]
I get unsafe if I use `>>=` but safe id I use the do notation. 

Ahh, I use a Refined Tagged Monad

https://github.com/nikivazou/APRICoT/blob/master/basic_lhs_tests/Tagged.hs#L29

**Comment by ranjitjhala** [comment]
What does the "ahh..." mean?

**Comment by nikivazou** [comment]
That maybe refining the monad is the source of unsoundness.

**Comment by ranjitjhala** [comment]
Is this still open? or did you figure it out?

**Comment by nikivazou** [comment]
Still open!

**Comment by ranjitjhala** [comment]
Fixed by #910 

Rather than checking the program it fails, asking you to run with with no-pattern-inline
