### ISSUE TITLE
Where does this constraint come from?

### ISSUE THREAD

**Issue by fhaust** [ucsd-progsys/liquidhaskell#926]
Weeell ... I [got `Liquid Haskell` to run](https://github.com/ucsd-progsys/liquidhaskell/issues/924#issuecomment-272922741).

Running on my [minimal code example](https://gist.github.com/fhaust/6596c007e74c5e270d163910553ddb2b) I get an error message I can't figure out:

```
 /tmp/xeno0/Xeno.hs:17:25-34: Error: Liquid Type Mismatch
 
 17 |     then parseTags str (fromGt + 1) 
                              ^^^^^^^^^^
 
   Inferred type
     VV : {VV : Int | VV == fromGt + ?a
                      && VV == ?b}
  
   not a subtype of Required type
     VV : {VV : Int | 0 <= VV
                      && VV < bslen str
                      && VV < index
                      && VV >= 0}
  
   In Context
     ?b : {?b : Int | ?b == fromGt + ?a}
      
     str : {str : ByteString | 0 <= bslen str}
      
     fromGt : {fromGt : Int | fromLt <= fromGt
                              && fromGt < bslen str}
      
     index : {index : Int | 0 <= index
                            && index < bslen str}
      
     fromLt : {fromLt : Int | index <= fromLt
                              && fromLt < bslen str}
      
     ?a : {?a : Int | ?a == 1}
```

Where exactly does that `VV < index` constraint come from?

(Don't know if this is the right place for asking for help on Liquid Haskell?)

**Comment by ranjitjhala** [comment]
This looks like it's coming from the termination checker, which by default,
Is trying to check that the bslen metric on the recursive parameter is
strictly decreasing.

You can switch it off by adding

{-@ LIQUID "--no-termination" @-}

**Comment by fhaust** [comment]
Hmm ... can I hint it in a direction that it understands that it is strictly increasing?

**Comment by gridaphobe** [comment]
@fhaust it has to be strictly decreasing (and bounded by 0) for the termination checker to be happy. That being said, you can usually write a **decreasing** metric in terms of an **increasing** value.

For example, in your `parseTags` function, `index` is strictly increasing and bounded by the length of the string, so the difference `bslen str - index` should be strictly decreasing. You can try telling LH to use this metric with the termination annotation `/ [bslen bs - index]` to the type for `parseTags`. The result should be 

```
{-@ parseTags :: bs:ByteString -> {a:Int | 0 <= a && a < bslen bs } -> Maybe Int / [bslen bs - index] @-}
```

**Comment by ranjitjhala** [comment]
Yes, in this case it looks like

(bslen str - index)

Is the termination metric so add it to the end of the type signature like

{-@ parseTags :: bs:ByteString -> {a:Int | 0 <= a && a < bslen bs } ->
Maybe Int / [bslen str - index] @-}

**Comment by fhaust** [comment]
Works like a charm!

Is that `-` to be read a a "minus" or as a "to"?

**Comment by ranjitjhala** [comment]
Great!

It's a minus: essentially you are telling LH that the value of that
arithmetic expression (bslen str - index) gets strictly smaller at each
recursive call AND is non negative, i.e. the recursion must terminate...

**Comment by fhaust** [comment]
Ok ... but that is not enforced, is it? I am basically telling LH something I know about the algorithm? Or is that condition checked somehow?

**Comment by nikivazou** [comment]
Yes, Liquid Haskell does check that the expression (we call it termination metric) you are providing is 
  - non negative 
  - decreasing at each recursive call 
If these two checks are OK, then Liquid Haskell concludes that  your recursive function terminates. 

Test it yourself: If you give a termination metric that does not satisfy these two conditions you will get a type error.
