### ISSUE TITLE
Can LH be used to prove "much smaller than" conditions?

### ISSUE THREAD

**Issue by fhaust** [ucsd-progsys/liquidhaskell#928]
I just implemented [*exponential smoothing*](https://en.wikipedia.org/wiki/Exponential_smoothing) and while finding a good time constant I thought about the fact that `1 - e^(-dt/t)` is equivalent to `dt/t` when `dt` is much larger then `t`.

Is this something that can be reasonably encoded in LH? From what I gathered I could write a function that has a precondition that (e.g.) `dt > t * 1e3` and would then have to check this precondition for every new value. Or I could just *assume* it to be true, but that is probably not really a good approach.

Thoughts?

**Comment by atondwal** [comment]
LH should do these checks for you. e.g.

```{.haskell}
{-@ f :: t:Double -> {dt:Double|t-dt<1e-3 && dt-t<1e-3} -> Double @-}
f :: Double -> Double -> Double
f t dt = t

-- This is a safe usage
g = map (f 1) [1.0005,1.0001,1.0000006]

-- This is an unsafe usage and will cause a type error at compile time
h = map (f 1) [1.0005,1.001]
```

**Comment by fhaust** [comment]
Fair enough. What about "dynamic static checks" [1]? 

    i :: Double -> Double -> Maybe Double
    i t dt = if abs (t - dt) < 1e-3 then Just (f t dt) else Nothing

Should be fine too. And dependent on that I could chose the safe or unsafe algorithm at runtime, nice.

[1] is there a name for that?

**Comment by atondwal** [comment]
Exactly. Not sure if there's a name for it... "verified guarded preconditions"? "verified runtime checks"?

**Comment by nikivazou** [comment]
You can use the [liquidAssume](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/include/Language/Haskell/Liquid/Prelude.hs#L77) as a "dynamic check".
