### ISSUE TITLE
Guards vs equational style

### ISSUE THREAD

**Issue by TomMD** [ucsd-progsys/liquidhaskell#941]
It appears some aspect of LiquidHaskell prefers guards over idiomatic equational style.  Consider:

```
fac :: Int -> Int
fac n = n * fac (n-1)
fac n | n == 0    = 1
      | otherwise = n * fac (n-1)
{-@ reflect fac @-}
```

Nothing wrong there, but:

```
fac :: Int -> Int
fac 0 = 1
fac n = n * fac (n-1)
```

Results in:

```
 <no location info>: Error: Uh oh.
     [snip]/Nat.hs:14:13: Error: Cannot promote Haskell function fac to logic
    altToLg on Default
```

Sorry if this is already a known limitation that I had missed.

**Comment by ranjitjhala** [comment]
Thanks for posting this! It is a known limitation in that the GHC core for
these two are different and the "reflection" implementation does not yet
handle certain patterns. However we should fix this. Perhaps @nikivazou can
take a look?
