### ISSUE TITLE
Question: What is the difference between = and ==?

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#948]
By experimentation it seems that definitions of the form
```
{-@ type QueueN a N = {v:Queue a | qsize v = N} @-}
```
are treated identically to
```
{-@ type QueueN a N = {v:Queue a | qsize v == N} @-}
```
which uses a `==` instead of `=`.

Is there a difference? When should the one be used rather than the other?

Sorry for the flood of (stupid) questions.

**Comment by ranjitjhala** [comment]
Hi @alanz -- yes, they are identical. LH accepts the `=` for historical
reasons, and have not gotten around to "suppressing" it...

On the contrary, **many thanks** for the many great fixes and reports!
