### ISSUE TITLE
x:Int vs {x:Int | ..}

### ISSUE THREAD

**Issue by chrisdone** [ucsd-progsys/liquidhaskell#949]
So it seems that the two are semantically different? I thought the former was syntactic sugar for the latter, but it seems `{ .. }` is a scope delimiter.

If you write

    x:Int -> { y:Int | x > 0 }

that works, but

    { x:Int | true } -> { y:Int | x > 0 }

is not in scope:
```
Date.makeDate :: Int -> Int -> {year : Int | month > 0} -> Date
         Sort Error in Refinement: {year##3 : int | month > 0}
         Unbound Symbol month
     Perhaps you meant: len, snd, fst
```

Is that correct? I'm trying to have conditions like `x>y` but where the `x` has its own conditions too. It seems with this restriction I should move all `x`'s conditions into the `{ .. }` expression of `y`.

**Comment by alanz** [comment]
Try

```
 x:{Int | true } -> { y:Int | x > 0 }
```

**Comment by chrisdone** [comment]
@alanz Oh, nice! I'm not sure why `x:Int` and `x:{Int|true}` differ but this serves my purposes.

**Comment by chrisdone** [comment]
The `x:Int` or `x:{Int|true}` doesn't work in data declarations, only `{x:Int}`. This parser is an absolute minefield! :joy: I can't tell when I'm doing something nonsensical or just when the parser is incomplete.

**Comment by alanz** [comment]
I already have a yak on my list to re-work the parser, and its error reporting.

**Comment by nikivazou** [comment]
Yes yes yes! Thanks @alanz!!!!

Well, you can always blame the parser. Sorry, but we (as the Liquid Haskell team) do not have enough people to fix this... (#SummerOfHaskell)

**Comment by chrisdone** [comment]
The upside is that I managed to get the below to work. I was unable to put the invariants of `makeDate` onto the `Date` itself (can't figure out the syntax), but it's good enough to my purposes. My task is to demonstrate what refinement types can achieve, and handling a date is often seen as "too complex for types to handle".

``` haskell
{-# LANGUAGE ScopedTypeVariables #-}

module Date where

data Date = Date { day :: !Int, month :: !Int, year :: !Int }
  deriving (Show)

{-@
makeDate :: day:{Int | day > 0 && day <= 31 }
         -> month:{Int | month > 0 && month <= 12 && (day < 31 || month = 04 || month = 06 || month = 09 || month = 11) }
         -> { year:Int | year > 0 &&
              (month /= 2 ||
               (day < 29 ||
                year mod 400 = 0 || (year mod 4 = 0 && year mod 100 /= 0)
               )
              )
            }
         -> Date
@-}
makeDate :: Int -> Int -> Int -> Date
makeDate d m y = Date d d y

works = makeDate 12 03 2017
works_leap_day = makeDate 29 02 2016
-- Does not compile:
-- invalid_nov_day = makeDate 11 31 2017
-- invalid_month = makeDate 12 15 2017
-- invalid_leap_day = makeDate 29 02 2017

main = do
  year :: Int <- readLn
  month :: Int <- readLn
  day :: Int <- readLn
  if year > 0
    then if month > 0 && month <= 12 && day < 31 || month == 04 || month == 06 || month == 09 || month == 11
           then if day > 0 && day <= 30 && valid_leap_days day month year
                  then print (makeDate day month year)
                  else error "Day is out of range!"
           else error "Month is out of range."
    else error "Year is out of range."
  where
    valid_leap_days day month year =
      (month /= 2 ||
       (day < 29 || mod year 400 == 0 || (mod year 4 == 0 && mod year 100 /= 0)))
```

**Comment by chrisdone** [comment]
Obviously this is probably not going to be useful in practice because a smart constructor could just return `Maybe Date`. I suppose the `Date` type itself having those invariants would be a neat way to demonstrate that any operations (such as incrementing a day, not going over the 31 bound) would have to retain those invariants.

**Comment by nikivazou** [comment]
Here, I put everything into the data definition 

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1489341889_56.hs


Funny: your `makeDate` did not verify at first because your definition has an error :)

**Comment by chrisdone** [comment]
That appears to link me to the `Evens` example. Can you gist it?

> Funny: your makeDate did not verify at first because your definition has an error :)

That's awesome! :joy:

**Comment by chrisdone** [comment]
Nevermind, hitting the link again displayed it properly. Thanks!

**Comment by gridaphobe** [comment]
@alanz if you have the time and parsing know-how to invest in improving our parser, that would be amazing! It truly is one of the biggest usability warts IMO...

The crux of the problem from what I can tell is that we have FAR too much backtracking via `try`. I count 63 (!) occurrences just in the LH parser, there are probably even more in the liquid-fixpoint parser that we build on top of.

**Comment by alanz** [comment]
I have not really looked into it, but it does seem that the 0.6 error reporting is better than on the `develop` branch.

It might be worthwhile capturing the actual grammar, as part of the documentation too.  Because it seems there is a level of documentation missing, that describes what annotations are valid, in terms of things like `type`, `invariant`, `predicate`, etc.

**Comment by chrisdone** [comment]
> try. I count 63 (!) occurrences just in the LH parser, there are probably even more in the liquid-fixpoint parser that we build on top of.

I'd agree with that hypothesis -- the way the error messages are always pretty much the same for a large number of cases and irrelevant to the issue. I noticed in my own work that skipping a tokenization step actually makes parsec worse at reporting what's going on.

**Comment by ranjitjhala** [comment]
The blame is mostly mine ... I think this parser was the first serious
thing I wrote with parser combinators :(

One challenge has been: how do we (however heuristically) know if one
parser is "better" than another? Without some notion of improvement, it's
hard to justify changes. Perhaps we can use the #try as such a metric and
attempt to rewrite in say megaparsec with as few "try"s possible? Any other
metrics that come to mind?

**Comment by alanz** [comment]
I was thinking of a test suite with good and bad parse strings, and making sure that the error messages make sense for the bad parse, and that all the good ones are accepted.

**Comment by alanz** [comment]
Which has a side effect of documenting the parser too.

**Comment by chrisdone** [comment]
I agree, a test suite lets you detect improvements and regressions and move forward.

I'd also write a tokenizer first and then parse the tokens with parsec. Not having to care about things like whitespace and generally normalizing while parsing reduces funny edge-cases, like I wrote a signature today and if I put a newline instead of a space it breaks, but not between other tokens. You also narrow down to a data type of permissible tokens which is self-describing. 

Also, liberal use of `unexpected` and `<?>` lets Parsec produce more useful error messages, but you do have to consciously design good messages up front. You can get real nice ones like this (written for a client to parse postgresql timestamps, which are horrible):

``` haskell
> case parse zonedTimeParser "2 March 17:32:01 1997" of Left e -> putStrLn e; Right x -> print x
(line 1, column 7):
unexpected invalid day name, invalid month name "March" or unsupported time zone "March"
> case parse zonedTimeParser "100 31 17:32:01 16" of Left e -> putStrLn e; Right x -> print x
(line 1, column 18):
unexpected missing or ambiguous date parts ("100", "31", "16")
expecting day name, full-date, month name, date part, time zone or end of input
```

**Comment by ranjitjhala** [comment]
Excellent suggestions @alanz and @chrisdone!

I think we can get started this way, populating
the test suite by trawling the GH issues for places
where the parser returns particularly bad error messages!

**Comment by gridaphobe** [comment]
In terms of metrics for "goodness" of a parser, we should also consider
the *scope* of the `try`s that we do use (smaller is better).

http://blog.ezyang.com/2014/05/parsec-try-a-or-b-considered-harmful/
