### ISSUE TITLE
Data constructor with no variables

### ISSUE THREAD

**Issue by Altai-man** [ucsd-progsys/liquidhaskell#951]
I have seen examples of how can datatypes be "lifted" into liquid types.

Although, this code:
```
data Pagination = Pagination Int Int

{-@ data Pagination = Pagination Int Int @-}
```

gives me

```
**** DONE:  A-Normalization ****************************************************
 
Var/Type length mismatch: 
  []
  [Int]

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


 /home/sena/Test.hs:5:10-20: Error: Malformed refined data constructor Test.Pagination
 
 5 | {-@ data Pagination = Pagination Int Int @-}
              ^^^^^^^^^^^
 
 Requires 2 fields but given 1
```

Is it possible to work with such datatypes now? Am I missing something?

**Comment by ranjitjhala** [comment]
The {-@ data T = ... @-} syntax is only used if you
want to _refine_ the type (here you are just using `Int`).

Furthermore, for unfortunate parsing/engineering reasons,
you need to use field names. So the following works:

```haskell
data Pagination = Pagination Int Int

{-@ data Pagination = Pagination { fld1 :: Int, fld2 :: Int } @-}
```

**Comment by Altai-man** [comment]
Ah, thanks! I indeed need to refine this type, although I didn't include it in my report because of readability reasons.

My goal is to try to refine `pagination` library, so the "real" type is
```
data Pagination = Pagination Natural Natural
{-@ data Pagination = Pagination { size :: Natural, index :: {x:Natural | x /= 0 } } @-}
```
(or something along the lines, since this introduces a new error about non-numeric nature of Natural type). Thanks again for your help, I guess, this exact issue can be closed.
