### ISSUE TITLE
Sort error on higher order proof

### ISSUE THREAD

**Issue by TomMD** [ucsd-progsys/liquidhaskell#958]
I'm trying to follow SF with liquid haskell and using the LH September blog on reflection as a guide.

So far I have:

```
import Language.Haskell.Liquid.ProofCombinators

{-@ identity_fn_applied_twice :: f:(Bool -> Bool) -> fId:(b:Bool -> {f b == b}) -> x:Bool -> {f (f x) = x} @-}
identity_fn_applied_twice :: (Bool -> Bool) -> (Bool -> ()) -> Bool -> ()
identity_fn_applied_twice f thm x
   = f (f x)
   ==. f x    ∵ thm (f x)
   ==. x      ∵ thm x
   *** QED
```

But the argument `f` is not in scope, so says liquid:

```
 Main.identity_fn_applied_twice :: f:(Bool -> Bool) -> (b:Bool -> {VV : () | f b == b}) -> x:Bool -> {VV : () | f (f x) == x}
     Sort Error in Refinement: {VV : Tuple | f b == b}
     Unbound Symbol f
 Perhaps you meant: b
```

I just pulled and rebuilt liquid from the develop branch.  Is this a bug or my mistake?

**Comment by nikivazou** [comment]
You need to add the higher order flag `{-@ LIQUID "--higherorder" @-}` that allows higher order expressions to flow in the logic.

**Comment by TomMD** [comment]
My goodness you're team is always so fast on this issue tracker. Thanks!
