### ISSUE TITLE
Parse error on simple boolean formula

### ISSUE THREAD

**Issue by TomMD** [ucsd-progsys/liquidhaskell#959]
Consider:

```
import Language.Haskell.Liquid.ProofCombinators

{-@ simple :: a:Bool -> { (a && a) == (a && a)  } @-}
simple :: Bool -> ()
simple _ = ()
```

The parser fails in a few ways depending on the exact formulation, but as an example:

```
 /private/tmp/so.hs:3:16: Error: Cannot parse specification:

 3 | {-@ simple :: a:Bool -> { (a && a) == (a && a)  } @-}
                    ^

     Leftover while parsing
```

**Comment by ranjitjhala** [comment]
Oops! Thanks for pointing out! (Good test to add to the parser suite)

I think <=> should work instead of == here?
For historical reasons we didn't have == on Bool ... but there is no need
for that now so we should fix this..

**Comment by TomMD** [comment]
Yes, `<=>` does work here.  Thanks, I figured this had something to do with the whole Bool/Prop history.
