### ISSUE TITLE
build / test / ci

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#964]
There seem to be multiple ways to build and test this project.

- stack
- makefile
- nix
- travis
- circleci

Are they all equivalent? Is any of them "blessed" in some way?  The travis mechanism has been broken for at least a year. It is not clear if circle ci tests are running, and if so where the results are.

Running the tests locally (via stack test) results in some failures. I have no idea whether this is normal/expected, or if my setup is wrong.

**Comment by alanz** [comment]
For concreteness, these are the failures from the stack test log for a local `stack test`

```
      elim-ex-map-3.hs:                       FAIL (2.02s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      elim-ex-map-1.hs:                       FAIL (1.98s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      QQTySigTyVars.hs:                       FAIL (1.93s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      QQTySig.hs:                             FAIL (1.93s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      elim-ex-list.hs:                        FAIL (1.94s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      QQTySyn.hs:                             FAIL (1.93s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      elim-ex-let.hs:                         FAIL (2.02s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      elim-ex-map-2.hs:                       FAIL (1.94s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
```

**Comment by ranjitjhala** [comment]
The "stack" thing should be blessed... but I think, for reasons that escape
me, the CI uses cabal.

are those tests failing on develop?!

/ cc @gridaphobe

**Comment by alanz** [comment]
It seems that `stack test` also runs the tests for `liquid-fixpoint`.

Is this expected / intended?

**Comment by ranjitjhala** [comment]
I think thats because `stack test` runs the tests for all the targets?
(When running manually I do `stack test liquidhaskell`)

That said, its fine to also run the liquid-fixpoint tests, they are tiny
(and _should_ pass too :))

**Comment by gridaphobe** [comment]
@alanz Yes, we probably need to do some spring cleaning on the repo...

`stack` is the "blessed" tool for local development, the `Makefile` and `.nix` files are old and have likely bitrotted. 

`circleci` is the "blessed" service for building commits and PRs, the logs are available at https://circleci.com/gh/ucsd-progsys/liquidhaskell/tree/develop, and it should automatically build/test any PRs (I'm not sure about commits on a fork..). We used to use travis, but I got frustrated by the 50min timeout that is easily triggered by our testsuite. Also, circle lets you upload build artifacts, e.g. the **logs** of failed tests! The reason we use cabal on circle is so that we can always test against the latest versions of our dependencies, i.e. we can be warned when a dependency is updated in an incompatible manner.

**Comment by gridaphobe** [comment]
The tests should all be passing according to the latest run on Circle.

https://circleci.com/gh/ucsd-progsys/liquidhaskell/tree/develop

You should find logs in `tests/logs/cur`, can you post one so we can see what's going on?

**Comment by alanz** [comment]
It looks like the failures may be missing/bad dependencies for the test file

```
liquid: /home/alanz/.stack/snapshots/x86_64-linux-nopie/nightly-2016-05-21/7.10.3/lib/x86_64-linux-ghc-7.10.3/double-conversion-2.0.1.0-9d4SFE0Uwt89cnl39kvRqX/libHSdouble-conversion-2.0.1.0-9d4SFE0Uwt89cnl39kvRqX.a: unhandled ELF relocation(RelA) type 42

LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.

liquid: liquid: unable to load package `double-conversion-2.0.1.0'
```

**Comment by alanz** [comment]
And I (finally) managed to confirm that the tests pass using `cabal test` locally.

I think there is an interaction around the "no-pie" issue for the tests under stack.

I tried running the tests with `cabal new-test` from cabal master, but this does not find the `liquid` exe because the assumption in https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/test.hs#L166 is no longer valid, the `dist-newstyle` directory structure is much more complex.

**Comment by alanz** [comment]
I am missing something on the circleci config for my account.  

I am getting failures, it seems to be using GHC 8.0.1 instead of 7.10.2?

https://circleci.com/gh/alanz/liquidhaskell/7
```
$ cabal install --upgrade-dependencies --reorder-goals --constraint="template-haskell installed" --dependencies-only --enable-tests

Resolving dependencies...
cabal: Could not resolve dependencies:
trying: liquidhaskell-0.7.0.0 (user goal)
next goal: ghc (dependency of liquidhaskell-0.7.0.0)
rejecting: ghc-8.0.1/installed-8.0... (conflict: liquidhaskell => ghc>=7.10.2
&& <7.11)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

cabal install --upgrade-dependencies --reorder-goals --constraint="template-haskell installed" --dependencies-only --enable-tests returned exit code 1

Action failed: cabal install --upgrade-dependencies --reorder-goals --constraint="template-haskell installed" --dependencies-only --enable-tests
```

The same build passes on the ucsd account: https://circleci.com/gh/ucsd-progsys/liquidhaskell/1344

I wonder if it is not a cache thing, and a fresh build (after clearing the cache) may fail on the ucsd account too.

**Comment by ranjitjhala** [comment]
looks like this is all set?
