### ISSUE TITLE
parser / lexer / liquid-fixpoint 

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#970]
At the moment liquid haskell builds a parser on top of the `liquid-fixpoint` one, which uses a parsec [LanguageDef](https://hackage.haskell.org/package/parsec-3.1.11/docs/Text-Parsec-Token.html#v:LanguageDef) to define the language.

One of the things this does is to define reserved words for the parser, ensuring that no identifier can be parsed that matches a reserved word.

BUT, the set of reserved words for the two languages are different, in that liquidhaskell is a superset of liquid-fixpoint.

There are some possible solutions

1.  Add the liquidhaskell reserved words to the liquid-fixpoint language definition.

2. Make the liquid-fixpoint language definition available for modification in liquidhaskell, and pass
    it back when used for parsing.

3. Carry on as now, where the parsec reserved word machinery is not used in liquidhaskell

I think option 1 violates layering, and unduly restricts other users of liquid-fixpoint. 

Option 2 makes things messy, as you have to pass the language definition through everywhere. Perhaps it could go into the parser state?  But this potentially has performance implications.

Option 3 means we do not get to use the reserved word feature, and potentially need to re-implement it in the liquid haskell parser.

Any preferences?

**Comment by alanz** [comment]
I see we already have some liquidhaskell resererved words in liquid-fixpoint

```haskell
         , "forall" -- LH
         , "exists" -- LH
         , "assume"  -- LH
         , "measure" -- LH
         , "module"  -- LH
         , "spec"    -- LH
         , "where"   -- LH
```

**Comment by ranjitjhala** [comment]
​Hi @alanz,

yes, I suspect that while 1 violates layering,
it is the best of the 3 difficult choices.
In general, as far as the parsing goes, I'd be
fine with changing Fixpoint to improve the LH
parsing experience (even if it ends up adding
haskell specific things to fixpoint.)

So perhaps 1?

Did you have any strong sense about 2 or 3?

Ranjit.

**Comment by alanz** [comment]
Given there is already a crossover, I will continue with it.

It does have the beneficial effect of protecting LH from any syntax extensions in liquid-fixpoint that lead to name clashes.
