### ISSUE TITLE
"Lazy" and "Strict" identical?

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#973]
Both `Lazy` and `Strict` are parsed identically

```haskell
    <|> (reservedToken "Strict"    >> liftM Lazy   lazyVarP  )
    <|> (reservedToken "Lazy"      >> liftM Lazy   lazyVarP  )
```

This seems to indicate that saying `Strict foo` is actually making it lazy?

**Comment by ranjitjhala** [comment]
Another glitch, I think this was because at the time we couldn't decide
which keyword to pick -- for this use case a case can be made for both :)

Still, over time we always just use "lazy" so let's drop the other one!

Thanks a ton @alanz!
