### ISSUE TITLE
tyKindVarIdP discarding kind info

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#974]
Why does the following discard the result of `kindP`?

```haskell
tyKindVarIdP :: Parser Symbol
tyKindVarIdP
   =  try ( do s <- tyVarIdP; reservedOp "::"; _ <- kindP; return s)
  <|> tyVarIdP
```

Should the kind annotation be deprecated in the language?

**Comment by ranjitjhala** [comment]
Not sure what this is for -- @nikivazou can you comment? (She is traveling
so may be delayed...)

**Comment by nikivazou** [comment]
Exactly. In Liquid Haskell we do not reason about kinds. That is we cannot
refine them or use them in the refinements. So the Liquid types ignore
kinds.

**Comment by alanz** [comment]
Ok, and the parser is designed to be able to work with a standard haskell signature that has been annotated, so has to accept the kind annotation.
