### ISSUE TITLE
Slight differences in parser output

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#981]
In my [parser-az](https://github.com/alanz/liquidhaskell/tree/parser-az) branch I now have all the original tests passing.

The parse results are slightly different from before in that more places are getting dummy symbols.

e.g. `x :: a -> a` used to parse as

```
"Asrts ([\"x\" (dummyLoc)],(a -> a (dummyLoc),Nothing))"
```
but now does as
```
"Asrts ([\"x\" (dummyLoc)],(lq_tmp$db##0:a -> a (dummyLoc),Nothing))"
```

Is this a problem?

See https://github.com/alanz/liquidhaskell/commit/6a938f23ae258d74b8a7e4e2825b9716768278a5 for the changes to the tests, showing the old and new output for various cases.

**Comment by ranjitjhala** [comment]
Hi @alanz,

Thanks, this is awesome!

I think this is fine - in fact IIRC we should have put in a dummy binder in
this case!

Should we merge now or?

Thanks a ton!

Ranjit.

**Comment by alanz** [comment]
You can merge now.

I will probably tweak a bit more in future, for specific error messages and
to clean up the junk that is still there.

Alan
