### ISSUE TITLE
Questions about holes

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#999]
I have the following program with holes

```
module Foo () where

{-@ LIQUID "--savequery" @-}
{-@ LIQUID "--eliminate=none" @-}

{-@ foo :: Int -> _ @-}
foo :: Int -> Int 
foo x = if x == 1 then 0 else 2 
```

Liquid Haskell creates a kvar for the hole (in this case `k_22`), is the type of `foo` is 
```
foo :: Int -> {v:Int | k_22}
```

But does not seem to solve for this `kvar` since the solutions file (.fqout) is empty. 
Questions 
- How do I see the solution for the hole? (note I used no elimination)
- If I export `foo` its type gets to be true, even though I explicitely gave it a holed type. Why?

**Comment by gridaphobe** [comment]
Is it possible that GHC is being clever and pruning `foo` as dead code before we even see it? (I hope not, because we use this trick for a bunch of tests..)

> If I export foo its type gets to be true, even though I explicitely gave it a holed type. Why?

Because it's exported, we force all kvars in exported types to true because we have no idea how they will be used downstream. I think it's important to specify external interfaces, but even ignoring that, we currently have no way of propagating **inferred types** to other modules, so it would be horribly unsound to solve such kvars.

**Comment by nikivazou** [comment]
No, GHC is not pruning it, because the .fq file has contrains for the k var. But I cannot see the solution to those contrains.

The exported explanation makes sense. It would make more sense if there was a types error: your hole it turned into a true.

**Comment by gridaphobe** [comment]
Oh, it just occurred to me that the reason there's no solution is because we're preemptively solving it to true. I think the way this is implemented is to just replace all exported kvars with true, before we generate constraints.

Also, I agree that an error (or at least a warning) about a hole being replaced with true due to exporting would be useful. It's less intuitive than for kvars that arise because no spec was written.

**Comment by nikivazou** [comment]
What do you mean "eplace all exported kvars with true"?
I have defined `module Foo () where` so that `foo` is not exported. 
Can you point me to this preemptive solving to see how I can experimentally change it?

**Comment by gridaphobe** [comment]
Oh yeah, nevermind that first paragraph...

**Comment by gridaphobe** [comment]
I believe it's this call to `maybeTrue`

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Bare/Plugged.hs#L57

**Comment by nikivazou** [comment]
And why is it there?
If I replace the `maybeTrue` with the following will some unsoundness happen?
```
maybeTrue :: NamedThing a => a -> ModName -> NameSet -> SpecType -> RReft -> RReft
maybeTrue _x _target _exports t r
  | not (isFunTy t) -- && (isInternalName name || inTarget && notExported)
  = r
  | otherwise
  = killHoles r
```

**Comment by nikivazou** [comment]
It is not this. 
The .fq file still has the constrains on the `kvar` but the `kvar` is not solved. 

So, something is happening at fixpoint, not LH.

**Comment by gridaphobe** [comment]
Oh there's also this line, I think the previous one was just for dealing with exported holes (which could then easily be converted into a warning or error)

https://github.com/ucsd-progsys/liquidhaskell/blob/f27eb99b93fa5efdcec32d571f0688158b3a3ef4/src/Language/Haskell/Liquid/Constraint/Init.hs#L78

**Comment by nikivazou** [comment]
But in my example, `foo` is not exported.

**Comment by gridaphobe** [comment]
> And why is it there?

Suppose you replace `maybeTrue` with your version, I think the following would be unsound.

```
module Foo where

foo :: {v:[Int] | _}
foo = []
```

```
module Bar where
import Foo

unsound = head foo
```

Regardless of what we infer for `foo`, the hole will still be exported. Then in `Bar` there will be nothing flowing into `foo`s kvar, and it can be solved for false, making the `head` call safe.

**Comment by gridaphobe** [comment]
> But in my example, foo is not exported.

True, I was just pointing you to the other place where we replace exported kvars with true :)

**Comment by ranjitjhala** [comment]
My wifi is flaky will likely not get to this anytime soon ...

**Comment by ranjitjhala** [comment]
The kvar here is "sliced" away by fixpoint as it does not transitively
influence any constraint with a concrete refinement on the RHS.

We say k1 -> k2 if there is a constraint where k1 is in the LHS and k2 on
the rhs.

We say k is concrete if there is a constraint where k is on the LHS and a
concrete refinement is on the RHS.

We only compute solutions for those kvars k' such that K' ->* K for some
concrete K (the rest are just assigned TRUE).

There may be a flag "noslice" to disable this; in general the code is in
modules called Graph or Deps (or just Grep for slice)

**Comment by nikivazou** [comment]
Thanks Ranjit! Two more questions
  - If a kvars survives slicing are there other ways to get cut? (I removed the slicing code and still kills some holes)
  - What is the best way to tell fixpoint "I care about these kvars"?

**Comment by ranjitjhala** [comment]
I think it may be harder than just the no slice because ... laziness. That
is with lazy eval, I think fixpoint automatically slices because we only
care about CONCRETE constraints ... if you have none then we never "need"
the solution for the other KVARS so it won't be computed?

(But why are they not printed out then?)

**Comment by nikivazou** [comment]
They are not printed because liquid exits before the lazy printing

**Comment by ranjitjhala** [comment]
So ... are you agreeing with my theory (laziness)? I am still puzzled
because shouldn't

Main = do print (2+2); return ()

Print 4

That is, why doesn't it print the solution?

**Comment by ranjitjhala** [comment]
@niki, I think your slicing stuff is working fine;
when you run with the "--noslice" it prints out
the solution. See this for example:

```

```
$ more niki.fq

qualif Nat(v:int): (0 <= v)

constraint:
  env []
  lhs {v : int | [v = 10] }
  rhs {v : int | $k1 }
  id 0 tag []

wf:
  env []
  reft {v: int | $k1 }

$ stack exec -- fixpoint niki.fq --save --eliminate=none

...

$ more .liquid/niki.fq.fqout

Solution:

$ stack exec -- fixpoint niki.fq --save --eliminate=none --noslice

...

$ more .liquid/niki.fq.fqout

Solution:
$k1 := 0 <= v
```

```

**Comment by ranjitjhala** [comment]
@niki, I think your slicing stuff is working fine;
when you run with the "--noslice" it prints out
the solution. See this for example:

```
$ more niki.fq

qualif Nat(v:int): (0 <= v)

constraint:
  env []
  lhs {v : int | [v = 10] }
  rhs {v : int | $k1 }
  id 0 tag []

wf:
  env []
  reft {v: int | $k1 }

$ stack exec -- fixpoint niki.fq --save --eliminate=none

...

$ more .liquid/niki.fq.fqout

Solution:

$ stack exec -- fixpoint niki.fq --save --eliminate=none --noslice

...

$ more .liquid/niki.fq.fqout

Solution:
$k1 := 0 <= v
```

**Comment by ranjitjhala** [comment]
In short, in your example, maybe it prints out "TRUE" as the solution as there _are_ no reasonable qualifiers? (i.e. TRUE is the actual solution?)

**Comment by ranjitjhala** [comment]
can i close?
